### ISSUE TITLE
Status Bar improvment

### ISSUE THREAD

**Issue by necropaz** [iotaledger/wallet#10]
Maybe it is possible to let the gui have acess to botbox values.. So everbody nows the latest milestone and we can write in status bar myActuelMilestone / coordinatorMilestone or as option as precent..

**Comment by atypicalprogrammer** [comment]
I don't think a lot of users will like querying a centralized service to get this info.

**Comment by atypicalprogrammer** [comment]
we now use latestSolidMilestoneIndex and latestMilestoneIndex in the status bar.
