### ISSUE TITLE
Translation key for "amount" does not exist

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/wallet#100]
"amount" does not have a translation key in the locales/en/translation.json file, so the Spanish version of the wallet looks like this:
![image](https://user-images.githubusercontent.com/19519564/27013980-acded0be-4ebc-11e7-84e1-d2fd2690f370.png)

**Comment by atypicalprogrammer** [comment]
Added the key to English translation, you can now go ahead and translate it on crowdin. thanks!
