### ISSUE TITLE
Wallet on Laptop with Intel i5 7200U doesn't send / reattach or promote

### ISSUE THREAD

**Issue by WurstCommander** [iotaledger/wallet#1000]
Prerequisites

[x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
[x ] I confirm that this is an issue with the wallet, not IRI
[x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
[x ] I confirm that this is not an issue related to stolen/lost funds
[x ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
[x ] I confirm that this issue is present on the latest version of the wallet

### Description

Wallet doesn't attach addresses, send or promote transactions, request invalid every time.
I tried multiple nodes from https://iota.dance/nodes, relogging, reseed, other wallets etc.

With my Desktop PC it works, is there a limit how good a CPU / GPU has to be? The Laptop is not very old (Lenovo Yoga 51014IKB)

### Steps to Reproduce

1. Open IOTA Wallet Client
2. Enter seed
3. Try sending, attaching address, promote transactions, reattach transactions etc. nothing works.
Request error every time, tried several nodes, rebooting, everything.

Windows 10 Home - newest Updates - Version 1709 (Build 16299.192)
IOTA Wallet - 2.5.6

**Hardware specs:**

- Intel Core i5-7200U
- AMD Radeon R5 M430 - 2048 MB, Core: 1030 MHz, Memory: 2000 MHz, DDR3
- 8192 MB DDR4, 2133 MHz, Single Channel

Everything else is fine, I checked the CPU / RAM with Prime 95 and Intel Stress Test.

Where could I see logs?

**Comment by th0br0** [comment]
Which PoW implementation are you using?

**Comment by WurstCommander** [comment]
WebGl 2, CCurl seems to be better, thanks. Sometimes CCurl went through

I think the main problem is, that all nodes are down or very slow

**Comment by Nemmes** [comment]
Check that your Windows Firewall is allowing connections for iotawallet.exe

**Comment by WurstCommander** [comment]
Definitely, not a connection issue :-) The nodes available were quite bad/slow. I tried opening my own node but the slack channel was down too, so this didn't help. Actually, the Console-Client written by someone on Github over here was much MORE better than this wallet. More verbose about errors etc.

**Comment by rajivshah3** [comment]
Are your firmware and drivers up to date?

**Comment by WurstCommander** [comment]
Since it's a long time ago and the client is deprecated now, I'll close this issue.
