### ISSUE TITLE
My Iota balance has been transferred out

### ISSUE THREAD

**Issue by JeffersonAirplane** [iotaledger/wallet#1003]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description
On Dec. 22 2017 I purchased 141.3 Mi.
Please see attachments
Since then I have not moved my Iota but there seems to be 7 transfers total. 
Have I been duped some how?
![image](https://user-images.githubusercontent.com/34805769/34912513-5f876b92-f898-11e7-9afd-9d7aaa8f9908.png)

![image](https://user-images.githubusercontent.com/34805769/34912543-d33ae9ce-f898-11e7-97f3-e802bfc4d3f0.png)

![image](https://user-images.githubusercontent.com/34805769/34912526-a2def96e-f898-11e7-85bc-64bbe6551ed8.png)

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
Log in with the seed I created by creating a 9 letter word x 9
2. [Second Step]
See a balance of zero
3. [and so on...]
Open up history tab to see 7 transfers, which the last 6 are not mine.

**Expected behavior:** [What you expected to happen]
My Iota balance to be there
**Actual behavior:** [What actually happened]
balance is 0
### Versions

[OS Version]
[Wallet Version]

![image](https://user-images.githubusercontent.com/34805769/34912568-815bfaac-f899-11e7-96ae-31921c944a1d.png)

**Comment by sl00k** [comment]
how did you generate your seed?

**Comment by JeffersonAirplane** [comment]
As explained above I created one manually
[First Step]
Log in with the seed I created by creating a 9 letter word
Then copy/ paste 9 times to equal 81 letters

**Comment by jasonkyc** [comment]
same problem is gone just yesterday
