### ISSUE TITLE
iri.jar file is missing

### ISSUE THREAD

**Issue by khwab** [iotaledger/wallet#1009]
Hello All,
I was following README.md instructions where it says
**Note: make sure compiled iri.jar is in the iri folder.**

How do I generate iri.jar ? I am using Ubuntu 14
I do have gone through electron-builder but couldn't understand how to generate it.

Thank you in advanced. 
Khwab

**Comment by rajivshah3** [comment]
You can clone it from the link @wonkytonky provided and then run the installation steps as specified in the README of iotaledger/iri
