### ISSUE TITLE
Invalid response whilst attaching to tangle 

### ISSUE THREAD

**Issue by cryptogoldie** [iotaledger/wallet#1013]
I have tried reattaching to tangle multiple times and its still saying invalid response. I have signed in and out too, same thing. How do I resolve the 'invalid response' issue I'm getting when I try to attached my address to tangle. I have already sent a transaction from binance but it's pending. 

I'm on the IOTA Light Wallet 2.5.5 - IRI 1.4.1.6

Thank you in advance
<img width="1440" alt="screen shot 2018-01-17 at 17 07 24" src="https://user-images.githubusercontent.com/35537463/35056969-5e6f73f6-fbab-11e7-8b20-b3819135afbf.png">

**Comment by wonkytonky** [comment]
change node

**Comment by cryptogoldie** [comment]
hey thanks for your reply, the thing I dont even have the option to change node. this is all thats on my screen.
<img width="1440" alt="screen shot 2018-01-17 at 21 14 24" src="https://user-images.githubusercontent.com/35537463/35067338-816da060-fbcb-11e7-83ee-b568778ec402.png">
<img width="1440" alt="screen shot 2018-01-17 at 21 14 34" src="https://user-images.githubusercontent.com/35537463/35067339-8189639a-fbcb-11e7-82d8-2e6b40ff94b3.png">

**Comment by utkarsh009** [comment]
@cryptogoldie It’s somewhere up there, in the menu bar. (Where Files, Tools etc. options are present). Here’s what the dialog looks like:
![0e1bab21-5cc8-45ec-9492-ef4a083f241c](https://user-images.githubusercontent.com/17116349/35076423-689160b0-fc1e-11e7-9328-13ae0d843ad6.png)

**Comment by cryptogoldie** [comment]
ah I see it now..THANK YOU... there's so many. I'm currently on bitfinex, what should I change it to? and also why is Bitfinex the one most people use?

**Comment by cryptogoldie** [comment]
okay thank you. I appreciate.. I will keep trying. Oh welldone on that.. thanks again

**Comment by Nemmes** [comment]
If you're on Windows make sure your Firewall rules allow iotawallet connections.  I had an issue with that.
