### ISSUE TITLE
wallet 

### ISSUE THREAD

**Issue by ekkko** [iotaledger/wallet#1018]
[X ] I confirm that this is an issue with the IOTA Wallet and not an exchange
[X ] I confirm that this is an issue with the wallet, not IRI
[X ] For pending transactions: I confirm that I have tried reattaching
 and promoting multiple times (check this box if your issue is not related
 to a pending transaction)
[X ] I confirm that this is not an issue related to stolen/lost funds
[X ] For private key warnings: I confirm that I am not at risk of reusing 
an address, or another user has verified that I am not (check this box if 
your issue is not related to a private key reuse)
[ X] I confirm that this issue is present on the latest version of the wallet

hi, three days ago i bought some Miota on binance and withdraw in my iota wallet
 yesterday when i check my wallet was empty i switch nodes, generate new address 
 with no success

Steps to Reproduce
1.download the wallet.
2.go online and generate seed.
3.save the seed in notepad and write mannualy on a sheet.
4.copy/paste from notepad and log-in in my wallet.
5.press on receive and coppy the address.
6.go to binance and withdraw in this address:
https://thetangle.org/address/GMQIVAWWYQ9EZDEJTCCKXSRPNZMVOTP9AVMUNBMNTBXRLPNBMIUBFTDGAKUXVBTBDQLD9YLYOPSKHDCLZ
7.my iota have they arrived and log-out.
8.- log-in next day and the wallet is empty

https://imgur.com/a/sM4PM

**Comment by shufps** [comment]
Did you use 2-factor-authentication?

If not every withdrawal is review manually and that can take up to 7 days (-> look the FAQ on binance).

**Comment by ekkko** [comment]
i use 2-factor-authentication- as i said my Miota arrived in my wallet

**Comment by shufps** [comment]
Ah you are right, the address says the IOTAs are confirmed ...

After clicking "receive" and copying the address, did you attatch it to the tangle?

If not, you can do it afterwards, as far as I know.

**Comment by shufps** [comment]
In your light-wallet there is a big button with "Attach To Tangle" right below your address and qr-code :)

**Comment by ekkko** [comment]
i try and doesnt work

**Comment by rajivshah3** [comment]
Try changing nodes. If that does not work, you mistyped the seed when you generated that address
