### ISSUE TITLE
Why IOTA Wallet on Android shows different amount than Linux Wallet?

### ISSUE THREAD

**Issue by h2oven** [iotaledger/wallet#1019]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ ] I confirm that this is an issue with the wallet, not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

I have IOTA wallet on my Android phone and in my computer (Ubuntu Linux) both with the same seed, but the balance is different, lower on the computer.
How can I solve this problem?
I have IOTA's on the exchange waiting for transfer to my wallet, but I don't do it yet because I'm afraid to lose them.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
Android and Ubuntu Linux
[Wallet Version]
Linux IOTA Light Wallet 2.5.6 - IRI 1.4.1.6
Android IOTA Wallet Version 0.9.109-32ea8fb

**Comment by wonkytonky** [comment]
generate more addresses on your wallet until balance is equal.. and don't send any money to a used address either

**Comment by rajivshah3** [comment]
The node might be behind
