### ISSUE TITLE
Words are cut off in the menu (DE/FR)

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/wallet#102]
The translations of "Terms & Conditions" are cut off in German and French:
![image](https://user-images.githubusercontent.com/19519564/27017257-31d1f0de-4ef5-11e7-97bd-d269d76a7095.png)
![image](https://user-images.githubusercontent.com/19519564/27017265-42acbe0c-4ef5-11e7-8d6c-17eac68ffe6d.png)

**Comment by atypicalprogrammer** [comment]
Fixed in dev.
