### ISSUE TITLE
My wallet was hacked today

### ISSUE THREAD

**Issue by DoggyCGN** [iotaledger/wallet#1021]
Hello, I need your help or some explanations,

today I locked back in my wallet, until my last view 30 days ago. The balance is "0" - the History is (was) empty, too. At first I was cool and shure, that the solution for this mistake is near. After some Google actions I found a matching thread. I generated a new receiving adress. After this, I saw some scary items in my history.

Obviously today (!) a transfer with exactly my previous IOTA-balance was initiated. There is a red arrow with my old IOTA balance in my history with several pending lines some hours before I locked in.

Is that a huge coincidence that I logged in today after many weeks without any wallet contact and the same day that my wallet was cleared of criminals or I think in the wrong direction. I hope so, because the history was also empty after my first lockin attempt. 

By the way: The transaction seems to be still pending. The receiving address has received several hundred transfers with different amounts today. I do not really think I was hacked. I handle my data with care.

Do I hthink wrong or am I really a cybercrimevictim?

**Comment by wonkytonky** [comment]
https://forum.helloiota.com/9100/To-everyone-posting-with-stolen-balances
