### ISSUE TITLE
Iota wallet issue IS ANYONE HAVING SAME ISSUE FEELING LIKE I GOT THEM STOLEN

### ISSUE THREAD

**Issue by bakeddcookies** [iotaledger/wallet#1023]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description
Yesterday I purchased 187 iota on binance. created iota wallet deposited iota into wallet successfully. Now today it does not give me an option in insert my seed. Windows 10

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step] Open iota light wallet 2.5.6
2. [Second Step] wallet loads with green background and white iota symbol
3. [and so on...] NO OPTION TO INSERT SEED. 
4. I did try 2 different nodes
![img_1899](https://user-images.githubusercontent.com/35412460/35178162-0f6a6fea-fd54-11e7-93c8-85ed94522834.jpg)
![img_1899](https://user-images.githubusercontent.com/35412460/35178167-1c19521a-fd54-11e7-9628-b8d0410cc392.jpg)

 

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by bakeddcookies** [comment]
please help lol :(

**Comment by jhmblvd** [comment]
Just can't connect to node. Tried everyone of them

**Comment by Diegocoin99** [comment]
a mí tampoco me dejar poner la seed :( qué pasa??

**Comment by bakeddcookies** [comment]
is it possibly down atm? so it is not just me?

**Comment by bakeddcookies** [comment]
i think i was phished by iotaseed.io?

**Comment by shufps** [comment]
use a different node.
