### ISSUE TITLE
No me genera le Seed en la wallet

### ISSUE THREAD

**Issue by Diegocoin99** [iotaledger/wallet#1024]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

No me genera la SEED

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

No me da la opción de añadir la SEED ni en la pc ni en androi, qué pasa?

**Comment by rajivshah3** [comment]
Por favor lee esto para generar una seed https://kb.helloiota.com/KnowledgebaseArticle50005.aspx

**Comment by rajivshah3** [comment]
Por favor lee esto para generar una seed https://kb.helloiota.com/KnowledgebaseArticle50005.aspx
