### ISSUE TITLE
IOTA Transfer From Binance - double Transaction stuck in pending.

### ISSUE THREAD

**Issue by GazzarooniiALT** [iotaledger/wallet#1025]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [X ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [X] I confirm that this is an issue with the wallet, not IRI
* [X] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [X] I confirm that this is not an issue related to stolen/lost funds
* [X] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [X] I confirm that this issue is present on the latest version of the wallet

### Description

I made a transfer from Binance for 39.5 IOTA.  
I seem to have two transactions pending for 39.5 IOTA (3 after trying to reattach)
I cannot reattach and just keep getting request error, no chance to promote.
I have a ticket open with Binance because there is a suggestion somewhere that they may have sent the transaction twice?

Other things of NOTE.

My first Recieve address has been reattached and promoted successfully but still shows as pending in the history.  Now with three pending transactions.

### Steps to Reproduce

1. Not sure this can be reproduced.

**Expected behavior:** [What you expected to happen]

I receive the payment and it shows up on my balance.

**Actual behavior:** [What actually happened]

I received the payment twice in my history but both are showing as pending.

### Versions

[OS Version]
MAC High Sierra version 10.13.2

[Wallet Version]
Version 2.5.6 (2.5.6)

<img width="812" alt="screenshot 2018-01-20 10 46 23" src="https://user-images.githubusercontent.com/35617892/35179161-3033b17a-fdcf-11e7-9e36-e8649dd975a8.png">
<img width="834" alt="screenshot 2018-01-20 10 47 29" src="https://user-images.githubusercontent.com/35617892/35179168-54fcc7a8-fdcf-11e7-94b9-c57c8137b885.png">

**Comment by mrsinguyen** [comment]
Same with me 

<img width="408" alt="screen shot 2018-01-20 at 10 38 24 am" src="https://user-images.githubusercontent.com/96544/35179497-21898f88-fdce-11e7-9424-fb0acca8f6e0.png">

**Comment by GazzarooniiALT** [comment]
That was my original state before I tried to reattach.  Then I got three of them.  So though best to stop.

<img width="473" alt="screenshot 2018-01-20 09 25 55" src="https://user-images.githubusercontent.com/35617892/35180030-96cb1614-fde1-11e7-90fd-39f491e23aba.png">

**Comment by wonkytonky** [comment]
change nodes.. keep reattaching/promoting

**Comment by rajivshah3** [comment]
This is normal behavior, it will happen each time you reattach

**Comment by GazzarooniiALT** [comment]
How can this be normal?  I have zero balance in my wallet and all transactions are pending.  Nothing is reattaching and I cannot promote anything.

@rajivshah3 
How can you close a case when nothing is working and nothing has been resolved?

**Comment by GazzarooniiALT** [comment]
Would running a full node help?  Instead of relying on connections to other nodes?

**Comment by GazzarooniiALT** [comment]
And in future, you might act like real support and not close tickets until you check there is a resolution.

I have coins stuck, no balance and no resolution, and that I cannot use or resale.  Which is going to be a serious option if this is how the technology and the support is.
