### ISSUE TITLE
I think i was phished... iotaseed.io

### ISSUE THREAD

**Issue by bakeddcookies** [iotaledger/wallet#1026]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description
Is iotaseed.io a scam seed generator?
Thanks

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by sl00k** [comment]
u all deserve it. and i want to be the guy who is behind the scam generators
so many retards, so many idiots. i laugh at you all day long.
to stupid to use a pen. i hope you all lost a lot of money, now go back to your idiot stuff u did before cryptos

**Comment by bakeddcookies** [comment]
you didnt even answer the question you fucking idiot

**Comment by eukaryote31** [comment]
I can confirm that it is currently backdoor-free; however, there may have been a backdoor in it at some point or there may be other malware in your browser or computer.

**Comment by rajivshah3** [comment]
@bakeddcookies please read what you're checking off:
>I confirm that this is not an issue related to stolen/lost funds

This is not a wallet bug

**Comment by rllybadcryptotrdr** [comment]
There definitely was a back door.  Everyone who used it just went broke.

**Comment by firasalmanna** [comment]
I can confirm, I used it and I lost all my Miotas. The transaction was made on 4/1/2018. Before the news started spreading.
Luckily I didn't transfer all my fund at that time to my wallet because of the congestion that happened to the network last month. THANKS TO IOTA NETWORK BEING POOR!

**Comment by rllybadcryptotrdr** [comment]
Anyone know who this Norbert guy is? I'd like to go knock on his door and say hello.

**Comment by bakeddcookies** [comment]
Ya this is BS but i guess we learned. I also saw that Norbert was the one who created iotaseed.io

**Comment by orripid** [comment]
why would you guys not make your own seed?  i cant believe so many people did this?  Im sorry for your losses but you have to be careful now,  you are your own bank

**Comment by rllybadcryptotrdr** [comment]
I don't have a great answer. I was new. Paper wallets with QR codes seemed to be standard practice in crypto. Most wallets provide a recovery phrase. It was recommended at the time, although as I was new, I wasn't looking in the right places.  I figured if I wasn't connected to the internet, it would be safe. Oops.

**Comment by rllybadcryptotrdr** [comment]
Saw a guy that lost 97Gi that he deposited 3 days ago. Some people got hit worse than others.

**Comment by cyrille-kabadjeu** [comment]
Look like I lost my 18G of IOTA! has IOTA foundation looks into it?
