### ISSUE TITLE
WONT LET ME ENTER SEED AT START MENU

### ISSUE THREAD

**Issue by bakeddcookies** [iotaledger/wallet#1027]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [X] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [X] I confirm that this is an issue with the wallet, not IRI
* [X] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [X] I confirm that this is not an issue related to stolen/lost funds
* [X] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [X] I confirm that this issue is present on the latest version of the wallet

### Description
I have a windows 10 O.S. i used the wallet fine for 3 days then this morning i could not enter my seed 2.5.6
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step] Open wallet
2. [Second Step] Cannot enter seed
3. [and so on...] I tried diffrent nodes
![img_1899](https://user-images.githubusercontent.com/35412460/35180399-a2587f44-fd7d-11e7-9b0d-bbd219a573a3.jpg)

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by dvdsnchz12** [comment]
I have the same problem, and try to reinstal the version 2.5.6 and 2.5.5 but continue with the problem

**Comment by shufps** [comment]
Try a different node ... I also had the problem but this seems to be node-dependant

**Comment by mohan-nagaraj** [comment]
I too had same problem. Selecting different node solved it.

**Comment by rajivshah3** [comment]
Choose a different node, this is not a bug
