### ISSUE TITLE
Title at the top of the window is cut off in full screen view

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/wallet#103]
When not in full screen:
![image](https://user-images.githubusercontent.com/19519564/27017312-9c948d46-4ef5-11e7-893c-b5d795127784.png)

When in full screen:
![image](https://user-images.githubusercontent.com/19519564/27017318-abcad324-4ef5-11e7-80e1-82814ad523b4.png)

**Comment by atypicalprogrammer** [comment]
Do you mean maximized or real full screen? Normally in real full screen there is no menu bar, it is shown on hover only and then it should have no title. 

What OSX version?

**Comment by rajivshah3** [comment]
This is with the real full screen, not maximized. I'm on macOS Sierra 10.12.5 Beta

**Comment by atypicalprogrammer** [comment]
Cannot replicate. At the moment actually the title in the title bar should be completely empty in full screen. Will check in later versions as electron is adding some new title bar functionality soon.
