### ISSUE TITLE
wrong node in wallet light version

### ISSUE THREAD

**Issue by Tiguan01** [iotaledger/wallet#1031]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [ x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ x] I confirm that this is an issue with the wallet, not IRI
* [x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [ x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x ] I confirm that this issue is present on the latest version of the wallet

I have the wrong node in my wallet light version,  wen i change the node my wallet doesnot work anymore . Do i need to make a new wallet light with the good node or can i do something els?
When i change the node in the wallet i can not make conection?

[Description of the bug or feature]

GESCHIEDENIS

7 Overdrachten 1 Adres
20/01/2018 02:07
WEPZOBNXINWOOFRIUFQKRROFZRLAGXNANWEZHRULDBRFQLBNFHFKXM9FGSZXJI9CNJCLPHYRNKFZWZZLDJUISLRJCD
MINEIOTADOTCOMToon bundle In afwachting
42
19/01/2018 21:41
WEPZOBNXINWOOFRIUFQKRROFZRLAGXNANWEZHRULDBRFQLBNFHFKXM9FGSZXJI9CNJCLPHYRNKFZWZZLDJUISLRJCD
MINEIOTADOTCOMToon bundle In afwachting
42
14/01/2018 22:37
WEPZOBNXINWOOFRIUFQKRROFZRLAGXNANWEZHRULDBRFQLBNFHFKXM9FGSZXJI9CNJCLPHYRNKFZWZZLDJUISLRJCD
MINEIOTADOTCOMToon bundle In afwachting
61
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen] 

**Actual behavior:** [What actually happened]

### Versions

[OS Version] Light version
[Wallet Version] 2.5.6.

**Comment by wonkytonky** [comment]
look for good node.. your wallet is fine .  there are a lot of public known nodes .. google for them

**Comment by Tiguan01** [comment]
when i fill the good node ten i cannot make connection the node from where
is send put i inmy wallet but then comes the error no connection to make


2018-01-21 13:01 GMT+01:00 wonkytonky <notifications@github.com>:

**Comment by Tiguan01** [comment]
it's the follow node i cannot connect  node.tangle.works:443, i have setup
light wallet with  eugeneiotasupport.com .

2018-01-21 13:53 GMT+01:00 Hindrik Warntjes <henkwarntjes@gmail.com>:

**Comment by rajivshah3** [comment]
The node node.tangle.works:443 is down. Please check http://iota.dance/nodes for a list of running nodes

**Comment by Tiguan01** [comment]
Don't believe it everything works again i have a running nodes and my test
minig is there, from the link above.
💪👍🙂




2018-01-26 4:23 GMT+01:00 Rajiv Shah <notifications@github.com>:
