### ISSUE TITLE
Недостатки (пароль,нода,кошелек oo нода)

### ISSUE THREAD

**Issue by PVBKXWYUMYTJ** [iotaledger/wallet#1034]
Народ, я хочу нормальный генератор 256 символов в кошельке, чтобы он создавался автоматически, также адрес автоматически привязывался, и автоматически переключался на актуальный не глючный сервер, а также чтобы я мог запустить ноду в 1 клик, а не мучатся, в биткоин кошельке все сделано нормально, почему у вас кошелек такой немного убогий по юзабельности.

**Comment by Fumlop** [comment]
not an issue, i think
