### ISSUE TITLE
IOTA wallet with balance 0!!! why??

### ISSUE THREAD

**Issue by alinabozi** [iotaledger/wallet#1035]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by yippykaiyay012** [comment]
How did you generate your seed?

**Comment by alinabozi** [comment]
From this website https://iotaseed.io/ which at the moment is taken down.
In my wallet history I am able to see transactions with minus in pending
and balance still 0 even I tried several times to click on receive and to
attache the generated address to tangle.
You have any idea?

**Comment by yippykaiyay012** [comment]
You used an unsafe online website to generate your seed. This goes with any crypto currency I'm afraid. Using an online seed generator is like going to a website to generate a password for your email account or online banking. Sorry for your loss but this is the case.

**Comment by aliemami** [comment]
that website is fraudulent. it has stolen many people's money. I hope IOTA foundation could detect and Revert funds taken away by them.

**Comment by Wakizashimaster** [comment]
If its still pending try going to this link and go to the #help channel.
https://discordapp.com/channels/397872799483428865/398452378333872138

**Comment by PVBKXWYUMYTJ** [comment]
IOTA не должна никому ничего возвращать , делая благое дело одному она дискредитирует всех, теряя неизменность, она должна улучшать удобство и безопасность , но не возвращать что либо.

**Comment by Oliverg22** [comment]
just had the same thing happen to me

**Comment by freddiboy** [comment]
All my iota is gone, I think it happens on the 19 Jan 2018

**Comment by prinsleo** [comment]
My to 19 january. 1650  4300 usd gone. ...how they can hakk 1000 computer. ..This is a inside Job from iota. ..



Ha en strålende dag!
        Vennlig hilsen
Arild Kårhus Stokkeland


-------- Opprinnelig melding --------
Fra: freddiboy <notifications@github.com>
Dato: 25.01.2018 16:35 (GMT+01:00)
Til: iotaledger/wallet <wallet@noreply.github.com>
Ko: Subscribed <subscribed@noreply.github.com>
Emne: Re: [iotaledger/wallet] IOTA wallet with balance 0!!! why?? (#1035)


All my iota is gone, I think it happens on the 19 Jan 2018

**Comment by gmadabushi** [comment]
I have lost 600.8 IOTA's on 19 January. Looks like this is a big scam. The IOTA team not responding is making it worst. I think we should collectively come with a article on Youtube asking people not to invest in IOTA anymore.

**Comment by yippykaiyay012** [comment]
For goodness sake. I'm sorry that you lost money but there is nothing wrong with iota. If you generated a seed online you basically asked a website for a password. I wouldn't go online and ask a website for a password to use for my online banking. The idea of making a video about "don't invest in iota" is laughable. What would you like the foundation to do? Just give you their iota? Because you made a mistake?

**Comment by gmadabushi** [comment]
I would expect IOTA to warn about that website. Very irresponsible group.

**Comment by gmadabushi** [comment]
I am going to put something in YouTube about this irresponsible group.

On Jan 25, 2018 5:48 PM, "Gopalan Madabushi" <gmadabushi71@gmail.com> wrote:

I would expect IOTA to warn about that website. Very irresponsible group.

**Comment by yippykaiyay012** [comment]
It would be a full time job looking for scams in crypto. They would never get work done. It's better for people to just develop common sense. Hope you get there one day. All the best.
