### ISSUE TITLE
problem in confirming , reattaching and promoting 

### ISSUE THREAD

**Issue by shahabshokuhi** [iotaledger/wallet#1036]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:
* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]
I had a transaction for sending iota from wallet to binance exchange on 20 January(3 days ago) but it wasn't confirmed and I tried reattaching ,and also did promoting online with different nodes several times (more than 50 times) but after several minutes  the message is "timeout please, restart with another node" .

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
confirming the transaction 
![iota](https://user-images.githubusercontent.com/34933353/35245151-7d92fb8c-ffba-11e7-91b6-435e99f28827.jpg)
![iota2](https://user-images.githubusercontent.com/34933353/35245226-ba42866a-ffba-11e7-8fdf-076a8c3f457e.jpg)

**Actual behavior:** [What actually happened]
pending after reattaching several times 
### Versions

[OS Version]
[Wallet Version]

**Comment by shahabshokuhi** [comment]
I had a transaction for sending iota from wallet to binance exchange on 20 January(3 days ago) but it wasn't confirmed and I tried reattaching ,and also did promoting online with different nodes several times (more than 50 times) but after several minutes the message is "timeout please, restart with another node" .

**Comment by wonkytonky** [comment]
keep trying  sometimes public nodes are beeing ddossed ..   they seem to be ok lately though
