### ISSUE TITLE
Балансировщик DLT (увеличение памяти для новых функций без изменения физического сервера)

### ISSUE THREAD

**Issue by PVBKXWYUMYTJ** [iotaledger/wallet#1037]
В биткоине все  хранят копии и с этим проблемы избыточности и невозможность добавить туда гиганские базы данных, а что если в какой то области локальной по пингу ноды, доступности в сети по истории,(нейросеть например подстраивается), создают избыточность ненужную при обращение к каким- то частям базы , тогда актуальная база при умной балансировке будет мигрировать в маленьких класстерах и дополнительной добавленной памяти в ноды и новые ноды (желающие хранить, а не обрабатывать преемущественно) сверх этого ,при создании хешей для сторон хотящих сохрнить информацию неизменной временно пока есть хеш сторон (удаление определяется автоматически консенсусом на основе хешей ) и их ноды как пожертвование с привязкой к хешам , таким образом можно разместить гиганские базы данных в IOTA помимо самой IOTA

**Comment by rajivshah3** [comment]
Hi, can you please provide an English translation?
