### ISSUE TITLE
Balance Dissapearing

### ISSUE THREAD

**Issue by Oliverg22** [iotaledger/wallet#1038]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [x ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x ] I confirm that this issue is present on the latest version of the wallet

### Description

My wallet seems to be glitching.  Everything was deposited fine around 2,440 iota coins and now it is saying only 1,600 when no withdraw was made.  Also, there seems to be about 95 transfers going on in the history page, when there should only be around 4.  I have no clue what is going on.  This wallet isn't too advanced though.  Never had any other wallets have issues.

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by wonkytonky** [comment]
change node maybe your current node is beeing glitchty , nodes are often setup by iota supporterers and not professional  systemadmins

**Comment by Oliverg22** [comment]
No that didn't help....I have about 98 pending transactions, none of which I even started.  I cant even send out the rest of my iota bc of the pending transactions.

**Comment by Oliverg22** [comment]
Just lost more and it looks like the rest are being transferred as we speak.  What are the chances that my coins just got stolen?

**Comment by prinsleo** [comment]
My fund also gett  out with out my knowlegde...it disapear and iota support is doing nothing. Its supose to be a secure wallet.

**Comment by Oliverg22** [comment]
Contact these guys
https://discordapp.com/channels/397872799483428865/398499876935303186
they helped me retrieve the funds that were still pending.  If they say
confirmed, they are gone for good.

**Comment by wonkytonky** [comment]
seems someone got your seed @Oliverg22    where you create seed?
