### ISSUE TITLE
Transfer from IOTA light wallet pending for over 24hrs

### ISSUE THREAD

**Issue by hagenborg** [iotaledger/wallet#1039]
I have a Pending Transfer - for 36 hours... I have tried to switch nodes and to Rebroadcast without luck.
What should i do?
![untitled](https://user-images.githubusercontent.com/35725224/35268468-82e9742a-0029-11e8-98fa-cae1b9cd3c01.png)

Thank you in anticipation.

Regards,
Thomas Eskesen

**Comment by wonkytonky** [comment]
reattach/promote instead

**Comment by hagenborg** [comment]
Thanx!
I have now Reattached & Promoted.
And its still Pending - now i'll wait... ?
![untitled](https://user-images.githubusercontent.com/35725224/35270612-02ecb730-0030-11e8-915a-72de8f504345.png)

**Comment by hagenborg** [comment]
"Confirmed" 
Thanx!

P.S. Can we delete 'unused' transfers from the History?
