### ISSUE TITLE
Translation Keys

### ISSUE THREAD

**Issue by nicoschtein** [iotaledger/wallet#104]
After spending a hours looking through translation files I can say that there are some inconsistencies.

The json files (e.g. `locales/en/translation.json`) are different from what the original google spreadsheet was.
There are multiple duplicated keys and there are even some with two different values like `Attaching address` and `Address attached`.
Also there are missing keys for updated words, like `RE-ATTACH` replacing replay.

What I suggest is that we get a single .json file with the most up to date english translation so we can use it as a base to update all other languages.

I've done some work already clearing up the list of keys here: https://github.com/iotaledger/wallet/pull/77 and https://github.com/iotaledger/wallet/pull/78
but it still may be out of date.

**Comment by rajivshah3** [comment]
On the topic of missing keys, the key for "amount" is missing (#100)

**Comment by atypicalprogrammer** [comment]
I suggest to start using https://crowdin.com/ or similar service to manage translations. Thoughts? Better alternatives?

**Comment by atypicalprogrammer** [comment]
Ok guys, please join the project at: https://crowdin.com/project/iota-wallet thx!
