### ISSUE TITLE
2.5.6 doesn't open the seed space

### ISSUE THREAD

**Issue by Rogerio2017** [iotaledger/wallet#1042]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ x] I confirm that this is an issue with the wallet, not IRI
* [x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [x ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ +] I confirm that this issue is present on the latest version of the wallet

### Description

After reattaching 5-6 times to the tangle the address of one 2-3 days pending transaction (https://thetangle.org/address/FYAJUGMQQ9ZYZCEXGHBVRLCRYYPDKJLIJPZXROYRG9AMLKRHS9JOZIKSBHQBNXFCRY9UMMNHGUMPHIYBYFDFXP9HZB) the IOTA Light Wallet 2.5.5 stopped to open. So, I updated for 2.5.6 but it doesn't open the space to put my seed.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by srinirajavelu** [comment]
me to have a same problem

**Comment by iota15000** [comment]
This morning, you can not connect to the wallet. I can not write my seed because the boxes are not displayed. How to please? It is painful !!!!

**Comment by iota15000** [comment]
problem solved, simply change the node

**Comment by Shkirmantsev** [comment]
I have a same problem. Version 2.5.6 . OS Ubuntu

**Comment by DMalonso** [comment]
I have the same exact issue and changing the node doesn't work... anyone have another solution? Thanks!

**Comment by iota15000** [comment]
reinstall wallet ...

**Comment by Rogerio2017** [comment]
I've reinstalled my wallet and restarted my windows10. And ... nothing... no Seed box.
So I've tried some others nodes at Tools/Edit Node configuration. At the fourth time it worked.
Then, It was 3 min more to logging.
But my 3 days ago transaction continue pending. 
Why the wallet has to search all the history each time?
