### ISSUE TITLE
my iota is missing

### ISSUE THREAD

**Issue by srinirajavelu** [iotaledger/wallet#1044]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [ ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ ] I confirm that this is an issue with the wallet, not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the wallet

### Description
Yesterday I was trying to transfer 179.26043 Mi from my iota wallet  to one of  my other iota wallet. but iota which I transferred from my wallet is not reflected to my other wallet. and  my balance is become zero in my iota wallet. its been credited to some one else wallet ( please refer image). please let us know how can I reclaim my iota back.it would be helpful if you could help me to get my iota back.
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]
Yesterday I was trying to transfer 179.26043 Mi from my iota wallet  to one of  my other iota wallet. but iota which I transferred from my wallet is not reflected to my other wallet. and  my balance is become zero in my iota wallet. its been credited to some one else wallet ( please refer image). please let us know how can I reclaim my iota back.it would be helpful if you could help me to get my iota back.
[Description of the bug or feature]

**Comment by wonkytonky** [comment]
if the iota is moved out and confirmed .. and you dont own the new address .. it's gone

**Comment by srinirajavelu** [comment]
status says conformed . but I know the address (PVHS9YULRRYRMPGYQDPXBSPEYVHWMJDG9JORZQUFQJZMFHCYPUJZGDUQFGAHVURVDNCZVRSSFIVMBUHMAFTYJZYCAC) Please  help

**Comment by srinirajavelu** [comment]
i tried to attach my wallet to tangle . Ist because of that.

**Comment by srinirajavelu** [comment]
this address is generated by one of my iota wallet. but the balance is not reflecting

**Comment by wonkytonky** [comment]
change node.. seems nodes are slow today

**Comment by PVBKXWYUMYTJ** [comment]
Надо переключится на не загруженную ближайшую ноду последней версии IRI , там они RANDOM список выбираете

**Comment by PVBKXWYUMYTJ** [comment]
Товарищ нетерпеливый , насоздавал несколько отправок транзакций на разные ноды, надо было подождать или отправлять с номальной ноды, а не спамить самого себя
https://thetangle.org/address/PVHS9YULRRYRMPGYQDPXBSPEYVHWMJDG9JORZQUFQJZMFHCYPUJZGDUQFGAHVURVDNCZVRSSFIVMBUHMA

**Comment by srinirajavelu** [comment]
will i get my iota back .

**Comment by freddiboy** [comment]
The same thing happens to me, all my iota is moved from my wallet

**Comment by prinsleo** [comment]
Make a New wallet and seed and real it from your New walket.and see if its stolen or moped from it by the iota team.



Ha en strålende dag!
        Vennlig hilsen
Arild Kårhus Stokkeland


-------- Opprinnelig melding --------
Fra: freddiboy <notifications@github.com>
Dato: 25.01.2018 16:33 (GMT+01:00)
Til: iotaledger/wallet <wallet@noreply.github.com>
Ko: Subscribed <subscribed@noreply.github.com>
Emne: Re: [iotaledger/wallet] my iota is missing (#1044)


The same thing happens to me, all my iota is moved from my wallet
