### ISSUE TITLE
NO CONNECTION Error message

### ISSUE THREAD

**Issue by stevandow** [iotaledger/wallet#1045]
* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

No GUI elements load. After a while a NO CONNECTION messages appears. 

### Steps to Reproduce

1. Open IOTA

**Expected behavior:** 
GUI elements load. 

**Actual behavior:**
GUI elements don't load. 
Error message appears: NO CONNECTION.  

### Versions

OSX 10.13.2 
Wallet Version: IOTA Light Wallet 2.5.6
![screen shot 2018-01-24 at 15 16 19](https://user-images.githubusercontent.com/6588803/35337095-99747932-011a-11e8-9b23-3feaa554c221.png)

**Comment by xama5** [comment]
Change your node. Tools -> Edit Node Configuration.

**Comment by stevandow** [comment]
@xama5 Did that. Thanks!
