### ISSUE TITLE
Binance Exchange never received my 803 Mi deposit

### ISSUE THREAD

**Issue by psk422982** [iotaledger/wallet#1046]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [ ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ ] I confirm that this is an issue with the wallet, not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by psk422982** [comment]
Here are the confirmation details
BUNDLE DETAILS

Hash: CAWVQFIYFAHNWTBHLIPSSSAONFRTYENBLHWRPOIEBEFDI9ZWPQGUYMBBQKQDXFBRNBEAZRNHQYQX99999

GXOQSWDMQSXBANTUUYMLYXC9UDKSTQDOLCGNNWFIVWTGWSOGRRPDFRMITEAFBJEWISECPXGGIPYQKGKMCUAWCZBAWW
803 Mi
YLHGZAAEGWVNVBMDORPHLZQLNLOAGUP9ZEHQNQVAPNHKRGANJOTQJFMOWKCREMO9OPBZAPMKMWEZJKIPWWVGXHUIZD
-805.9+ Mi
YLHGZAAEGWVNVBMDORPHLZQLNLOAGUP9ZEHQNQVAPNHKRGANJOTQJFMOWKCREMO9OPBZAPMKMWEZJKIPWWVGXHUIZD
0
GXCRARLPTRFVIBFRCKZCPQI9VKD9FOFVEPPSHRRGSWZCVIVPSHBYJEJWJRPTDHRIIQBOVGQDNVDILKYDYGKXRNCPW9
2.9+ Mi
Persistence: Confirmed

**Comment by wonkytonky** [comment]
mail binance support  itoa tangle seems to work

**Comment by 1234johnny** [comment]
I do not send my wallet to Binance. Do you have to keep waiting or what?
Transaction
KLLHRDVNXPWDEBAWHAZWMIBT9JMQTMRXRRWUKFTHDTFTPALKJNWTBBBOYNRTPDXHOWKSVZTBNFBA99999
copied
January 23, 2018 08:26:29 - 2 days and 12 hours ago

Value
    129 Mi 
Conversion
    315,74 USD 
Tag
    999999999999999999999999999 

Pending
Index in bundle
    0 / 9
Weight magnitude
    17

Address
    FYVTOOIBPUMTW9WLCA9ATJJ9YCMWICKNRJPDWYIZFFSJTVWJVJCIRNCWZERRAFNVZXQC9DEY9UAKCFADXQBLKOGDRW 
Bundle
    YBZMIIIBHF9JXGEZYOYBISQPHAY9JBZYHRRS9WPVULXJIPWLPIKWZYVEEIIBCJZVTYPCCZECXBAWIA9PB

**Comment by 1234johnny** [comment]
the shipment registers pending. 2 days ago, what is done in this case.

**Comment by rajivshah3** [comment]
Please read the checkboxes: 
I confirm that this is an issue with the IOTA Wallet and not an exchange

This should not be reported on GitHub. Please contact Binance.

**Comment by 1234johnny** [comment]
If it is already pending 3 days from my iota purse, it has to do binance.

Transaction
KLLHRDVNXPWDEBAWHAZWMIBT9JMQTMRXRRWUKFTHDTFTPALKJNWTBBBOYNRTPDXHOWKSVZTBNFBA99999

copied
January 23, 2018 08:26:29 - 2 days and 23 hours ago
Value129 Mi Conversion
293,927 USD
Tag999999999999999999999999999
Pending
Index in bundle0 / 9Weight magnitude17
------------------------------
Address
FYVTOOIBPUMTW9WLCA9ATJJ9YCMWICKNRJPDWYIZFFSJTVWJVJCIRNCWZERRAFNVZXQC9DEY9UAKCFADX
QBLKOGDRW
<https://thetangle.org/address/FYVTOOIBPUMTW9WLCA9ATJJ9YCMWICKNRJPDWYIZFFSJTVWJVJCIRNCWZERRAFNVZXQC9DEY9UAKCFADX>
Bundle
YBZMIIIBHF9JXGEZYOYBISQPHAY9JBZYHRRS9WPVULXJIPWLPIKWZYVEEIIBCJZVTYPCCZECXBAWIA9PB
<https://thetangle.org/bundle/YBZMIIIBHF9JXGEZYOYBISQPHAY9JBZYHRRS9WPVULXJIPWLPIKWZYVEEIIBCJZVTYPCCZECXBAWIA9PB>



2018-01-25 22:19 GMT-05:00 Rajiv Shah <notifications@github.com>:
