### ISSUE TITLE
I can't find my IOTA in my wallet

### ISSUE THREAD

**Issue by freddiboy** [iotaledger/wallet#1047]
I need help to recover my Iota, I open my wallet today and all my iota is gone. Attached is the image
![iota_stolen](https://user-images.githubusercontent.com/35784645/35396087-e9fefc00-01e3-11e8-8151-5184330fab32.png)

**Comment by freddiboy** [comment]
how did some one got access to my wallet to steal all my iota. I keep my seed on a usb and not on my computer

**Comment by prinsleo** [comment]
Hello. Me to on a paperback.



Ha en strålende dag!
        Vennlig hilsen
Arild Kårhus Stokkeland


-------- Opprinnelig melding --------
Fra: freddiboy <notifications@github.com>
Dato: 25.01.2018 16:30 (GMT+01:00)
Til: iotaledger/wallet <wallet@noreply.github.com>
Ko: Subscribed <subscribed@noreply.github.com>
Emne: Re: [iotaledger/wallet] I can't find my IOTA in my wallet (#1047)


how did some one got access to my wallet to steal all my iota. I keep my seed on a usb and not on my computer

**Comment by slobalucy** [comment]
hi dont panic, theres a lot of issues with iota. Can i suggest you go to tools and change the node until the babance appears? Have you tried this??
