### ISSUE TITLE
I lost my IOTA

### ISSUE THREAD

**Issue by masterang007** [iotaledger/wallet#1048]
please help!!! I've lost 100 MIOTA

19/01/2018 13:43
CTORMCUAAMTBPK9XPSQEHJPARDRA9XTPUWC9EEARSWMZNTYAWXGLEVXVKQDXKBHARUFZEKBGSVKFJYHMZMHLTPJZDC

BUNDLE DETAILS
Hash: NUEFGCFREIHNJFNPWSVTGCCDYOJRRP9KWFJQPTUFJU9AGX9XFGQXTVALRCKMVXPVUSHOFFNCLCUS99999
CTORMCUAAMTBPK9XPSQEHJPARDRA9XTPUWC9EEARSWMZNTYAWXGLEVXVKQDXKBHARUFZEKBGSVKFJYHMZMHLTPJZDC
100 Mi
RNOPMZYOZDQHKKSAT9YFRWXNJTVFSRJUNXRCQEUFSCLONVMKRSFZRHVESPAVGPWFCBDOCVSSUPSEATJZANYGRVLSWY
-24.5 Mi
RNOPMZYOZDQHKKSAT9YFRWXNJTVFSRJUNXRCQEUFSCLONVMKRSFZRHVESPAVGPWFCBDOCVSSUPSEATJZANYGRVLSWY
0
GDXJINIJNTAEPUHZIVIHQKZKOCFCQ9KJU9IJCVUIQQCCQTXJUYFWYTH9BBMVJMJHSKHZTFAUBVJTSKZJYGNBFVUQCB
-75.5 Mi
GDXJINIJNTAEPUHZIVIHQKZKOCFCQ9KJU9IJCVUIQQCCQTXJUYFWYTH9BBMVJMJHSKHZTFAUBVJTSKZJYGNBFVUQCB
0
Persistence: Confirmed

**Comment by yippykaiyay012** [comment]
It's gone if it's confirmed. Same as any crypto. You probably generated your seed on a website.

**Comment by masterang007** [comment]
I think they've to spot this early, or maybe they're part of them taking benefit.

**Comment by yippykaiyay012** [comment]
Are you trying to imply that the iota foundation has a part in the seed scam you used? That would be a laughable accusation. Owning crypto is your own responsibility anyway, no one elses.

**Comment by masterang007** [comment]
Maybe iota foundation part of them, how come iota foundation claim you're creating the fascinate technology but didn't know this early and how to get back people money. People trust you but you keep talking about this is not your responsibility, what is iota foundation action?

**Comment by yippykaiyay012** [comment]
I don't think you are ready for crypto. Best start off with monopoly.
