### ISSUE TITLE
I lost my IOTA

### ISSUE THREAD

**Issue by gmadabushi** [iotaledger/wallet#1049]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [y ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ y] I confirm that this is an issue with the wallet, not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [y ] I confirm that this is not an issue related to stolen/lost funds
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by gmadabushi** [comment]
I lost 600.8 IOTA's and saw a transfer address. Now I do not see the transfer address as I downloaded a new version of IOTA. Is there any way to get back my IOTA's

**Comment by yippykaiyay012** [comment]
Where did you generate your seed. You probably used iotaseed.io

**Comment by gmadabushi** [comment]
Yes.

**Comment by yippykaiyay012** [comment]
Yup you got scammed. Nothing wrong with iota. Like I've said, it's like asking someone to make an online bank password for you. Would you trust it? It's not the foundations responsibility to look for and warn you of every scam. Owning crypto is your own responsibility.

**Comment by gmadabushi** [comment]
Looks like you are part of that organization and scam.

Thanks
--------------------------------------------
Gopalan D. Madabushi
Phone : 732-693-1518
E-mail: gmadabushi71@gmail.com
