### ISSUE TITLE
will not let me retire iota

### ISSUE THREAD

**Issue by dvdsnchz12** [iotaledger/wallet#1051]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [* ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [* ] I confirm that this is an issue with the wallet, not IRI
* [* ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [* ] I confirm that this is not an issue related to stolen/lost funds
* [ *] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ *] I confirm that this issue is present on the latest version of the wallet

### Description
After mining in https://mineiota.com   will not let me retire iota.
Only have retire iote the first time, after withdrawing the first time the option does not leave withdraw.
I prove reinstall version 2.5.6. and change host of node but no resolve.
any more with this problem?

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version] win 10
[Wallet Version] 2.5.6

**Comment by rajivshah3** [comment]
Please contact the owner of that website. This does not appear to be a wallet issue.
