### ISSUE TITLE
hi help me  MEBX9XW9G9QVGSVMWLGCWPI99TSYFWIOPAOUNWGAEXBDBQUQUEAPVZFSHAFRNHABWXAWETDKKUVS99999

### ISSUE THREAD

**Issue by rezareza00** [iotaledger/wallet#1054]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [* ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [*] I confirm that this is an issue with the wallet, not IRI
* [* ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [*] I confirm that this is not an issue related to stolen/lost funds
* [*] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [*] I confirm that this issue is present on the latest version of the wallet

### Description

 [my issue is reattaching :    My Address : DCUVRPQLPCDUAWHFHUIXYTOPXCHIGADN9BHEDXWVNQHEDOAFRBLTNIABJKGLMCANTZDJMM99CJAKFVYPXGPKEPKJQX
 My hash : MEBX9XW9G9QVGSVMWLGCWPI99TSYFWIOPAOUNWGAEXBDBQUQUEAPVZFSHAFRNHABWXAWETDKKUVS99999   ]

### Steps to Reproduce

1. [1]
2. [2]
3. [3]

**Expected behavior:** [my balance is 541,456 mi]

**Actual behavior:** [my balance is 0 mi]

### Versions

[OS Version]
[IOTA.Wallet.2.5.6-exe]

**Comment by rezareza00** [comment]
Hash:  MEBX9XW9G9QVGSVMWLGCWPI99TSYFWIOPAOUNWGAEXBDBQUQUEAPVZFSHAFRNHABWXAWETDKKUVS99999

**Comment by pfgithub** [comment]
Did you use an online seed generator?

**Comment by rezareza00** [comment]
Yes

**Comment by rajivshah3** [comment]
This is not a bug and should not be reported on GitHub.

**Comment by rezareza00** [comment]
hi help me  Please
my issue is =Generate new address(Not active)
my wallet=IOTA.Wallet.Setup.2.5.7.exe
