### ISSUE TITLE
IOTA Deposit on Bitfinex completed in iotasear.ch but nothing shows on Bitfinex

### ISSUE THREAD

**Issue by c35punk** [iotaledger/wallet#1055]
Sent 1Giota to my exchange wallet address:

EBESVAZVXWJMALXWXVUKFMMMKLCFIUHQVCD9POKXLYVCBEABYDQNYLBKLWFCCNA9GRBLRGGMRQUPDMVLD

The transaction is completed but I didn't receive nothing yet. Is this normal?

https://iotasear.ch/transaction/EKRYSTKBBSRTEORJYIYCZCIFOXL9MP9IKPO99CHDSQWNHXLKP9KMPJPOTOAGOCRZSCRMMCEUZMRQ99999

**Comment by rajivshah3** [comment]
This should not be reported on GitHub. Please contact the exchange if you have concerns. Sometimes there can be a delay

**Comment by c35punk** [comment]
Sorry, I forgot to close it. Thanks
