### ISSUE TITLE
Угроза bitcoin lightning network

### ISSUE THREAD

**Issue by PVBKXWYUMYTJ** [iotaledger/wallet#1056]
Если bitcoin lightning network реализуется (будет принят большинством), то iota сможет занять только узкую нишу, и это замедлит развитие экосистемы.

**Comment by PVBKXWYUMYTJ** [comment]
Стоит сделать нормальный кошелек-ноду, смартконтракты, и нормальную децентрализацию, чтобы все верили проекту.

**Comment by rajivshah3** [comment]
This is not a bug. Please do not report this on GitHub.
