### ISSUE TITLE
Transaction stuck pending

### ISSUE THREAD

**Issue by vancouver1** [iotaledger/wallet#1060]
### Prerequisite
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ ] I confirm that this is an issue with the wallet, not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] Iconfirm that this is not an issue related to stolen/lost funds
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

I can't get my wallet to wallet transfer to confirm, I rebroadcasted and reattached multiple times. I transferred funds on Jan 25.

![iota](https://user-images.githubusercontent.com/35904785/35488848-d1a22aa8-0443-11e8-9638-ce93753ac6e0.JPG)

Hash AAZSKIKTDOIEVIRZPYEUDCXENLOPRMIJAERJOZYBTHPSBQVJ9JEQDWSRTOTANRUUHNBJZATVIBJU99999

address 9YCSBZNYT9CCZPUKYUTJCGDECBNAZ99GUMENLDPAJYPLHYNAWPSBRTFZFHBCQYLFRFTZBYWALOSSWJVWDLAWNICHVC

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version] 2.5.6  IRI 1.4.1.7

**Comment by lbux** [comment]
Transaction confirmed, try using Discord's #help channel. People will help you promote transactions.

**Comment by vancouver1** [comment]
hi, now my balance shows zero, also no history, wtf?

**Comment by lbux** [comment]
You're probably using an old node. Try this node http://nodes.iota.fm:80 , if it still shows 0 then read [this](https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab)

**Comment by vancouver1** [comment]
Thank you Ibux, it works now

**Comment by Michal2333** [comment]
Hi guys,

i need your help. My IOTA is pending for more than 72 hours.
May I ask somebody to confirm my IOTA ID address in order to let the transaction proceed/confirm?

Or may I ask you to recommed somebody to help me with.

Thank you

Michal
