### ISSUE TITLE
Where is IOTA Wallet Setup 2.5.7.exe ?

### ISSUE THREAD

**Issue by BeanSampa** [iotaledger/wallet#1061]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [ x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ x] I confirm that this is an issue with the wallet, not IRI
* [ x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ x] I confirm that this is not an issue related to stolen/lost funds
* [ x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ x] I confirm that this issue is present on the latest version of the wallet

### Description
Is there a Windows Version ?

[OS Version] Windows 10
[Wallet Version] 2.5.7

**Comment by BeanSampa** [comment]
How can I get a version of Windows?
After IRI 1.4.2.1 Wallet 2.5.6. Shows Balance: Zero.

**Comment by lbux** [comment]
![image](https://user-images.githubusercontent.com/30765968/35494355-ffa99a64-046e-11e8-9f2c-94724e611010.png)
This should answer your question.

**Comment by resuschris** [comment]
@BeanSampa generate new addresses until the balance shows up. i just finished getting my balance back. had to generate 42 adresses before it showed up so patience.....

**Comment by lbux** [comment]
IOTA.Wallet.Setup.2.5.7.exe is now live

**Comment by chrisoro** [comment]
Windows 10 Smart Screen is reporting that this setup is malicious.

You might want to find out why Windows flags it as such...

**Comment by iota15000** [comment]
Connection refused ?????

**Comment by lbux** [comment]
@iota15000 Change your node to http://nodes.iota.fm:80

**Comment by iota15000** [comment]
connection is ok  ...... but balance 0 ?????

**Comment by lbux** [comment]
@iota15000 Please read [this](https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab). Try using [Reddit](https://www.reddit.com/r/Iota/) or the [IOTA forums](https://forum.iota.org/) next time, GitHub isn't the place to post these kinds of issues.

**Comment by PVBKXWYUMYTJ** [comment]
касперский помечает желтым ограничением, не доверенным ,  работает

**Comment by PVBKXWYUMYTJ** [comment]
программа находится , смотреть расположения расположения файла , меню мышкой по ярлыку

**Comment by rajivshah3** [comment]
@chrisoro IOTA currently does not sign wallet releases, so sometimes the antivirus treats it as a false positive.

**Comment by rajivshah3** [comment]
Closing as this is no longer an issue, the EXE has now been uploaded
