### ISSUE TITLE
Balance 0 this morning

### ISSUE THREAD

**Issue by FRAMISFIT** [iotaledger/wallet#1065]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [X ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [X ] I confirm that this is an issue with the wallet, not IRI
* [X ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [X ] I confirm that this is not an issue related to stolen/lost funds
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the wallet

### Description
Balance 0 this morning

connection seed ok   , tangle ok    but balance is empty. 

Versions  2.5.6

**Comment by aderzelle** [comment]
Same issue here. I downloaded the 2.5.7 but balance is still 0.

**Comment by wonkytonky** [comment]
snapshot happend.; google it

**Comment by aderzelle** [comment]
Indeed, I thought the new 2.5.7 was supposed to generate and attach to tangle automatically, my mistake. 

Thank you

**Comment by cocoaboost** [comment]
I had balance 0 this morning too, yesterday I transferred successfully Miota from Binance for the first time. I transfered 19.4 Miota to test the wallet. Then, when I accessed to the wallet this morning the funds were missing. The wallet was not updated. I was running the 2.5.4 version. I updated it to the new version 2.5.7 but I doubt it is a wallet issue. How do I access to the tangle to verify transactions?

**Comment by cocoaboost** [comment]
well ~~ i found something 
checking my balance on https://iotabalance.com/ the funds are there actually, it just doesn't show up on the wallet

**Comment by cocoaboost** [comment]
ok~ nvm, i just had to click > receive > attach to tangle in the wallet, the funds are in the wallet again, i'm a newbie srry xp

**Comment by iSleepZz** [comment]
Maybe there are easier ways. But every time I made a new address and connected to tangle, I got a transaction for each time
