### ISSUE TITLE
Balance went 0

### ISSUE THREAD

**Issue by c35punk** [iotaledger/wallet#1066]
After I updated my wallet from 2.5.6 to 2.5.7 (deleted %APPDATA% and uninstalled the whole thing) I logged in to my account and recover my funds using the following settings:

![123123](https://user-images.githubusercontent.com/25898207/35506550-52f9355c-04f2-11e8-8592-e49bcb2a9231.JPG)

, all my balance went missing an hour ago... with one transaction:

https://iotasear.ch/transaction/9CJZY9YSCTYTDDQINMUWSKRXRJTKAAQEWQFAP9MOUCKRJ9NREYSCYUKMPJDDEZDGZKWLFZLKANWPA9999

The transaction states that the amount is 1 Miota but it has the "UD" tag and -1.2G were deducted from my wallet... PLEASE HELP
![capture](https://user-images.githubusercontent.com/25898207/35505857-1bb87e92-04f0-11e8-87e8-a6fec12f5c2a.JPG)

I returned to my machine and my balance was 0 then I reattached to tangle, logged in to another node and received 126.7 Miota (from nowhere, does not show as an incoming Tx) and in the history it states that I was deducted with 1.2G... a number which I didn't used ever for a transfer...

PLEASE HELP
![showcase](https://user-images.githubusercontent.com/25898207/35506256-6178693c-04f1-11e8-852f-9c3cc91fc280.JPG)

This is the info under the Transaction which I did earlier for 1 MIota the address is correct (CPUUFZOHOXHTAUJBFKKWGTTWAAPOTJ9WXQUPBOKEJCPDTTNRLUGOFPVNENJOVGCMAVJTADJOGFXBDLGZWNMBKXTCTD), but then we have -1.2G (9QUYVZIRJJXGKMOJQMCKIBDPLXUYUYLXPLLKKPKYCZLQTYZN9UEOGLXHJIORKCISMNAGQAPFVDKIESFDDOBRUHHZWA) to +1.2G (ESKUKWRALWNSAHUWYBFELNYGGDJZPDKHXTKMHLKUMPJVESFPVMGATH9MZJER9HQUYLCQTSDQFCVYSS9KXBCTQRLXNC). How can I recover my IOTAs

**Comment by wonkytonky** [comment]
how did you create seed?

**Comment by c35punk** [comment]
With seed generator August 2017

**Comment by c35punk** [comment]
This address received my money:

https://iotasear.ch/address/ESKUKWRALWNSAHUWYBFELNYGGDJZPDKHXTKMHLKUMPJVESFPVMGATH9MZJER9HQUYLCQTSDQFCVYSS9KXBCTQRLXNC

What UD Tag means anyway?

**Comment by wonkytonky** [comment]
what is "With seed generator August 2017" ?   
there are no oficial seedgenerators. 
chances are high someone scammed you ..   with a fake seed generator website

**Comment by c35punk** [comment]
It means that I have used Seed Generator like this one https://www.iotaseedgenerator.online/ to create my wallet and I did this in August  2017... Since then I have used my wallet multiple times with no problem. On 27th of January (2 days ago) I have decided to transfer all my IOTAS to a new custom seed wallet because of the scam with those IOTA Generators. I have been able to send nearly half of my balance to Bitfinex, but since then I have made some other (smaller Txs) just to test my new wallet. One of my TXs was for 100Miotas  (confirmed) to another Bitfinex account (which I still don't have). Every transaction after that one in which I have tried to send iotas was ending up with ERROR: PRIVATE KEY REUSE... Then I have downloaded Wallet 2.5.7 attached it to Tangle and got my 1.3GIOTA. After that there waas this transaction which I made yesterday to test my new wallet for 1MIOTA which I received on it but got deducted with 1.2GIOTA... That's the problem. I have sent 1MIOTA but from my account were taken 1200MIOTA... That's the problem I wasn't hacked... or so I think... Any opinion is highly appreciated.

So, please check out my previous comment and see what's the

**Comment by c35punk** [comment]
@wonkytonky  and others from the Dev team to step up please.

**Comment by resuschris** [comment]
I'm sorry but you probably got scammed. Online seed generators are phishing sites. This was a huge issue literally like a week ago. your Mi is probably gone forever. I'm sorry.

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/35518518-158b676a-0512-11e8-955f-83c80046de79.png)
so you did this 1mi tx right?

**Comment by c35punk** [comment]
Yes

**Comment by wonkytonky** [comment]
just a guess.. but  go to your old wallet and generate a lot of addresses.. maybe the snapshot messed with it

**Comment by c35punk** [comment]
I will, and I will post the results. Thanks... Hope dies last...

**Comment by c35punk** [comment]
It's all good now... I was able to recover my balance with multiple addresses as @wonkytonky suggested. Thanks mate!

![allgood](https://user-images.githubusercontent.com/25898207/35528268-04263102-0536-11e8-8635-ccaa294f57bb.JPG)
