### ISSUE TITLE
54 IOTA zu Binance überwiesen und 0.000054 kommen nur an?

### ISSUE THREAD

**Issue by TinaGudi** [iotaledger/wallet#1069]
Ich habe alles korrekt durchgeführt, von der IOTA Wallet. Meine Wallet ist nun auf Null und die Coins sind verschwunden?
Meine Güte. Mal eben Geld verbrannt.

Woran liegt das?

**Comment by PVBKXWYUMYTJ** [comment]
Binance  считает в MIOTA (1000000 iota) , следовательно 0,000054 (54 iota =0,000054 Miota).

**Comment by PVBKXWYUMYTJ** [comment]
Про комиссию бирж и обменников не стоить забывать кстати.

**Comment by sl00k** [comment]
mein gott, lass dir hirn wachsen.
auf der börse sind miota und du hast iota verschickt. ich kann dir gerne 1€ schicken und du schreibst mir 1000000€ gut ok? 
geld verbrannt also? informier dich erstmal bevor du rumstänkerst. es nervt langsam

**Comment by rajivshah3** [comment]
@TinaGudi https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab
