### ISSUE TITLE
Wallet showing 0 Balance

### ISSUE THREAD

**Issue by amacd123** [iotaledger/wallet#1074]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the wallet

IOTA Light Wallet 2.5.4 IRI 1.4.2.1

Balance was showing this Saturday.  Opened wallet this morning, showing 0 Balance.  No upgrades, no changes were made.

OS Windows 10

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by fxcgomes** [comment]
Same thing here. No balance and no transaction history whatsoever (i did quite a few). Everything blank.

I've updated to 2.5.6 IRI 1.4.2.1 and still nothing.

**Comment by tro69** [comment]
Update to the latest version of wallet (2.5.7).
Log into your wallet with your seed.
Go to the RECEIVE section and press ATTACH TO TANGLE.
Then press GENEREATE NEW ADDRESS and ATTACH TO TANGLE until you get the correct balance.

**Comment by Michaellooo** [comment]
same happened here today... zero balance and no trasactins....   PLEASE HELP!

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab
