### ISSUE TITLE
problems with wallet balance

### ISSUE THREAD

**Issue by rogeriotigre** [iotaledger/wallet#1075]
Today my wallet was in with the balance 0.
I updated it to version 2.5.7 and did not solve it.

### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [ ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ ] I confirm that this is an issue with the wallet, not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [ ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by rajivshah3** [comment]
This is not a wallet bug, please follow these instructions: https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

**Comment by rogeriotigre** [comment]
My transaction history is not showing up.

[image: Imagem inline 1]

Atenciosamente

Rogério Alves Tigre

(11) 9 7520-8655

2018-01-29 18:56 GMT-02:00 Rajiv Shah <notifications@github.com>:

**Comment by mineroloco** [comment]
hello rogeriotigre

The same happened to me,

in receiving generates new seed and links it later in transaction history a transaction is generated, follow the link, show bundle and link it. push in persintence.

It's up to generate new seed to receive and do the same process.

I got it and I already have my balance.
