### ISSUE TITLE
не отображаются средства на кошельке

### ISSUE THREAD

**Issue by Andrey810** [iotaledger/wallet#1076]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by Andrey810** [comment]
на кошельке не отображается баланс, что делать

**Comment by Andrey810** [comment]
на кошельке не отображается баланс, что делать

**Comment by Andrey810** [comment]
на кошельке не отображается баланс, что делать

**Comment by rajivshah3** [comment]
Please read this: https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab
