### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by rezareza00** [iotaledger/wallet#1078]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [* ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [* ] I confirm that this is an issue with the wallet, not IRI
* [* ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [* ] I confirm that this is not an issue related to stolen/lost funds
* [* ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [* ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [* ] I confirm that this issue is present on the latest version of the wallet

### Description

[hi help me Please
my issue is =Attach to tangel and Generate new address(Not active)
my wallet=IOTA.Wallet.Setup.2.5.7.exe]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [my balane is 400 mi]

**Actual behavior:** [my balance is 0 mi]

### Versions

[OS Version]
[IOTA.Wallet.Setup.2.5.7.exe]

**Comment by wonkytonky** [comment]
what do you mean: "not active" ?
