### ISSUE TITLE
Tools: Missing "generate new seed" option in main menu - wallet 2.3.0 - iri 1.2.1

### ISSUE THREAD

**Issue by java99** [iotaledger/wallet#108]
Hi,

since the new wallet version, i do not see any option to generate a new seed. 
Attached a screenshot - following iota-guides it should be in tools. But it cannot be found anywhere all over the main menu.
MacOs:Sierra

![bildschirmfoto 2017-06-12 um 21 59 13](https://user-images.githubusercontent.com/2676451/27052651-a1dba238-4fba-11e7-9ee1-49baa843604d.png)

**Comment by atypicalprogrammer** [comment]
Function has been removed as requested by @domschiener

**Comment by stanchuks** [comment]
How do we know create seed and login?
