### ISSUE TITLE
reclaimed tool

### ISSUE THREAD

**Issue by tedtankal** [iotaledger/wallet#1080]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

reclaimed tool

### Steps to Reproduce

1. generated new offline seed
2. went in iota wallet to reclaim tool
3. confirmed old seed and new seed
4. new seed used now and wallet balance is zero

**Expected behavior:** 
I would like to have my coins back

**Actual behavior:** 
coins disappeared

### Versions

[Windows 10 Home - Version 1709 - OS Build 16299.192]
[IOTA Light Wallet 2.5.7]

**Comment by rajivshah3** [comment]
Not all of the reclaims have been processed. Please wait for yours to be processed.

**Comment by tedtankal** [comment]
Hi. Just wondering why I still haven’t got my coins ??
It s been too long. 
Please advise 

Teddy P. Kalife

**Comment by tedtankal** [comment]
Hi
It s been a long time since my message. And still today nine of my coins are shown. Please advise soonest

**Comment by tedtankal** [comment]
I just verified the address to wich my iota coins were attached on thetangle.org and found out that the balance was transferred to another one????? !!!!!
Please help !
How can this happen????

the address is below for your follow up:
PKFWURYWDI9KIPIWVZKKKAL9SKYVJUWOFNENZOLZQLCKUTQYAJNSWAZIKHZCFZRZKNBMGLSGZUVVWOEFWJSYTDIJX9

**Comment by lo5tinpr0** [comment]
Hey @tedtankal , please have a look at #1196 and check the way you created your seed.
To be clear, there is only one way to transfer IOTAs: You have to know the corresponding seed.

**Comment by tedtankal** [comment]
Hi
I have already checked. 
And I created my seed offline. Also was quite familiar with transfers. Already did it to hitbtc exchange a while ago. 
My coins have been stolen it seems !!!
Can you do something about it?!

Teddy P. Kalife

**Comment by lo5tinpr0** [comment]
As I have already written, transactions can only be executed with the appropriate seed.
All situations similar to yours I have experienced so far have been due to the fact that the seed was not safely stored or known to someone else.
Is there any chance that someone else knows your seed?
And no, there is no way to get IOTAs back once transferred. This is technically impossible.
