### ISSUE TITLE
Can't use 47.25 mIOTA (million)

### ISSUE THREAD

**Issue by mallond** [iotaledger/wallet#1082]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

Description

This is a harry audacious deal-breaking bug. 

I have a confirmed address of 47.25 mIOTA at address: KNZWZMHMIGGQDTAJHF9PNYIVTDSGQINABL9TZKFXTSVPUKDXALKPLUAO9GG9XWTATGCVZWB9X9DEOQLTBBZQVPFRXZ

I have done all that was requested and cannot see nor transfer any funds.

1. Log in with seed, show zero balance
2. Promote
3. Reatach

Zero balance happened when I switched to another IOTA node. There was a 1000 iota transfer pending. Went back to orginal node that was showing balance, and both showing 0 balance.

48 hours and waiting no change - Jan 30, 2018

Expected behavior: To see my balance and transfer funds

Actual behavior: Zero balance 

Versions: 2.5.6

OS Version: Mac El Capitan
2.5.6

**Comment by rajivshah3** [comment]
Please update your wallet to the latest version. If this still happens you are most likely using the wrong seed. This is not a bug

**Comment by mallond** [comment]
Updated to the latest, it now works.
