### ISSUE TITLE
iota wallet contains 0 balance

### ISSUE THREAD

**Issue by agharibkhanyan** [iotaledger/wallet#1087]
hey guys. so after returning from vacation i logged on my iota wallet and my balance is 0 . i should have 500 so i dont know what happened. my transfer history had 0 sent and 0 received as if the address was new. any help pleaseee?

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

**Comment by agharibkhanyan** [comment]
hey thanks for the help also when i look up my iota address on a website that tracks it my original withdrawal to my wallet now says pending

**Comment by agharibkhanyan** [comment]
the new upgrade wont open on my computer after i download it??
