### ISSUE TITLE
stole from the iota wallet

### ISSUE THREAD

**Issue by rostov4anin** [iotaledger/wallet#1088]
Hey . Iot coins were missing from my purse. 600 coins were simply stolen, transferred to another purse. There was no access to my laptop. I ask you to understand and if possible return my funds. Wallet number MF9SJVSDRGBRUNAKJYZHIGQKYGMMGDQIEHPMGELKATHHRVQGODHKLW9DWVLPUWYKNT9QRFSNZVJICKSYYOGE9CARZC

**Comment by yippykaiyay012** [comment]
Where did you generate your seed?

**Comment by rostov4anin** [comment]
created himself
went to the purse   GAAITAYDDTTCNAQLCGOKHGSDEHFPECL9THPK9ZOCAPWLJPQTMOARHF9OJHKHPFOWWTIOPPRLIQVHJ9DKDYTFM9UYP9

**Comment by legsh71** [comment]
I have similar issue; I had transferred iotas from the exchange (binance), then 2 days later funds were sent on its own to some address I had no idea about, and then after trying to tangle it, reclaim, etc with no results; one day wallet not only does not show my funds, but also the history of the transactions is gone.
I had created my seed myself, without any generation tools; it allowed me to login into my wallet, generate receive address, transfer funds to the wallet and then loose it all somewhere in iota world.
At this point i feel like this whole iota system is just a scam

**Comment by wonkytonky** [comment]
@legsh71 google iota snapshot

**Comment by rostov4anin** [comment]
was like this

![image](https://user-images.githubusercontent.com/36049167/35696571-eaa48854-0798-11e8-938a-557d3a22868e.png)

**Comment by rostov4anin** [comment]
now updated and there is now this
![image](https://user-images.githubusercontent.com/36049167/35696680-29066496-0799-11e8-92de-96d5f3b0f360.png)

**Comment by wonkytonky** [comment]
gene
![image](https://user-images.githubusercontent.com/19390834/35696970-318a6ae6-0789-11e8-9e2b-7f16bec12373.png)
seems about right.. you send 21mi out.. and the remaining is back in your wallet

**Comment by rostov4anin** [comment]
I had 600 coins
![image](https://user-images.githubusercontent.com/36049167/35697166-74eceda2-079a-11e8-8c32-72fc666a282e.png)

**Comment by wonkytonky** [comment]
which address had 600iota?

**Comment by wonkytonky** [comment]
generate a lot of addresses in your wallet, maybe your wallet hasnt generated all addresses yet  after snapshot

**Comment by SimpleGenius23** [comment]
I had the same issue with 999,97 iota.. gone...
