### ISSUE TITLE
Balance and Transactions disapeared!!

### ISSUE THREAD

**Issue by douglasapolinario** [iotaledger/wallet#1089]
Hi, my balance and transactions history disapeared from my wallet. I would like a help.

**Comment by wonkytonky** [comment]
wrong seed

**Comment by legsh71** [comment]
same here; first my iotas were gone and now history of the transactions; hope somebody could advise how to contact somebody at iota to explain what happens/happened;  have one seed I had created myself before logging in initially into the wallet and then after multiple attempts to tangle, etc went through reclaim process; now have old seed and new one and no funds back; no old history

**Comment by EmbeddedAndroid** [comment]
So I found this, https://www.finder.com.au/iota-snapshot-on-sunday-what-iota-holders-need-to-do-before-then, solved the problem above.

**Comment by douglasapolinario** [comment]
@EmbeddedAndroid thanks. This post worked to me.

**Comment by mjpablo23** [comment]
yeah basically keep attaching to tangle and generate new addresses

**Comment by Mushu16** [comment]
Hi guys, I also had the same issue of balance not showing, but the solution is

Not all nodes are active or able to connect to, so I connected to the
----Wallet Configuration ----
cryptoiota.win:14265 Host
Min Weight = 15
Curl Implementation - Webgl 2 curl implementation

and when you sign in to wallet,
keep generating new receiving addresses until it gets connected to the Tangle Network
(good indication that your computer is trying to connect is the bottom left showing CPU usage Fluctuate up and down)
