### ISSUE TITLE
Misleading FAQ "You can generate a seed via Tools » Generate Seed"

### ISSUE THREAD

**Issue by coolslon** [iotaledger/wallet#109]
In help -> FAQ -> Help -> Creating a New Account is written "ou can generate a seed via Tools » Generate Seed". But there is no such option in tools menu:
![image](https://user-images.githubusercontent.com/3864178/27055339-c1242842-4fcc-11e7-9c34-244f243932f4.png)

**Comment by atypicalprogrammer** [comment]
Will be removed from FAQ, thanks!
