### ISSUE TITLE
Wallet empty with no history

### ISSUE THREAD

**Issue by cryptobanyasz** [iotaledger/wallet#1091]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [x ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x ] I confirm that this issue is present on the latest version of the wallet

### Description
The iota wallet is empty and has no transaction history at all. It's like a brand new installation. I installed the new version and still having the same issue, blank wallet. 
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen] 

To see my funds in the wallet as before.

**Actual behavior:** [What actually happened]

Wallet is empty with no history.

### Versions

[OS Version] Windows 10
[Wallet Version] 1.4.2.1

**Comment by chrisdukakis** [comment]
Hello @cryptobanyasz did you try to click receive and attach the addresses you've previously used to tangle? This should allow to access your funds.

**Comment by AugisRim** [comment]
But should we remember these addresses from history? And how it is possible to attach?

**Comment by cryptobanyasz** [comment]
I didn’t tried that. I was just simply opening it like before but this time is empty.

**Comment by cryptobanyasz** [comment]
I attached a previously sent address as suggested to tangle and I am back with the funds, all good. It was a bit confusing the attach part because you cannot erase the receive address and when you right click to paste nothing changes visually but it does work. Thank you all for the help.

**Comment by wonkytonky** [comment]
please close issue if fixed..
