### ISSUE TITLE
my Iota balance got stolen !!!

### ISSUE THREAD

**Issue by aalsaggar** [iotaledger/wallet#1092]
I left most of my iota in an exchange , but I had 70.5 in the wallet (I'm using mac) I just logged in and i saw the balance as 0 , it was sent out 4 days ago , below are the details:

Hash : ZJEITGUBRTWJUNDQTTEEKANNNFGPQCYCQQICFAVJY9FWEHOVJZEKXJUGMLKRQ9MWCDQTQMSROTKL99999
Receiving address: 
GLVMIGWZARPEMUCHACHUKADTCVVCPQ9HFITNUHNSWFLHPBWWNXEELXHROFBQNRDHIPYSQEQMYVSSBJEDBJXRLBGKUX
My address :  
YUWMJJ9OLGUAUCRGDPIURS9YOYQEYFKXGWIRHNNA9LXGWIAALDPENZNZNZAPJGQBPBLWGEFCNUUABYCTZVJYMZAU9C

does that mean it got stolen or there is something I don't know ?

**Comment by wonkytonky** [comment]
how did you generate seed?

**Comment by aalsaggar** [comment]
on an online generator, I remember that I searched a lot about it before using it

**Comment by aalsaggar** [comment]
this one :  
https://iotaseed.io/

**Comment by TomOnGit** [comment]
For the love of .. please just include a simple link “how to generate a seed” in the wallet to a pen article with trustworthy information..

I’m quite. A technical user and couldn’t figure it out. List 228 iota due to using online generator.

Just add a simple link and most of these issues will be prevented.

**Comment by wonkytonky** [comment]
@aalsaggar  thats a scamm website, it will take your seed and steal it

**Comment by aalsaggar** [comment]
I guess it's my fault that I got scammed but you are right @TomOnGit they should include a link , they are doing a bad job and that's not a good indicator on the future of the project.
