### ISSUE TITLE
again wallet not working

### ISSUE THREAD

**Issue by Tiguan01** [iotaledger/wallet#1093]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [ x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ]x I confirm that this is not an issue related to stolen/lost funds
* [ x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by Tiguan01** [comment]
My wallet again not work vers. 2.5.6.  also mining does not work anymore.
Have tried diverend nodes but nothing works.
Also send mu iota to another adress does not work

**Comment by wonkytonky** [comment]
v2.5.7

**Comment by Tiguan01** [comment]
installed v2.5.7 same problem cannot send

2018-02-02 21:05 GMT+01:00 wonkytonky <notifications@github.com>:

**Comment by wonkytonky** [comment]
more info

**Comment by rajivshah3** [comment]
Is there a specific error message that you get?

**Comment by yavordrones** [comment]
my funds are gone. no history no nothing. shitcoin

**Comment by rajivshah3** [comment]
@yavordrones https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

**Comment by Tommyt1ckle** [comment]
Hi

I'm in a similar position.... can anyone help please?

Address
JOXKMYOILIQEWEELFHVDVNRJXDWJGAREJ9HGZOZEHZHHLPNT9JGDMCCEKYRZDGKBVPBCCWKEDFELNMWTLVBKJEVLFH

TXID
QHWZIYFUYIDAZ9CYPOTX9DFZNJN99UU9RVYCRH9OGLK9JJHHOVFHJDAHNSOIKYFKMXGHUHVJYFM999999

Address
PKFYVJYWJUWOBM9MWASNY9JNEUSOBGXO9RNPPQTO9ROFSDVGTPV9EODXZOVJEPDVHZAAFGRAVIYHTOVEBMPVIXOAPX

TXID
9HAHNVFYYLTZYNMQLINPBEEWXKMCKXV9F9TPNPADQRBYQJJ9ZECWYQBWIUGLXTHTUNOKRJKB9ZTT99999

**Comment by rajivshah3** [comment]
@Tommyt1ckle please complete the reclaim process, this is not a wallet issue and should not be reported here. For more info see https://blog.iota.org/gui-v2-5-2-latest-release-with-iota-reclaim-tool-32d364d6241a
