### ISSUE TITLE
iota stolen 1/29/18

### ISSUE THREAD

**Issue by papadrew2954** [iotaledger/wallet#1094]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by papadrew2954** [comment]
i had 49.5 iota transferred out on 1/29/18.  i believe they were stolen . i have no idea what to do . im hoping someone can help or point me in the right direction 

BUNDLE DETAILS

Hash:
JLCEAIKZNEDBKYMDLUFZYJ9YHLIWGYDK9AXNYAPBZHEZVXWBUHRABCGHEFYRLCE9WGENUKZCAGYTPJMECPGJBKVSWW

my address
JLCEAIKZNEDBKYMDLUFZYJ9YHLIWGYDK9AXNYAPBZHEZVXWBUHRABCGHEFYRLCE9WGENUKZCAGYTPJMECPGJBKVSWW

receivers address
XU9MWQDILQPXZOHTVDN9PMITLDVWOPSNNFDBJMWDUGMTBKX9KPOAZPADNUJ9PTUWHLWHQKSIBWUDZWFXYCIFMBTJZW

**Comment by wonkytonky** [comment]
how did you create seed?

**Comment by papadrew2954** [comment]
I’m pretty sure I used an online seed generator . After a little research, I see that this has recently happened to many . Is there any way to get them back ?

**Comment by papadrew2954** [comment]
Also , that hash is wrong . I can post the correct one when I’m home in a few hours

**Comment by wonkytonky** [comment]
online seed generators often are scam websites.. don't use them
 i think you created the same issue before .

**Comment by papadrew2954** [comment]
Same issue. I accidentally closed it after I created it

**Comment by xcbmcc** [comment]
Hello !
I have a big problem . After the last wallet update my balance is 0. and History does not show my old transactions. only a transaction with the entire amount of the wallet withdrawn but not confirmed on January 30th.
I mention that I did not make the seed online.
I tried all my wallet recreation steps but I did not succeed.
I tried with reclaim tool from my wallet and created a now seed but ..
Balance 0 remained, and only transactions with the "pending" balance are shown.
But it is not just a withdrawal transaction, there are many with the same amount.
The last jot address I'm familiar with is the one I filed from binance.
9AUQXALENPUOPNLGGXFNTFBG9VVZKAIDWQBALJFJBZFNAAEVBFIHSE9SSRPRVMXBYWUDJLULDSULEHNKDDTUISMMLC

Any suggestion? Help me please.

**Comment by srsgmrcy** [comment]
ok . you enter iota wallet . and you click receive . and click attach to tangle . keep clicking until the money comes

**Comment by xcbmcc** [comment]
How many times ? I try that i think for 30 times ..

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab
