### ISSUE TITLE
My Iota Wallet is reflecting no balance, my tokens have been taken from my wallet 

### ISSUE THREAD

**Issue by NelsonNS** [iotaledger/wallet#1095]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [8*] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [* ] I confirm that this is an issue with the wallet, not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [ ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ *] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature] I don't know about a bug, but my tokens have been taken from a wallet, this wallet to be exact. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen] I expected that my tokens have been taken from my wallet because I once had a balance and now there isn't a balance. 

**Actual behavior:** [What actually happened] Missing tokens or just maybe "misplaced"? 

### Versions

[OS Version]
[Wallet Version] IOTA Light Wallet 2.5.6-IRI 1.4.2.1

**Comment by wonkytonky** [comment]
download lastest version wallet
generate addresses until balance is showing up again

**Comment by srsgmrcy** [comment]
ok . you enter iota wallet . and you click receive . and click attach to tangle . keep clicking until the money comes

**Comment by y5hot** [comment]
Am not sure you read my message fully. I have already clicked attach to tangle multiple times and still zero balance. This is not working.

**Comment by NelsonNS** [comment]
That was helpful! I have all of my Iota back into my wallet!!

**Comment by y5hot** [comment]
not for me

**Comment by NelsonNS** [comment]
I don’t understand how? I had the same exact issue. My wallet was empty, had no transaction history. Until, I went to receive and kept selecting GENERATE NEW ADDRESS; I click it a bunch of time. I kept doing it continuously for at least 10 tines and the coins slowly started to appear.

**Comment by rajivshah3** [comment]
This might help: https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

If this process doesn't work for you, make sure you did not use a malicious online seed generator. This is not a wallet bug and should not be reported here.

**Comment by NelsonNS** [comment]
I was able to get everything resolved. Since I don’t work on your end, please let me know how I’m suppose to know it wasn’t a bug? No need to respond, just wanted to put it out there.

**Comment by rajivshah3** [comment]
In the checklist of your original post, you should have seen this option:
```
I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
```
You did not check that box. That issue was mentioned as one of the issues not being a wallet bug

**Comment by y5hot** [comment]
I am seriously freaking out now. I have tried all week re attaching addresses and still ZERO balance. I have also ensured all addresses I have generated are confirmed, rebroadcasted etc and STILL ZERO BALANCE. I then went to  https://iotabalance.com/ and pasted my wallet addresses I know for a FACT have balances and STILL ZERO. - I NEED HELP as I am so stressed out.

Below is showing Zero in my lite wallet,

Balance 9.5 mi

Address	LEOQZUPAHFWZ9HHUKGBJSFSUWDZJVCGOCY9OUSNHZMAHTBBTNBTRCHAUAEWAYUGOTKQBFK9WRDHCTBIR9N9KXPFLUB

Txid	ZPOFUIWUJLWXUHTWPBEQSHWNJZPMZIBVOYBIYKHJGNMEEDET9QVARVGCGFSUYMRMMKVFLU9REW9U99999

**Comment by y5hot** [comment]
I can confirm I did not use any malicious seed generator I can confirm there was no History when i logged in and when i re generated my addresses and checked the transactions no outgoing transactions showing IOTA going out. ?

**Comment by y5hot** [comment]
Should I use Reclaim Tool ?

**Comment by y5hot** [comment]
I am happy to pay someone to help me !

**Comment by y5hot** [comment]
I used the Reclaim Tool and this still hasnt worked

**Comment by y5hot** [comment]
Hi Can someone check https://thetangle.org and explain what has happened:  I had 9.96 Gi in this address SRWNYEFKAHFKRFP9GEPIZVNEWIXKURSOZHVAYQNQODYNSRRSFCCZ9FHJTSLS9D9BCBZAZCCAAUQTRKJCDOYXZAFPNW but now it is zero I am not sure why the funds are in another address ? is this custody address ?

**Comment by rajivshah3** [comment]
Please go to http://forum.helloiota.com for help. This is not the correct site for help
