### ISSUE TITLE
Iota lost ? 

### ISSUE THREAD

**Issue by xcbmcc** [iotaledger/wallet#1096]
Hello !
I have a big problem . After the last wallet update my balance is 0. and History does not show my old transactions. only a transaction with the entire amount of the wallet withdrawn but not confirmed on January 30th.
I mention that I did not make the seed online.
I tried all my wallet recreation steps but I did not succeed.
I tried with reclaim tool from my wallet and created a now seed but ..
Balance 0 remained, and only transactions with the "pending" balance are shown.
But it is not just a withdrawal transaction, there are many with the same amount.
The last jot address I'm familiar with is the one I filed from binance.
9AUQXALENPUOPNLGGXFNTFBG9VVZKAIDWQBALJFJBZFNAAEVBFIHSE9SSRPRVMXBYWUDJLULDSULEHNKDDTUISMMLC

Any suggestion? Help me please.

**Comment by t6omas** [comment]
I have the same problem, but I have not used seed generator. Do you have a solution to this problem?

**Comment by srsgmrcy** [comment]
ok . you enter iota wallet . and you click receive . and click attach to tangle . keep clicking until the money comes

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

**Comment by Netzarim** [comment]
I had about 150K iota disappear.  I did not use seed generator either.  All transactions in the wallet disappeared as well...

**Comment by xcbmcc** [comment]
I try to reatach to the tangle more then 200 times but my founs balance remain 0 .
9AUQXALENPUOPNLGGXFNTFBG9VVZKAIDWQBALJFJBZFNAAEVBFIHSE9SSRPRVMXBYWUDJLULDSULEHNKDDTUISMMLC

My iota are lost or is just a bug ?

**Comment by t6omas** [comment]
impossible to recover the iota, it's really weird this problem
