### ISSUE TITLE
reclaim of my iota

### ISSUE THREAD

**Issue by srinirajavelu** [iotaledger/wallet#1097]
Hi,
my iotas are missing when I transfer iota to one of my address due to "key reuse". So I tried reclaim tool to claim my iota and I completed the reclaim process successfully . but balance are not reflecting in my new seed (wallet). after that I have tried one more time to reclaim. will I get my iota back in my new address? . how much time I should I wait (waiting for last one week)?. is it fine if I reclaim multiple times? .

**Comment by rajivshah3** [comment]
This is not a wallet bug. Please do not report this here. You can find help at https://forum.helloiota.com.
