### ISSUE TITLE
Seed / Password checking: from notification to validation

### ISSUE THREAD

**Issue by coolslon** [iotaledger/wallet#110]
Basic idea is that UI should be **fool-proof** for general adoption.
1. Seed checking should happen before logging in (not as a current solution with showing notification after logging in). This way user would be informed from GUI itself that their SEED is invalid/week/insecure etc. This is a usual way like validation work in most popular products.
2. Maybe "Password" could be removed, as for normal user "password" word is associated with something they can keep in memory and retype. 81 random char seed is not this type of thing. Also, it is usually everywhere allow numbers, which is not a case for the wallet.
3. Maybe some icon or text link could be added to describe what is SEED? Something like this:
![image](https://user-images.githubusercontent.com/3864178/27056551-292fe224-4fd1-11e7-8956-c03fcacaa0ef.png) so that user should not guess what is it or search info about it.
4. Popup could be displayed after starting wallet for the first time "What is seed and why I should keep backup of it?". This popup could have a checkbox "never show this again" to hide it for next run.

**Comment by atypicalprogrammer** [comment]
Invalid seeds are no longer allowed to log in. Password is removed also. Will add question mark that links to FAQ for seed information.
