### ISSUE TITLE
I open my iota light wallet 2.5.6. today and my balance was to 0 ? I got no history of transaction in my wallet ? It look like it still there when i check on the tangle but nothing in the wallet when i open it with the seed.

### ISSUE THREAD

**Issue by Cryptocollector** [iotaledger/wallet#1101]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [ ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by wiki-qi** [comment]
me too ，how to solve this problem

**Comment by Cryptocollector** [comment]
Sorry guys' it's all good now. I've didn't see about the snapshot.
