### ISSUE TITLE
hi i lost my 200 miota , i made two transaction from binance on eis 9 miota another is 190 miota, earlier it was showing balance , but before one week showing zero balance , when i check the address transaction history found 9 iota showing  trans. history but 190 iota histroy not there, what should i do? may be some one has stolen ? address are BFZJXTCKZRHBXHWEIGTXWBXLOVMY9MNMMLFPFZRBNPVXCGMHQCVVRUQPCWXSIUMJHMDJYMVAZPUSLTSZZPAAKJNYKB & second is XTGBRMKAWL9VHSITEYCQKXVZLEJPLOPXWBOMQVPFYG9UMUCEHVMQO9AMHULAHCIADDTRXYPUKVZRXHBDYEPXQD9BDC

### ISSUE THREAD

**Issue by vikassoniengg** [iotaledger/wallet#1102]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA  and not an exchange
* [ ] I confirm that this is an issue with the , not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [ ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the 

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[ Version]

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

**Comment by vikassoniengg** [comment]
Thanks for your reply, but how can I get back my iota


Thanks & regards,

Vikas jain

+971554867003

**Comment by rajivshah3** [comment]
After looking again, it seems like your IOTA were unfortunately stolen. As the transaction is confirmed, it cannot be reversed
