### ISSUE TITLE
IOTA Wallet Showing 0 Balance - No transaction history

### ISSUE THREAD

**Issue by IAMCZR** [iotaledger/wallet#1103]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [X] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [X ] I confirm that this is an issue with the wallet, not IRI
* [ X] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [X ] I confirm that this is not an issue related to stolen/lost funds
* [X ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [X ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [X ] I confirm that this issue is present on the latest version of the wallet

### Description

LOG INTO THE WALLET
NO BALANCE
NO TRANSACTION HISTORY
CREATE RECEIVE ADDRESS
RE-ATTACH AND PROMOTE MULTIPLE TIMES
NOTHING

### Steps to Reproduce

? 

**Expected behavior:** [What you expected to happen]

THIS IS WHAT SHOULD BE HAPPENING:
1. LOGIN
2. SEE THAT MY FUNDS ARE STILL THERE
3. SLEEP AT NIGHT KNOWING THAT I DIDNT GET ROBBED!

**Actual behavior:** [What actually happened]

WTLHYRFHVLSCJYSSAJSYLVXDFRXUCTHKRLIQFHPJTYQKLISMDXCXCYTMOOWIAAMOVQYAQHAYFJVZGJ9DWTNWJ9JNDB

2.5.7 IRI 1.4.2.1

WINDOWS 10

**Comment by wdsadsalgasd** [comment]
I have identical problem. Didnt open wallet one month. Now is balance 0 and I have 500 coins in the wallet

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab
