### ISSUE TITLE
I keep getting "iota.api.wereaddressesspentfrom is not a function" when trying to send IOTA

### ISSUE THREAD

**Issue by michpohl** [iotaledger/wallet#1104]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [ x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ x] I confirm that this is an issue with the wallet, not IRI
* [ x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ x] I confirm that this is not an issue related to stolen/lost funds
* [ x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ x] I confirm that this issue is present on the latest version of the wallet

### Description
On windows 10:
When I try to send any amount of IOTA I keep getting the error message "iota.api.wereaddressesspentfrom is not a function"
I've tried multiple addresses to make sure it's not related to the address I'm using. 

### Steps to Reproduce

1. Send IOTA to a receiving address
2. See error message

**Expected behavior:** it should just send them, right?
**Actual behavior:** wallet shows above mentioned error message.

### Versions

[OS Version] Windows 10 Pro 64bit
[Wallet Version] 2.5.7

**Comment by rajivshah3** [comment]
Have you tried reinstalling the wallet?

**Comment by michpohl** [comment]
Oh no, what a stupid mistake! Of course I forgot to do that. Thank you, it works fine now.
