### ISSUE TITLE
zero balance after upgrade (or snapshot) not corrected by recommended actions

### ISSUE THREAD

**Issue by Eporediese** [iotaledger/wallet#1105]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [?] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

zero balance and no history after upgrading to 2.5.7 and logging for the fist time for a couple of weeks

### Steps to Reproduce

1. Upgraded to 2.5.7 on 2/3 and logged in for the first time in a couple of weeks. Checksum is correct.
2. After reading https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab I attempted to generate and connect 11 adresess. I do not have a record of the addresses that I used before that the upgrade but there was only ever one or two at the most. I only ever received IOTA, not sent
3. At various times I have I re-connected the new addresses, tried promote, broadcast, attaching to other nodes ...

**Expected behavior:** To see a non-zero balance and my true transaction history

**Actual behavior:** Still seeing a zero balance and the addresses that I generated on 2/3 or later in the history, each with 0 iota transferred. Some of these transactions show Confirmed and some show Pending (even though re-attachments of the bundles show confirmed).
![lite_wallet_257_issue](https://user-images.githubusercontent.com/34603224/35835779-a2d61168-0aaa-11e8-856c-c9e0162eb0a6.png)

### Versions

[OS Version]
Window 10
[Wallet Version]
Lite wallet 2.5.7

**Comment by ZaneCEO** [comment]
SAME here! Please note that under you click `11 Addresses` you can see all your addresses (also the first one). I see my 3, but no coins.

**Comment by Eporidiese** [comment]
Confirmed. All 11 have no coins. 
Some of these were addresses that I transferred coins to from Binance in December (and Binance has records of that).
I did check these addresses on Thetangle.org and iotasear.ch but there is no record there of any non-zero transactions or any activity before Feb 3.
I am thinking that this rules out that it is a wallet issue - seems more like an IOTA issue.
Thoughts?

**Comment by ZaneCEO** [comment]
In my case I fear I was scammed. Have a look here: https://www.reddit.com/r/IOTASupport/comments/7vrau1/have_i_been_scammed/

**Comment by Eporidiese** [comment]
I am not sure but this looks different (though perhaps not better). In your case, you can see some history and an incoming and outgoing(?) transaction. If you don't know where that transaction went, I would agree that it doesn't look good.

In my case there is no history at all for the addresses in question before Feb 3, even Binance used them to transfer funds to the addresses that I provided back in December. 
No non-zero transactions show up at all on the 11 addresses, either in my wallet or in the Tangle.
Big mystery ... to me anyway.

Good luck anyway. It's a learning experience if nothing else.

**Comment by ZaneCEO** [comment]
Good luck to you too.

**Comment by rajivshah3** [comment]
@Eporidiese if you aren't seeing any history on iotasear.ch or thetangle.org on the addresses you generated, you probably have the wrong seed

**Comment by Eporidiese** [comment]
Thanks Rajiv, but I don't think that is the problem as:
1) My checksum is the same
and
2) The addresses that I re-generated using my seed in the lite wallet (and the offline paper wallet) are the same as the addresses that I used to transfer IOTA in December.

**Comment by wonkytonky** [comment]
then you should  be able ot trace your money thetangle.org

**Comment by Eporediese** [comment]
Ah ... yes, now I see it at least for some of my addresses. My IOTA were apparently stolen on Jan 20. 
https://thetangle.org/address/VZHVNJYCIWHPWDNUXNPRRREVYJGELPJMJJZERSFYFQTQ9QT9CDHLYCIKJJXISHVUGFUVISOSOJKJKEODB

Thanks for your help rajivshah3 and wonkytonky.

**Comment by KirillMd** [comment]
Hi, guys! I have some problem with my balance. Today, after a couple of week I opened my IOTA light wallet 2.5.6. and saw 0 balance, but I had my iota tokens there. I see my transaction and balance on thetangle.org but no see in wallet. Could you help me, what should I do? Many thanks for any help

**Comment by KirillMd** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab
I helps!
