### ISSUE TITLE
There are no coins on my balance sheet (

### ISSUE THREAD

**Issue by tema-xa** [iotaledger/wallet#1109]
Good day!
I do not have any coins in the Light Wallet IOTA. There are coins on the phone in the wallet, there are no coins on the computer. The node changed, did not help. There are also no transactions in history. Where's all gone? What is the problem? Help me please.

p.s.: sorry for googlet ranslate))=)

**Comment by jkliachev** [comment]
Absolutely same issue. The transaction history is empty as well. This is very worrying in general. The seed was generated not on web and the security to wallet is strong. My wallet looks like as a new wallet.

**Comment by rishab8** [comment]
All you need to do is generate new addresses 
Your balance will come back

**Comment by jkliachev** [comment]
I tried to generate new addresses several time but it didn't help. The balance and the history is empty. Any other advise? Thanks!

**Comment by rishab8** [comment]
You have to atleast generate same number off address as you had before
Other then this there is no other way I know off

**Comment by jkliachev** [comment]
Hi, after more than 10 times trying to generate new address the balance is recovered finally. I don't know why it is happens but I definitely consider that there's still a lot of work on the wallet and the system as a whole. Thanks once again for the assistance!

**Comment by nasri10** [comment]
hi, can u pls help me?? I have the same problem. How do i generate new address?

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

**Comment by tema-xa** [comment]
Thank you! Coins in wallet))
