### ISSUE TITLE
Send transaction gives "private key reuse" error if the history shows pending transactions.

### ISSUE THREAD

**Issue by Kirppu81** [iotaledger/wallet#1110]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [X ] I confirm that this is an issue with the IOTA Wallet and not an exchange
I got the exchange done with older version.

* [X ] I confirm that this is an issue with the wallet, not IRI
Light Wallet 2.5.6 and 2.5.7 uses the same IRI version.

* [X ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
I got the transaction done with older version.

* [X ] I confirm that this is not an issue related to stolen/lost funds
Nothing has been lost.

* [X ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
It was a small amount, ~32ki on 6th February 2018

* [X ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
Transaction would not have succeesed this was the case.

* [X ] I confirm that this issue is present on the latest version of the wallet
Older version worked

### Description

[Description of the bug or feature]
IOTA Light Wallet 2.5.7
Send transaction gave "private key reuse" error. for fresh recieving address.
History shows earlier recieve transactions multiple times in two statuse confirmed and pending.

### Steps to Reproduce

1. Try to make send transaction with version 2.5.7, while history has pending transactions. Gave me private key reuse warning.
2. Try to make same send transaction with version 2.5.6, completes the transaction.

3. Verify transaction at iotasear.ch
Transaction found here:
https://iotasear.ch/address/CWFUXUZXEXRCR9YEAXDLEJFQPNLDDFETCDCOWPCRQYOXUACNUIFWQWDDIJI9VXWDXKDQFBHXRIMF9MLPDZAQANVXKA

**Expected behavior:**
Transaction to complete with version 2.5.7

**Actual behavior:**
Gave private key reuse error and didn't complete the transaction.

### Versions
Linux 3.16.7-24 [custom openSuse 13.2 installation]
Wallet version: Iota Ligh Wallet 2.5.7

**Comment by chrisdukakis** [comment]
@Kirppu81 This is because inputs have been spent prior to latest snapshot. (see: https://thetangle.org/transaction/IGTTVRLDCPKAOLIFIGKTWEOSBQXFW99WVCOOYQXWYFGMHMASRBIJU9ZGDODPAFEY9UVUSTNBKUTQA9999) You should not receive tokens to addresses you've previously spent from, it's not secure and wallet aims to prevent this. The 2.5.7 version detects spent addresses prior to snapshot, hence the difference.

**Comment by Kirppu81** [comment]
My understanding was that recieving to same address was fine, untill you spend the address balance partially or whole. Which raises couple of questions.

a) How can you send/spend your balance in the situation when you get the "private key reuse" error?
 * They can't be freezed for ever in the wallet...

b) Is there gonna be some auto relocate balance from partially used address?

**Comment by chrisdukakis** [comment]
You can't be spent those tokens, until sweeping to unused addresses is implemented.

**Comment by Kirppu81** [comment]
Thanks for the informative answer. Case closed.
