### ISSUE TITLE
Norwegian translation

### ISSUE THREAD

**Issue by resuschris** [iotaledger/wallet#1112]
Making a Norwegian translation of wallet.
will make a pull request when finished, but it will have to be spellchecked by third party before implementation. I have Left some of the Main iota terms in english because of risks of confusing and complicating usage.

File: [wallet/locales/no/translation.json](https://github.com/iotaledger/wallet/blob/master/locales/no/translation.jsonl)

### Versions

[Win 10]
[2.5.7]

**Comment by rajivshah3** [comment]
Hi, you can actually make these translations at https://crowdin.com/project/iota-wallet
