### ISSUE TITLE
Opened wallet and 0 balance   

### ISSUE THREAD

**Issue by pHbonz** [iotaledger/wallet#1113]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [x ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x ] I confirm that this issue is present on the latest version of the wallet

### Description

I opened my IOTA wallet today, first time in a week or so and found a 0 balance.  I have not sent any IOTA since last logged on to walle.  at that time I had 1.3 Gi... I tried several times to verify.  Then I uploaded the newest version and tried 2 more times.  Still 0 balance... what is up?

### Steps to Reproduce

1. open wallet
2. 0 balance
3. updated version, still 0 balance

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
failed to show my actual balance

Version
2.5.7

[OS Version]
Windows Light Wallet

**Comment by jkliachev** [comment]
Hello, 

I had the same issue. This is due to the newest changes that IOTA made recently. The solution is to generate new addresses a few times wait for ~10sec and then your balance should be back again to your wallet.

Best

**Comment by pHbonz** [comment]
Awesome.... that worked.   Thanks jkliachev, you saved me....

**Comment by pHbonz** [comment]
Thanks so much... did it and it worked..

**Comment by KirillMd** [comment]
Hi, guys! I have the same problem with my balance like pHbonz. Today, after a couple of week I opened my IOTA light wallet 2.5.6. and saw 0 balance, but I had my iota tokens there. Could you help me, what should I  do? Many thanks for any help

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

**Comment by KirillMd** [comment]
Thanks a lot rajivshah3! It helped!
