### ISSUE TITLE
This Guy keeps stealing and YOU keep doing NOTHING 

### ISSUE THREAD

**Issue by NelsonNS** [iotaledger/wallet#1116]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [ x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [ x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [x ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ x] I confirm that this issue is present on the latest version of the wallet

### Description: Once again a VERY well known (posted all over your site )thief accessed my wallet and took my IOTA. 

[Description of the bug or feature]: It may be your bug to access funds. 

### Steps to Reproduce

1. [First Step] You guys need to find a way to stop this person and actually develop a working wallet. 
2. [Second Step] You guys should REFUND all of your investors 
3. [and so on...] And this should make good on everyone who believes in you 

**Expected behavior:** [What you expected to happen] I wish you would give me and everyone else that can show proof if being a victim of thief their tokens 

**Actual behavior:** [What actually happened] My wallet was ACTUALLY accessed and tokens were ACTUALLY taken. 

### Versions

[OS Version] 2.5.6
[Wallet Version] I.R.I 1.4.2.1.

**Comment by wonkytonky** [comment]
what is the wallet issue here?

**Comment by NelsonNS** [comment]
I received this notice in my wallet that my tokens were taken. Please see below.

**Comment by wonkytonky** [comment]
how did you create seed?

**Comment by NelsonNS** [comment]
I created my own,  by following a step-by-step video on YouTube.

**Comment by wonkytonky** [comment]
what video ? i 'll look at the steps

**Comment by NelsonNS** [comment]
https://youtu.be/nQy0XvCp3Sk here is the link

**Comment by wonkytonky** [comment]
the video shows a few ways to generate seed.. which one you used?

**Comment by wonkytonky** [comment]
keylogger could have taken it this way

**Comment by NelsonNS** [comment]
I wouldn’t be able to tell you or confirm. All I do know is, my tokens were once there then I saw them all get withdrawn

**Comment by shufps** [comment]
Please send an address which should have balance.

I never heared something about a VERY well known thief ...

**Comment by hammercrypto** [comment]
I've experience the same to find my wallet completely empty when I generate my own seed not using any online tool and I have a keylogger detector on my computer.  Obviously from ready articles it seems that this is not just a few wallet but many many wallets experiencing this major problem.  Any answer would be appreciated.

**Comment by NelsonNS** [comment]
Not to sound mean, but with the support crowd here, no matter what you say, they will only place blame on you. I have exhausted my days attempting to get things resolved and it won’t happen. They won’t pay you what you lost and they won’t help you create a barrier. So, I found it best to just walk away from this product.

**Comment by NelsonNS** [comment]
Hello! 

Please see below 



I have taken the address listed about and did a google search and have found that the address above has been tired to many Iota wallets for taking their tokens. So if that’s not well known then I don’t know what would be considered. This individual or individuals are on a google search then I must say they are known!

**Comment by shufps** [comment]
Would it be possible for you to just write things clearly with information you have?

I won't ask a third time ... It is mandatory to GIVE INFORMATION when wanting help and not blahblah without any information content.

**Comment by ascendant337** [comment]
The same thing happened to me. It si funny that that same day, January 23rd, I had Iota in the wallet and I was trying to send it to Binance as I wanted to cash out. When funds never arrived, i started investigating and my friend has found my funds at this address
NOFUKFKSLVRB9DFNRIXBKEQ9PQJLLONOTJHGFJZJHIPOBBMLTJPNPDKKCVXJIMZYKBOGWGCKXPWTIXXLCKENOEL9JD
I am at a total loss about what to do to recover funds.
I did harass Bianace support claiming that I sent them the funds, and they keep repeating that is not their deposit address. Then I asked them to send me the list of newly generated addresses from my Iota deposit page(to which I sent funds), they just closed the conversation for comment. There was a follow up link so I did that(twice, as the closed the follow up link the first time) and asked them again what happened to the funds and for the list of deposit addresses. In my Iota wallet, there is no history of any Send, just my deposit reattachment addresses(I tried to see if Iota would show up, as usually does, but it did not).
I do understand that is my responsibility to generate seed but the information on this subject was completely unknown to me last year when I did the transition to the new wallet(I had the old iota wallet seed generated by programmer friend). The new seed I generated was online and I thought nothing of it as the transfer was complete and such. The iota showed up in the new wallet.
The one thing I do not understand is how a thief can see that I am sending iota to Binance and can act before me the same day?
And to the thief...I love you man, enjoy your retirement.

**Comment by shufps** [comment]
Did you use powershell for generation the seed? The random generator is very weak and the seeds can be bruteforced in a couple of hours.

Online-Seed generation is known to be stolen ...iotaseed.io is one of them (I think they now have another domain which does exactly the same).

**Comment by ascendant337** [comment]
I used an online generator, it all looked legit, so I thought that is the way. I am not sure what website was it then. 
I can see the funds here: 
https://thetangle.org/transaction/NHRYVPODBPFMUIPIKODKUOJWTDYDBCQBLSJXHJLYENYQJAUFZLOAPZGW9FF9CMZYNHNWLO9KDGBJZ9999
Not sure if I can do anything to recover them?
