### ISSUE TITLE
Roubaram minhas iotas 

### ISSUE THREAD

**Issue by Fernando4568** [iotaledger/wallet#1117]
Prerequisites
If you are not suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

[x] I confirm that this is an issue with the IOTA Wallet and not an exchange
[x] I confirm that this is an issue with the wallet, not IRI
[x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
 I confirm that this is not an issue related to stolen/lost funds
[x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
 For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
[x] I confirm that this issue is present on the latest version of the wallet
Description: Once again a VERY well known (posted all over your site )thief accessed my wallet and took my IOTA.
[Description of the bug or feature]: It may be your bug to access funds.

Steps to Reproduce
[First Step] You guys need to find a way to stop this person and actually develop a working wallet.
[Second Step] You guys should REFUND all of your investors
[and so on...] And this should make good on everyone who believes in you
Expected behavior: [What you expected to happen] I wish you would give me and everyone else that can show proof if being a victim of thief their tokens

Actual behavior: [What actually happened] My wallet was ACTUALLY accessed and tokens were ACTUALLY taken.

Versions
[OS Version] 2.5.7
[Wallet Version] I.R.I 1.4.2.1.

**Comment by wonkytonky** [comment]
seems same guy as https://github.com/iotaledger/wallet/issues/1116
sockpuppet accounts probably

**Comment by rajivshah3** [comment]
https://blog.iota.org/the-secret-to-security-is-secrecy-d32b5b7f25ef

**Comment by simoesrdp** [comment]
Please I am very scared and disappointed will steal all my MIOTES, I have zeroed the criminal transaction was confirmed on the 30/01/2018 at 00:12 (follow the hach: WALS9CKXILBGGXYAQWUTBJOGQKEBBGEJYDJUNAV9ARYEQMHUMCEQJXYPFWIPVR9QVEXTBSJKTPKGZ9999

I created the seed on this site http://www.iotaseed.io. Someone help me please!
