### ISSUE TITLE
multiple monitor setup issue | 2.3.0

### ISSUE THREAD

**Issue by mettenian** [iotaledger/wallet#112]
I have a laptop with docking station and two external displays. If I close the wallet with the window on an external display, switch off external displays and reopen the wallet, the wallet window is not visible.

The x value stored in bounds":{"x":3666,"y":173,"width":520,"height":736} in "settings.json" is no longer valid. After editing this value, the window reappears.

**Comment by atypicalprogrammer** [comment]
Should be fixed in next release, if not, let me know.
