### ISSUE TITLE
ZERO IOTA COIN!!!! 

### ISSUE THREAD

**Issue by Feldjeger** [iotaledger/wallet#1120]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [Y] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ ] I confirm that this is an issue with the wallet, not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [ ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the wallet

### Description

Logged in my IOTA LIGHT WALLET and there were no my IOTA COINS!
Nearly one week ago they were in place

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** Want my coins back!

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version] - 2.5.6

**Comment by rridder** [comment]
Have the same problem, logged in after a long time suddenly al my tokens are gone. Can also not see history.

**Comment by Feldjeger** [comment]
Thank you! They are back (=

**Comment by naorye** [comment]
I don't see my coins too... tried to attach to tangle, generate address, change nodes but nothing helps. Any idea?

**Comment by giladtamam** [comment]
Have the same problem. I tried severl times.
Please help!
