### ISSUE TITLE
Wallet empty

### ISSUE THREAD

**Issue by Artur20000** [iotaledger/wallet#1121]
Good afternoon! When I decided today to go to the purse, I saw on the balance sheet 0. I changed many times "Edit Node Configuration", it's still on the balance 0. This how to understand?

**Comment by hammercrypto** [comment]
I have experience the same thing and tried to reclaim and nothing...lost all my iota at this point.

**Comment by shufps** [comment]
ask google how to get your iotas back after a snapshot

**Comment by lekor84** [comment]
Good day! The same problem, lost all 9.5 miota : - (What to do? Translation history is not displayed either.

**Comment by Artur20000** [comment]
I hope from the developers or employees will already answer the question: where are my miota?

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab
