### ISSUE TITLE
Iota Wallet is Empty/No History - My 29 IOTA Tokens are missing 

### ISSUE THREAD

**Issue by Sakara2018** [iotaledger/wallet#1122]
Hi 

I really need some help. I have just logged into my IOTA Wallet and it is empty, there is no history at all. 

I had approximately 30 IOTA Tokens and I sent 1 to an online exchange early January so I had 29 and now I have logged on and my wallet is completely empty.

**Comment by shufps** [comment]
ask google how to get your iotas back after a snapshot (which occured on 28st january).

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

**Comment by Sakara2018** [comment]
All sorted. Thank you very much for your solutions.
