### ISSUE TITLE
Wallet empty - no history - 135 miota missing

### ISSUE THREAD

**Issue by cryptoinvestment** [iotaledger/wallet#1123]
* [x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [x ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x ] I confirm that this issue is present on the latest version of the wallet

I try both 2.5.6 and 2.5.7 wallet for windows, tried different nodes and my seed was created by me. I checked about one week ago and it was there, now displays 0 and no history at all.

[Windows]
[2.5.6 and 2.5.7]

**Comment by shufps** [comment]
you checked the box  it is not a zero balance issue related to a snapshot ... probably IT IS.

Ask google how to get your iotas after a snapshot back.

**Comment by hammercrypto** [comment]
I tried this and it works... https://youtu.be/kFvX1Oy8-VE

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab
