### ISSUE TITLE
roubaram minhas iotas

### ISSUE THREAD

**Issue by Fernando4568** [iotaledger/wallet#1126]
boa noite sou Fernando eu tinha 10 iotas e sumiu da minha wallet gostaria de saber se vai ser devolvidas pelos responsaveis por este erro que afetou tantas pessoas ou qual atitude tomar quero minhas iotas devolta o erro nao foi meu !!!! aguardo respostas               Att Fernando

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

**Comment by Fernando4568** [comment]
boa tarde quero receber minhas iotas , eu quero respostas cade os responsaveis foram roubas 1 bilhao e 6 milhoes  de outra moeda e deram suporte ,entrevista deram satisfacao e vao devolver . cade voceis
