### ISSUE TITLE
missing iota

### ISSUE THREAD

**Issue by cr0manty** [iotaledger/wallet#1127]
i have 34 mi, but today im going to check my wallet and there is 0 balance, i try atach tangle(35 times) but my balance still 0, how can i back my iota?( i have transfer for my iota)

**Comment by cryptohustle808** [comment]
all my iota is missing too! havent log into my wallet for 3 days. i just logged in to find a zero balance. i had 441mi

**Comment by wonkytonky** [comment]
@cr0manty  was your history also gone? (before you did the 35 reattachments?)

**Comment by cr0manty** [comment]
@wonkytonky i checked ~20 jan, when i check there was 2.5.4 (in my history i had transfer before 35 reattachments

**Comment by wonkytonky** [comment]
generate a few more addresses.;  in background when you dont send all your money out 1 address.; it creates a new addres  to send the remaining amount

**Comment by cr0manty** [comment]
@wonkytonky i had 1 adress with all my iota, what i need to do now?

**Comment by wonkytonky** [comment]
as i said.. genereate a few more addresses ..

**Comment by cr0manty** [comment]
@wonkytonky generate, what next?

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

**Comment by cryptohustle808** [comment]
Thanks! I appreciate it!
