### ISSUE TITLE
Private Key Reuse - Funds Stuck

### ISSUE THREAD

**Issue by iutnL** [iotaledger/wallet#1130]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [ x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ x ] I confirm that this is an issue with the wallet, not IRI
* [ x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ x ] I confirm that this is not an issue related to stolen/lost funds
* [ x ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ x ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ x ] I confirm that this issue is present on the latest version of the wallet

### Description

I posted this on IOTA forums (https://forum.helloiota.com/11853/ERROR-PRIVATE-KEY-REUSE-DETECTED) and was told to post here instead. Here is the error I'm receiving.

**ERROR: PRIVATE KEY REUSE DETECTED!

You are attempting to sign a transaction with input that have an already been used. IOTA uses Winternitz one-time signature (W-OTS) scheme, due to it's `one-time` nature, the security of funds in an address decreases rapidly if you re-sign new transactions using the same key. Please wait for previous transaction to confirm, e.g. by promoting/reattaching, before sending another transaction.** 

From what I can gather online, this is because there is a Pending transaction in my History. However, I cannot Rebroadcast, Reattach or Promote the transaction, because when I click "Show Bundle", the message says "Persistence: A reattachment confirmed". 
I also tried creating a new seed/wallet. I sent a small amount from the original wallet to the new wallet and it worked. But when I changed the Receive address on the 2nd wallet and tried again with the full amount from the original wallet, I got the PRIVATE KEY REUSE DETECTED again. My funds are stuck.

### Steps to Reproduce

1. Make transaction
2. Reattach transaction while Pending
3. Try to send funds after 2nd transaction is confirmed and 1st is still Pending

**Expected behavior:** Send money to another wallet

**Actual behavior:** ERROR: PRIVATE KEY REUSE DETECTED

IOTA Light Wallet 2.5.7

**Comment by rajivshah3** [comment]
This is because one of your addresses has been sent from, and then received funds afterwards. This is not a bug

**Comment by iutnL** [comment]
Hi rajivshah3, thank you for the reply.

I’m a noob... What steps can I take to access my funds? I tried attaching new receive addresses multiple times, waiting for them to complete, then sending, but still continue to get that error. Any direction would be appreciated. Thank you.

**Comment by iutnL** [comment]
I've tried with the Command Line wallet using the following command:

_node my-wallet.js Transfer ADDRESS AMOUNT_

I tried to send to both an exchange, and a brand new IOTA Light Wallet seed, and both times I received the following error:

**{ status: "error", message: "Transfer failed. Request Error: COMMAND attachToTangle is not available on this node"}**

How can I resolve this?

**Comment by rajivshah3** [comment]
Use a node that has PoW enabled: https://iota.dance/nodes
