### ISSUE TITLE
Wallet balance 0

### ISSUE THREAD

**Issue by TobyGawneGoogle** [iotaledger/wallet#1131]
[Description of the bug or feature]
I transferred 273 MIOTA from Binance to the light wallet on 5th Jan 2018. The balance showed in my wallet find.

As of 13th Feb 2018 my balance showed as 0.

I followed the online advise and reinstalled the latest wallet and reattached around 30 addresses.

Balance still 0.

I got the transaction ID from Binance and found it on the tangle explorer. The target address in this transaction IS attached to my wallet. Balance still 0.

I noticed in the tangle explorer that my funds were transferred out on 19th Jan at 5am. This was not me. Have my funds been stolen? Have the IOTA foundation taken custody?

Whats happening? 

Have i lost my coins?

the address the coins were sent to (from Binance to my wallet) is
AUMQWXR9SMVUUO9ODWABHKQJHTBLZHMGQKQWCPQDN9JNOMLAVBZECCY9GT9RLXYGNCUTYAZCJTSXPVHVWQYPEQAI9C

Please help....

[OS Version]
Windows 10
[Wallet Version]
2.5.7

**Comment by zhernosekovi99** [comment]
same problem

**Comment by elmamut** [comment]
https://forum.helloiota.com/105/Help-My-IOTA-balance-is-zero-steps-to-help-you-find-your-balance

http://www.iotahispano.com/2017/11/09/entre-a-mi-wallet-y-tengo-balance-0-que-hago/

**Comment by VeronaSester** [comment]
Did anyone get answers to this? I have the same problem. I had over 6 Mi and I didnt withdraw them but I can see in the history there are 2 withdraws. Did my IOTA get stolen? I dont see the previous history, like when i made the deposits into my account. They used to show up :(  Im not sure whats going on. Can anyone help me get my IOTA back?? Im sorta freaking out!

**Comment by zhernosekovi99** [comment]
Same problem with me. I have try to resolve this problem couple day, but
all unsuccessful.
An idea of iota is this no basic BlockChain.
It work on nude, were hey decentralize on network, problem what I see is
not connect to Nude.
Very uncomfortable situation when you can’t get you many...
I hope it problem with nude and problem will resolve. The worst  scenario
they just been  stole, but it not looks like it is. It would be  showing on
transaction history. However You did write to write me, we need to make a
grupe to to domende our many back.
Let me know if you have any information about.
I will let you know about any changes....
Thanks! Have nice day.

**Comment by rajivshah3** [comment]
Please follow these steps: https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab
