### ISSUE TITLE
After snapshot some of my IOTA is gone

### ISSUE THREAD

**Issue by mafkees87** [iotaledger/wallet#1139]
Hi,

I have 3 wallets.
After the snapshot i created a new receive adress on each of them.
1 wallet shows to less IOTA and 2 were oké.
After one week one of my iota adress shows only the half of my iota (cannot see a transaction).
Whats going on? :X

hope you can please help me.

**Comment by wonkytonky** [comment]
google: iota snapshot

**Comment by mafkees87** [comment]
not the same as the snapshot zero balance error!

**Comment by wonkytonky** [comment]
did you try to connect to other nodes?

**Comment by mafkees87** [comment]
Hello,

No I didnt tried different nodes.
I just tried a different nodes en it works!

Thank you wonklytonky!.

I feel so stupid :P haha
