### ISSUE TITLE
Help. Zero balance account

### ISSUE THREAD

**Issue by cuokochi** [iotaledger/wallet#1140]
I've had this account for months. I copy and paste my seed. My seed is not online generated. 
My account shows no transactions and a zero balance. 
What happened to my iotas. 
Thanks

**Comment by cuokochi** [comment]
Finally figured it out after a few hours. 
Decided to leave some info for other non technical people like myself. 
For details on accessing your funds please review the following link ;
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

here's the the brief and dumbed down version for fools like myself. 

1. Copy and past your seed to the lasted version of the light wallet ( for me it also worked on an older version) 

2. Under the receive section click on the banner that states "ATTACH TO TANGLE". This process may fail depending on the host node you are attached to. If it fails just attach to a different node. 

3. After you have successfully attached please click on the same banner and you will see another banner "GENERATE NEW ADDRESS". Click on this. This should generate your previous address with your transaction history. Attach to this address.

4. Repeat step 3 ( click on GENERATE NEW ADDRESS)if you have more than one previous address associated transactions or funds and attach after generating your previous address. 

You can always check for your previous address on the exchange you bought your iota under withdrawal history. 

Hope this helps somebody.

**Comment by wonkytonky** [comment]
you did re open this issue..  can you close it? ;) since  the problem seems to be resolved..
