### ISSUE TITLE
Lost most of my iota after last snapshot

### ISSUE THREAD

**Issue by Pinkpineapple** [iotaledger/wallet#1142]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [ x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [x ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ x] I confirm that this issue is present on the latest version of the wallet

### Description

I had 101 MIOTA before the last snapshot. Before the snapshot i made a transfer to bitfinex(new adress). After a few days(after snapshot) 94 IOTA(not MIOTA) was returned to my wallet, nothing got transfered to my biffinex wallet. Where the HELL is my tokens now?!?! Grateful for some help. 

### Steps to Reproduce

1. I have reattached and generated about 100 adresses to get my balance back, without any luck.
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen] 
I expected all of my 110 miotas to be transfered to Bitfinex

**Actual behavior:** [What actually happened] 
The transfer didnt come thru and i had 94 IOTA returned to my wallet( aprx 109 Miota lost)

### Versions

[OS Version] Sierra
[Wallet Version] v2.5.6, v2.5.7

**Comment by wonkytonky** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab
