### ISSUE TITLE
Pending forever, slow transactions

### ISSUE THREAD

**Issue by larrysmith1000** [iotaledger/wallet#1144]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by larrysmith1000** [comment]
Description

I realizes this may not be an issue with the wallet, but can someone direct me to whom I should talk to about solutions.

I have done several transactions, and with everyone I do, it takes a minimum of 5 or 6 reattaches and promotions an hour appart each.  My most recent transaction will I have promoted 12 times over the last 72 hours, and still no luck.

An issue that may be a part of the wallet.  When I click Promote, and the wallet says "Reattaching" it never says attached, although the Tangle explorer records the new transaction, which means the wallet is not indicating what the tangle has recorded.

WHO SHOULD I TALK TO ABOUT THIS ISSUE IF I AM NOT IN THE RIGHT PLACE.

Thanks!

**Comment by rajivshah3** [comment]
Based on this and the other issue you reported, you should try switching nodes

**Comment by wonkytonky** [comment]
also check if the milestones are updated.. sometimes a node is not synced and just switching to node that is synced willl help alot

**Comment by larrysmith1000** [comment]
Thanks rajivshah3 and Wonkytonky.

I should have mentioned that I have done both of these things using information from iota.dance and here http://iotasupport.com/lightwallet.shtml.

Any other suggestions?

**Comment by MarceloSog** [comment]
Can anybody help me? I have 3Gi in pending transaction ... And it does not appear in the wallet or the hash ... Someone could help me by favorrrr I'm desperate to pay the loan kkkk (laughs of nervous kk)...

Adress: OLQEIRKRTPJQRHVANRUZGHVSKFYKMCNHAUBSJDQLNBZHLBUJTJJDKQMTHYTRYRYGZLJOO99MTOWXTLAY9

I managed to make a withdrawal of less than 902 Miotas, to 3 months but the 3Gi never arrived ...
I used wallet android and desktop 2.5.4 forwards. I tried sending them to bitfinex ... But not everything ...

**Comment by Kirppu81** [comment]
Same problem for couple of days for my small test transactions.
HASH: PXBRCPXQKHOKKCZGTLVNWYRLAMWL9FDTXICETFSIIDMYXMPYRYRSY9QSCMIDCKELATZCJRJGJOEB99999

Tried: multiple nodes, reattach 13th times on different days, promote, broadcast, wallet versions 2.5.7/6 + Offical Android Beta wallet

Tangle network problem or wallet issue?
