### ISSUE TITLE
Interface really slow.

### ISSUE THREAD

**Issue by larrysmith1000** [iotaledger/wallet#1145]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ x] I confirm that this is an issue with the wallet, not IRI
* [x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [x ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x ] I confirm that this issue is present on the latest version of the wallet

### Description

When I click on things in the wallet, nothing happens for nearly a minute.  For example, when you click on "Bundle" in the History menu, literally nothing happens.

**Expected behavior:** [What you expected to happen]

When you click on UI links like "Bundle" you would expect the program to respond.

**Actual behavior:** [What actually happened]

When you click on UI links like "Bundle" the response is delayed by about a minute or more.

### Versions

[OS Version] Windows 10
[Wallet Version] 2.5.7

**Comment by rajivshah3** [comment]
Try switching nodes. When you click “show bundle”, the wallet sends a request to the node to get the transaction data. If the node is slow in responding, the wallet will be slow sometimes.
