### ISSUE TITLE
I have zero balance, it seems that the iota token was stolen

### ISSUE THREAD

**Issue by GIL7GIL** [iotaledger/wallet#1146]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [ x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [ x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x ] I confirm that this issue is present on the latest version of the wallet

### Description

[the portfolio appears in zero balance in the PC portfolio but 7 token appear in the android wallet, but the balance does not correspond to my funds.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[windows 10]
[2.5.4]

**Comment by cuokochi** [comment]
Finally figured it out after a few hours.
Decided to leave some info for other non technical people like myself.
For details on accessing your funds please review the following link ;
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

here's the the brief and dumbed down version for fools like myself.

Copy and past your seed to the lasted version of the light wallet ( for me it also worked on an older version)

Under the receive section click on the banner that states "ATTACH TO TANGLE". This process may fail depending on the host node you are attached to. If it fails just attach to a different node.

After you have successfully attached please click on the same banner and you will see another banner "GENERATE NEW ADDRESS". Click on this. This should generate your previous address with your transaction history. Attach to this address.

Repeat step 3 ( click on GENERATE NEW ADDRESS)if you have more than one previous address associated transactions or funds and attach after generating your previous address.

You can always check for your previous address on the exchange you bought your iota under withdrawal history.

Hope this helps somebody.
