### ISSUE TITLE
iota not confirming deposits to exchanges

### ISSUE THREAD

**Issue by treivaj** [iotaledger/wallet#1147]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ ] I confirm that this is an issue with the wallet, not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [ ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by treivaj** [comment]
8 days ago i deposited 51i instead of 51.484349Mi the 51i got confirmed but the 51.484349 Mi will not confirm and coming from IOTA wallet like the confirmation of address: CA9NVULBJRIIC9NIWYPRWUYHLSJEDXFOUBWXWKDHKYXVDZBFBEHSOIEGLB9AO9BNFKPASPK9TRFHTLUJAJELFXWJLX to be Confirmed or am I being jacked for my 51.484349Mi  IOTA

**Comment by rajivshah3** [comment]
Keep reattaching and promoting the transfer. This is not a wallet bug

**Comment by treivaj** [comment]
Binance said this is an issue and it's on Iota side so therefore it is a
bug and when I keep reattaching Andre Broadcasting there are now 3 pending
confirmation transactions it is an Iota issue and that came from binance

**Comment by wonkytonky** [comment]
it's not a bug. choose a good node and reattach/promote  until confirmed

**Comment by treivaj** [comment]
Every time I do that I get a pop-up box telling me that it's already
showing the transaction being sent but each time it's been sent Iota is not
confirming it I have both hash and the address it was being sent to and the
wallet will not allow you to keep sending or keep rebroadcasting for the
same address and when I put in a new address it would not recognize it it
is a bug in the wallet and when I looked at the node it claims it's okay so
it's a bug in your wallet open the ticket and fix it
