### ISSUE TITLE
CONNECTION REFUSED ?

### ISSUE THREAD

**Issue by 2222prashant** [iotaledger/wallet#1153]
Dear Sir / Ma'am,

i am useing IOTA Light Wallet 2.5.7 - IRI 1.4.2.1 when i submit Seed & click on Login it shows an error message "CONNECTION REFUSED" what does it mean i have my IOTA coins in my SEEDS HOW TO RECOVER IT

its a humble request to guide me for the same & help me recover my IOTA coins

regards,
Prashant

**Comment by wonkytonky** [comment]
change a few nodes

**Comment by 2222prashant** [comment]
Thanks very much it worked well i really appreciate your prompt reply
GOD BLESS YOU
