### ISSUE TITLE
IOTA transaction taking too long! Someone help me? Please!

### ISSUE THREAD

**Issue by betobortolotto** [iotaledger/wallet#1155]
I sent "Mi 14.496552" and is still pending! I tried "Rebroadcast" and "Reattach" buttons a lot of times.. nothing happened. 
I also tried change the node a lot of times and still pending.

OS: Windows 10 PRO
Wallet: Desktop 2.5.7

HASH:  QFYRBVNYUEEZQPEUJOOBUBPEDPDWZENDTKAWXQVZPMRXZNNSGMTFRCRCTJETSDVRQUHSQMVCXJVPA9999

**Comment by betobortolotto** [comment]
Sorry about my English.

**Comment by wonkytonky** [comment]
try : 

![image](https://user-images.githubusercontent.com/19390834/36642474-1db9bafc-1a40-11e8-952c-0c2633455be2.png)

i just tested this node seems to work good

**Comment by betobortolotto** [comment]
Thank you for your help! But it did not work.

**Comment by betobortolotto** [comment]
Can someone help me?

**Comment by betobortolotto** [comment]
25 more duplicate unconfirmed transactions (probably reattaches)

https://iotasear.ch/address/FDQOWRXXOFVNGN9URDKKLYVAPV9DWPVINQZQZAHALANHKJGLMZAW9JXRTJCZBGMTYHR9LGOFMI9RKN9KW

**Comment by betobortolotto** [comment]
I was able to solve the problem. I just uninstalled the program and then deleted all files from the "% appdata% / IOTA Wallet" folder.
