### ISSUE TITLE
try to fill the form, wallet again not work

### ISSUE THREAD

**Issue by Tiguan01** [iotaledger/wallet#1156]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [ x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [ x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ x] I confirm that this issue is present on the latest version of the wallet

### wallet don't work

nothing recieve or send

### Steps to Reproduce

1. [First step   tried different nodes
2. [Second Step] nothing happens
3. [and so on...]

**Expected behavior:** [What you expected to happen] there are 9  problems in history, nothing happens

**Actual behavior:** [What actually happened]

### Versions 2.5.7.

[OS Version] windows 10
[Wallet Version] 2.5.7

**Comment by rajivshah3** [comment]
Switch to one of the nodes at the top of http://iota.dance/nodes. Make sure to reattach and promote

**Comment by Tiguan01** [comment]
Tried differend nodes but no one works, my history has from mining 9
transfers in history but nothing happends.
They still there from iota faucet https://mineiota.com/ also mining don't
work anymore because i have no tangle.
Hope you can help me

2018-03-04 19:30 GMT+01:00 Rajiv Shah <notifications@github.com>:
