### ISSUE TITLE
NOT CONFIRMING ~ PENDING

### ISSUE THREAD

**Issue by srsgmrcy** [iotaledger/wallet#1157]
![image](https://user-images.githubusercontent.com/36108525/36646585-5e485b6a-1a8a-11e8-8f56-bdfc535b77a5.jpg)
![image](https://user-images.githubusercontent.com/36108525/36646603-72322174-1a8a-11e8-9d50-3becf4be9da3.jpg)

ı sent 25 mi ıota Wallet —> binance . But 1 weeks pending write . I Do usually reattach and rebroadcast but not sent . Write pending help meeeee please 
![image](https://user-images.githubusercontent.com/36108525/36646554-19224b0e-1a8a-11e8-8db9-2902d049440b.jpg)
![image](https://user-images.githubusercontent.com/36108525/36646565-33b52cf2-1a8a-11e8-95e2-4ed3d01bee0a.jpg)

[OS Version]
[Wallet Version]

**Comment by lbux** [comment]
Get the hash and re-attach and promote [here](http://pro.iota.fm/).

**Comment by wonkytonky** [comment]
try again.. confirms seem to go pretty fast lately .. chance nodes .. check if milestones are synced
