### ISSUE TITLE
Address generation takes really long / never finishes

### ISSUE THREAD

**Issue by rage13337** [iotaledger/wallet#116]
There are several users that got problems with address generation. I will collect more and more data (see google sheet). At the moment i dont see connection between the different systems and the problems.

Some users need 20-50 minutes for one address generation, others cannot generate an address at all (tested with different light-wallet hosts). All with GUI 2.3.0

https://docs.google.com/spreadsheets/d/1RwM6s5YWEYo74S4utQa7KkaGLylEsA0WwjJlcTa2ZYM/

**Comment by atypicalprogrammer** [comment]
You should collect GPU details also.

**Comment by rage13337** [comment]
Ongoing.

**Comment by JohannesKnecht** [comment]
Have the same problem.
Tried everything possible (opening ports, reinstalling while clearing every iota file)
In my case though it is working on my desktop pc, maybe there is a problem when you are calling from the same ip but from a different machine ?

**Comment by atypicalprogrammer** [comment]
I suggest you put an issue here instead: https://github.com/iotaledger/ccurl
