### ISSUE TITLE
Zero balance

### ISSUE THREAD

**Issue by Jowilfried** [iotaledger/wallet#1161]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ x] I confirm that this is an issue with the wallet, not IRI
* [ x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [x ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x ] I confirm that this issue is present on the latest version of the wallet

### Description

Hi, 

I have contacted you some time ago and thanks to your quick support we managed to transfer part of my fund from my wallet. I still have 222 on it but now it shows zero. I have reattached multiple times (17..) and but still nothing appears. I precise that I am using the node parameters proposed on this github: https://turnip.iotasalad.org:14265 with 14 as Min value.

Thanks in advance for your help, I contact you as I do not see what else to try.

Charles

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by wonkytonky** [comment]
or you have not created enough addresses , try to chance nodes aswell just pick random in the drop down list. 

or  your seed is not correct .. but I assume it is. 

so try to keep generating addresses       
do you know how much you generated before snapshot?

**Comment by Jowilfried** [comment]
I have to confess that I didn't checked my number of addresses before,  all I know is that I have made only two transactions and that I cannot access a long history to see.
I will continue to try while changing nodes.

Thanks for the quick reaction

Charles

Télécharger Outlook pour Android<https://aka.ms/ghei36>



De : wonkytonky
Envoyé : lundi 26 février à 10:59 PM
Objet : Re: [iotaledger/wallet] Zero balance (#1161)
À : iotaledger/wallet
Cc : Jowilfried, Author


or you have not created enough addresses , try to chance nodes aswell just pick random in the drop down list.
or your seed is not correct .. but I assume it is.
so try to keep generating addresses
do you know how much you generated before snapshot?

**Comment by wonkytonky** [comment]
if you only created 2 addresses  , 17 should be enough. .. are you sure you used the same seed?

**Comment by Jowilfried** [comment]
Yes, I have only one seed on a crypted USB..

________________________________
De : wonkytonky <notifications@github.com>
Envoyé : lundi 26 février 2018 23:14
À : iotaledger/wallet
Cc : Jowilfried; Author
Objet : Re: [iotaledger/wallet] Zero balance (#1161)


if you only created 2 addresses , 17 should be enough. .. are you sure you used the same seed?

**Comment by Jowilfried** [comment]
I have tried again and again and nothing. I do not even know what I can post here to help understand the issue. No log, no error message, I cannot give other information than a zero balance whith multiple tries to attach tangle to different nodes..


________________________________
De : wonkytonky <notifications@github.com>
Envoyé : lundi 26 février 2018 23:14
À : iotaledger/wallet
Cc : Jowilfried; Author
Objet : Re: [iotaledger/wallet] Zero balance (#1161)


if you only created 2 addresses , 17 should be enough. .. are you sure you used the same seed?

**Comment by wonkytonky** [comment]
whats the addrss that holds the money?

**Comment by panique** [comment]
Same here. This seems to affect a lot of people (100.000s of views on youtube videos titled "how to fix zero iota balance" etc.). Totally unprofessional wallet, guys!

**Comment by Jowilfried** [comment]
Hi,


Here is the local wallet adress where 622 MIOTA were sent from Bitfinex:

- Adress: HPSJBQERMVIWNMKJFFWHRZIGMOPPWXL9NIFGZEXERALEQFYTDLJMPO9S999MBHDLWXUECVVZTHAGNTOHWPXYJFBRKD

- TX Id: BTZDREQZMKQ9UAQOUAUJH9QMSOHONCWCGPAAQLPXBWKPHB9HEJFHNKVAQOKZBLXLLNMUSSGJOVWQA9999


Then I sent 400 MIOTA to Bitfinex:

- Adress: SJWERQWSOIYVSQLYMPYWKGFEXRCDHGWUQMKBDAHDGKJCLJ9ZCEZJGVFWXHLGZWCFX9WROURQARUPLGUEWQMFLKCWTY

- TX Id: RXU9URWF9RSRCWSXHGB9IHRITVQWKCVUMBMBCIIFVFOLAXTXMPIK9EI9TMLDNCTJVQLXDMGUMKAN99999


So I still have 222 MIOTA on my local wallet from which I have only one seed.


It very difficult for me to understand the issue, can you help, I have reattached like 30 times with differents nodes and still nothing. 0 IOTA indicated in my wallet. Although I have only made 2 transactions (from Bitfinex and to Bitfinex)...


Thank you in advance.

Charles


________________________________
De : Chris <notifications@github.com>
Envoyé : mardi 27 février 2018 15:06
À : iotaledger/wallet
Cc : Jowilfried; Author
Objet : Re: [iotaledger/wallet] Zero balance (#1161)


Same here. This seems to affect a lot of people (100.000s of views on youtube videos titled "how to fix zero iota balance" etc.). Totally unprofessional wallet, guys!

**Comment by Jowilfried** [comment]
In case you didn't get my answer as I didn't answered directly to you:


Hi,


Here is the local wallet adress where 622 MIOTA were sent from Bitfinex:

- Adress: HPSJBQERMVIWNMKJFFWHRZIGMOPPWXL9NIFGZEXERALEQFYTDLJMPO9S999MBHDLWXUECVVZTHAGNTOHWPXYJFBRKD

- TX Id: BTZDREQZMKQ9UAQOUAUJH9QMSOHONCWCGPAAQLPXBWKPHB9HEJFHNKVAQOKZBLXLLNMUSSGJOVWQA9999


Then I sent 400 MIOTA to Bitfinex:

- Adress: SJWERQWSOIYVSQLYMPYWKGFEXRCDHGWUQMKBDAHDGKJCLJ9ZCEZJGVFWXHLGZWCFX9WROURQARUPLGUEWQMFLKCWTY

- TX Id: RXU9URWF9RSRCWSXHGB9IHRITVQWKCVUMBMBCIIFVFOLAXTXMPIK9EI9TMLDNCTJVQLXDMGUMKAN99999


So I still have 222 MIOTA on my local wallet from which I have only one seed.


It very difficult for me to understand the issue, can you help, I have reattached like 30 times with differents nodes and still nothing. 0 IOTA indicated in my wallet. Although I have only made 2 transactions (from Bitfinex and to Bitfinex)...


Thank you in advance.

Charles


________________________________
De : wonkytonky <notifications@github.com>
Envoyé : mardi 27 février 2018 00:20
À : iotaledger/wallet
Cc : Jowilfried; Author
Objet : Re: [iotaledger/wallet] Zero balance (#1161)


whats the addrss that holds the money?

**Comment by Jowilfried** [comment]
Hi,


Can somebody give an answer to my problem? I have tried like 30 differents cryptocurrencies local wallets and it is the first time that I have such issues.

I am not a troll and do not want to impact negatively any project in this area but I begin to feel like a pigeon and I am not the only one.

I am happy not to have put thousands in this but really, it is quite ironical to see IOTA website claiming a "Scalable, decentralized, modular, no fees project". That might be the best joke I read from a long time. At least add that this is a gama project. Or zeta, even an SQL database would be more efficient.


I am ok to try solutions but none are given and I have made no mistake like wrong adress type or loosing private key. I am close to call this a scam or total theft because nowhere it is written that the protocol is not even working and there is no disclaimer on it. If it was decentralised I would maybe take on me but for now it is far for this point.


I am writting as if I was on my island putting a paper in the sea, I am glad that my life does not depends on this but my belief in this project and the way I will talk about it does.


Charles




________________________________
De : Chris <notifications@github.com>
Envoyé : mardi 27 février 2018 15:06
À : iotaledger/wallet
Cc : Jowilfried; Author
Objet : Re: [iotaledger/wallet] Zero balance (#1161)


Same here. This seems to affect a lot of people (100.000s of views on youtube videos titled "how to fix zero iota balance" etc.). Totally unprofessional wallet, guys!

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/36819735-dc7aa7d8-1cea-11e8-9d15-6a6935a27918.png)
the address you have shown doesnt hold any value anymore . 
seems money was sent out of it.. 

how did you create seed?

**Comment by Jowilfried** [comment]
Yes I know that, I checked on the Explorer. But I have also read stories about similar issues that were solved by devs because it is not a fault from the user, nor a hack.

From what I remenber my seed was generated through the wallet installed on my computer. I am quite sure that it has not been hacked since it is kept on a crypted USB where I have private keys for other cryptos and none have been stolen.

So ok for the explorer but I am not technically competent to attest that it is not a problem on the protocol itself as my issue is not isolated, many are exposed..

________________________________
De : wonkytonky <notifications@github.com>
Envoyé : jeudi 1 mars 2018 00:53
À : iotaledger/wallet
Cc : Jowilfried; Author
Objet : Re: [iotaledger/wallet] Zero balance (#1161)


[image]<https://user-images.githubusercontent.com/19390834/36819735-dc7aa7d8-1cea-11e8-9d15-6a6935a27918.png>

[https://user-images.githubusercontent.com/19390834/36819735-dc7aa7d8-1cea-11e8-9d15-6a6935a27918.png]

the address you have shown doesnt hold any value anymore .
seems money was sent out of it..

how did you create seed?

**Comment by Jowilfried** [comment]
And add to my previous message. You showed my first 622 transaction from bitfinex to my local wallet. It was a full transaction. But the other tx is a 400 from local to bitfinex. And this one indicates that I still have 222 on local. But no, the wallet consider that I have none..


________________________________
De : Charles Keïta <charles.keita@live.fr>
Envoyé : jeudi 1 mars 2018 00:58
À : iotaledger/wallet; iotaledger/wallet
Cc : Author
Objet : RE: [iotaledger/wallet] Zero balance (#1161)


Yes I know that, I checked on the Explorer. But I have also read stories about similar issues that were solved by devs because it is not a fault from the user, nor a hack.

From what I remenber my seed was generated through the wallet installed on my computer. I am quite sure that it has not been hacked since it is kept on a crypted USB where I have private keys for other cryptos and none have been stolen.

So ok for the explorer but I am not technically competent to attest that it is not a problem on the protocol itself as my issue is not isolated, many are exposed..

________________________________
De : wonkytonky <notifications@github.com>
Envoyé : jeudi 1 mars 2018 00:53
À : iotaledger/wallet
Cc : Jowilfried; Author
Objet : Re: [iotaledger/wallet] Zero balance (#1161)


[image]<https://user-images.githubusercontent.com/19390834/36819735-dc7aa7d8-1cea-11e8-9d15-6a6935a27918.png>

[https://user-images.githubusercontent.com/19390834/36819735-dc7aa7d8-1cea-11e8-9d15-6a6935a27918.png]

the address you have shown doesnt hold any value anymore .
seems money was sent out of it..

how did you create seed?

**Comment by wonkytonky** [comment]
there is no wallet with seed generator where did you download it?

**Comment by Jowilfried** [comment]
Maybe my memory is bugging, I think I have use this: https://iotasupport.com/gui-newseed_fr.shtml


(in french as it is my native langage).


If not I might have used a generator, to be honest I do not remenber.

________________________________
De : wonkytonky <notifications@github.com>
Envoyé : jeudi 1 mars 2018 01:09
À : iotaledger/wallet
Cc : Jowilfried; Author
Objet : Re: [iotaledger/wallet] Zero balance (#1161)


there is no wallet with seed generator where did you download it?

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/36820321-909a55ae-1ced-11e8-85bd-d3c26edfa01a.png)
this is where you send the remaining  -221.37 Mi .. 
but as you can see ..   that has also an outgoing transaction   to some other wallet that holds 2.5gi did you ever have 2.5gi? if not thats probably the hackers address

**Comment by wonkytonky** [comment]
do you remember when you created seed? because the only time there was a seed generator in the wallet is very long time ago .. like before june 2017

**Comment by Jowilfried** [comment]
I dont remember, I installed wallet on august 2018 so it is not before that. I had a look to my tx of 422 to bitfinex and in the childrens tx (5 of them) none indicate non-zero value. Thus I dont know how you got to the adress you pointed, I am not able to check this on my local wallet..

Other point, I doubt very much that I was hacked as:

- If hacker had the seed during creation he would have taken fund quickly, not waiting that I withdraw 2/3 of it

- It seems to have happen to many people, although at first I thought there were just fake stories trolling the space


I am not Edward Snowden and am not able to evaluate if I was hacked or not, so..


________________________________
De : wonkytonky <notifications@github.com>
Envoyé : jeudi 1 mars 2018 01:17
À : iotaledger/wallet
Cc : Jowilfried; Author
Objet : Re: [iotaledger/wallet] Zero balance (#1161)


do you remember when you created seed? because the only time there was a seed generator in the wallet is very long time ago .. like before june 2017

**Comment by wonkytonky** [comment]
if u used an online seedgenerator scam website  the hacker waited long time before he started taking funds out so he could suprise everybody.

**Comment by Jowilfried** [comment]
I think I will accept this, even if not believing it. I have lost too much time for nothing. I do not know what your involment is in this project but really I am not confident in it, all the steps were quite difficults, needing help from people like you. The last one was a 1/3 lost, not a changing life amount but, still it is my money.

In addition if I used a generator I have used something recommended by IOTA website, this is for sure as I am not random generator expert. So this might be a global theft and it would be a public news on specialized media. That is not the case.


However I greatly appreciate your support, and the time you took. I am angry but not against you, it is just that you are my only interface with this.


________________________________
De : wonkytonky <notifications@github.com>
Envoyé : jeudi 1 mars 2018 01:34
À : iotaledger/wallet
Cc : Jowilfried; Author
Objet : Re: [iotaledger/wallet] Zero balance (#1161)


if u used an online seedgenerator scam website the hacker waited long time before he started taking funds out so he could suprise everybody.

**Comment by wonkytonky** [comment]
i'm just a guy on the internet.. not   related to iota team.  trying to help other ppl . 

there will be a new wallet in a few months called trinity wich  should be realy easy to use and has a good seedgenerator build in to avoid things like this

**Comment by Jowilfried** [comment]
My thanks are greater if your from not on the dev team. Happy for the trinity thing but I think I am done with IOTA.


________________________________
De : wonkytonky <notifications@github.com>
Envoyé : jeudi 1 mars 2018 01:51
À : iotaledger/wallet
Cc : Jowilfried; Author
Objet : Re: [iotaledger/wallet] Zero balance (#1161)


i'm just a guy on the internet.. not related to iota team. trying to help other ppl .

there will be a new wallet in a few months called trinity wich should be realy easy to use and has a good seedgenerator build in to avoid things like this

**Comment by panique** [comment]
IMPORTANT: MAJOR SCAM WITH IOTA SEEDS:

Chances are high that you have zero balance because your seed was generated by ANY online seed generator, as basically ALL of them are scams.

This is a big thing :/ and there is zero chance in getting your funds back. HOLY SHIT !

https://www.financemagnates.com/cryptocurrency/news/4-million-iota-tokens-stolen-hackers-online-seed-generators/

**Comment by Jowilfried** [comment]
Maybe but I think I used the local wallet generator. Not 100% sure however.
I have high doubts as I read stories of people who managed to get there funds back with dev's help since mains issues of this type come from protocol problems and not seed hacked.
I am very disappointed by iota. The whole experience was a nightmare.


Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Jowilfried** [comment]
As the people in charge are able to refund nobody can be sure that their loss comes from a hack. And due to the poor quality of the protocol users are far from being confident.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Jowilfried** [comment]
Joke,  how can iota global coordinator not stop any hack as they are in charge of the database ?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
