### ISSUE TITLE
Sent Iota Tokens to Binance 10 days ago and they have not been confirmed 

### ISSUE THREAD

**Issue by Sakara2018** [iotaledger/wallet#1162]
Hi 

I really need some help. On the 15th February 2018 I sent 29 Iota Tokens to Binance and the transaction still says unconfirmed. My Binance address is empty and my Iota wallet still says that I have 29 Iota coin and when I try to send it again, it says I have to wait until the pervious transaction is complete. 

Why is it taking some long to confirm the transaction?

**Comment by wonkytonky** [comment]
reattach/promote  your original transaction until it confirms
