### ISSUE TITLE
I lost 181 Iota using the Iota light wallet 2.5.7 too

### ISSUE THREAD

**Issue by yan76net** [iotaledger/wallet#1163]
[x] I confirm that this is an issue with the IOTA Wallet and not an exchange
    [x] I confirm that this is an issue with the wallet, not IRI
    [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
    [x] I confirm that this is not an issue related to stolen/lost funds
    [x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
    [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
    [x] I confirm that this issue is present on the latest version of the wallet

OS Windows 7 64bit
Old wallet IOTA.Wallet.Setup.2.4.0
It was 181 Miota.
New wallet IOTA.Wallet.Setup.2.5.7

Seed [redacted]
 is not work after setup.
1)I try reclaime  tool after setup new wallet.
There is not instruction how to generate New seed.
2)I try generate seed at the https://seed.iota-foundation.org
New seed was [redacted]
Proof transaction is pending...
PROMOTE...
I have reattached multiple times.
Promote did not work.

3)I tried again to make a new seed by adding a few letters to the old one.

It is [redacted]
I try new reclaime  tool.

Proof transaction is pending...
PROMOTE...
I have reattached multiple times.

4)Now I have zero balance on all three seeds

PS Why in the comments "reclaim tool" there is no instruction how to generate a new seed
or where to look how to generate
or just make a button to generate this new seed
and what to do next?

**Comment by wonkytonky** [comment]
https://seed.iota-foundation.org is scam website, don't use online seedgenerators EVER

**Comment by rajivshah3** [comment]
Please do **not** post your seed online
