### ISSUE TITLE
Feature Request: QR scanner

### ISSUE THREAD

**Issue by bashma** [iotaledger/wallet#117]
Hi,
it would be great if you guys could integrate QR codes and a QC scanner in the wallet. Would make tx easier.

thanks

**Comment by atypicalprogrammer** [comment]
There is a QR code for the address, what more do you need?

**Comment by bashma** [comment]
You're right. There's one when generating the address, but there is no scanner to send tx

**Comment by atypicalprogrammer** [comment]
I don't see any component for electron that allows that, do you know of any? (QR code webcam scanner)

**Comment by bashma** [comment]
I’m not sure. I just know that the byteball wallet offers that functionality. It uses the webcam on my laptop and the cam on the phone to scan QR codes.
Sorry, I’m no developer

**Comment by thachp** [comment]
I can contribute to this feature only if core developers approve this enhancement.
