### ISSUE TITLE
My Iota Balance suddenly is at zero

### ISSUE THREAD

**Issue by MarcoPolo14** [iotaledger/wallet#1170]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [ x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ x] I confirm that this is an issue with the wallet, not IRI
* [ x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ x] I confirm that this is not an issue related to stolen/lost funds
* [ x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ x] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [I log into IOTA Light Wallet version 2.5.7 using my private key ]
2. [It connects Balance is zero]
3. [I tried switching to another light node and I still have a zero balance]

**Expected behavior:** [I expext my balance to show up]

**Actual behavior:** [Zero balance]

### Versions

[Windows 10]
[2.5.7]

**Comment by MarcoPolo14** [comment]
Another important piece of information. I try to generate a new receive address and I get an Request Error when I try to attach to Tangle. Also my history has no send or receive history. It is empty.

**Comment by wonkytonky** [comment]
chose other nodes   , generate addresses until balance shows up

**Comment by MarcoPolo14** [comment]
Yes, that is exactly what I did. Apparently if you don't check your balance often this wallet loses track. I changed to another node and created some new receive addresses and that restored my balance. The developers need to fix that problem so it does not happen. It makes the wallet and technology look unreliable.

**Comment by wonkytonky** [comment]
trinity a new wallet will be statefull and remember all the address you have after snapshot and it will be no problem anymore..
