### ISSUE TITLE
My IOTA coin was gone!

### ISSUE THREAD

**Issue by Moonfishkv2** [iotaledger/wallet#1172]
I deposit the IOTA coin about few months ago and had not touch it until now. So I login and I realised the coin was gone. I am not sure if this is really need update to a new version. I have tried the latest version as it not working when I use my current password. 

Also I have tried 2.4.0 but the message say "No connection" while I try to click on Transition.

What can I do now? Any advice from you would be greatly appreicated!

Many thanks :)

**Comment by Moonfishkv2** [comment]
I have updated a new version 2.5.7 and then generate a new address and it is zero balance. Not working. 

I have keep the old password but nothing work as well.

I need to search it back.....or maybe not

What can I do?

**Comment by wonkytonky** [comment]
keep generating addresses

**Comment by Moonfishkv2** [comment]
Please clarify.....Keep generating address? The old or new one? I tried both of them. Nothing change.

Thanks, J

**Comment by Moonfishkv2** [comment]
I did generate the address but nothing work. Not happy with IOTA for their poorly written programming!

**Comment by rajivshah3** [comment]
https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab

**Comment by jmazzella5** [comment]
Hey @Moonfishkv2 did you ever get your balance back I am having the same issue and have generated over 50 addresses with still no balance.
