### ISSUE TITLE
Iota Balance gone

### ISSUE THREAD

**Issue by bgoeschl** [iotaledger/wallet#1173]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [ ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ ] I confirm that this is an issue with the wallet, not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [ ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the wallet

My IOTA Wallet is empty too,

I tried to install the latest wallet 2.5.7 and connected to tangle many times, but nothing came back!

In my history, there is a registered transaction which took place when i was asleep. All my IOTA where withdrawn

Can I do anything to get them back?
### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by Moonfishkv2** [comment]
You are not only one...There are many people have say their money is gone including me! Not happy with this!

**Comment by leofitz7** [comment]
Someone else posted this issue and a fix for it.  It worked for me.

Log into your latest version wallet v2.5.7, with your Seed. If no transfer history and zero balance, go to Receive, then 'Attach to Tangle' to generate a new Receive address. This connected me to a node and a few seconds later my Balance showed up. I transferred it out to Binance and after a few minutes it said 'Transfer Complete'. After ten minutes the balance was in my Binance account.
If after going through these steps you have no success, go to 'Tools/Edit Node Configuration' and choose another server node from the dropdown. If no connection, run through the 'Attach to Tangle' routine again.
Good Luck

**Comment by Moonfishkv2** [comment]
Fantastic! It's work now! Phew! Happy to reiceve my funds back!

Thank you so much for your help Leofitz7! 👍 🥇 

Thanks again! :)

**Comment by bgoeschl** [comment]
Hi leofitz7,

 

unfortunately, I can see a transaction in history, where every single IOTA got withdrawn. The transaction is even completed, it happened when I was asleep.

 

Thank you very much for your message.

 

Best Regards

 

Von: leofitz7 [mailto:notifications@github.com] 
Gesendet: Donnerstag, 8. März 2018 16:35
An: iotaledger/wallet <wallet@noreply.github.com>
Cc: bgoeschl <bernhard.goeschl@aon.at>; Author <author@noreply.github.com>
Betreff: Re: [iotaledger/wallet] Iota Balance gone (#1173)

 

Someone else posted this issue and a fix for it. It worked for me.

Log into your latest version wallet v2.5.7, with your Seed. If no transfer history and zero balance, go to Receive, then 'Attach to Tangle' to generate a new Receive address. This connected me to a node and a few seconds later my Balance showed up. I transferred it out to Binance and after a few minutes it said 'Transfer Complete'. After ten minutes the balance was in my Binance account.
If after going through these steps you have no success, go to 'Tools/Edit Node Configuration' and choose another server node from the dropdown. If no connection, run through the 'Attach to Tangle' routine again.
Good Luck

**Comment by rajivshah3** [comment]
Unfortunately, if the transaction is confirmed, the funds cannot be recovered
