### ISSUE TITLE
Balanze zero (several addresses generated does not solve issue).

### ISSUE THREAD

**Issue by jas2002** [iotaledger/wallet#1175]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description
THIS IS NOT A PENDING TRANSACTION ISSUE and I have followed the FAQ steps: _https://mathewwinstonjohnson.gitbooks.io/iota-guide-and-faq/getting-started/faq/balance-disappeared.html_ with no results.

STEP 1:
(2018-02-03 ) TxID to my IOTA Wallet:
BBUGUKXXMYBGZBDNITVPHBPNGDCJSMRYK9MVIMFSIAXHYSVEV99CKHXPCRNAFCJEQZVPSZUCPQ9XA9999

Transfered to my address (which was generated by wallet v2.5.6):
DWSFOQLCBJDMCFJOTSOHYE9QGBPKLSYSRTU9MGMUOJOEEEUDVJRJANAVQISSHDW9RWKQDWGPQVJJYSRUZBXVMPBPKX

STEP 2:
One month later, I have checked in _https://iotasear.ch_ and my funds are there.

But in the wallet balance remains at zero, although I have generated up to 8 addresses (and therefore up to 19 transactions with zero have been generated after multiple reattachments, promotes and so).

I only have one seed, btw.

### Versions

[OS Version]
Windows 7 ultimate
[Wallet Version]
IOTA light wallet 2.5.7

**[UPDATED: SOLVED]**
When transfering my IOTAs to wallet one month ago, I made a typo mistake when entering my seed.
Thanks to FVANtom and his tool I managed to solve it:
_https://github.com/FVANtom/find-typo-in-iota-seed/releases_

It's not a wallet issue then.

**Comment by CaliBitcoins** [comment]
I am having the same issue. Funds left wallet, appeared, but never confirmed in Binance. IOTA transfers have been terribly slow in the past, but this situation has persisted for over 30hrs despite rebroadcasting, promoting, switching nodes, and facilitating transactions.
