### ISSUE TITLE
IOTA REMOVING FUNDS AND NOT CONFIRMING TRANSACTIONS (30+hrs) - UNRELIABLE - UNSTABLE

### ISSUE THREAD

**Issue by CaliBitcoins** [iotaledger/wallet#1176]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [X] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [X] I confirm that this is an issue with the wallet, not IRI
* [X] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [X] I confirm that this is not an issue related to stolen/lost funds
* [X] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [X] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [X] I confirm that this issue is present on the latest version of the wallet

### Description

IOTA Funds left wallet (NOW AT ZERO BALANCE), but remain pending, transaction does not resolve. Rebroadcast, Reattach, Node Swtich, etc does not help. Users trust this system to reliably store/transfer IOTA. As conceptually good as IOTA maybe there are many, many such issues listed for this product. If IOTA cannot perform this very basic function it should not be promoting itself as a cryptocurrency/asset/security. I have waited, read all available technical articles, tried different "reattachments" and my funds are still stuck after 30+ hours.

### Steps to Reproduce

1. Generate new destination address 
2. Send funds to the new address
3. Wait for DAYS...

**Expected behavior:** [What you expected to happen]
Sending funds between IOTA addresses should be reliable and fast. I expect transactions to resolve in a reasonable amount of time (2hrs max). 

**Actual behavior:** [What actually happened]
Transactions remains in pending status - no confirmation/execution of transaction, even though funds were removed from wallet.

### Versions
Windows 10 
[OS Version]

2.5.7
[Wallet Version]

HASH: TWWQETRSGOZZVRTEXSTSMBEKEPX9WUQIUEDNLDKSKSWVSNA9WPPEXNCJQWLGTPJPSCOKGNJMFHANA9999

**Comment by MeanAngryVeteran** [comment]
This is scary shit.  I was going to try to ship to a wallet that I have on Android, but now no way until some of these issues get resolved.

**Comment by CaliBitcoins** [comment]
Yeah man... It doesn't look like an isolated incident. I recall a previous transaction took like 6 hours or something, and it freaked me out. Well now that I am trying to get out of this coin I made a transfer to Binance almost 2 days ago, the exchange sees the attempt, but the transaction never confirmed, and the coins are gone from my wallet/address. From what I have seen here, a lot of other people are experiencing something similar. Good luck!

**Comment by rajivshah3** [comment]
Your transaction is confirmed.

**Comment by wonkytonky** [comment]
probably used an unsynced node.. use a good node next time

**Comment by CaliBitcoins** [comment]
USE A GOOD NODE? Like that is my responsibility, when your software lists available nodes? IOTA IS GARBAGE, and with responses like this I can see why it is failing.

**Comment by wonkytonky** [comment]
your transaction confirmed. not sure what you are complaining about?
