### ISSUE TITLE
IS IOTA LOSS A LAW ENFORCEMENT ISSUE YET???

### ISSUE THREAD

**Issue by CaliBitcoins** [iotaledger/wallet#1177]
I just want my transaction to go through, and I promise I will never use the tangle again....

Emails sent to Foundation, Binance, Bug Reports.... NOTICE COMMENTS ON BLOG ARE DISABLED??

IOTA IS BEGINNING TO LOOK LIKE A SCAM.

**Comment by MeanAngryVeteran** [comment]
IOTA IS BEGINNING TO LOOK LIKE A SCAM  

I'm thinking the same thing.

**Comment by CaliBitcoins** [comment]
The explorer states the system is processing 2 transactions per second, but the last transaction occurred like 7 hours ago... Not exactly the type of innovation I was hoping for. This is the kind of crap that is hurting crypto. 

I believe markets like Binanace have a duty to traders to hault trading on malfunctioning markets like this to protect users and the crypto ecosystem generally. I have notified them. I hope these people figure this out quickly, but judging by the time line of the complaints piling up here it doesn't look good.

**Comment by rajivshah3** [comment]
This is not a bug report and should not be posted on GitHub.
