### ISSUE TITLE
wallet credit is gone

### ISSUE THREAD

**Issue by Diatryma75** [iotaledger/wallet#1178]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [x ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x ] I confirm that this issue is present on the latest version of the wallet

### Description

I send my balance to following adress, but there is nothing arrived:

CMXKGSW9CISFK9QGREYYKWXRCTAZVXGEPSMYTIB9NFFHKAD9EOEJMZRJLJWQZGIHHOOCLMPKXKTUSOSTDVCDQ9XWOX

Can you say me, where my iota is gone. Is there an error in the adresse?

Here is the hash for the transaction:
CMXKGSW9CISFK9QGREYYKWXRCTAZVXGEPSMYTIB9NFFHKAD9EOEJMZRJLJWQZGIHHOOCLMPKXKTUSOSTDVCDQ9XWOX

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** The ballance should go to binance wallet, but binance means, thats not one of my adresses
**Actual behavior:** Both wallets are empty
### Versions

[OS Version] Windows 10
[Wallet Version] V2.5.7
![iota_wallet](https://user-images.githubusercontent.com/37255413/37251193-4a61e6f0-24c8-11e8-9077-aead3a3e333c.jpg)

**Comment by wonkytonky** [comment]
CMXKGSW9CISFK9QGREYYKWXRCTAZVXGEPSMYTIB9NFFHKAD9EOEJMZRJLJWQZGIHHOOCLMPKXKTUSOSTDVCDQ9XWOX   the money arrived here as you can see in the screenshot .. it was  confirmed.   if thats a binance address .. you have to talk with binance. they own the money now

![image](https://user-images.githubusercontent.com/19390834/37252409-dbf87126-2520-11e8-8f53-90839ab4d2c5.png)

**Comment by CaliBitcoins** [comment]
These guys told me the same thing. THE MONEY NEVER ARRIVED. I have written to Binance too. This is happening to a lot of people, and they are still promoting this software and asset even though everyone is losing their money. If you are a victim of this scam please send us an email  IOTA.CLASS.ACTION@gmail.com

**Comment by wonkytonky** [comment]
the problem is at binance  obviously  they have the money

**Comment by CaliBitcoins** [comment]
Transactions incomplete after 3 days. Explorer showing 2.4 Transactions per seconds, AND last non-zero transaction completed 19 hours ago... The system is broken, and MY FUNDS ARE NOT SHOWING UP AT THE DESTINATION ADDRESS. Binance handles Billions of transactions, Iota seems to have difficulty completing ANY transactions, but you people are still not assisting/reimbursing despite continuing to promote this system to investors. This is FRAUD.

**Comment by wonkytonky** [comment]
https://thetangle.org/address/EMIPSFEHBMXIZFZUSIRHKGAFMCLMOHPOBRXBHFFBWEHVHPIJWEGTUDNTUESDJG9JTBYGMPMLPNSWWRRFD  but it confirmed lol  it is showing up on your destination address

**Comment by CaliBitcoins** [comment]
So glad you think its funny that people who have trusted your software are losing their money. 
![screenshot 98](https://user-images.githubusercontent.com/35133352/37257832-8ba9007c-252b-11e8-9abc-fbf6aaf86a5c.png)

**Comment by wonkytonky** [comment]
the tx hash you showed in the "issue https://github.com/iotaledger/wallet/issues/1176#issuecomment-372124151"   you created is diffrent then the one in this screenshot so you are giving  us wrong information to begin with

**Comment by CaliBitcoins** [comment]
Well, good luck bro. This type of thing should not be on the markets....

**Comment by wonkytonky** [comment]
i tracked your tx's. seems first  you send to  EMIPSFEHBMXIZFZUSIRHKGAFMCLMOHPOBRXBHFFBWEHVHPIJWEGTUDNTUESDJG9JTBYGMPMLPNSWWRRFDIPEWPT9FD  

and now are trying to send the same money thats not there anymore to your binance address. 

ofcourse it will never  go to the binance address after it was already spend to  another address

**Comment by CaliBitcoins** [comment]
No it was first sent to KQ9LJ9NKGFXUYLJZYKNDE9FPGXASLDYQFQEONZPCADZSNCUOJOMNVRIGGQYUSJSPTNFFMCVRKRI9TUNQWXMHCAZXNX

You can see in my transaction history time stamp. The funds reappeared in my wallet, after transaction attempted, multiple times, then have now completely disappeared to a destination unknown. 

![screenshot 99](https://user-images.githubusercontent.com/35133352/37258437-4b5c4664-2535-11e8-86e7-86ae8e2dac4d.png)
.

**Comment by wonkytonky** [comment]
it could be indeed you send money first to the KQ9LJ9NKGFXUYLJZYKNDE9FP...; address.; but it didnt confirm ..        the money that was send out to EMIPSFEHBMXIZFZUSIRHKGAFMCLMOHPOBRXBHFFBWEHVHPIJWEGTUDNTUESDJG9JTBYGMPMLPNSWWRRFDIPEWPT9FD 
did confirm first . so it's out of the wallet. 

if it wasnt you , you got hacked.

**Comment by CaliBitcoins** [comment]
The wallet kept loosing transaction history, and showing full balance. The first two times this occurred I generated new address and reattempted transaction. The original transaction is the one seen, but unconfirmed in Binance, it is the first listed in my transaction history.

**Comment by CaliBitcoins** [comment]
FUCK IOTA.

**Comment by jefferssson** [comment]
I have excactly same problem.
Did they answer from binance?

Icopy pasted my iotA adresss but iotas never came home.
https://thetangle.org/transaction/XCPIWNRSCIUJMRWTM9WXIUKXWRXJPBC99I99XGW9CKYQHPHPDNJEHAOPVGY9YKCHHFENWOSABKXJ99999

**Comment by rajivshah3** [comment]
@Diatryma75 please contact binance about this issue. This is not an issue with the IOTA wallet

**Comment by CaliBitcoins** [comment]
It is not Binance... I had the same problem. Look what people from MIT are saying about IOTA:

https://medium.com/@neha/cryptographic-vulnerabilities-in-iota-9a6a9ddc4367
