### ISSUE TITLE
IOTA ZERO BALANCE HACK - v2.5.7

### ISSUE THREAD

**Issue by CaliBitcoins** [iotaledger/wallet#1182]
Send funds, and while authorized transaction remains pending funds go out a second time (unauthorized doublespend) - Authorized Transaction Fails 

Exchanges admit CUSTOMERS LOSING MONEY with IOTA WALLET. 

IOTA COMPROMISED.... FOUNDATION KNOWS BUT CONTINUES TO PROMOTE AS SAFE == CRIMINAL
![iota-zerobalancehack](https://user-images.githubusercontent.com/35133352/37361858-1fbcb192-26b1-11e8-8fb0-03519c50ef3f.png)

**Comment by rajivshah3** [comment]
I have reported your account to GitHub for repeated spamming and fudding.
