### ISSUE TITLE
Man in the Middle Attack - All IOTA STOLEN - v2.5.7 COMPROMISED!!!

### ISSUE THREAD

**Issue by CaliBitcoins** [iotaledger/wallet#1185]
1) I send transaction - remains pending
2) Unrecoganized Incomming Transaction occurs
3) Funds Double Spend to Unauthorized Fraud Address while initial authorized transaction remains pending

DO NOT USE THIS WALLET!!! SEE CLOSED ISSUES - MANY, MANY PEOPLE LOOSING IOTA FROM HACKS
![iota-zerobalancehack](https://user-images.githubusercontent.com/35133352/37443999-b6c22916-27cc-11e8-9507-49618a8239c1.png)

**Comment by derdigge** [comment]
Thats really bad. I am happy i read this before moving my iota to a wallet outside the exchange.
Is there a safe wallet yet?

**Comment by rajivshah3** [comment]
Please fill out the template. There's a reason it's there. Please also provide the transaction hashes in full

**Comment by rajivshah3** [comment]
Closing until required information is provided

**Comment by CaliBitcoins** [comment]
@derdigge yeah bro... Im not the only one. When I provided this info to members of the Iota Foundation, they told me I am a liar. Really bad... 

MIT has found the system to be compromised too. See this article:
https://medium.com/@neha/cryptographic-vulnerabilities-in-iota-9a6a9ddc4367

**Comment by rajivshah3** [comment]
That report has been refuted multiple times.

**Comment by CaliBitcoins** [comment]
MIT is the leading authority on Crypto, and Technology generally... After seeing my own IOTA hacked and lost, I think I will take MIT's word for it. Thank you.

**Comment by rajivshah3** [comment]
The DCI organization is very loosely affiliated with MIT. I suggest you read the articles that refute DCI's report before making conclusions
