### ISSUE TITLE
_-_-_-_ DO NOT READ THIS ISSUE! _-_-_-_  IOTA v2.5.7 COMPROMISED!!! - MAN IN THE MIDDLE- ZERO BALANCE HACK - IOTA STOLEN

### ISSUE THREAD

**Issue by CaliBitcoins** [iotaledger/wallet#1186]
1) I make transaction first - lowest transaction on image
2) Someone sends me a small amount of IOTA (idk who) to verify address - middle incoming tx
3) ALL IOTA GOES OUT 2nd TIME (DOUBLESPEND) TO FRAUD ADDRESS - top transaction

THIS IS THE 3rd MAJOR IOTA FAIL:
1) SEED GEN / BRUTE FORCE SEED HACK
2) CRYPTOGRAPHIC DEFECT - https://medium.com/@neha/cryptographic-vulnerabilities-in-iota-9a6a9ddc4367
3) ZERO BALANCE - MITM ATTACK - WALLET DEFECT pictured below

IOTA FOUNDATION KNOWS AND CALLS US LIARS, BABIES, CONSPIRACY THEORISTS WHILE CONTINUING TO PROMOTE THIS AS A SECURE INVESTMENT GRADE ASSET. JUST LOOK AT NUBER OF VICTIMS IN CLOSED WALLET ISSUES.

Why don't more people know?? Vast majority of financial IOTA transactions do not occur on the IOTA tangle, they occur in the hardened environment of the exchanges. 

What happens when IOTA moves out of the exchanges? It gets hacked! 

I was so optimistic regarding IOTA's claims - but after this hack, and my interaction with the founder, and others I realize how weak the architecture is, and how the IOTA Foundation is perfectly happy misrepresenting their product, regardless of the damage they are causing by perpetrating this fraud.

This type of thing is really bad for the crypto economy, and the reputation/viability of the crypto asset class. 

Do your DUE DILIGENCE before investing. Hope this helps prevent your loss.

![iota-zerobalancehack](https://user-images.githubusercontent.com/35133352/37485410-993045be-2848-11e8-8237-2de9da4d3521.png)

**Comment by yippykaiyay012** [comment]
The chances are you generated an unsafe seed. This attack doesn't even make sense.

**Comment by rajivshah3** [comment]
Closing because user is consistently spamming issues, making outrageous claims, and not filling out the issue template despite being asked to do so.
