### ISSUE TITLE
Balance and history cleared

### ISSUE THREAD

**Issue by SupaHam** [iotaledger/wallet#1187]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

I've logged into my wallet seed only to find my balance as 0 and history empty. I'm sure the seed I've put in is the same one I used to make transactions. I've search on iotasear.ch and the couple transaction addresses I have show up with a 404, presumably as if my transactions never took place. What's going on?

**Expected behavior:** My actual balance and history

**Actual behavior:** Empty balance

### Versions

Microsoft Windows [Version 10.0.16299.309]
IOTA Wallet Release 2.5.7

**Comment by sa1lboats** [comment]
same issue here had about 2Miota checked the addresses and doesn't show anything leaving but balance says 0

**Comment by rajivshah3** [comment]
@SupaHam @sa1lboats please see https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab?source=linkShare-72a15a7f8d77-1521875455

**Comment by sa1lboats** [comment]
No change

**Comment by rajivshah3** [comment]
@sa1lboats are you sure you have the correct seed?

**Comment by SupaHam** [comment]
@rajivshah3 Just read that. I don't know what I'm expected to do now. I can't go 'pre-snapshot' since we're now after the event. Every time I log into any node with my Seed, I hit attach to tangle and it either loads for ever, using a lot of CPU. Or, it says Request Error. There's no button to generate a new address.

I am on version 2.5.7 which seems to be the same one as stated in that article as well.

What do I do?

**Comment by SupaHam** [comment]
I've changed Curl Implementation to `CCurl implementation` and I'm now able to attach to tangle. However, I only see my first transaction, and my balance is missing the rest.
