### ISSUE TITLE
Re-use error trying to send to Binance.

### ISSUE THREAD

**Issue by zacwise91** [iotaledger/wallet#1188]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [x ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [ x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ x] I confirm that this issue is present on the latest version of the wallet

### Description

[Every time I try to send IOTA from the desktop wallet to Binance I get a key re-use error message. All of my transactions are confirmed but every time I try to send it seems to create a new pending transaction of 0 iota in my history. I've been consistently switching addresses so that's not the problem. Tried several different nodes and no luck. I always reattach/promote the mysterious new transactions for 0 iota that pop up but even when they are confirmed, I get the same error message when I try to send to Binance. I have no idea what else to do. Any suggestions would be greatly appreciated.]

### Steps to Reproduce

1. [Generate new address on Binance]
2. [Attempt to send from Iota Dektop wallet v2.5.7]
3. [Get error for key re-use]
4. [New pending transaction of 0 appears in history]
5. [Reattach/promote until this mysterious transaction is confirmed]
6. [Attempt steps 1 and 2 again]
7. [Steps 3 and 4 happen again]

**Expected behavior:** [for the balance to send to the Binance address after I press "Send it Now"]

**Actual behavior:** [Received a key re-use error even though I did not reuse address and tried multiple different nodes and addresses]

### Versions

[Wallet Version 2.5.7]

**Comment by rajivshah3** [comment]
It sounds like you received to an address you already sent from. In order to get those funds out, you’ll need to use something like the CLI wallet (https://github.com/iotaledger/cli-app)
