### ISSUE TITLE
Not working on Centos server 

### ISSUE THREAD

**Issue by lettertoamit** [iotaledger/wallet#12]
I have tried to check your code in linux server , I think its not working as electron prebuilt

/usr/local/lib/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

Can you please enlighten me . ... how should i install or where i am wrong ??

**Comment by atypicalprogrammer** [comment]
Server? Why do you need a GUI on a (headless?) server? 

Try `sudo apt-get install libxss1`

**Comment by lettertoamit** [comment]
apt-get command does not work on it ,
 only yum works on centos 


No package libxss1 available.
Error: Nothing to do

**Comment by atypicalprogrammer** [comment]
Sorry, didn't notice that :-)

To clarify, this is not a headless server? You've got a desktop environment? Did you follow the installation instructions in the readme? You are trying to compile it yourself? Can you use the release and does that work ok?

**Comment by lettertoamit** [comment]
![image](https://cloud.githubusercontent.com/assets/11607454/18827801/4508f6bc-83f2-11e6-8d07-50af38028283.png)
![image](https://cloud.githubusercontent.com/assets/11607454/18827851/894070ee-83f2-11e6-9a98-1f92bb09d737.png)


![image](https://cloud.githubusercontent.com/assets/11607454/18827856/9060a4f2-83f2-11e6-9f00-cb10e4b5519b.png)


![image](https://cloud.githubusercontent.com/assets/11607454/18827870/9c8c37dc-83f2-11e6-8bd5-9b1bc86621d7.png)


I am stuck in here at last step

**Comment by domschiener** [comment]
You don't have any neighbors, so it doesn't continue. Add neighbors in the settings.json file.

**Comment by mecgrath** [comment]
How the nodes will get interacted between the DAG , so I want to know when a wallet A send the money to Wallet B , how does it get decided it reach to Wallet B only , Please help ?

**Comment by mecgrath** [comment]
And if it transact between number of nodesthen why other node will participiate into it ?
