### ISSUE TITLE
Problems with transaction

### ISSUE THREAD

**Issue by klemp** [iotaledger/wallet#1211]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [x ] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x ] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
I wanted to transfer IOTA (almost 2 G IOTA) from my Bitfinex account, so a downloaded and installed the latest wallet 2.5.7
2. [Second Step]
I opened the new wallet and after some clicks a managed to attach the address to the tangle. I already have some IOTA in this NODE from before.

3. Went to bitfinex and made the transaction. I also checked the address before conformation and it was OK
4. I looked in the wallet history and noticed that there is no address pending.
5. I checked Bitfinex and transaction was already completed. In the wallet history there was still no sign of the new address.
6. In wallet Receive zone I again tried to attach the address to the tangle. After many request errors and invalid responses I finally managed to reattach it to the tangle and in history 2 new addresses were pending (one of them was the one that I made the transaction from Bitfinex).
7.I went to https://iotasear.ch and there I could see that the transaction is already conformed. In History it was still pending.
8. After a While the new addresses in history disappeared and in wallet receive the address that I used for the transaction was displayed.
9. After that I have managed to reattach the address to the tangle 3 - 4 times and the new transaction become visible again for a while and the disappeared again (it is very time consuming because 99% of the clicks result in request errors or invalid responses). A also rebroadcasted and reattached the address with the transaction, but was unable to promote it. The address in receive part of the wallet is almost always the one I used for transaction. After many clicks I still didn't get IOTAs from Bitfinex. I still have the right amount of IOTA from before.

Is there a solution to my problem?

**Expected behavior:** [What you expected to happen]
I expected that the transaction will be made without any problems.
**Actual behavior:** [What actually happened]
I can not get IOTAs that a sent to my node

### Versions

[OS Version]
Windows 10 Enterprise
[Wallet Version]
2.5.7

**Comment by wonkytonky** [comment]
find a good node

**Comment by klemp** [comment]
I changed the node and the right balance and history was displayed. Thank you very much. Problem solved.
