### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by larsDom** [iotaledger/wallet#1214]
Hello,

I'm honestly a relative newbie in terms of IOTA. Now I bought some IOTA on Binance and downloaded the IOTA light Wallet via Googleplay. The deposit from Binace to Wallet was also relatively fixed. When I wanted to withdraw the coins again you were only gone. But now as MIOTA to see again but the debits are still seen as a pending order. Have already X-promoted etc but nothing to do. I have now downloaded the desktop version IOTA light Wallet 2.5.7 with the hope to solve the problem with it. But nothing to do here. Can not make new debits then get the following error message:

ERROR: PRIVATE KEY REUSE DETECTED!

You are trying to sign a transaction. IOTA uses Winternitz one-time signature (W-OTS) scheme, due to it`s one-time` nature, the security of funds in an address retire rapidly if you re-sign new transactions using the same key. Please wait for previous transaction to confirm, e.g. by promoting / reattaching, before sending another transaction.

But yes that's just my problem that I do not get confirmed.

I'm thankful for any advice
Sorry if translation error = Google translator

**Comment by lo5tinpr0** [comment]
Hey @larsDom , please upload the transaction hash here (see picture).

![unbenannt](https://user-images.githubusercontent.com/37935152/39095532-68c5ef60-4642-11e8-9d49-608ade717e2a.PNG)

Alternatively, you can also upload the address where the MIOTA should go to.

> But yes that's just my problem that I do not get confirmed.

That's no problem. There is a way to help you out with that.

> Sorry if translation error = Google translator

No problem. What's your native language, may I ask? And: [https://www.deepl.com/translator](url) :)

**Comment by larsDom** [comment]
There are now several transactions because I've tried more often.
First 19.04.2018 at 08:17
ARLOXCAAHEJPXURUOLKVUEINTYTQOCQBGJQFRTLV9ZGYLKNRYXVGKCBSJTIYVVNFWPETZXQJDRQRZ9999

then: 19.04.2018 22:36
POJALSRZVDUWRJ9SJJFOVEUQCPPMRBXBLGVLQBRGFNFLKNWMPYZOMRGQEIRLCIIQZJSGF9THTGXXA9999

on the 21.04.2018 19:10
FBQDONSJWDTFJQWARTKPA9LHXZKTHVZCSEGHKBVRRNLDZVQBYGTUQWJYXBIQJBRKE9NREEOG9TDN99999

on 21.04.2018 19:32
STTPXFNOCESZH9MLIASGDFPJMBOSSOGVXETEJAEH9DRDSWPPFIVNWKJQRECKUAUMPRDYQJTHQMNW99999

on the 21.04.2018 20:23
GOFSVEQXZZPCFUPZ9XWLXDMNQPDRSYBDAMA9SEGU99AWABHTWOJLOANJDPEJXXLFZGYYT9BOOJIL99999


on the 22.04.2018 09:32
HOALGEYPUGTIKTUYZTHHDUKZDET9PUFDNBRWYZAUNSUKEICVIVNWOWAVZPGOIPMNHGRXCPAVJUPA99999

on the 22.04.2018 11:36
MAXZEGTTCQALDLKRM9OKZULFNIPFTQPDOWGDVDKCFHUNJDWZYIOSSSHSJMXDKW9ZTIOITYXSOCF9A9999

more hash codes:

ORDUMVDUZHLAI9YFK9N9UWZPRGOSCWUYLGRGVGINWJSXB9ACJKGE9NOBBMEQUWTTURC9DOMVPAUSZ9999

DMVILJHAFVGJEGVA9ZNFEMXDLCLJRHHHTOUB9MBNQWUWNGPW9KY9XOOGSBKCZUKANIHBTVBIYNBWZ9999

TEZGLGSIOPC9XA9HGONEPW9HSTSLMSPJ9ZAPWUCCWOLZAILQQJSVFGVXTSHOFOZ9QRUWZTYIEHHI99999

THGCLRBAISTAJJJTAIZTUMUJDRXYURAKGEFOTULFFOJXVDDQUPLYNHUAMJTIMENCKOTGHKZTPEADZ9999

WEFLNHBCM9IXJST9IKKDKFPEJLUHRTUNLHYVHBJUYMAACRNEJTWNMYEFTQTOZAOYXIHFIQXCIWXHA9999

YHOUHLSULVZVTSXUTY9SQF9M9EYVIHNSKRCDCQSKPWQOLAILSDKVWQXUATGGIO9RHPCEFWCXUMIT99999

KXHXMFGXDKEZATHMNRHRFOGONAZFMMLLYOOUEOLMKOFHLHMGEMRKGZFMIUJCRUN9JSZNMHINGYBC99999

**Comment by larsDom** [comment]
It should go to this address:
VESJJVHUHSIQIDDPDJ9GDQXXHTWNXBJLDRJUCKRZIDLYPDPDPC9PFBB9IDBCJE9JXVCZ9JGB9WUTXKWZAGWUTGSVJD

**Comment by wonkytonky** [comment]
https://thetangle.org/address/VESJJVHUHSIQIDDPDJ9GDQXXHTWNXBJLDRJUCKRZIDLYPDPDPC9PFBB9IDBCJE9JXVCZ9JGB9WUTXKWZA

it did arive

**Comment by lo5tinpr0** [comment]
There we go :) Everything should be fine now!
I did a little bit of promoting here [http://pro.iota.fm/promote.html](url).

You can use this website if there is a case of never ending "pending" transaction, ok?

**Comment by larsDom** [comment]
Yes you are the best many thanks itcoming :)

**Comment by wonkytonky** [comment]
be sure to use a node thats has synched milestones.;   normaly tx take about 10-15min .. sometimes even 2min

**Comment by larsDom** [comment]
thank you

**Comment by larsDom** [comment]
Sorry something is still wrong it should be 35 IOTA but there are only 0.00003500 IOTA arrived, where is the rest?

**Comment by lo5tinpr0** [comment]
Hey @larsDom , there isn't something like 0.00003500 IOTA. 1 IOTA (1i) ist the smallest unit in the IOTA system. 1.000 IOTA (1.000i) are 1 KIOTA (1Ki). 1.000 KIOTA (1.000Ki) are 1 MIOTA (1Mi) and so on...
There you can see the total amount of IOTAs out there:

![iota total amount](https://user-images.githubusercontent.com/37935152/39096832-154f9a94-4655-11e8-918b-71ca7e7f3c13.jpg)

> VRQCOIHYKFTIGNUXKHZK9ELQLVYOEABSIONCCOOFDOETWFQAIREJZ9UAGWZOYEWBBZOVMAFFJJOO99999

This transaction should be fine too by now.

**Comment by larsDom** [comment]
It's now debited from my desktop wallet, but nothing has arrived at the destination seed yet

**Comment by lo5tinpr0** [comment]
Is this (V9HFSWNSCSVDU9XPKXBKLSGBMCNGYJQKZLCYELUNTNGL9MK9ZCKY99MYSUKKSCODEEVTWVRGZKMBJGFQWVNRIFSLMZ) the address where the IOTAs should go to?
This transaction is confirmed and should be shown in the corresponding wallet.

**Comment by larsDom** [comment]
Yes that's the address but it has not arrived :(

**Comment by lo5tinpr0** [comment]
Did you create a new seed and send it there?
So you are using two different seeds now?

**Comment by larsDom** [comment]
Yeah right, I downloaded run IOTA and created a new seed. Have then copied the address. Can you save the coins now?

**Comment by lo5tinpr0** [comment]
There is no one else who can save the coins but you.
You have two seeds and on both wallets (every single seed creates a new wallet) should be some IOTAs.
Log in with each seed, no matter where you created the seed, and then you can see the value of your wallet.

**Comment by larsDom** [comment]
ok thanks i look what i can do

**Comment by lo5tinpr0** [comment]
You can only run one wallet at the same time. So log in with one seed on the desktop app and log in with the other seed on the mobile app.
There should be two different wallet balances.

**Comment by larsDom** [comment]
ok thanks i found the coins :)

**Comment by lo5tinpr0** [comment]
Glad everything worked out :)

**Comment by larsDom** [comment]
Ok thanks again. Now everything works again. I was already desperate. wishing a nice evening
