### ISSUE TITLE
Updated the balance to zero

### ISSUE THREAD

**Issue by Igor616** [iotaledger/wallet#1224]
Wallet updated to 2.5.7 and the balance is zero. the nodes all looked but the balance never showed up?

**Comment by lo5tinpr0** [comment]
Hey @Igor616 , try to generate new addresses and attach them to the tangle. After a few times your old balance should reappear.

**Comment by Igor616** [comment]
Thanks for the quick reply) did it but the Balas are not full half no

**Comment by Igor616** [comment]
Thank you very much) everything is fine) restored) THANK you;-)
