### ISSUE TITLE
binance no IOTA

### ISSUE THREAD

**Issue by Igor616** [iotaledger/wallet#1242]
Hello I have transakcija does not pass on binance ZFSRVSEAE9M9FZ9PVZZGQYWQSYQZDRLTAH9SPKUXCPTGTJJL9YBSZXTCVUGWKOPSVRGKRNUJNOXEZ9999

**Comment by lo5tinpr0** [comment]
Hey @Igor616 , your transaction has been confirmed. Should a transaction take a little longer again, you can promote and reattach it here: [http://pro.iota.fm/](http://pro.iota.fm/)
