### ISSUE TITLE
The wallet is running in my task manager but not visible anywhere on screen

### ISSUE THREAD

**Issue by ChrisFT** [iotaledger/wallet#125]
The first time I installed the wallet it opened as expected, after closing and trying to re-run the wallet it now doesn't come on screen although it apparently is running (can see this in task manager).  (Version 2.3.0).

**Comment by atypicalprogrammer** [comment]
Force quit it in the task manager and try opening it again. If you want, try to replicate to know if this behavior happens time and time again, or if it was a one-off.

**Comment by ChrisFT** [comment]
I've tried that - didn't help. I've installed-uninstalled etc and also tried installing the previous release which actually did work - it ran, I generated a seed etc, closed it and then couldn't get it to show up again (despite it saying it was running in task manager) and so the same problem persists.

**Comment by atypicalprogrammer** [comment]
What OS ?

**Comment by ChrisFT** [comment]
Windows 10 Education

**Comment by atypicalprogrammer** [comment]
Run the exe via command line interface and note if you see any errors in the output.

**Comment by ChrisFT** [comment]
Just tried this - no errors are output.

**Comment by atypicalprogrammer** [comment]
You did close any other instances first via the task manager, right?

**Comment by ChrisFT** [comment]
Yeah

**Comment by atypicalprogrammer** [comment]
Until I can replicate the issue, I cannot do anything. I tried it on windows 10, works just fine over here.
