### ISSUE TITLE
Balance in GUI shown in Gi cut-off zero's at the end of the value

### ISSUE THREAD

**Issue by Nyrsta** [iotaledger/wallet#127]
Let's assume a seed contains 7502770184 iota.
The balance in the GUI wallet will show 7.5+ Gi
When you click it open it will show 7.502770484 Gi  (9 numbers after the dot)
Everything OK here!

Let's assume a wallet contains 7502770100 iota
The balance in the wallet with show 7.5+  Gi
When you click it open it will show 7.5027701 Gi  (only 7 numbers after the dot! The zero are left away)
If I transfer away 7.5027701 Gi I will have 99 iota left in my seed!

We should always see the exact balance without the 0 cut off in my opinion. We should not have the need to count here.

So example screenshots from within wallet.
![balance](https://user-images.githubusercontent.com/5579055/27263944-2c82cbfa-5475-11e7-8d7a-0beb6966852d.png)

**Comment by atypicalprogrammer** [comment]
I've checked the conversion in the wallet and 7.5027701 Gi is converted to 7502770100 i.

**Comment by atypicalprogrammer** [comment]
Closed until more info given, cannot replicate.
