### ISSUE TITLE
initialization error

### ISSUE THREAD

**Issue by dsilbert2u** [iotaledger/wallet#128]
trying to install the iotaledger i got the following error: 

    Error: Unable to access jarfile /Users/xxxx/wallet/iri/iri.jar
    Process exited with status 1

i'm not see an iri.jar file in that folder. any help here would be greatly appreciated. was also curious if the documentation was outdated, and if we should be using electron-prebuilt (which is deprecated) vs electron.

**Comment by atypicalprogrammer** [comment]
Get the jar from https://github.com/iotaledger/iri/releases (mainnet) and name it iri.jar, place it in a subdirectory called "iri".

electron and electron-prebuilt are the same now (just an alias), will update docs, thanks.
