### ISSUE TITLE
How do i know wallet is installed on headless server 

### ISSUE THREAD

**Issue by lettertoamit** [iotaledger/wallet#13]
How do i know wallet is installed on headless server ..........
How can i see my wallet in it. 

I have tried this code is working in windows desktop but when i switch it to my linux server without GUI that too remotely.I am not able to find out wallet working.

**Comment by atypicalprogrammer** [comment]
Headless server? For headless server you simply download the jar (latest as of this post is : http://188.138.57.93/IRI-1.0.6.jar ) and execute that as follows: 

java -jar IRI-1.0.6.jar YOURPORT udp://IP1:port1 udp://IP2:port2 udp://IP3:port3 

(YOURPORT would typically be 14265)

IPs are your neighbors, join slack ( http://slack.iotatoken.com ) to ask for neighbor nodes.
