### ISSUE TITLE
Norton found a security Risk in your windows installer exe

### ISSUE THREAD

**Issue by squadwuschel** [iotaledger/wallet#130]
When I Download your Windows Installer my Norton Security is deleting it, because :

![grafik](https://user-images.githubusercontent.com/1572878/27392573-4d47be3e-56a7-11e7-957c-62ac12f61af4.png)

**Comment by atypicalprogrammer** [comment]
More than likely a false positive.

**Comment by atypicalprogrammer** [comment]
Closed until further info given.

**Comment by asifssarker** [comment]
When I scan any IOTA Wallet setup exe file through the virustotal, it alerts some trojan and malware detected! Sound very strange, hope some one can give me the right wallet file to download, thanks.

https://www.virustotal.com/en/

IOTA.Wallet.Setup.2.4.0.exe

Baidu | Win32.Trojan.WisdomEyes.16070401.9500.9582 | 20170817
WhiteArmor | Malware.HighConfidence | 20170817
