### ISSUE TITLE
HELP!!!  My Iota Balance is 0!

### ISSUE THREAD

**Issue by eluterior** [iotaledger/wallet#132]
I deposited 1,467 of Iota into my Iota Light Wallet 3 days ago and it disappeared!  I have re-generated new addresses again and again to no avail.  Please help me...  My email address is teorod3@gmail.com

**Comment by atypicalprogrammer** [comment]
Probably using a wrong seed.

**Comment by eluterior** [comment]
I took a picture of the seed and copied it.  Is there a way to recover the
correct seed if indeed this is the wrong seed.  I'm lost, need my balance...
