### ISSUE TITLE
Problems to send iotas from one seed to another...

### ISSUE THREAD

**Issue by AlePitarch** [iotaledger/wallet#136]
Hi, i get error all the times i tried (2 weeks) to send iotas from one seed to another (light wallet). Could somebody help me with this?

When i go to my new seed and try to attach to tangle the address i get "REQUEST ERROR: INVALID TRANSACTION HASH" - Anyway, i copy the address and then go to my old seed, go to send, paste the address, put the amount and i get again "REQUEST ERROR: INVALID TRANSACTION HASH"

Thanks for the replies!

**Comment by atypicalprogrammer** [comment]
This is to do with the light node that you are using, which is overloaded and returning HTTP 500 errors.
