### ISSUE TITLE
Wrong amount in history

### ISSUE THREAD

**Issue by Fredi100** [iotaledger/wallet#139]
After transfering 100 Mi from bitfinex to my seed. I saw the transaction appear in the history. But instead of 100 Mi it states 1 Gi which would be awesome, but is not correct.
![2017-06-25](https://user-images.githubusercontent.com/2962747/27517995-25f4c520-59d6-11e7-8300-e607de51f4c9.png)

**Comment by atypicalprogrammer** [comment]
This is fixed in dev build, it's due to multiple output bundle. You are correct, no 1 Gi for you ;-)
