### ISSUE TITLE
Things not clear on doc ( confused with relation between doc and code wallet )

### ISSUE THREAD

**Issue by snvankit07** [iotaledger/wallet#14]
Hi ,I am impress with your DAG based concept , but i am confused as i have tried your code 
on my linux  server ( ubuntu desktop  still struggling to install ).

1) should my neighbor execute same code of wallet in his ubuntu server or i should distribute my executable to all.
2) how can i find my 100 iota
3)  if(seed  == wallet) or seeds are server and wallet is executable.
4) how to convert my server to seed.

**Comment by domschiener** [comment]
1. No, just download and install and find neighbors, then you're ready to go.
2. There is no 100 IOTA.
3. Seed != wallet 
4. You don't have to do anything. Your seed is your "password" to access your account.
