### ISSUE TITLE
Feature Request: Safe / Unsafe Indicator and Other Info in Address List

### ISSUE THREAD

**Issue by msm595** [iotaledger/wallet#141]
As I understand it, Iota addresses become significantly weaker after a spend due to the nature of the underlying Winternitz one-time signatures. 

I suggest adding additional info to the address list to show whether that address is safe for receiving funds (no outgoing transactions from it), as well as individual balances and perhaps other information. The format can be similar to items in the transfers list.

**Comment by craypto** [comment]
All addresses are safe to receive funds. Its the spending from the same address that is the problem. The GUI wallet already takes care of this for you by spending from a new address every time.

**Comment by msm595** [comment]
But what if you (1) receive at an address, (2) send from it, then (3) receive at it again. To remove the coins a second time would result in that weakness. My suggestion is to mark the address after (2) in the list of wallet addresses to prevent (3) and address reuse.
