### ISSUE TITLE
URI scheme

### ISSUE THREAD

**Issue by joakim** [iotaledger/wallet#144]
I see that the app registers the `iota` URI scheme, but it's not handled in any way. Any plans for how the URI will be structured?

[BIP21](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki) is a well established scheme for Bitcoin, and may be a good starting point.

**Comment by atypicalprogrammer** [comment]
No plans at the moment, be sure to discuss this on slack with @dom and the rest of the community.

**Comment by joakim** [comment]
I just went ahead and made a proposal based on BIP21 :)

https://github.com/joakim/iota-uri-scheme

Especially interesting when combined with Eric Hop's [IOTΛlias proposal](https://medium.com/iota-demystified/iot%CE%BBlias-a-wallet-protocol-for-implementing-public-and-private-aliases-219f1ce6e1cb), solving donations, aliases and more. See [this issue](https://github.com/joakim/iota-uri-scheme/issues/2) that I've opened.
