### ISSUE TITLE
Multi-Signature and 2FA features?

### ISSUE THREAD

**Issue by craypto** [iotaledger/wallet#145]
Is there multi sig available for IOTA? If there isnt, this is a really important feature that I dont think would be too hard to implement. This could be really useful for organizations and adds a lot of security for them and individuals in how they store their seeds.

Also, is 2FA ever going to be implemented in signing into a wallet? I know this has become common practice for many websites, but I dont know if I have seen it implemented in a wallet. My intuition tells me that it is just another form of multisignature, but maybe harder to implement (because you have to connect with another device and its architecture). 

While I absolutely LOVE the simplicity of the clients and wallets ive used with IOTA, I can see how some people feel a bit insecure by the simplicity.

**Comment by frohal** [comment]
"Also, is 2FA ever going to be implemented in signing into a wallet?"
This will only protect that one physical copy of the wallet/seed.
This would require a feature of generating/storing seed inside a wallet-file first (without ever beeing able to take it out of the wallet), with an encryption that only could be unlocked with 2FA, But the second you write down the seed first, or by any means expose the seed 'outside' the wallet, the protection by 2FA is gone...

**Comment by todofixthis** [comment]
Hey @craypto!  FYI, multisig functionality is implemented (or under development) in the IOTA API libraries.  In particular, it is already implemented in the Javascript lib, which the Wallet app uses under-the-hood, so it's definitely _possible_ to implement in the Wallet.  I can't speak to when that will happen, though (I work exclusively on the Python API library).

WRT MFA, think of your seed less as a wallet password, and more like the input to an algorithm.  **No matter which device you are using,** if you have the seed, then you can generate the private keys for your addresses.

I do like the idea of using multisig as a safety measure though, and it would be interesting to see a hardware multisig feature integrated into the wallet.  Your seed would still be vulnerable to theft, but all of the addresses that have any IOTAs in them would be multisig, so an attacker wouldn't be able to spend your IOTAs without **both** your seed and your hardware device.

See https://github.com/iotaledger/wiki/blob/master/multisigs.md for more info about how multisig works in IOTA.
