### ISSUE TITLE
Wallet database location bug. switching between 2 different locations?

### ISSUE THREAD

**Issue by lueyforje** [iotaledger/wallet#146]
run iota windows full node 2.3.0 
then go in the menu > tools > Open Database Folder >

and you will end up in this directory "C:\Users\Username\AppData\Roaming\IOTA Wallet\iri"
then stay in your client you switch to light mode and switch back in to full node 

tools >Switch to Lightnode > tools >Switch to fullnode > tools > Open Database Folder 
and this time you will end up in another directory "C:\Users\Username\AppData\Local\Programs\iota"

both directories has a copy of database, the wallet IS switching between these two different databases!
it also happens when you change a setting in the wallet where it auto restarts the wallet. (edit node settings etc..)

**Comment by atypicalprogrammer** [comment]
Are you using dev branch or the released 2.3.0?

**Comment by lueyforje** [comment]
hi, i downloaded from https://github.com/iotaledger/wallet/releases
