### ISSUE TITLE
in a fresh install if user chooses light node as first choice, they wont have option to change to full node

### ISSUE THREAD

**Issue by lueyforje** [iotaledger/wallet#147]
also in a fresh install of windows gui wallet 2.3.0
when the user first selects light wallet node to use their wallet during the first run, after that if they decide to go full node, it will not work, it just takes you to the port settings page instead of the neighbors page to add in for the full node.

**Comment by atypicalprogrammer** [comment]
port settings page == the neighbors page..? What am I missing here? Screenshot?

**Comment by lueyforje** [comment]
looks like its working normally in the latest 2.3.1. 
before if installing iota for first time (no neighbor ip saved) and you choose light wallet first and then decide to choose full node, it did not give the option to add neighbor nodes after clicking > switch to full nodes, instead it went to the port setup page.
