### ISSUE TITLE
IOTA Concept problem

### ISSUE THREAD

**Issue by mecgrath** [iotaledger/wallet#15]
How the nodes will get interacted between the DAG , so I want to know when a wallet A send the money to Wallet B , how does it get decided it reach to Wallet B only , Please help ?  And if it transact between number of nodesthen why other node will participiate into it ?

**Comment by atypicalprogrammer** [comment]
Please ask these questions on the slack or on the forum ( http://forum.iotatoken.com ) - as it is not related to the wallet app I will close the issue.
