### ISSUE TITLE
Balance keeps fluctuating up and down

### ISSUE THREAD

**Issue by PatriQ94** [iotaledger/wallet#154]
Logged into the newest version of  wallet (v2.3.1), after couple of minutes the Balance started randomly fluctuating up and down (without doing/clicking anything within the wallet). So does the number of transfers and addresses in "History" tab. They do not change simultaneously but async or random I should say. Tried generating like 30-40 new adressess and the balance was steady for couple of minutes, afterwards started fluctuating again. The cycle keeps going on and on and on...

**Comment by wonkytonky** [comment]
i had the same issue so what you can try is  :
close your wallet application. 
in windows : <youruser>\AppData\Local\IOTA Wallet
delete all files there
restart wallet  
enter your seed
this helped me. it's a dirty quickfix ..

**Comment by PatriQ94** [comment]
This actually did help. It does not flucuate anymore.
