### ISSUE TITLE
My remaining IOta Coins will not transfer from history to balance.

### ISSUE THREAD

**Issue by popie197** [iotaledger/wallet#155]
Iota... I purchased Iota coins on BitFinxx Exchange and on July 6th.  I set up my Iota wallet to transfer the coins to my iota light wallet.  THe first transaction of 50 coins went quickly and I received them in my balance of iota wallet in minutes.  
I then sent the balance of my coins from the BitFinexx exchange and the coins have been pending for over 25 hours.
I checked the BitFinxx exchange and they show both confirmations and updated my account.  
I see the remaining coins (690 Mi) still pending in the Iota light wallet 2.2.6 - IRI 1.2.4 version.   Can you please provide assistance to have the coins transferred from pending to complete and place in the balance of Iota light wallet.  
Thank you.

Best Regards,

David

**Comment by arancauchi** [comment]
This is not necessarily a wallet issue, rather, it could be a double spend error on the part of Bitfinex. Have you tried checking the address in one of the iota tangle explorers, such as http://www.iota.tips/ ?
