### ISSUE TITLE
LatestSolidSubtangleMilestoneIndex does not update

### ISSUE THREAD

**Issue by k3kc** [iotaledger/wallet#157]
2.3.1 full GUI node on windows.
latestSolidSubtangleMilestoneIndex never changes when I click "view Node info". However, it jumps close to (but never at) latestMilestoneIndex when I restart the node.

**Comment by k3kc** [comment]
Update: it started to update once the node became in full sync (after 5 days). However, before it was frozen.

**Comment by wonkytonky** [comment]
you can also just change to a node that has latest milestone
