### ISSUE TITLE
Light Wallet 2.3.0 says "could not connect to remote node" on Windows 10 ... x64

### ISSUE THREAD

**Issue by cbennie** [iotaledger/wallet#160]
Hi, I have not used this wallet for about two weeks and now, I get the above message.

Tools | Edit Node Configuration - gives 
Host
http://lightserver1.iota.community:14600

Min Weight Magnitude
15

How shall I proceed?
Many thanks.
Cecil.

**Comment by wonkytonky** [comment]
http://www.iotasupport.com/gui-lightwallet.shtml

enter other node.

fyi there is a new wallet.. uninstall current one
https://github.com/iotaledger/wallet/releases
make sure your current seed is long enough   read info on the  release page.

install new wallet 2.3.1
choose your node(there's a dropdown menu i think)
enter seed 
try again
