### ISSUE TITLE
windows wallet loads long time at the small loading box.

### ISSUE THREAD

**Issue by lueyforje** [iotaledger/wallet#162]
Windows wallet 2.3.1 iri 1.2.4 
i think usually when not in full sync but had this happened before with fully in sync wallet, but when without full sync it does this every time, takes forever to get back once restart the wallet.
 I think it takes hours, the more tx in the db the longer it takes.

might be related to this issue here after discussing with alon https://github.com/iotaledger/iri/issues/233

**Comment by cmrichsw** [comment]
I have the  same problem and than crashes after I exit the program. IOTA support is very difficult

Trying to get help in https://forum.iota.org/ fails because my IP range is being blocked. How do you think people are going to invest in your currency if they lose money and get no help?

**Comment by cmrichsw** [comment]
We all have to learn not all of us are Know it alls!
    On Monday, January 1, 2018, 8:05:46 AM GMT+7, Rajiv Shah <notifications@github.com> wrote:  
 
 
Closed #162.
