### ISSUE TITLE
CPU usage not correct

### ISSUE THREAD

**Issue by sdellava** [iotaledger/wallet#166]
Hi Devs, I've guess the CPU usage shown in the bottom of the Windows Wallet is not correct

It is almost the double of the value reported by the System monitor.

As you can see in this screenshot the wallet says 70% and the real value is 37%

![image](https://user-images.githubusercontent.com/11772150/28469373-4b9e9ab6-6e36-11e7-834f-ba4e3a926d22.png)

**Comment by bmavity** [comment]
It looks like this is an issue with the cpu usage module that the wallet is using.

> Memory usage will also display the RSS only, process cpu usage might differ from a distribution to another. Please check the correspoding man ps for more insights on the subject.

You can ask over here https://github.com/soyuka/pidusage

**Comment by soyuka** [comment]
As shown in the Task manager is the total cpu usage on the computer, not the one from the process. Those values can not be compared because cpu upsage is computed with the `usermodetime` and `kernelmodetime` (values in milliseconds used by the current process) through the process `uptime`.

**Comment by soyuka** [comment]
Just looked at the code, [this is wrong](https://github.com/iotaledger/wallet/blob/96e847272c5e225d2656c1bf967b934e4d98f942/app/js/main.js#L1416). 

If you `unmonitor` here you're removing the process history and the process usage computation will never be correct. The `unmonitor` method should be called in `stopTrackingCPU`.
