### ISSUE TITLE
Light Wallet Turns Black When Trying to Attach Receiving Address to Tangle 

### ISSUE THREAD

**Issue by bdon22** [iotaledger/wallet#167]
![4fc997a86c2259c8d720116857f583dc](https://user-images.githubusercontent.com/30383284/28497491-70a25c82-6f56-11e7-88e9-59dedae17232.png)

I get this screen when I try to attach a receiving address to the tangle. Tried to re-install and reboot Windows, condition remains.

**Comment by krdh** [comment]
IOTA Light Wallet 2.3.1 - IRI 1.2.4  on ( Win7-64 SP1 home Premium ),connected to [iota.bitfinex.com:80]

I have a similar situation that it Never completes the command [attach to tangle], no timeouts or error/warning messages.

![image](https://user-images.githubusercontent.com/18367475/28567892-3127f74e-7134-11e7-819c-26e881cf72c1.png)
![image](https://user-images.githubusercontent.com/18367475/28567990-8b7ab678-7134-11e7-8fc2-f7b1d791df2f.png)

**Comment by rage13337** [comment]
If you use a Intel GPU (f.e. HD 520) please update your GPU drivers!
