### ISSUE TITLE
wallet gui full node connection refused on login

### ISSUE THREAD

**Issue by chronakazi** [iotaledger/wallet#168]
i have active neighbors and was successfully logged in earlier today. after a restart i'm met with a connection refused error and am unable to login. created a new seed and successfully logged in with that, but im still wondering why my first seed suddenly throws an error. my node info looks normal and very close to full sync. any guidance in getting my initial seed properly reconnected and logged in would be great. thanks.

windows 10 server, dedicated ip. 
server log: 
https://pastebin.com/86DHpAtb

**Comment by rajivshah3** [comment]
I had this issue once. I think it refuses log in if your node is not completely, fully synced

**Comment by chronakazi** [comment]
yea ive been hunting around to solve my sync issues but i am very close. thanks for all your help!

**Comment by AbinavMay24** [comment]
i installed wallet on windows 8 and worked fine . Update to 10 and now i get connection refused Error. ANy suggestions ??
