### ISSUE TITLE
macOS: Can't copy and paste between light-node and rest of the operating system

### ISSUE THREAD

**Issue by adrianbrink** [iotaledger/wallet#169]

**Comment by bmavity** [comment]
Copy and paste what? Addresses?

If you click on them, it copies them to the clipboard on mac.

**Comment by rajivshah3** [comment]
What version of macOS are you on? I had a bug like this once, but it might have been caused by something else.

**Comment by rajivshah3** [comment]
Try running the following commands:
```
launchctl stop com.apple.pboard
launchctl start com.apple.pboard
```
This will kill the clipboard process and start a fresh one. Keep in mind that you will need to quit all programs or restart your computer otherwise some apps will still use the old process and the clipboard data will not match up as expected.
