### ISSUE TITLE
Issue While SettingUp Project

### ISSUE THREAD

**Issue by DrBulao** [iotaledger/wallet#17]
Hi,

I have followed each and every step in Wallet and IRI project.

After all the node setups and maven setups,finally I am able to run the program.

While I run it in browser (localhost:14265://), I got one JSON with "{Duration : Randomno(1) }".

Can you please guide how to use this program.In CMD screen it shows some null pointer exception,too. ?

If you can let me know that what should be desired output then it would be really helpful
Thanks
Parth Kansara

**Comment by atypicalprogrammer** [comment]
This is the wallet app, it starts a standalone app, so how or why are you accessing it in the browser instead?

**Comment by atypicalprogrammer** [comment]
Closed until more info is supplied.
