### ISSUE TITLE
Incorrect Balance when Sending Transaction

### ISSUE THREAD

**Issue by willowfoot** [iotaledger/wallet#178]
Dont know if this is a bug, but have seen this happen more than once.

When I've sent a transaction during the pending state, the balance changed (went to 0 one time)
but then when confirmed balance was restored to normal ...

Light wallet 2.3.0 on a MAC.

**Comment by Dudenicks** [comment]
No need to worry. The wallet sends your balance for security reasons to a new internal adress.
