### ISSUE TITLE
How can I download the IOTA wallet if I have 32-bit windows??? It brings me up a message about "32-bit being unsupported"

### ISSUE THREAD

**Issue by ian369** [iotaledger/wallet#179]

**Comment by eragmus** [comment]
If 32-bit is not supported, then the IOTA GUI wallet is not compatible with a 32-bit Windows computer. An alternative can be to use the Android wallet, or upcoming iOS wallet when it releases.

**Comment by ReversalMasterZ** [comment]
Any new on the iOS wallet??
