### ISSUE TITLE
My IOTA wallet is showing a zero balance!!!

### ISSUE THREAD

**Issue by kangsta4life** [iotaledger/wallet#180]
I had a balance yesterday in my IOTA wallet but today when I checked in... it is showing a zero balance!  What is going on?  Anyone?

**Comment by eragmus** [comment]
Please follow instructions in the blog post:
https://blog.iota.org/new-gui-transition-phase-explained-b536ed80f412

If "pending" at the end after doing the "transition", then login to new seed, go to "history section, click "show bundle" on the incoming transaction, and click "reattach".
