### ISSUE TITLE
IOTA were gone

### ISSUE THREAD

**Issue by bart886** [iotaledger/wallet#182]
I buy IOTA on bitfinex and transfer to my wallet on 24-06-2017 and  i had IOTA in wallet. I have not used my wallet until today. Everything was gone. Balance 0. TXID UJL9FXLL9LKWMLRTZIMICXHFXPOK9K9A9VDYDUWARY9CJQDRWTMLIU9EGYENILZMGVRBPVMRQGWY99999. What happened?

**Comment by bart886** [comment]
ok i now

**Comment by stepby7** [comment]
Calm down mate!

1.       How familiar are you with the system?

2.       Do long is your seed?

3.       Do you think your seed may have been compromised?

4.       Is your seed made up of repeated phrases? (Never mess with a seed)

There are a number of things that can make your funds invisible to you when
they are actually available. It has happened to me before.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Clermont1** [comment]
same issue. Sept 14 and still not showing up. wallet address is correct.  where can we find the transaction? txid: GOIVWVTBZNCNCJBYZYYMKXXUDUILN9QNCFKMNFRBWLSRTZRPAIUJILZRESYFRB9VJPJPS9CVLJVF99999
