### ISSUE TITLE
My IOTA Wallet is Showing Zero also...!!!

### ISSUE THREAD

**Issue by AKALIY** [iotaledger/wallet#183]
Me Too ZERO BALACE..!!!!!

**Comment by WendyCoin** [comment]
Mine too!

**Comment by Polve** [comment]
You need to generate addresses and attach them to the tangle.

I'm able to generate only one though, maybe we need to wait for the bundle to be confirmed but after many hours mine is still "pending".

**Comment by eragmus** [comment]
@AKALIY @WendyCoin @Polve Please follow instructions in the blog post:
https://blog.iota.org/new-gui-transition-phase-explained-b536ed80f412

If "pending" at the end after doing the "transition", then login to new seed, go to "history section, click "show bundle" on the incoming transaction, and click "reattach".
