### ISSUE TITLE
Windows 7 64Bit Java Loop

### ISSUE THREAD

**Issue by pondsea** [iotaledger/wallet#19]
I have a brand new install of Windows 7 Ultimate 64 bit.

When i downloaded the official GUI install.exe it found that i dont have java installed.

I clicked next to download java.

Java pops up, i click install but that is the end of the java prompts.

After a while iota prompts to say that i dont have java installed. Then i go through the same process without ever fully installing java.

I installed the java manually and that corrected the issue.

**Comment by atypicalprogrammer** [comment]
So, does it actually complete the java download? (Did the progress bar fill completely?)

Perhaps it has something to do with privileges? Are you using a non-admin user?

**Comment by pondsea** [comment]
Yes Java was fully downloaded. I am using a admin user. When i installed Java manually it worked without any permission issues.

**Comment by pondsea** [comment]
I am installing a fresh win 7 64 bit installation so will be able to verify this.

**Comment by pondsea** [comment]
Looks like this can be closed in new 2.0 wallet. It just says java failed and to download it manually.

**Comment by pondsea** [comment]
@atypicalprogrammer @domschiener
