### ISSUE TITLE
Zero Balance

### ISSUE THREAD

**Issue by ghost** [iotaledger/wallet#193]
When I opened my IOTA desktop wallet (that I got from GitHub) today my balance says zero and I should have 1998. I have my randomly generated seed which works but all of a sudden my coins are gone. When I look at history it shows nothing. I have not attempted any transfers. I check it daily and so yesterday all was good. I am trying not to freak out, I cannot imagine that I was hacked because it is a pretty small amount relatively speaking. Please advise!

I am a total newbee and need step by step guidance on how to deal with this. 

Thank you :)

Jennifer Golden
805.423.5835

**Comment by stockermans** [comment]
Hello jgogurl,

Nothing to worry about. There was some annoucements.
You need to upgrade the wallet, and there is a Transition you must do.
Here is the post about it.
https://blog.iota.org/new-gui-transition-phase-explained-b536ed80f412

After you do that, you will have a new seed, and your balance will be in that :)

**Comment by adamrp** [comment]
From the article you linked:

>This involved sending the balance from your old seed to a new seed as an extra security precaution.

Can one of the developers please expand? This statement makes it sound like some central authority has the power to move any account's funds arbitrarily.

**Comment by wonkytonky** [comment]
nobody can move anything . unless you have the seed..   no central authority has your seed.; only you because you have the seed.

**Comment by adamrp** [comment]
@wonkytonky That's what I thought. I think it's a typo in the blog post. I believe it should say "involves" (present tense) instead of "involved" (past tense). The use of the past tense there makes it sound like the transfer was already performed by someone other than the rightful seed-owner.
