### ISSUE TITLE
Issue in the transition of iota a new seed

### ISSUE THREAD

**Issue by Jazmany** [iotaledger/wallet#195]
Hi everybody, I need your help. Trying to change my IOTAs to new seed for update, I had a Issue. I installed iota light wallet and I followed all the steps. My balance of IOTAS were correct, but when I put the new seed and then press transition it did not works.

I have waiting for two hours and it continue in the transitioning process and it never finish. I tried to cancel but cant do it while it is transitioning. I dont know what to do. Im worried, dont want to lose my IOTAs.

![iota](https://user-images.githubusercontent.com/30935717/29225945-cd4e0aa0-7e95-11e7-809f-1925a31cfb0f.jpg)

**Comment by robocop1976** [comment]
I ve had pretty much the same issue. As I clicked away the window in which I was asked for the new seed... Hope to get an answer soon (202)

**Comment by ejpcmac** [comment]
I had a related issue: I set the same seed as the old one, as it was specified in the first message from the transition utility. Then, I saw a pending transaction in my wallet for weeks, but it never arrived. I now upgraded to 2.5.1, and all my IOTA (143M) are all gone.
