### ISSUE TITLE
when I search my address , it shows zero balance

### ISSUE THREAD

**Issue by ikashi08** [iotaledger/wallet#197]
How can i retrieve my IOTA?

**Comment by wonkytonky** [comment]
hi go trough other issues here.. there's a  few ppl who had the same issue.  probably because you didn't do an update yet.  there has been an update and snapshot.

**Comment by ikashi08** [comment]
i already made an update.. what snapchat?

**Comment by Dudenicks** [comment]
which wallet release do you use?
