### ISSUE TITLE
Cannot get any neighbour txt and so stuck at 6000

### ISSUE THREAD

**Issue by Pedro-Martial** [iotaledger/wallet#20]
I am using the same laptop as wallet 1.0 and i have open firewall to ioto wallet and the port. I am using noip and i can confirm my neighbors are seeing my correct ip.

I have 17 neighbors and yet cannot get any connection. I have about ten or more others with the same problem.

I a running the spammer to encourage connection but still on 6000 and cannot proceed.

please check the ioto slack in testing as we have been discussing this issue.

server log

IRI 1.1.1.1
Confirmed transactions = 1
24 tails need to be analyzed
23 extra transactions approved
Confirmed transactions = 24
0 tails need to be analyzed
0 extra transactions approved
Transactions to request = 0 / 24 (46 ms / 0%)
Transactions to request = 0 / 24 (28 ms / 0%)
Transactions to request = 0 / 24 (29 ms / 0%)
Transactions to request = 0 / 24 (29 ms / 0%)
Transactions to request = 0 / 24 (32 ms / 0%)
Transactions to request = 0 / 24 (30 ms / 0%)
Transactions to request = 0 / 24 (29 ms / 0%)
Transactions to request = 0 / 24 (29 ms / 0%)
Transactions to request = 0 / 24 (28 ms / 0%)
Transactions to request = 0 / 24 (29 ms / 0%)
Transactions to request = 0 / 24 (29 ms / 0%)
Transactions to request = 0 / 24 (29 ms / 0%)
Transactions to request = 0 / 24 (28 ms / 0%)
Transactions to request = 0 / 24 (28 ms / 0%)
Transactions to request = 0 / 24 (28 ms / 0%)
Transactions to request = 0 / 24 (28 ms / 0%)
Transactions to request = 0 / 24 (29 ms / 0%)
Confirmed transactions = 1
25 tails need to be analyzed
24 extra transactions approved
Confirmed transactions = 25
0 tails need to be analyzed
0 extra transactions approved
Transactions to request = 0 / 25 (45 ms / 0%)
Transactions to request = 0 / 25 (35 ms / 0%)
Transactions to request = 0 / 25 (32 ms / 0%)
Transactions to request = 0 / 25 (34 ms / 0%)
Transactions to request = 0 / 25 (34 ms / 0%)
Transactions to request = 0 / 25 (32 ms / 0%)
Transactions to request = 0 / 25 (35 ms / 0%)
Transactions to request = 0 / 25 (35 ms / 0%)
Transactions to request = 0 / 25 (33 ms / 0%)
Transactions to request = 0 / 25 (33 ms / 0%)
Transactions to request = 0 / 25 (34 ms / 0%)
Transactions to request = 0 / 25 (32 ms / 0%)
Transactions to request = 0 / 25 (34 ms / 0%)
Transactions to request = 0 / 25 (33 ms / 0%)
Transactions to request = 0 / 25 (32 ms / 0%)
Transactions to request = 0 / 25 (36 ms / 0%)
Transactions to request = 0 / 25 (33 ms / 0%)
Confirmed transactions = 1
26 tails need to be analyzed
25 extra transactions approved
Confirmed transactions = 26
0 tails need to be analyzed
0 extra transactions approved
Transactions to request = 0 / 26 (33 ms / 0%)
Transactions to request = 0 / 26 (28 ms / 0%)
Transactions to request = 0 / 26 (29 ms / 0%)
Transactions to request = 0 / 26 (29 ms / 0%)
Transactions to request = 0 / 26 (28 ms / 0%)
Transactions to request = 0 / 26 (28 ms / 0%)
Transactions to request = 0 / 26 (31 ms / 0%)
Transactions to request = 0 / 26 (27 ms / 0%)
Transactions to request = 0 / 26 (27 ms / 0%)
Transactions to request = 0 / 26 (27 ms / 0%)
Transactions to request = 0 / 26 (28 ms / 0%)
Transactions to request = 0 / 26 (29 ms / 0%)
Transactions to request = 0 / 26 (28 ms / 0%)
Transactions to request = 0 / 26 (28 ms / 0%)
Transactions to request = 0 / 26 (29 ms / 0%)
Transactions to request = 0 / 26 (27 ms / 0%)
Transactions to request = 0 / 26 (28 ms / 0%)
Confirmed transactions = 1
27 tails need to be analyzed
26 extra transactions approved
Confirmed transactions = 27
0 tails need to be analyzed
0 extra transactions approved

**Comment by tiresias54** [comment]
do you use the old database? If yes, you must delete all the .iri files and restart.

**Comment by atypicalprogrammer** [comment]
Too many neighbors. Make sure your neighbors use your node ip as well. This is not an issue with the wallet so this will be closed.
