### ISSUE TITLE
it says that my iota wallet doesnt exist for deposits

### ISSUE THREAD

**Issue by jogearg** [iotaledger/wallet#200]
i already create my iota wallet and it says that my deposit adrees of iota wallet doesnt exist canyou help me please???

Example
Invalid iota address (MFMDCUKPXQSLEBIPHLRWBEIJKGAOJJAYDUNKJRMPDHEGENQIHGPAUMNTS9C9U9WBJHG9IXXAJAUQHBJGAHZOFSTOZX)

**Comment by wonkytonky** [comment]
thats a bitfinex error right?

**Comment by Dudenicks** [comment]
Which wallet release do you use? There was a software update and a transition of seed after the snapshot. So if you did not pass this transition, then your old seed will not be found by bitfinex.
