### ISSUE TITLE
INVALID TRANSACTION HASH

### ISSUE THREAD

**Issue by nightsfa4** [iotaledger/wallet#201]
I got the : IOTA Light Wallet 2.4.0 IRI 1.3.1

Wanna sent IOTA , but  X Invalid transaction Hash appears.

Everthing is correct on my side,

What can i do ?

**Comment by wonkytonky** [comment]
try again, or change node and try again  still error?

**Comment by nightsfa4** [comment]
If You can explain me how i run a full node , never changed to.
What you i wirte into : "Neighboring Nodes" if i use http://service.iotasupport.com:14265 ?

**Comment by iotauser** [comment]
Have the same issue when trieng to reattach an unconfirmed transaction (bundle hash: KERFTKCPQKPQIXVFRXDOLCLPECVCHVYIEHAILZJCQKHV9SLSPRHFDUKNIEEUCUFFUPFFXTRLBLFJIWYXABVKXHWFQ9) tried different nodes with the same result. Trying to make another transaction results (after a double spend warning) in the same 'invalid transaction hash' message. And I don't unerdtand why it has to be a double spend because the unconfirmed transaction was about 2222 kIOTA, the new one should be 3333 kIOTA while the balance in the wallet is 116 mIOTA, so these transactions should be possible without double spend.

**Comment by capitalsounds** [comment]
I have the same problem.  I have downloaded and installed 2.4.dmg (for Mac) and successfully located my full balance (100 addresses), all good.  However, when inputting my new seed, confirming and then got the same 'Invalid Transaction Hash' message.

I tried it again and the second time the Transaction was validated.

The confusion I am now facing is that the balance of IOTA in the New 2.4 wallet is showing '0' ??

I am guessing that I need to wait for the 'transaction' showing as 'pending' with my full balance on needs to be confirmed and then the balance will show in full under 'balances'?

Apologies in advance if this is a basic Q but I am keen to ensure this transition is smooth prior to adding more of my IOTA.  Thanks

**Comment by playforpleasure** [comment]
I have IOTA still pending to be confirmed after updating to the new wallet. So I tried to reattach but when I reattach it says invalid transaction hash. Do you know what I should do?

**Comment by capitalsounds** [comment]
Be good for everyone to update the thread with news or solution as/when they come about.  

I'm going to leave my transaction as pending until tomorrow and try to re-attach.

There is a lot of volume building at present so I wonder If the tangle is just super-busy?

**Comment by rage13337** [comment]
**Everyone with the "INVALID TRANSACTION HASH" can also update the GPU drivers to the latest version! Especially Notebook GPUs can cause this problem.**

If this is not the case try another light-wallet host, reattach the incoming tx and wait at least 30-60 minutes.

**Comment by capitalsounds** [comment]
UPDATE:  I left my transaction under the news seed overnight and then logged into my new wallet this morning - my full IOTA balance has now been attached and is showing in the 'Balance'.

I suspect the delays have been due mainly to the high volumes going into IOTA at the moment.

All good now here, thanks for the input to the feed.
