### ISSUE TITLE
IOTA wallet upgrade issue (no new seed entered)

### ISSUE THREAD

**Issue by robocop1976** [iotaledger/wallet#202]
Hi, 

Ive upgraded to the new wallet on my IMac but clicked away (by mistake) the window that asked for the new seed. I did click the balance is complete button but after that it went wrong. On my andriod app I can still see my funds but I assume that runs with the old wallet still. If I use the same old seed in the upgraded wallet on my IMac it show zero.

Can someone help me to get access again to my IOTA?

Thank you in advance

**Comment by wonkytonky** [comment]
uninstall new wallet..     install it again..    try again.. 
always save all your seeds  before trying something
