### ISSUE TITLE
IOS not allowing version 2.4 to be opened Mac

### ISSUE THREAD

**Issue by zach4** [iotaledger/wallet#203]
IOS not allowing version 2.4 to be opened on my Mac book from my applications "Not a recognized application please download approved applications from the App Store"?????????????????????

**Comment by NanoAkron** [comment]
This isn't a problem with the app but the fact that apple doesn't like companies it hasn't approved.

Right click (or alt-click) on the app and choose 'open' and it'll force the OS to accept that you know what you're doing.
