### ISSUE TITLE
my upgraded  iota wallet is keep saying invalid seed

### ISSUE THREAD

**Issue by sarab3** [iotaledger/wallet#204]
when I login in my old iota wallet on my pc today ,it showed 0 balance and there was not any transaction history. I upgraded it to new version and when I trying to transfer iota from my old wallet it keep saying invalid seed. please help!!!

**Comment by LORDTITS** [comment]
I am having the same issues as well. First it tells me that my seed can only contain CAP and 9 when I within 3 letters from completing my seed. Even then it logs me in. No Balance. No history of any transactions. 
Please advise. TY

**Comment by wonkytonky** [comment]
install old wallet (wallet A) , make new seed thats correct with old wallet (wallet B)
try to send money from wallet A to B
try to do the transition  again  with new wallet  on B

**Comment by LORDTITS** [comment]
I will give it a shot..thank you! Its been terryfing not having found them
jaja
