### ISSUE TITLE
Missing MD5/SHA256 checksums on download page

### ISSUE THREAD

**Issue by goligo** [iotaledger/wallet#206]
As many people are dealing with high amounts of IOTA, it would be great if you could check the integrity of your download first with a MD5 or SHA256 hash. This is common practice for other cyrptos as well, e.g. https://github.com/ethereum/mist/releases .

**Comment by AronVanAmmers** [comment]
Agreed. For the separate IRI packages the releases are already signed by @paulhandy https://github.com/iotaledger/iri/releases. @domschiener could do the same for wallet releases?

**Comment by wonkytonky** [comment]
agreed, this is  5min of work

**Comment by AronVanAmmers** [comment]
The latest wallet release (2.5.1) has sha256 checksums listed 💪

**Comment by wonkytonky** [comment]
right..  this issue can be closed :)
