### ISSUE TITLE
Cannot connect to remote note!

### ISSUE THREAD

**Issue by JarBarKar** [iotaledger/wallet#207]
HELP!
Its been 2 days and I could not even access the wallet. Whenever I opened the application, it would only shows a logo of IOTA (no text box prompting for seed). After that, it shows an error message "Cannot connect to remote note". I had tried reinstalling several times, connect to different servers and completely cleared IOTA files in my pc. Yet, the same issue still persist... Any kind souls can help me with this issue. THANKS! 👍 
![aaa](https://user-images.githubusercontent.com/31005449/29270751-c64b9780-812a-11e7-8392-e991f9435f51.PNG)

**Comment by wonkytonky** [comment]
choose another node in the dropdownlist

**Comment by JarBarKar** [comment]
yup done it already, still doesnt work... :/

**Comment by DarrenSeabrook** [comment]
Yes, I'm having the same problem. I used IOTA for the first time today, installed the latest version 2.4.0. (I have never used any previous versions). 

I'm getting the same message as JarBarKar, and I've tried all of the remote nodes.

I've disabled my antivirus and host-based firewall programs.

I'm using Win7, 64 bit.

Please advise.

**Comment by rage13337** [comment]
A friend deinstalled his AVG antivirus and then it worked

**Comment by JarBarKar** [comment]
I guess some programs are causing this issue.. Tried on another laptop and it connects just fine. Might reformat pc if this issue persist. Thanks anyway!

**Comment by JarBarKar** [comment]
ok guys i found a fix alr. I just uninstalled my anti-virus and now everything is working well. Thanks alot @rage13337 for your idea! @DarrenSeabrook u should try uninstalling ur antivirus first to see if it works.
