### ISSUE TITLE
Receive address can't connect to the tangle 

### ISSUE THREAD

**Issue by Jornuts** [iotaledger/wallet#208]
My receive address:
XVXPIXJUIUMQGVUZHRKBGM9QWAUAMZCBVM9HKXY9LOZPHRLREZQYZPIDK9HXXTUWSQUDIHIZKKHJDBPEBVCZPTKYIR

can't connect to the tangle it has been pending for a week?

**Comment by wonkytonky** [comment]
generate new address try again,  also check if you are connected to a node thats synced.
