### ISSUE TITLE
Sidebar `Logout` visible even if logged out already (not logged in yet). breaks app

### ISSUE THREAD

**Issue by dadaphl** [iotaledger/wallet#209]
if you click the `Logout` button in the side menu the app goes to a white screen and becomes unusable until restart.
![screen shot 2017-08-15 at 14 53 43](https://user-images.githubusercontent.com/415536/29316943-216d2468-81ca-11e7-8a10-03cbdd482bb8.png)

**Comment by adamscarcella** [comment]
I just found this bug too. Glad the report has already been made, but sad it's not fixed yet. I'm using version 2.5.6 IRI 1.4.1.4 on macOS High Sierra 10.13.2

Steps to reproduce:

1. Launch Wallet
![image](https://user-images.githubusercontent.com/1242159/34327631-5e3f15ac-e897-11e7-9268-85f06603eac3.png)

2. Click White Circle/Green Question Mark icon to open the sidebar panel that shows Help, Contact, Privacy & Terms and Logout
![image](https://user-images.githubusercontent.com/1242159/34327632-6e1da150-e897-11e7-8391-f04f7899fc53.png)

3. Click Logout and the whole app turns white with no way to revert.
![image](https://user-images.githubusercontent.com/1242159/34327642-91e9b718-e897-11e7-8598-ff1d85f87455.png)


Suggestion, either grey out or remove the Logout button if you are not logged in.
