### ISSUE TITLE
reattach button missing

### ISSUE THREAD

**Issue by olemundo** [iotaledger/wallet#211]
Supposely there is a button on bundle details named reattach, but i have never seen it, on all my pending bundles, there is only one button, rebroadcast.

Who can I reattach the tangle ? ( I read that it helps to speed up pending confirmations )

![image](https://user-images.githubusercontent.com/31049702/29337698-9623d340-8212-11e7-9d31-6facd290170e.png)

**Comment by wonkytonky** [comment]
if you try again now.. is it still not there?

**Comment by olemundo** [comment]
Nothing has changed, but I have additional info.

Due to my ignorance of the 'double spending' concept, many transferences where done consecutively, without waiting for each of them being confirmed. 

Maybe when a attempt of 'double spending' is detected, the reattach button is purposely disabled...? Or it should appear anyway ? As I said, it keeps only giving me the REBROADCAST option. If it should appear, then it keeps failing.

**Comment by gabin22** [comment]
I also encounted this problem, spend iota from same address twice , and reattach button missing.
now my transaction is pendding and my money is dangerous .
fix up the bug quickly,please !
when will the next version of wallet release ?
