### ISSUE TITLE
No Seed Given on Light Wallet

### ISSUE THREAD

**Issue by atticusfnch** [iotaledger/wallet#214]
I downloaded the wallet, chose light node. I could not connect to the first two servers I tried. Connected to a third at Bitfinex port:80 and then it automatically asked for my seed before I had even generated a seed. Please fix this. Now I have to delete everything and reinstall. Very time consuming :(

**Comment by Dudenicks** [comment]
This is no issue, this is expected behaviour. You have to generate your own seed. https://matthewwinstonjohnson.gitbooks.io/iota-guide-and-faq/content/getting-started/dl-wallet/what-is-my-seed.html
