### ISSUE TITLE
Invalid Iota Address

### ISSUE THREAD

**Issue by mycatd** [iotaledger/wallet#217]
When trying to deposit Iota from Bitfinex into my Iota wallet, I get message on bitfinex "Invalid Iota Address.  This is the address I copied (after it was attached): EQ9KEBGBGIQO9TMI9WQNRIEJWXGNEJTBWFBSWE9A9XBMSXUEQQRDRSTIUBCPURXARINQOWSAPKWLJXNTGCZNSGQYGW

**Comment by rage13337** [comment]
I know a friend with the same problem, on a different PC with the same address it was no problem. 
Maybe you can also try a different browser?

**Comment by wonkytonky** [comment]
refresh bitfinex page; had same issue.. it worked after refresh

**Comment by cmrichsw** [comment]
IOTA crash several times -
Coins wallet address – 
Cannot send my IOTA balance to my wallets I have tried 3 of them it says my address wallet length is incorrect.
wallet address -  3G71hzN8Ny1Vre4P1ZbfXJx13LVCgu5hj8

**Comment by stockermans** [comment]
Please see my response to the issue you created regarding this topic cmrichsw.

**Comment by mycatd** [comment]
I tried refreshing bitfinex and tried a new browser but still have never been able to successfully send IOTA to my wallet.

**Comment by mycatd** [comment]
Ok, I saw I was using an older version (2.3.1) so I uninstalled it and installed the 2.4.0 version wallet and it sent.  Still waiting for it to reach my wallet but hopefully there will be no further issues.
