### ISSUE TITLE
IOTA snapshot, August 9th   HISTORY PENDING  STATUS

### ISSUE THREAD

**Issue by Pops1979** [iotaledger/wallet#218]
Good morning
I moved the the IOTA balance from old Wallet to new 2.4.0. like described in guide
Than I have my balance 0 and in history I view my pending position from 12/08/2017
I did some tests and I create news addresses . Some have been confirmed others are staying in pending. 
Then I did a test and a person sent me 1 iota who came right away
Then I tried to send 1 iota to the recipient but this is still pending

If anyone can help me!!!
This is the hash of the iota in pending: KMCBDAFRKMFXZVJGMNJXYFBHZ9JWGHQAVP9T99ZRGZPWPN9XQYFWOGHQMAWETLKGIMQ9MPJUVUJI99999

Thank you veru much!

Luca

**Comment by rage13337** [comment]
Hi Luca, 

go to the History tab and search for the transaction with your IOTAs, open it and click on "reattach". Then you will see a new transaction that is pending, wait again for an confirmation. After about 1h i would try to reattach it again. You can also try another light-wallet host under "Tools" -> "Edit Node Configuration"

**Comment by Pops1979** [comment]
Ok thank you !!!
I try....
I`m worried about this situation



Il 16 ago 2017 12:50 PM, "rage13337" <notifications@github.com> ha scritto:
