### ISSUE TITLE
incorrect address length - IOTA

### ISSUE THREAD

**Issue by cmrichsw** [iotaledger/wallet#219]
![iota wallet problem](https://user-images.githubusercontent.com/31068926/29364369-648af678-82bd-11e7-8448-64fca213a81d.jpg)

**Comment by wonkytonky** [comment]
it's a bad adress indeed...  works as designed.

**Comment by cmrichsw** [comment]
You probably do not know what you are talking about I have tried to different wallets with the same problem

**Comment by wonkytonky** [comment]
it will not work on any wallet becasue: "it's a bad adress indeed... works as designed."

**Comment by cmrichsw** [comment]
You probably do not know what you are talking about I have tried to different wallets with the same problem

On Wednesday, August 16, 2017, 8:43:46 PM GMT+7, barbar <notifications@github.com> wrote:


it's a bad adress indeed... works as designed.

**Comment by cmrichsw** [comment]
Now 3 wallets same error message - Incorrect address length

it's a bad adress indeed... works as designed. -BULLSHIT

**Comment by cmrichsw** [comment]
With 3 wallets same error I don't think so.

On Wednesday, August 16, 2017, 8:53:57 PM GMT+7, barbar <notifications@github.com> wrote:


it will not work on any wallet becasue: "it's a bad adress indeed... works as designed."

**Comment by Dudenicks** [comment]
It is not possible to send IOTA to BITCOIN wallet! And it never will!

**Comment by tuddman** [comment]
close. mark as spam.
