### ISSUE TITLE
IOTA crashes

### ISSUE THREAD

**Issue by cmrichsw** [iotaledger/wallet#222]
Cannot send my IOTA balance to my wallets I have tried 3 of them it says my address wallet length is incorrect.
wallet address -  3G71hzN8Ny1Vre4P1ZbfXJx13LVCgu5hj8 

![iota wallet problem](https://user-images.githubusercontent.com/31068926/29389861-f866f3f2-8316-11e7-9b42-ce12307d8b92.jpg)
 wallet address is correct

**Comment by stockermans** [comment]
Hi cmrichsw, 

The problem you are having is due to the following reason:
You are trying to send iota to a non-iota address.

Essentially what you are attempting to do is like:
"Sending physical postal mail with the address being an email address."

An iota address is 90 Characters long, of only Capital letters and the number 9.
You can see an example in your wallet by going to the history, under addresses, and you can see what it looks like.

You are trying to send to 'not an iota address'.

**Comment by cmrichsw** [comment]
Thank you for the reply -
So how do I send to my wallet? I want to move the IOTA balance to my own personal wallet


On Thursday, August 17, 2017, 6:56:05 AM GMT+7, Michael <notifications@github.com> wrote:


Hi cmrichsw,

The problem you are having is due to the following reason:
You are trying to send iota to a non-iota address.

Essentially what you are attempting to do is like:
"Sending physical postal mail with the address being an email address."

An iota address is 90 Characters long, of only Capital letters and the number 9.
You can see an example in your wallet by going to the history, under addresses, and you can see what it looks like.

You are trying to send to 'not an iota address'.

**Comment by cmrichsw** [comment]
This is my IOTA history -  IOTA keeps crashing as well
Again I want to move IOTA balance to my own wallet or cash out

On Thursday, August 17, 2017, 6:56:05 AM GMT+7, Michael <notifications@github.com> wrote:


Hi cmrichsw,

The problem you are having is due to the following reason:
You are trying to send iota to a non-iota address.

Essentially what you are attempting to do is like:
"Sending physical postal mail with the address being an email address."

An iota address is 90 Characters long, of only Capital letters and the number 9.
You can see an example in your wallet by going to the history, under addresses, and you can see what it looks like.

You are trying to send to 'not an iota address'.

**Comment by cmrichsw** [comment]
Ok so how do I create a address for my own personal wallet to cash out of IOTA?

**Comment by stockermans** [comment]
Since your screenshot is showing the IOTA wallet already, you have 67 Mi inside **your own** IOTA wallet. You have IOTA addresses under ''history + addresses'', and can create new ones under ''receive''.

**Comment by cmrichsw** [comment]
You have IOTA addresses under ''history + addresses'', and can create new ones under ''receive''
Yes correct and then??  do I use this receive address in my BTC wallet??

Thank you for your HELP

**Comment by Dudenicks** [comment]
It is not possible to send IOTA to BITCOIN wallet! And it never will!

**Comment by tuddman** [comment]
close. mark as spam.
