### ISSUE TITLE
Problem attaching address to the tangle

### ISSUE THREAD

**Issue by BenGiles49** [iotaledger/wallet#223]
![image](https://user-images.githubusercontent.com/31085502/29392976-4d03da54-8355-11e7-9c2a-9180c9f7055a.png)
![image](https://user-images.githubusercontent.com/31085502/29392993-6b9587b0-8355-11e7-82e0-51940560c8e2.png)

As soon as I press attach to tangle button in first image, the wallet goes black (as seen in the 2nd image) and wont do anything.
Could someone please help my figure this problem out, thanks in advance

**Comment by rage13337** [comment]
Hi, can you add your system specs like CPU , GPU , OS?

**Comment by ClaCec** [comment]
Hi, facing the same problem. I am working on Windows 8 with 2 cores and 4 logical processors.
Any idea what I can do to get rid of this vlack window?
Thanks a lot

**Comment by rage13337** [comment]
Try updating your GPU drivers, old Intel HD GPUs caused some problems
