### ISSUE TITLE
Wallet interpreting seed incorrectly?

### ISSUE THREAD

**Issue by mattisback** [iotaledger/wallet#224]
I was transitioning my wallet to a new address after the snapshot.  Everything worked fine, I then logged in to my wallet with my new seed and wrote down my checksum (say it was ABC).
Then I closed the program and opened it again.  When I pasted in my seed I was now getting a completely different checksum (say XYZ).  I tried a large number of combinations (eg. leave off the starting or ending character(s)) and could not find something that gave the right checksum.  If I did try to log in to the correct seed (which was showing the wrong checksum), I just saw an empty wallet.
The program would allow me to enter any seed with between 60 and 81 characters made up of A-Z and 9.  Which is weird perhaps?  Later it only allows 81 character seeds period.
After some frustration I deleted my settings (~/.config/IOTA Wallet) and re-extracted the program to get a 'fresh install'.  I'm running Ubuntu 16.04.  Now I tried pasting in the same seed from above and it gave the correct checksum again (ABC).  I could see my full balance when I logged in.
I can verify 100% that I was pasting in the same seed in both scenarios.  I tried for about an hour before 'reinstalling'.  
The other thing worth noting is that after 'reinstalling', the wallet only allows me to enter seeds that are exactly 81 characters in length.  Anything else and I get an error saying that I'm not allowed to use characters other than A-Z and 9.  Which is weird, because removing a character from the end of an accepted seed should probably give a warning about how the seed is too short, not that the character set is wrong (when it clearly isn't).
I can only assume that there is some configuration of settings that was making the program interpret my seed incorrectly (since it was generating the wrong checksum)..
I've tried typing my seed manually into the andriod app as well and it works.

**Comment by mattisback** [comment]
Any updates on this?

**Comment by mathiasrw** [comment]
> wrote down my checksum

What exactly are you referring to here?

**Comment by mattisback** [comment]
The seed checksum on the IOTA Light wallet.
IE "SGY" as pictured in this image:
![checksum](https://preview.ibb.co/mCC5Xw/Screenshot_20171205_223704.png)

**Comment by mattisback** [comment]
The version where I was having this issue was version 2.4.0 (on ubuntu).
