### ISSUE TITLE
send IOTA to non-iota address

### ISSUE THREAD

**Issue by cmrichsw** [iotaledger/wallet#225]
How do I send IOTA 2.4.0 light wallet to a non IOTA wallet (address) ? www.coins.co.th

**Comment by stockermans** [comment]
You can't send IOTA to a non-iota address. Just like you can't send Thai Baht to a Euro account (It needs to do a currency conversion first).

**Comment by cmrichsw** [comment]
How is this done?

**Comment by cmrichsw** [comment]
How is this done?

On Thursday, August 17, 2017, 9:21:48 PM GMT+7, Michael <notifications@github.com> wrote:


You can't send IOTA to a non-iota address. Just like you can't send Thai Baht to a Euro account (It needs to do a currency conversion first).

**Comment by cmrichsw** [comment]
This is my receive address in IOTA - how do I send it to coins.co.th   ?
NRKWXKIFYPNTCGFHPBQFBKUDQYJHY9WHDBACQHPLDPHZDWAIROIIWRPLKKNEVRJWZHBRAMGEEXUWUVCZZP9MQLGD9C

**Comment by cmrichsw** [comment]
You can't send IOTA to a non-iota address. Just like you can't send Thai Baht to a Euro account (It needs to do a currency conversion first).
My question is what can I do not what I cannot do?

**Comment by Dudenicks** [comment]
NOT POSSIBLE! NEVER! INSTALL IOTA WALLET!

**Comment by Dudenicks** [comment]
What you can do is buy BITCOIN with your IOTA and then transfer the BITCOIN to your BITCOIN wallet.

**Comment by tuddman** [comment]
close. mark as spam.

**Comment by cmrichsw** [comment]
What you can do is buy BITCOIN with your IOTA and then transfer the BITCOIN to your BITCOIN wallet. Please explain how to do ?  I am not able to get  support IOTA in my country 

NOT SPAM tuddman

**Comment by Dudenicks** [comment]
Go to bitfinex.com and sell Iota for bitcoin. Where did you get your Iota from?

**Comment by cmrichsw** [comment]
![iota withdraw](https://user-images.githubusercontent.com/31068926/29482078-871c621e-84b4-11e7-89d7-a37fc4823d25.jpg)

Thank you for taking your time to help me - I have sent 67 iota to Bittfinex 2 times it shows 1 confirmed and 1 pending in iota wallet and it is still showing available. I bought from Bittfinex

Thanks again for your help
