### ISSUE TITLE
IOTA SENT FROM ONE WALLET TO ANOTHER BUT LOST SEED

### ISSUE THREAD

**Issue by CLIFFORDJBRANCH** [iotaledger/wallet#226]
SENT IOTA FROM MY FIRST WALLET TO A SECOND WALLET I CREATED TO HAVE IT SPLIT UP. I AM UNABLE TO FIGURE OUT THE SEED BUT IT IS SHOWING THAT IT WAS TRANSFERRED THERE. IS MY IOTA GONE SINCE I CAN NOT ACCESS IT?

**Comment by wonkytonky** [comment]
if you don't have the seed you won't be able to access it.
