### ISSUE TITLE
Seed problem - 0 balance

### ISSUE THREAD

**Issue by adorb** [iotaledger/wallet#228]
Hi,

I have 5 diferents wallets. I was able to transition 4 of them and i sent my money back to Bitfinex, but i have one that keep showing 0 balance.

The problem is now i am not sure wich seed is the missing one (i know 5 seeds but i don't know exactly which seed have this last wallet). I am sure abaout all my seeds because i sent Iotas 2 times for each one and i saved it in 2 diferents places.

So, i know the balance of this seed (2023 Miotas) but tryed more them 10 times to transition 2 seeds i think have this balance without sucess. I just want to send my money back to Bitfinex and wait for a good wallet.

Transactions for the missing wallet:

https://iotasear.ch/hash/BNBBNSXZJWZLZTFMCGHDWRQJOSNLAOYWBFWOXGNUAQPWPCEPFKOCHHWUJPJONTRRQIIETYQDWNLYQETZ9

**Comment by adorb** [comment]
One problem thai i saw is the date i sent Iotas for this seed was 03-08-17, but on the adrees show that the transaction just have 1 day. Something is wrong?

**Comment by wonkytonky** [comment]
if you generate adresses with one of your seed does it have the adress https://iotasear.ch/hash/VDBGGTPVHFSOYXVIOAEWOYFPCCQGVOUYJDLUPYGJPREIXJHAJIAMQAQXRUUAPKWCFGWBCIREBEXKNQSFA
?

**Comment by adorb** [comment]
How many adresses i have to generate to see this one?

I'm just trying it right now.

**Comment by wonkytonky** [comment]
as many as you created before when you had balance

**Comment by adorb** [comment]
wonkytonky, no. But this adress do not mach with the adresses i sent money opn bitfinex too.

**Comment by wonkytonky** [comment]
then your seed is not 100% the same.  it  generates the exact same adresses every time for the same seed

**Comment by adorb** [comment]
wonkytonky, i just figured it out.

Before my post i already transitioned my seed (i just forgot). And i changed just 3 letter in the new seed. With the old seed i could not see anything anymore inside the wallet.

I just tryed to put all seeds i have on my notebook (without any transition) and one of them have the balance i was missing. I have more them 15 seeds on my notebook and i was just trying everything to see if i did something that i forgot.

**Comment by wonkytonky** [comment]
i'm glad it is resolved :)
