### ISSUE TITLE
Trying to get help in https://forum.iota.org/ fails because my IP range is being blocked.

### ISSUE THREAD

**Issue by cmrichsw** [iotaledger/wallet#229]
Trying to get help in https://forum.iota.org/ fails because my IP range is being blocked. How do you think people are going to invest in your currency if they lose money and get no help?

The reply's I am getting on this blog are the reasons I am having a problem but no real answers.

I want to transfer my IOTA to a BTC wallet....

**Comment by Dudenicks** [comment]
NOT POSSIBLE! NEVER! INSTALL IOTA WALLET!

**Comment by tuddman** [comment]
close. mark as spam.
