### ISSUE TITLE
I want to transfer my IOTA to a BTC wallet....

### ISSUE THREAD

**Issue by cmrichsw** [iotaledger/wallet#230]
Please someone must have the answer ??

**Comment by Dudenicks** [comment]
NOT POSSIBLE! NEVER! INSTALL IOTA WALLET!

**Comment by tuddman** [comment]
close. mark as spam.

**Comment by cmrichsw** [comment]
YOU thuddman are very impolite. For your information I do have the new IOTA wallet. Now WHAT exactly can I do with IOTA keep it forever Or hang it on the wall to look at ???? 

THIS IS A QUESTION NOT SPAM

**Comment by cmrichsw** [comment]
I HAVE IOTA WALLET now what???

**Comment by tuddman** [comment]
GH issues should be reserved for addressing issues with the actual codebase.  NOT user support.

Numerous people have mentioned this bizarre stream of opened issues, by you @cmrichsw, from a new account.

You are asking why the IOTA wallet is not acting like a personal exchange for you, to magically convert BTC to IOTA and back again.   Ask polite questions in the appropriate channels if you do not understand.

**Comment by cmrichsw** [comment]
WHO IS BIZARRE?? you tudman

**Comment by cmrichsw** [comment]
IOTA does not have support or I would go there. IOTA support cannot be accessed from my area

Help and I will go away -THANK YOU

**Comment by adamrp** [comment]
@cmrichsw Bitcoin is one cryptocurrency. IOTA is a different cryptocurrency. It's just like the real world: if you want to "convert" one currency to another (e.g., you want to convert Euro to USD), you have to use an exchange. Similarly, if you want to convert one cryptocurrency to another (e.g., IOTA to BTC), you have to use an exchange. [Bitfinex](https://www.bitfinex.com) is such an exchange.
