### ISSUE TITLE
IOTA Wallet v 2.4.0 issue - not attaching to tangle 

### ISSUE THREAD

**Issue by monjere** [iotaledger/wallet#231]
Why do i end up in full node when i install this wallet?
Tool tab has option "switch to light node" so i go through process and remain in full node.
Also cannot connect to tangle.

I uninstalled and instaled earlier version v 2.3.1
Got it to install as light node.
Tools tab had option to "switch to full node"
But would not connect to tangle.

So reinstalled v 2.4.0 
Chose light node
Once installed seem to be in full node as Tools tab has option "switch to light node"
Would not connect to tangle.

CAN anyone help me solve this issue?
Any help appreciated.
Even confirmation this is not just happening to me.

regards
monjere

**Comment by wonkytonky** [comment]
it's a typo i think.. you are in light wallet      when you just open the wallet..

**Comment by monjere** [comment]
Hi,

Thanks for response.

Someone on IOTA slack said the same thing and i know i selected light node when installing both versions so i tend to agree with you both. Typo in v 2.4.0 tool tab.

Still have the issue of not being able to attach to Tangle for both versions though (even v 2.3.1 when i had it installed and know i was in light node - tool tab having option to switch to full node)

I left both versions (at different times of course) running and attempting to attach to Tangle for hours with no joy.

regards

monjere

**Comment by wonkytonky** [comment]
are you connected to a host thats  synced ?

**Comment by monjere** [comment]
I went throuh every host in the vlist for both versions.....

**Comment by monjere** [comment]
i had recomendations from others on slack to use this host or that host and followed through on them all... no joy

**Comment by monjere** [comment]
![a home -tools tab -switch to light node - click it](https://user-images.githubusercontent.com/31123260/29478817-05884722-84c3-11e7-955e-ccaa6c734070.JPG)
![b this shoes so click witch to light node](https://user-images.githubusercontent.com/31123260/29478832-15383448-84c3-11e7-8600-a6fcaf8ac492.JPG)
![c then this shows - choose host - start - back to pic a](https://user-images.githubusercontent.com/31123260/29478838-1a6eaabe-84c3-11e7-996d-6757e54dd95f.JPG)

**Comment by monjere** [comment]
A) home -tools tab -Switch to light node - click it
![a](https://user-images.githubusercontent.com/31123260/29478882-598142c0-84c3-11e7-8931-6c2ba83c1d27.JPG)

**Comment by monjere** [comment]
A) home -tools tab -Switch to light node - click it

![a](https://user-images.githubusercontent.com/31123260/29478897-6f87b7a2-84c3-11e7-9e47-a553ed70636d.JPG)

**Comment by monjere** [comment]
B) This shows - so click switch to light node.

![b this shoes so click witch to light node](https://user-images.githubusercontent.com/31123260/29478908-8999d648-84c3-11e7-9079-34acae17f5bf.JPG)

**Comment by monjere** [comment]
C) Then this shows - choose host - click start - back to pic a

![c](https://user-images.githubusercontent.com/31123260/29478930-a7d0b776-84c3-11e7-939e-2448186a8793.JPG)

**Comment by wonkytonky** [comment]
so the attaching to tangle never stops running?

**Comment by monjere** [comment]
Just keeps on working away trying to attach

**Comment by monjere** [comment]
and never does

**Comment by wonkytonky** [comment]
do you have an intel graphix driver (like onboard gfx card on your motherboard) ?

**Comment by monjere** [comment]
no im just on my laptop... dont tell me that i need a "special" computer to run a wallet?????

windows 8.1 Pro 64 bit
intel core i5 421ou CPU @ 1.7GHZ (4 CPUs) ~ 2.4 GHZ
4096 MB Ram

**Comment by wonkytonky** [comment]
no, apparently  windows has standard drivers for intel gfx .. but it should be native drivers

**Comment by monjere** [comment]
hmmmm......... im not completely computer illiterate but i am not completely literate either...

So are you saying my drivers are incorrect in my laptop and that is why i cannot attach to tangle?

if so, then do i need to change them/update them/do something to them?

you seem t know your stuff.....

thanks for taking an interest and responding...

monjere

**Comment by wonkytonky** [comment]
if you have intel gfx driver it's often the case.. i'm not saying this is why you have troubles.. but  i think trying it out wouldn't be bad. 
https://downloadcenter.intel.com/  

be sure to check your hardware first and find out what kind of gfx you have .

**Comment by monjere** [comment]
Intel(R) HD Graphics Family

**Comment by monjere** [comment]
Adapter String : Intel(R) HD Graphics 4400

**Comment by wonkytonky** [comment]
did you install official drivers ? does attaching work now?

**Comment by monjere** [comment]
I got distracted - things to do BUT
I ran a program that looked at drivers and it said 26 wew out of date including the Intel(R) HD Graphics Family so it looks as if it can be the issue.
Will try to manually update this afternoon - i have to figure out how to do etc
Dont quite get it

**Comment by monjere** [comment]
Ok tried twice and failed miserably.

My computer is,
Intel(R) Core (TM) 15 - 421OU CPU @ 1.7 GHz - 240 GHz
4.0 installed RAM
x 64 bit OS x64 bit Processor
Windows 8.1 Pro

I wnt to download centre https://downloadcenter.intel.com/ and found the download for  specs as per my computer - On this link -

https://downloadcenter.intel.com/download/26984/Graphics-Intel-Graphics-Driver-for-Windows-15-40-?v=t

I found -

This download is valid for the product(s) listed below.

and in that list was -

Intel® Core™ i5-4210U Processor (3M Cache, up to 2.70 GHz)

which matches my specs.

So i went back to top of page and found  on LHS - 

Windows 8.1, 64-bit*

and downloaded 

win64_1540136.4703.zip

and saved it to downloads as in a Folder called Graphics update.
I unzipped it and extracted to same folder

Off i trod to device manager
Opened up Display adaptors and right clicked on Intel(R) HD Graphics Family
Clicked update driver software
Clicked Browse my computer for software
Chose the folder where i had stored the D/Load
Clicked on my D/Load (and no matter what i click on - main folder or anything in it) i get the - 

WINDOWS has determined the driver S/W in your system is up to date

So anyway - that is where i be at the moment
So no still not attaching to THE TANGLE...lol

**Comment by monjere** [comment]
Yeeeehah....... Success.

I found a free driver updater online that worked like a dream.
30 mins of updating various drivers (all listed for me by program) and when i attempted tp use IOTA wallet i logged in and entered my seed , well lo and behold i was attached in about 5 seconds.

I used a program called Driver Boost ,.
see below link ...

https://www.lifewire.com/driver-booster-review-2619190

It has good intel , instructions and links to the down load.

Thanks for your responses @wonkytonky. You got me moving to find a solution.

regards

monjere

**Comment by fructiv** [comment]
Hi all,

I have encountered the exactly same problem (Awaiting forever at the "Attaching To Tangle" state) and unfortunately the recommended solution (updating graphic drivers and updating all drivers with Driver Boost) did not work in my case.

The configuraion of my PC is as follows:
Intel(R) Core (TM) i7-6500U CPU @2.50 GHz
8.0 installed RAM
x 64 bit OS x64 bit Processor
Windows 10 Home

So do you have any other suggestions?

**Comment by monjere** [comment]
Title editted as your request.

Hmmm, interesting that it did not work. 
Worked like a dream for me and i had been having the issue for weeks.

I must say from the start that i am no computer expert ... Far from it...

Some other suggestions i recieved in other forums ..
1) are you sure you are in Light node (ie you chose light node when you installed)
2) look under tools tab and see if option "switch to light node" is there
   or does it say something else (neighbour node - from memory) - there was some comment about me being in light node attempting toattach to full node ???
3) have you tried to connect using other nodes - tools > edit node config

Anyway i will keep my eye open and if i see anything that may assist you i will post it..

Another good resource is iotatangle.slack in the #light wallet chat. 
Plenty of people who know what they are talking about..

regards
monjere

**Comment by fructiv** [comment]
Hey monjere,

Thank you for your reply, changing the heading and summing up the solutions.
1) Yeap I chose the light node option. Even I made a clean reinstall several times and it did not work
2) It is strange that "switch to light node" option is there. It doesn't feel correct since I must be in a light node right? So how can I assure that I am in a light node. Because as I said I always picked the light node in all the installations and configurations.
3) Yeap I have tried connecting several hosts, but if you have any suggestions I might gladly try it as well...

Thank you for the advice I have been checking the slack since I had the problem and trying out the things but nothing has worked so far :(

Regards...

**Comment by monjere** [comment]
@fructiv,

All good. 
Always willing to help out a fellow struggler (i.e someone having issues)

Sorry to hear it is still not working as i know how frustrating it can be.
Its a simple damn wallet ..LOL... I had weeks of this issue. 
DROVE ME MAD! .............Hours and hours watching "attaching to Tangle"

**"It is strange that "switch to light node" option is there."**
I have been told on slack forum that this is a TYPO in the code and will be fixed next update release.
This option being there really confused me so ignore it now.

What i suggest is to - as previously stated im no expert by any means - but - 

i) uninstall v2.4.0 and reinstall a previous version (i think it is v2.3.1) and see if that one will attach. 
   If you do this also look at tools tab and i believe it will not be given the  option "switch to light node" but given option "switch to full node".
  At least then you will know you are installing correctly (and ARE in light node) and you can attempt to attach in this version to "see what happens" and change hosts etc to also see if it makes a difference.

2) I myself, would also run the Driver Booster (or another similar program) again, and see if there is a chance it will re-update any of the drivers. I suggest this becaause after all the issues i had Driver Boost was my saviour. I updated EVERY driver it gave me the option to update and did them one at a time.

3) If you have access to another computer (option i did not have) download  onto that one and see if it will attach on it. If so whats the difference between the two computers....

4) Post on every TANGLE Forum you can find asking for some advice. You only need that one smart "wallet master" to go - Oh just do this!................

I will keep an eye out for this issue in other forums etc and post links here if i see anything that could possibly help.

Just dont let it beat you.......... Damn computers cannot win...

regard
monjere

P.S Im away later today to internet free zone (YAY) for few days so will check in when back...

**Comment by fructiv** [comment]
Hello monjere,

I am in the same situation that you went through last week and it seems mine will take longer to solve. Thank you for your suggestions. I tried all of them, but the problem is ongoing. So is it possible anyhow to check which drivers did Driver Booster update in your computer? Because before updating all drivers as far as I can see you gave it a try to update the graphic card driver and it did not work either. Or maybe Driver Booster updated your graphic card to some other version. Besides have you changed any other settings (regarding eg battery management, CPU utilization etc) in your computer or have you updated any other software (eg jre)?

I am also a bit busy these days so I cannot fully concentrate on seeking a solution but I am trying my best to overcome this issue. Thank you again for your support.

Regards...

**Comment by monjere** [comment]
@fructiv 
Just got back and saw your post.
I had a look at Driver Boost and found the 11 drivers it updated for me. See below:

Operation Type           : Install
Operation Time           : 20/08/2017 4:30:27 p.m.
Device Type              : System devices
Device Name              : Intel(R) 8 Series SMBus Controller - 9C22
Driver Name              : ELAN SMBus Driver
Driver Provider          : ELAN SMBus
Previous Driver Date     : 3/10/2016
Previous Driver Version  : 10.1.1.38
Available Driver Date    : 9/11/2016
Available Driver Version : 15.1.2.10

=========================

Operation Type           : Install
Operation Time           : 20/08/2017 4:28:20 p.m.
Device Type              : Network adapters
Device Name              : Realtek PCIe GBE Family Controller
Driver Name              : Realtek Lan Driver
Driver Provider          : Realtek
Previous Driver Date     : 26/11/2013
Previous Driver Version  : 8.23.1126.2013
Available Driver Date    : 27/06/2017
Available Driver Version : 8.56.627.2017

=========================

Operation Type           : Install
Operation Time           : 20/08/2017 4:26:30 p.m.
Device Type              : Memory technology devices
Device Name              : Realtek PCIE CardReader
Driver Name              : Realtek PCIE Card Reader Driver
Driver Provider          : Realtek Semiconductor Corp.
Previous Driver Date     : 6/03/2015
Previous Driver Version  : 6.3.9600.21269
Available Driver Date    : 30/09/2016
Available Driver Version : 10.0.14393.21292

=========================

Operation Type           : Install
Operation Time           : 20/08/2017 4:25:56 p.m.
Device Type              : Sound, video and game controllers
Device Name              : Realtek High Definition Audio
Driver Name              : Realtek High Definition Audio Driver
Driver Provider          : Realtek Semiconductor Corp.
Previous Driver Date     : 11/04/2017
Previous Driver Version  : 6.0.1.8117
Available Driver Date    : 14/06/2017
Available Driver Version : 6.0.1.8186

=========================

Operation Type           : Install
Operation Time           : 20/08/2017 4:13:05 p.m.
Device Type              : Intel(R) Dynamic Platform and Thermal Framework
Device Name              : Intel(R) Dynamic Platform and Thermal Framework Processor Participant
Driver Name              : Intel Dynamic Platform and Thermal Framework Driver
Driver Provider          : Intel
Previous Driver Date     : 23/10/2015
Previous Driver Version  : 8.1.10605.221
Available Driver Date    : 13/05/2016
Available Driver Version : 8.1.10608.329

=========================

Operation Type           : Install
Operation Time           : 20/08/2017 4:12:25 p.m.
Device Type              : Intel(R) Dynamic Platform and Thermal Framework
Device Name              : Intel(R) Dynamic Platform and Thermal Framework Manager
Driver Name              : Intel Dynamic Platform and Thermal Framework Driver
Driver Provider          : Intel
Previous Driver Date     : 23/10/2015
Previous Driver Version  : 8.1.10605.221
Available Driver Date    : 13/05/2016
Available Driver Version : 8.1.10608.329

=========================

Operation Type           : Install
Operation Time           : 20/08/2017 4:11:29 p.m.
Device Type              : Universal Serial Bus controllers
Device Name              : Intel(R) 8 Series USB Enhanced Host Controller #1 - 9C26
Driver Name              : Intel Chipset Driver
Driver Provider          : Intel
Previous Driver Date     : 21/06/2006
Previous Driver Version  : 6.3.9600.18191
Available Driver Date    : 31/07/2013
Available Driver Version : 9.4.0.1025

=========================

Operation Type           : Install
Operation Time           : 20/08/2017 4:10:56 p.m.
Device Type              : IDE ATA/ATAPI controllers
Device Name              : Intel(R) 8 Series Chipset Family SATA AHCI Controller
Driver Name              : Intel Rapid Storage Technology Driver
Driver Provider          : Intel Corporation
Previous Driver Date     : 1/08/2013
Previous Driver Version  : 12.8.0.1016
Available Driver Date    : 4/11/2015
Available Driver Version : 14.8.0.1042

=========================

Operation Type           : Install
Operation Time           : 20/08/2017 4:10:32 p.m.
Device Type              : Sound, video and game controllers
Device Name              : High Definition Audio Device
Driver Name              : Intel Display Audio Driver
Driver Provider          : Intel(R) Corporation
Previous Driver Date     : 22/08/2013
Previous Driver Version  : 6.3.9600.16384
Available Driver Date    : 27/02/2017
Available Driver Version : 6.16.0.3199

=========================

Operation Type           : Install
Operation Time           : 20/08/2017 4:09:48 p.m.
Device Type              : Network adapters
Device Name              : 802.11n Wireless LAN Card
Driver Name              : MediaTek Wireless LAN Card Driver
Driver Provider          : MediaTek, Inc.
Previous Driver Date     : 26/06/2013
Previous Driver Version  : 5.0.26.26
Available Driver Date    : 16/01/2015
Available Driver Version : 5.0.55.0

=========================

Operation Type           : Install
Operation Time           : 20/08/2017 4:07:49 p.m.
Device Type              : Display adapters
Device Name              : Intel(R) HD Graphics Family
Driver Name              : Intel(R) Graphics Media Accelerator Driver
Driver Provider          : Intel Corporation
Previous Driver Date     : 16/09/2013
Previous Driver Version  : 10.18.10.3308
Available Driver Date    : 16/03/2015
Available Driver Version : 10.18.14.4170

=========================

Hope this helps.
This is all i did before the wallet "magically" started working so i hope it helps you out.

regards

monjere

**Comment by monjere** [comment]
I forgot to say -

Yes i did try something else before Driver Boost.
I followed @wonkytonky advice (as above) and attempted to manually update my graphics card.
It did not work as when i attempted to install/use the downloaded file my computer kept telling me my system was "up to date" and the install would/could not proceed.
That was when i went looking for another method and found Driver Boost.

regards

monjere
