### ISSUE TITLE
How to convert IOTA in my IOTA wallet to be traded?

### ISSUE THREAD

**Issue by cmrichsw** [iotaledger/wallet#232]
Could someone just please answer the question and I will go away. It should be quite obvious by now  I want to trade my IOTA why is this so hard to understand?? 
Please someone HELP

**Comment by wonkytonky** [comment]
bitfinex.com

**Comment by cwg888** [comment]
i刚学会了，打赏地址：UXQWFSEZIWMFETQSQU9TGXGHGKSYACPEGIGOPVWTCWXVLIWAYSNGRCIOXNURVDODWNDPCUGQUAWCYFFMBJXWRPE9ND

**Comment by cmrichsw** [comment]
Oh Ok I will sent it today to -

On Saturday, August 19, 2017, 12:53:31 PM GMT+7, cwg888 <notifications@github.com> wrote:


i刚学会了，打赏地址：UXQWFSEZIWMFETQSQU9TGXGHGKSYACPEGIGOPVWTCWXVLIWAYSNGRCIOXNURVDODWNDPCUGQUAWCYFFMBJXWRPE9ND
