### ISSUE TITLE
New Wallet Won't Accept Seed

### ISSUE THREAD

**Issue by Neopatriarch** [iotaledger/wallet#233]
I have an android wallet, that carries my balance.

I have successfully downloaded the windows wallet. It requests the seed to transfer the balance.

However, it will not accept either the original string I entered nor the seed presented under >settings>>password>show seed in the Android app. The string it shows is similar in every way to the original accept all the words are upper case and all spaces have "9"s.

What to do? Please help.

**Comment by wonkytonky** [comment]
how long is your seed?

**Comment by Neopatriarch** [comment]
The original one was 10 words long. The one that appears in the app is just one long string.

**Comment by wonkytonky** [comment]
https://github.com/iotaledger/android-wallet-app
this is the github for andiod wallet.  maybe ask for info there

**Comment by wonkytonky** [comment]
can you close this one too?
