### ISSUE TITLE
Transition address search not finding balance

### ISSUE THREAD

**Issue by slimpkl** [iotaledger/wallet#235]
My old wallet was showing my balance fine before the snapshot and then went to zero. I updated to 2.4, tried the transition process, searched through many addresses on all available hosts and haven't recovered anything yet. I made sure to write down my seed so I didn't lose it and I'm not getting a login error. Is there anything I'm doing wrong, or am I missing a step that is still resulting in a missing balance?

**Comment by wonkytonky** [comment]
is  any of the generated adresses  the same as your old address?

**Comment by slimpkl** [comment]
No, i compared all the generated addresses from my history to the address i used to transfer from bitfinex and none match

**Comment by wonkytonky** [comment]
then the seed is not the same.   an exact same seed would regenerate  the same address. maybe some typo  at beginning or end  of seed?

**Comment by slimpkl** [comment]
Ive gone through all the possible mistakes i think i wouldve made but no luck. I think i located the address i sent it to on iotasear.ch though with the correct dates and amount, but i guess it doesnt matter because i still need the seed to access it correct? If theres no other way to access the address i guess ill keep trying the transition tool. thanks for replying, please let me know if theres anything else i can try

**Comment by wonkytonky** [comment]
unistall wallet and get the old wallet again. try to see if you can access your iotas from there..

**Comment by slimpkl** [comment]
I tried that once ready, im trying it again now, been through three addresses and nothing so far, ill try generating for longer than i did last time

**Comment by wonkytonky** [comment]
you don't need to generate more adresses then you generated .. when you had access to the wallet.  fyi.
