### ISSUE TITLE
Sending IOTA to Address

### ISSUE THREAD

**Issue by FreakyTea** [iotaledger/wallet#237]
Hi,

i tried sending IOTA to bitfinex yesterday. On my Gaming Rig (Windows 10 Pro, Wallet 2.4.0, i7 6700HQ, 8GB RAM, GTX 1060) but it didn't go through. I reattached 2 Times, but now i have 3 Pending transactions. Rebroadcasting didn't work either.

What should i do? Wanted to try it on my Mac today..

i think i can't abort these transactions or do i?

is this a known issue? (all addresses i see in details are known to the tangle - i checked that with the iota.cool tools)

**Comment by FreakyTea** [comment]
PS: now if i try to reattach i get an Error

**Comment by FreakyTea** [comment]
UPDATE: Reattaching via Mac works... lets see if my transaction completes

**Comment by srezz** [comment]
Same problem. Also sending to Bifinex from Windows 10 based IOTA Light Wallet 2.4.0 - IRI 1.3.1 and also sitting in history as pending now for 6 hours. Also generated and attached to tangle 3 receiving addresses and tried to rebroadcast a couple of times. Nothing helps. Perhaps there are some issues at Bitfinex?

**Comment by wonkytonky** [comment]
do you have a slow pc srezz?

**Comment by srezz** [comment]
Hello barbar,

I have Dell Latitude E6420 and here is its specs *https://tinyurl.com/y9kvg24t
<https://tinyurl.com/y9kvg24t>*
*Don't know whether or not it's slow in your terms*

**Comment by wonkytonky** [comment]
seems fast enough.   try switching nodes, are they synced?

**Comment by srezz** [comment]
What does it mean "synced"?

**Comment by srezz** [comment]
I've switched once already

**Comment by wonkytonky** [comment]
sure your gfx driver isnt the windows generic one?.

**Comment by srezz** [comment]
Here is what I have https://ibb.co/johawk

**Comment by wonkytonky** [comment]
did you already  just try to send it again?

**Comment by srezz** [comment]
I've got already 13 transfers and 10 addresses....

**Comment by wonkytonky** [comment]
can you show us the transaction ?

**Comment by srezz** [comment]
http://tangler.org/search/?kind=address&hash=IRJHCFMORGHLXOPEMCGB9TEXXATJI9CXWICXQZRGYNIBXEIFQMSBXQWJIGCCWPYQVDNTCWJWYHCCYADKCIVMTHJIJ9

**Comment by wonkytonky** [comment]
seems he does some doubles inputs and outputs in 1 move     
maybe i dont know enough about the protocol to know thats ok or no. 
But except for that all seems fine.. 

you can try to uninstall the wallet:
make sure this map is empty  after unistall

C:\Users\<youruser>\AppData\Local\IOTA Wallet  


now install again.

Try to send your money with a NEW trasaction again

**Comment by srezz** [comment]
OK, let me try...

**Comment by srezz** [comment]
After reinstallation do I have to do the "Transition"?

**Comment by wonkytonky** [comment]
no

**Comment by srezz** [comment]
If no, then it shows all my old pending transactions. Is there any way to cancel them?

**Comment by wonkytonky** [comment]
there is no way to cancel them.. they will be pending for ever

**Comment by srezz** [comment]
So, what do I do? On the the top of 2 pending bundles to send I create a new transfer?

**Comment by wonkytonky** [comment]
yes

**Comment by srezz** [comment]
I've created a new request to send some IOTA to a new address. Prior to that I attached an Address to a tangle in the Receive Section. 

Now it's stuck "sending"  with the rotating gear https://ibb.co/iKcve5

**Comment by wonkytonky** [comment]
if it keeps hanging  on sending : 
https://github.com/iotaledger/wallet/issues/231
seems a lot like this issue with the drivers 
did you change gfx drivers meanwhile?

**Comment by srezz** [comment]
No

**Comment by wonkytonky** [comment]
if it keeps on "sending" .; try to close programe with task mangager . and try again. 
if that not helps .. try to install  latest drivers for your intel gfx card. 
and try again

**Comment by srezz** [comment]
The drivers are the latest ones - I've already checked @ Dell

**Comment by wonkytonky** [comment]
strange,   if you have another pc / mac . try to install latest wallet there . 
the money is still there no worries.   seems your pc just doesn't want to create a transaction some how.
its wierd because you clearly could before the Reinstall of the wallet.

**Comment by srezz** [comment]
Exactly. There was no problems what so ever with the "old" wallet

**Comment by srezz** [comment]
I've updated to the latest Windows  intel gfx card and reinstalled the Wallet again, attached a receiving address to a tangle and created a new "send" transaction to a new receiving address with with the "Transfer Completed" outcome. https://ibb.co/ekvyGk

**Comment by FreakyTea** [comment]
Did it also show confirmed in your history?

On 21. Aug 2017, at 21:47, srezz <notifications@github.com<mailto:notifications@github.com>> wrote:


I've updated to the latest Windows intel gfx card and reinstalled the Wallet again, attached a receiving address to a tangle and created a new "send" transaction to a new receiving address with with the "Transfer Completed" outcome. https://ibb.co/ekvyGk

**Comment by srezz** [comment]
History shows my new bundle as "pending"

**Comment by FreakyTea** [comment]
Yeah just like mine.. and it Never changes...

On 21. Aug 2017, at 21:52, srezz <notifications@github.com<mailto:notifications@github.com>> wrote:


History shows my new bundle as "pending"

**Comment by wonkytonky** [comment]
ok reattach after 30min

**Comment by FreakyTea** [comment]
I did several times since yesterday...

On 21. Aug 2017, at 21:59, barbar <notifications@github.com<mailto:notifications@github.com>> wrote:


ok reattach after 30min

**Comment by srezz** [comment]
Will do, thnks...

**Comment by FreakyTea** [comment]
Here is a screenshot..

https://ibb.co/nGbkU5

**Comment by wonkytonky** [comment]
FreakyTea  show us the transaction in   https://iotasear.ch/  i can have a look at it

**Comment by FreakyTea** [comment]
Sry here it is: https://iotasear.ch/hash/XCMANGQGTFPHO9CBWBVODZINXDEMLIHNAUBGHFKPHBSPRGWAWP9XLNHSWCZHJGAMGRZXSJPMBMK999999

**Comment by wonkytonky** [comment]
you seem to have the same problem FreakyTea
![image](https://user-images.githubusercontent.com/19390834/29536299-87ecbada-86bd-11e7-9bfa-d6e3f62550da.png)

wallet is doing double inputs and outputs..  like srezz had. 
- safe seed somwhere safe
- uninstall wallet
-  empty   C:\Users<youruser>\AppData\Local\IOTA Wallet
- install wallet again
- login 
- dont do transition part
- send money  with NEW transaction

**Comment by wonkytonky** [comment]
srezz, you can do reatttach now

**Comment by srezz** [comment]
Doing it

**Comment by FreakyTea** [comment]
Okay i gonna try it thanks! :)

**Comment by wonkytonky** [comment]
seems by reattaching you got those double inputs and outputs seems normal behaviour

**Comment by srezz** [comment]
wonkytonky, how many more reattachments are needed?

**Comment by wonkytonky** [comment]
normaly 1 after 30min works for me .. never had to do another one.      i just stested again for myself 1min 30seconds  for confirmation

**Comment by FreakyTea** [comment]
WTF..

On 21. Aug 2017, at 22:30, barbar <notifications@github.com<mailto:notifications@github.com>> wrote:


normaly 1 after 30min works for me .. never had to do another one. i just stested again for myself 1min 30seconds for confirmation

**Comment by FreakyTea** [comment]
Which light wallet server do you use?

On 21. Aug 2017, at 22:30, barbar <notifications@github.com<mailto:notifications@github.com>> wrote:


normaly 1 after 30min works for me .. never had to do another one. i just stested again for myself 1min 30seconds for confirmation

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/29537082-9b352502-86c0-11e7-9971-e36e38225782.png)

**Comment by srezz** [comment]
Don't you think it's some sort of a Wallet bug since it's not just one isolated instance?

**Comment by FreakyTea** [comment]
No the server your light wallet is connected to :)

On 21. Aug 2017, at 22:32, barbar <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://user-images.githubusercontent.com/19390834/29537082-9b352502-86c0-11e7-9971-e36e38225782.png>

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/29537127-d24b0ff2-86c0-11e7-9fc6-3b062b9fddd1.png)

**Comment by FreakyTea** [comment]
Wow .. okay used this Server -> worked.. 1 min and my iota were sent!


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: barbar<mailto:notifications@github.com>
Gesendet: Montag, 21. August 2017 22:34
An: iotaledger/wallet<mailto:wallet@noreply.github.com>
Cc: FreakyTea<mailto:fclemenz@outlook.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [iotaledger/wallet] Sending IOTA to Address (#237)


[image]<https://user-images.githubusercontent.com/19390834/29537127-d24b0ff2-86c0-11e7-9fc6-3b062b9fddd1.png>

**Comment by wonkytonky** [comment]
congratz. 👍

**Comment by wonkytonky** [comment]
how about you srezz? any progress?

**Comment by srezz** [comment]
I've got "Reattach Completed" for the 2nd time https://ibb.co/kPUB2Q
My Send shows "Transfer Completed" https://ibb.co/g2FvU5
My Receive shoes "Address attached" https://ibb.co/j8syhQ
My History Shows "Pending" https://ibb.co/cbMfwk

**Comment by wonkytonky** [comment]
so all is good now?

**Comment by srezz** [comment]
Except nothing going anywhere...

**Comment by wonkytonky** [comment]
can you show us in explorer your latest transaction  srezz?

**Comment by srezz** [comment]
http://tangler.org/search/?kind=address&hash=MONPRMF9MQ9VZJJL9ZZBLLLTTRQAYNCJBJPRQYSEBPUH9HFTITCOXQ9ORUZCBRFSLLDIL9GIZJ9QYXCCWZJB9XEQWD

**Comment by FreakyTea** [comment]
Srezz which light wallet Server are you using?

**Comment by srezz** [comment]
http://iota.bitfinex.com:80

**Comment by wonkytonky** [comment]
change to 

![image](https://user-images.githubusercontent.com/19390834/29538194-ea2db3dc-86c4-11e7-8dcd-7f8da5ad7cb8.png)

try again reattach

**Comment by wonkytonky** [comment]
i red that the bitfinex host is "slow" sometimes

**Comment by srezz** [comment]
Changed, reattaching...

**Comment by srezz** [comment]
It says "invalid transaction hash"

**Comment by FreakyTea** [comment]
Okay try what Barbar said.. uninstall everything than reinstall, use the said light wallet server and send again

That worked for ne

On 21. Aug 2017, at 23:08, srezz <notifications@github.com<mailto:notifications@github.com>> wrote:


It says "invalid transaction hash"

**Comment by wonkytonky** [comment]
or make new transaction  and send again (even if it sais double spend )

**Comment by srezz** [comment]
R u talking to me wonkytonky?

**Comment by wonkytonky** [comment]
yes srezz , since you are connected to new host.; lets try one more time 
with new transaction  (and just klik yes  if it nags about double spend)

**Comment by srezz** [comment]
OK

**Comment by wonkytonky** [comment]
btw https://t.me/iotatangle  here's a telegram chat where you can ask questions about this it might be faster to just chat

**Comment by srezz** [comment]
It says "Transfer Completed",

**Comment by FreakyTea** [comment]
Now you have to wait 2-3 min and in your history it should have been confirmed :)

On 21. Aug 2017, at 23:24, srezz <notifications@github.com<mailto:notifications@github.com>> wrote:


It says "Transfer Completed",

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/29538938-3995fd1e-86c8-11e7-880c-5fa5798c5c19.png)
still not confirmed 6min

**Comment by wonkytonky** [comment]
confirmed! 👍

**Comment by wonkytonky** [comment]
did you sent to bitfinex?

**Comment by srezz** [comment]
Marvelous! Thank you!

**Comment by wonkytonky** [comment]
close this issue  (or put "SOLVED") in titel .. 

seems it is fixed.      

lesson learned here: change host if it keeps pending  for no reason

**Comment by srezz** [comment]
What is so special about that Telegram Forum?

**Comment by wonkytonky** [comment]
nothing special about telegram chat.  it's just more easy to talk

**Comment by srezz** [comment]
It's for FreakyTea to close the issue since I'm posting under his thread. Or can I do it too?

**Comment by wonkytonky** [comment]
FreakyTea  should probably do it

**Comment by srezz** [comment]
Thanks again wonkytonky, you're a life saviour....

**Comment by srezz** [comment]
wonkytonky where do you check transaction confirmations?

**Comment by wonkytonky** [comment]
https://iotasear.ch/hash/MONPRMF9MQ9VZJJL9ZZBLLLTTRQAYNCJBJPRQYSEBPUH9HFTITCOXQ9ORUZCBRFSLLDIL9GIZJ9QYXCCW

try to figure out how this all works navigating trough bundles  and transactions ..  you make. 

i spend a day testing and experimenting  with wallets and looking  in https://iotasear.ch/  to see what's happening

**Comment by FreakyTea** [comment]
Thanks :)

**Comment by FreakyTea** [comment]
Thanks :)
