### ISSUE TITLE
It seems the wallet setup file is infected by Trojan & Malware.

### ISSUE THREAD

**Issue by asifssarker** [iotaledger/wallet#239]
When I scan any IOTA Wallet setup exe file through the virustotal, it alerts some trojan and malware detected! Sound very strange, hope some one can give me the right wallet file to download, thanks.

![iota](https://user-images.githubusercontent.com/19061261/29742869-2568f6c6-8a87-11e7-92bf-9fcfedd9a768.png)

https://www.virustotal.com/en/

**Comment by wonkytonky** [comment]
you can download baidu anti vuris and check for yourself.     no virus found on my side

**Comment by asifssarker** [comment]
Thanks for the replay. Please check it through https://www.virustotal.com/en/ , it has many other engine including and it is not only the baidu but also WhiteArmor found a malware too. I did check many times but the results are same. I also found other post some one has the same issue with norton. Please ave a look: https://github.com/iotaledger/wallet/issues/130   

So is there any other wallet file to download?Thanks.

**Comment by wonkytonky** [comment]
scanned with northon : no virus

that leaves us someone to test whiteArmor

you can always try wallet for other operating system like linux

**Comment by asifssarker** [comment]
Thanks.

**Comment by Dfisch3r** [comment]
I got a virus with Kaspersky too

**Comment by wonkytonky** [comment]
just scanned with  kaspersky security scan. :  it's clean

**Comment by NRCNZ** [comment]
My Kaspersky automatically quarantines the wallet and deletes it as it believes its a Trojan ?

Is this issue occurring for anyone else ?

**Comment by Dfisch3r** [comment]
Yes, i had to set in Kaspersky the IOTA Wallet as "clean".

**Comment by asifssarker** [comment]
Yes, Kaspersky  on of the best up there I suppose!

**Comment by larrysmith1000** [comment]
Me too, but I have had the wallet for a long time, and never had any problems before.  It's weird that it just happened now.
