### ISSUE TITLE
IOTA GUI wallet can not be opened

### ISSUE THREAD

**Issue by blackhatzw** [iotaledger/wallet#24]
IOTA Wallet 2.0.0-IRI 1.1.1.1 can't be opened with error "The iota server process has exited", even I restarted my computer, detail is as below:

GUI version: IOTA Wallet 2.0.0-IRI 1.1.1.1
OS: Windows Server 2012 R2 Standard(AWS EC2 
VM)
Java version(64-bit): 
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

![iota error](https://cloud.githubusercontent.com/assets/7719933/20953095/e0316d66-bc6b-11e6-8b8e-7719c156f0a5.jpg)

**Comment by blackhatzw** [comment]
There is no other iota process, to confirm this, I restart my PC then open IOTA GUI wallet, it has the same error.

**Comment by atypicalprogrammer** [comment]
Open app via command line (Type path to app in dos window), this will allow you to see server output and may tell us what the reason is for this behavior.

**Comment by websioux** [comment]
I've had the same on windows, I made a syntax error with my neighbors list (I know it since I copy pasted it). I did not manage to find a way to correct it. The server can never be restarted and since the GUI needs it to allow the change of the neighbors liste, it is stuck.

**Comment by atypicalprogrammer** [comment]
The new version should show an error dialog with ability to edit the neighbors list. Let me know if it doesn't.
