### ISSUE TITLE
IOTA Showing Zero Balance

### ISSUE THREAD

**Issue by dv1040us** [iotaledger/wallet#243]
Hi I was away on vacation for 5 days and returned today log-in my IOTA with the seed but balance say zero.
I tried transition and clicked a bunch of different address but balance still zero i even tried and click receive and attach to tangle something showed in history as 2 transfer and 2 address under transfers it say pending  and the other bundle say confirmed

**Comment by dv1040us** [comment]
Hi I was away on vacation for 5 days and returned today log-in my IOTA with the seed but balance say zero.
I tried transition and clicked a bunch of different address but balance still zero i even tried and click receive and attach to tangle something showed in history as 2 transfer and 2 address under transfers it say pending and the other bundle say confirmed

**Comment by wonkytonky** [comment]
seems tome your SEED is not the same if no balance showwed up.   maybe small typo?

**Comment by dv1040us** [comment]
i copy and paste that seed its all caps and worked before I left on vacation what can i do ?

**Comment by dv1040us** [comment]
like Im doing a transition im at 400 address and balance is zero

**Comment by wonkytonky** [comment]
skip the step transition.. and try to login with seed

**Comment by dv1040us** [comment]
im logging and balance say zero i did click receive and and pressed Attach To Tangle and after 10 mins showing under history one is pending and the second confirmed

**Comment by wonkytonky** [comment]
so you tried the transition.. entered seed. did the 50 genrate adresses and nothing showwed up. 

also login with seed without transition and generated and no balance showwed up. 

then your seed is not the same.

**Comment by dv1040us** [comment]
im searching with my seed and balance (50 Address):0 shows

**Comment by wonkytonky** [comment]
do you remember your last address?

**Comment by dv1040us** [comment]
i found it was off one letter im so sorry bro.

**Comment by dv1040us** [comment]
but i do see under history with my correct seed one is confirmed and 2 pending why maybe i  pressed tangle twice

**Comment by dv1040us** [comment]
will those two pending drop off and confirmed stay

**Comment by wonkytonky** [comment]
without seeing some screenshots i have no idea what's gonig on.. but if you have your money back . thats good enough for me :)

**Comment by dv1040us** [comment]
sorry last one if i delete this wallet and install it under my new laptop will my original seed work ?

**Comment by wonkytonky** [comment]
yes,  .. you just have to generate a few adresses   if no balance   on new laptop..     your seed is the only thing you need ..  just keep it safe without typos  ; )

**Comment by wonkytonky** [comment]
i like to use keepass to save seeds

**Comment by dv1040us** [comment]
yes sir

**Comment by wonkytonky** [comment]
can you close this issue?
