### ISSUE TITLE
Sending IOTA from IOTA wallet to exchanges takes forever

### ISSUE THREAD

**Issue by ruihaoid** [iotaledger/wallet#244]
I am using the latest version of IOTA Light Wallet 2.4.0 - IRI 1.3.1.

When I tried to send my IOTA outwards to exchanges, it takes forever.

Methods I have tried:
1) Updating my PC drivers, especially Intel Graphics Card
2) Changing different nodes
3) Making sure I am able to view the node information before Sending
4) Attempt made to "Attach to Tangle" under Receive tab. But the process of "Attaching to Tangle" takes forever too
5) Every changes made were after closing and reopening of the wallet
6) The numbers at the bottom left hand are synced

My PC is constantly running at >100% CPU.

I am at my wits end and I do not know what should I do anymore.

Please help.

**Comment by wonkytonky** [comment]
is it also running at 100% without the wallet open?

**Comment by ruihaoid** [comment]
The 100% was when the wallet was kept open, the CPU stated at the bottom status bar.
