### ISSUE TITLE
Windows 7 (64bit), unable to install IOTA 2.4.0

### ISSUE THREAD

**Issue by Admonion** [iotaledger/wallet#246]
Im tryng to install latest IOTA 2.4.0 on windows 7 ultimate, very protected and clean PC. It loads setup shows that was loading something, looks like it finishes, but actually nothing happens, i tried more then 10 times.

Then after few restarts it installed Microsoft visual C++, and then again nothing with IOTA. I tried 10 more times and nothing, it just repeats - loading window of IOTA install and then like its starting to install and then it disappears. Also tried all this with security off, still same game.

I have latest java dev kit.

**Comment by pablof-ing** [comment]
Can not run iota Gui full wallet. i have problems with iri. please a hint
[ScreenMesage.docx](https://github.com/iotaledger/wallet/files/1257531/ScreenMesage.docx)
[ScreenMesage.docx](https://github.com/iotaledger/wallet/files/1257536/ScreenMesage.docx)
