### ISSUE TITLE
wallet don't start - wallet 2.0.0 IRI 1.1.1.1- ubuntu 16.04

### ISSUE THREAD

**Issue by Icet00** [iotaledger/wallet#25]
I don't know if it's just for ubuntu 16.04:
I post the fix someone answer me on slack. Or for the second, the solution I found on Internet.
On npm start, I was stopping at :
[ '-XX:+DisableAttachMechanism',
'-jar',
'/home/user/folder/iri/iri.jar',
14265 ]
IRI 1.1.1.1

Solution : open wallet/app/js/main.js with any text editor

change at line 1262 data.match(/Welcome to IRI (Testnet)?\s*([0-9\.]+)/i);
by data.match(/IRI (Testnet)?\s*([0-9\.]+)/i);

The following one is not specific for the iota wallet but more for bower. Will be nice to add it on the tutorial for those who doesn't know :
bower install
If you see :
Error: EACCES: permission denied, open '/home/username/.config/configstore/bower-github.json'

One of the bower installation folder is owning by root(or other) :
sudo chown username:group directory

**Comment by domschiener** [comment]
Did you run npm install && bower install before running it locally?

**Comment by domschiener** [comment]
The other issue seems more likely related to how you installed npm / nodejs locally.
