### ISSUE TITLE
bitfinex

### ISSUE THREAD

**Issue by defeedme** [iotaledger/wallet#250]
this wallet simply does not work. keep getting Invalid iota address (VSYMZIBNU9WLKBEGMMFNARRAAEYOLESHEJ9BIGYTGLUBMGUZUK9GZNNSEFXWWRFWVCO9LQBQYBFYIR9BLGRSIKJOSH)
did everything exactly as instructed
![iota-wallet_2017-08-26_16-4](https://user-images.githubusercontent.com/31375635/29744964-833fbde8-8a7d-11e7-945a-7cb469d639cf.jpg)

any ideas

**Comment by rage13337** [comment]
Please always use the latest version https://github.com/iotaledger/wallet/releases/tag/v2.4.0
