### ISSUE TITLE
feature request: double password

### ISSUE THREAD

**Issue by Dfisch3r** [iotaledger/wallet#251]
Hi,

could one add the feature that you log in with your Seed and than with a self given password to unlock the Wallet? Also if the case that someone guess your Seed is very unlikely, you get with  this method a better feeling that your money is safe. Also i think this feature will be highly requested in the future.

**Comment by Undercover1989** [comment]
I guess u mean a two factor authentification like Google Authentificator?
This would be nice.

**Comment by Dfisch3r** [comment]
I think the comment under this was deleted, somone wrote that he thinks that it would be an good idea two add 2FA. I agree!
