### ISSUE TITLE
Balance Still Not Showing.....Again

### ISSUE THREAD

**Issue by helplease** [iotaledger/wallet#252]
Please help someone.  I've gone through the "transition" to light wallet version 2.4, bought more IOTA and was able to successfully send some.  A few days ago my balance shows zero and all of the history has disappeared.  The explorer for my address appears to have transitioned to another address.  Here is my address-->>>GOOPRENDINYXIRGISDHGEBTUFJDMG9USNXAWFCRJAWKLPGHTICIWMLZUZVYJYCMPCNGCZYVD99IZI99SCNAQBEKEAH

I've tried attaching to tangle over 50 times, using various nodes to connect to, restarted several times and there is still no history from before.  Also, the person I sent to still shows a pending transaction that has been rebroadcast several times to make it clear, no joy.  I've uninstalled the wallet and deleted the cache also.  The hash of the stuck transaction pending is DYPYHBNVJXLVRBRMBWFSROBBYBBBNEWUFWBRGCARKOVDFIFHMWRE9KANCQGATMKNZWYMRGMHLKDK99999
This was sent on 8/18.  Can someone please assist?

Thanks.

**Comment by wonkytonky** [comment]
this was you doing a test right?
![image](https://user-images.githubusercontent.com/19390834/29818678-c91413fe-8cbd-11e7-8d61-809ec52b9b02.png)

**Comment by helplease** [comment]
No I didn't send this and saw after transitioning.  I figures this was part of the snapshot process.

**Comment by wonkytonky** [comment]
if it wasn't you.. someone did..   how did you create your seed?  in window powershell?

**Comment by wonkytonky** [comment]
ik looks to me you did do the transfer : because some of that money you still have access too: 
![image](https://user-images.githubusercontent.com/19390834/29868227-742d01ea-8d7e-11e7-9d66-a7b758cc8f30.png)

![image](https://user-images.githubusercontent.com/19390834/29868264-9b8ae4be-8d7e-11e7-91b0-b2d07892fa2b.png)

**Comment by wonkytonky** [comment]
also you did not do 50 reattachments but  1 and that one got confirmed.

**Comment by helplease** [comment]
What does that mean?

**Comment by helplease** [comment]
Correct.  The transfer of 5 with the Tag of Test was me as well as the ones that followed.  I still show zero balance and none of the history in the wallet.

**Comment by helplease** [comment]
I created my own seed.

**Comment by wonkytonky** [comment]
lets start again: 
https://iotasear.ch/hash/DSCXQZYKWTUCSCFWDALCL9DKG9SV9DVNQOUIEDNZJJKJFUAOL9WVCSZLZXBZCJNPACAF9AOJRSPINE9KB this is you doing transition you had 1.159732525 Gi there

**Comment by helplease** [comment]
Yes that part is correct.

**Comment by helplease** [comment]
I do appreciate you helping me track this.  The issues that remain is that the recipient still shows the transaction of 535.893017 Mi pending, yet I cannot see any of the history we are tracking in my wallet.  What can be done to have the transaction confirmed after this period and also for me to be able to see the balance and history in my wallet.

Thanks alot.

**Comment by wonkytonky** [comment]
the next transaction you did was send 5mi to this address right?
![image](https://user-images.githubusercontent.com/19390834/29877127-0eadc298-8d9f-11e7-9df6-415c8d669a85.png)

**Comment by helplease** [comment]
Correct.  That was a small test

**Comment by wonkytonky** [comment]
you can also see the 2 transactions  with the 535.893017  right?.  One of them confirmed the other one will keep on pending this is normal behaviour ..   
![image](https://user-images.githubusercontent.com/19390834/29880705-bffffc60-8da8-11e7-8f50-27f87892f2e7.png)

**Comment by helplease** [comment]
When you say "normal behavior".  I'm not clear as to why this is still pending and if anything can be done to confirm this on the tangle.

**Comment by wonkytonky** [comment]
you did 2 transactions 
the first one which did not confirm(which keep pending for ever)
then a re attachment tht did confirm 
only 1 of them will be allowed  otherwise you'll double spend

the money arrived at destination didnt it? 
https://iotasear.ch/hash/UBMBKN9VONOYU9GNTXEDZSGBUKODCDCAWJJB9FXZXNYCCQDBBJ9TBAHUFGWUIP9LTSIVXFYQIGVEFCMXD
so it works , reattaching is part of how iota works. often you don't have to reattach  and it just confirms ni 3min

**Comment by helplease** [comment]
Makes sense, and the confirmed one did arrive.  I am still at the place where I can't see any balance or history using the same seed to do all these transactions.  What can be done for me to actually see and use my balance here?

**Comment by wonkytonky** [comment]
have the correct seed.  the money is not gone.. it's still in your addresses , but you need  a correct seed to access them.    look for little typo, maybe you changed a few letters after generating seed with software to add extra entropy?

**Comment by helplease** [comment]
Also, the pending has reduced my balance by that amount according to explorer info you provided, while my wallet when it showed a balance showed 1.1 GI

**Comment by wonkytonky** [comment]
pending cannot reduce balance size what the wallet. when something is pending iet means it doesnt move .

this is a dirty and **not safe** way but you can try to see if your seed works here: 
https://iota-wallet.org/wallets/login

or try with the android app (also not 100% tested for now)

**Comment by helplease** [comment]
Tried using the browser to send to and get the following

18 mins 4 secs | Unconfirmed | 9JZ9MQLNBPOJA9W… | OXZGALMATOIQSQO… |   | IN | 1 i
-- | -- | -- | -- | -- | -- | --
18 mins 4 secs | Unconfirmed | ALR9LCDKZTFCAXK… | OXZGALMATOIQSQO… |   | IN | 1.154732524 Gi

Will this also be unconfirmed for good?

**Comment by helplease** [comment]
Android app does not show balance either

**Comment by wonkytonky** [comment]
reattach after 30min.. which is about now

**Comment by helplease** [comment]
Failed to re-attach. Invalid Bundle provided

**Comment by wonkytonky** [comment]
yeah i think this webwallet is still "old" 

ok  uninstall the wallet on your pc.
install it again. 

login with your seed.. and try to do the 'transition' again

**Comment by helplease** [comment]
trying that now

**Comment by helplease** [comment]
I
<img width="576" alt="not 1 iota" src="https://user-images.githubusercontent.com/31427139/29956434-c4939af2-8eac-11e7-8b50-e71121034a48.png">
've searched 10,000 addresses and still cannot see my balance.  What are your next steps for me to be able to access my IOTAs?

**Comment by helplease** [comment]
Update... I can see my balance now.  That was scary, but the issue is resolved!

Thanks.
