### ISSUE TITLE
Balance not showing (nor history) in IOTA Light Wallet 2.4.0 IRI 1.3.1

### ISSUE THREAD

**Issue by AgustinCalvo** [iotaledger/wallet#253]
I hadn't logged in the wallet for a few days and when I logged in today the balance was 0. This is wrong.
I should have IOTAs in my balance.
My address is JNZFCZPEHSVULCHMPCAATSUASGRSZPPVWOXYAOXVCTYHDZEYGKDNTDDUQQIFSTACC9ORHSVXSHIDQVLBWB9CXOPOIC.
Can someone please help understanding why this happens?

**Comment by AgustinCalvo** [comment]
I do see history now but now I see a transfer pending WHICH I DID NOT DO on the 30/08/2017 at 11:22 to RFHXGORDAPGLODKSDSSGKNNYSNZHCYEHZPJNKJOOUTT9KAFEMPEQWFU9NFCYM9QXWLGOOGQBZLWTFRIDB9CQBZMLAC...  Has my wallet been hacked?

**Comment by wonkytonky** [comment]
can you show us the last adress that had value?   the 2 adresses you show have 0 value. they look like a adress attachement tx

**Comment by AgustinCalvo** [comment]
JNZFCZPEHSVULCHMPCAATSUASGRSZPPVWOXYAOXVCTYHDZEYGKDNTDDUQQIFSTACC9ORHSVXSHIDQVLBWB9CXOPOIC this address had 3 MIOTA on 29/08/2017.
The Hash of the transfer that received the 3 MIOTA is DERNQUUIKHPKQUYPRIBS9WTGURFLKUQFFLJVTTRZJCTOQAHGUXGOJFU9WQUMZFAOTTVTK9TWVJTB99999
![image](https://user-images.githubusercontent.com/31440575/29866178-e7b7a978-8d77-11e7-88ce-4bf12e9fc3bb.png)
![image](https://user-images.githubusercontent.com/31440575/29866198-fc35e3c4-8d77-11e7-9d35-82936aee2f80.png)

**Comment by AgustinCalvo** [comment]
I actually saw the balance showing 3

**Comment by AgustinCalvo** [comment]
You are right, now I see the address being RFHXGORDAPGLODKSDSSGKNNYSNZHCYEHZPJNKJOOUTT9KAFEMPEQWFU9NFCYM9QXWLGOOGQBZLWTFRIDB9CQBZMLAC.
But balance is still 0

**Comment by wonkytonky** [comment]
in none of the adresses you shown.. there is an out or incomming value of 3.  they are all 0 value transactions.  so they are not the one's who send your money to some other place (if that is what happend)

**Comment by wonkytonky** [comment]
seems to me .. you don't  have 100% same seed .. and then generated a few adresses, attached them..    but the money was never in this wallet .     because of maybe not using the correct seed.  
maybe some typo?

**Comment by AgustinCalvo** [comment]
This is the link to the transfer from Biffinex (as you can see it was actually 357.35 MIOTA): https://iotasear.ch/hash/JJRCPUMMHUQZABFGIIWQTVSHAFQGCMYBRZWOYEDTXSHGNUBVRXZUEDWRBGQGT9QYJGOWQOTZUBYCLSGADQGLLD9WAY

**Comment by wonkytonky** [comment]
the money is still there .. so that's a good thing.
now  in order to access it  you need a correct seed .. that can generate the correct address. 
the seed you are using now is not generating this correct address.   so there  must be some typo or a little mistake in your seed . 


somethimes cashing is wrong:  on windows : 
close wallet
delete files in : 
C:\Users\<youruser>\AppData\Local\IOTA Wallet
start wallet again
try again with your seed

**Comment by AgustinCalvo** [comment]
Done but still shows 0, after many addresses:
![image](https://user-images.githubusercontent.com/31440575/29869358-f0973742-8d82-11e7-9d65-dc5e8c1473d3.png)

**Comment by wonkytonky** [comment]
skip the transition, and login with your seed..

**Comment by AgustinCalvo** [comment]
Balance remains 0

**Comment by wonkytonky** [comment]
then your seed is not correct.  look for typos

**Comment by AgustinCalvo** [comment]
typed it 10 times, cut and pasted to verify it is correct. Is there a way to generate new seed?

**Comment by wonkytonky** [comment]
if you create a new seed.; it will be a different wallet. and will not give you access to your coins 

did you create a few addresses   : login, skip transition(if that still pops up) and generate few adresses.  does your balance show now?

**Comment by AgustinCalvo** [comment]
I repeated deleting the files in the C:\Users<youruser>\AppData\Local\IOTA Wallet, skipped transition, login and closed a few times but balance still shows 0

**Comment by wonkytonky** [comment]
did you create a few addresses? : login, skip transition(if that still pops up) and generate few adresses. does your balance show now?

**Comment by AgustinCalvo** [comment]
Yes, I generated 5 addresses and connected to 4 different nodes

**Comment by wonkytonky** [comment]
then your seed is not the same. if it was you should eventually generate the correct address that holds the value. Thats probably also the reason why your history was empty

**Comment by AgustinCalvo** [comment]
If that is the case is there anything I can do?

**Comment by MarlonX19** [comment]
I was having the same problem. I was logging in but my balance was showing ZERO and even though I kept hitting the ''balance is incomplete'' all it did was create a lot of addresses. I solved that by skipping that part. Tip, try to download it on Linux and log in from there.

**Comment by RatiBoiseBaron** [comment]
Hello everyone, I would need some help please. Here is what happened. I just transferred (well after the snapshot) some IOTA coins from Binance to my 2.5.4 IOTA light wallet. After some time, i could see in my wallet history, a lot of transactions with the correct balance but all showing as pending. after a few days, i tried logging out and in again and now, i see 0 balance and 0 history. i tried clicking on receive - attach to angle a few times (hoping that would help). now all what i see is still 0 balance and in the history, a few transactions showing pending but they all show a 0 balance so i'm really freaking out now. I'm all new to the crypto world and not really tech savvy. Thanks a lot for your precious help !
