### ISSUE TITLE
IOTA Withdrawal 

### ISSUE THREAD

**Issue by bcplayer69** [iotaledger/wallet#255]
I hadn't logged in the wallet for a few days and today I logged in again. The balance was 0. This is wrong.
I should have IOTAs in my balance. From bitfinex to my IOTA Wallet 201MIOTA

Can someone please help understanding why this happens?

[IOTA.pdf](https://github.com/iotaledger/wallet/files/1264880/IOTA.pdf)

**Comment by c35punk** [comment]
Did you attached to Tangle your wallet after the confirmation of the tx?

**Comment by wonkytonky** [comment]
first double check if you entered the correct seed : 1 typo and you are in a different wallet.

**Comment by bcplayer69** [comment]
Seed is correct. Tangle ist attached. You can see this at the pdf. file.

**Comment by wonkytonky** [comment]
does the address that holds iota..   show up in your wallet history?

**Comment by bcplayer69** [comment]
I can not find any information in the wallet. Meanwhile the version 2.5.4 and also Reclaim Tool tried. No success. Why was such a wallet produced and marketed when it is full of mistakes? This sucks without end.

**Comment by ThomasPepperz** [comment]
Not a mistake.
IOTA is fundamentally a distributed database and snapshots are necessary
for maintenance. Here’s the thing, these are the costs of being an early
adopts and a supporter of beta tech imagine when IOTA goes alpha.

But tell me, have you looked up the status of your one of your addresses on
the list? CURL UNUSEs or NOT TRANSITIONED? We got you, friend.

**Comment by bcplayer69** [comment]
The host was at Bitfinex. I changed that because Bitfinex does not work anymore. But what do you mean about CURL UNUSEs or NOT TRANSITIONED?
