### ISSUE TITLE
Can't even get the login to come up.

### ISSUE THREAD

**Issue by T1029** [iotaledger/wallet#256]
Yesterday evening I transferred over 400 Iota to the Iota Light Wallet 2.4.0 .  The transaction remained at pending for about an hour before I had to turn the computer off and go to bed. I did select the "attach to tangle" button before turning the computer off which I later thought may have been a mistake. Today, I just get a blank Iota Wallet screen without any login options at all. Have I lost my Iota or do I just need to wait until the system catches up. I'm not great with computer tech and terminology so please any advise needs to be at beginners level.

**Comment by c35punk** [comment]
I have the same problem on two instances of my wallet. I only get the IOTA logo on my wallet and no login options...

**Comment by T1029** [comment]
Hi c35, I just managed to get into my wallet by following what another Iota member advised. I will copy and paste what she said worked for her and now me.

Megan Higginbotham
4 hours ago
ok I just went to tools > edit node configuration > switch to lite node and selected a server and now its letting me log in... weird bug

Good luck mate.

**Comment by c35punk** [comment]
I am using Light node mode already. I'll give it a try...

**Comment by c35punk** [comment]
I was able to login Tools->Switch to Light Node->*I have selected the first server*... et voila :). 

What is the difference between Light node and Full node anyway. When I am using Light node wallet does that mean that my tokens actually reside on some remote server rather than my machine and if I choose to use Full node that would mean that the tokens reside on a private key file locally? Please do clarify. :) 

Thanks in advance.

**Comment by T1029** [comment]
Hi c35, good to hear it worked for you. As for the technical stuff it all bamboozles me but what you said sounds like you might be on the right track. All I know is that whether it's light node or full node it's got to be more secure than leaving them on an exchange wallet. I bought another coin about a week ago which had it's own wallet but I could not download it after many long hours of trying so I had no choice but to leave them on the exchange. I'm hoping they get the wallet problems fixed eventually. It seems to be a recurring problem. Wallets.

**Comment by wemersonrv** [comment]
Hi, after install the wallet and run in Light mode and server selected; just shows a green window and no seed /login option. and the menu options do not access anything.

When close it and open again, few times open in this window; others opens in the window that we choose the Light/Full Mode, so i select a server again but not works.

See how appears: 

![image](https://user-images.githubusercontent.com/2028673/29920683-e5dc02a4-8e24-11e7-8dca-6dfe77794f5e.png)

**Comment by wemersonrv** [comment]
Hi @c35punk , In my case; as i say in the issue #257 nothing happens. and when i try to access the menu **Tools --> switch_to_light_mode** nothing happens... and as you can see in the attached image, the wallet is in ligth mode, but with problem

**Comment by Craigcal56** [comment]
That light wallet  got serious issues NOT working here either the light version there is more to this the debug  ccurl not hitting target text not stretched or something like that the debug said  Just a green screen no login at all tried all versions new old even the supposed fix wallets funny one worked just a few weeks ago im running linux its something with connections check node status its showing INFO but out of there nothing but a green screen

**Comment by Kuoi** [comment]
It seems the linux wallet is WORKING in ubuntu ,linux mint or other distro's when you start it in 'terminal' using this command ... "iota --ignore-gpu-blacklist"

**Comment by khozema** [comment]
Yes , I had the same problems of a blank wallet without the login seed.
After c35 answer above , I chose a server and got the login/seed.
But its not working for a localhost. Can anyone explain how I can set 
localhost on port 14265 as mentioned in the IOTA doc and get the login
seed instead of choosing a 3rd party server and what the implications of
choosing a third party server are
