### ISSUE TITLE
Linux IOATA wallet not seeing balance

### ISSUE THREAD

**Issue by azilber** [iotaledger/wallet#259]
Using the same seed I can see my balance on Windows and Android wallet, but not Linux wallet.

Linux wallet is LightWallet 2.3.1

**Comment by wonkytonky** [comment]
use latest wallet on linux

**Comment by azilber** [comment]
Using Linux wallet 2.4.0 it's unable to find my balance.

It's up to 200 addresses.  How long do I need to keep searching for my balance for?

**Comment by azilber** [comment]
Ok, nevermind  Apparently that 'search screen' was for conversions.  I killed it and was able to login with my seed and see my balance.

**Comment by wonkytonky** [comment]
:) nice to see it worked out
