### ISSUE TITLE
GUI Wallet says "sending..." but Proof of Work doesn't start

### ISSUE THREAD

**Issue by scottjp** [iotaledger/wallet#26]
When attempting to send a transaction, the wallet says "sending..." as expected, but the proof of work does not kick in and the CPU usage stays low. Generating addresses works as expected. 

![gui-bug](https://cloud.githubusercontent.com/assets/4450280/21016303/fea9ce04-bd5c-11e6-8805-6952348f8d60.png)

Three users can confirm that this issue is isolated to a single seed and when sending from other seeds the problem does not exist.

**Comment by domschiener** [comment]
Will look into this.
