### ISSUE TITLE
0 Balance, But my balance appears in my history

### ISSUE THREAD

**Issue by CollinLee818** [iotaledger/wallet#262]
I am signing in to my wallet today, after depositing 127 Mi, and it worked flawlessly with my balance showing last night.

My balance is showing 0,
But my history shows 127.3 Mi next to the address that I sent it to.

Even a few hours ago my balance was available, but now when I log in, it does not shoe a balance?

**Comment by CollinLee818** [comment]
I uninstalled the wallet, and reinstalled it and it showed up. 

Quick question? Am I supposed to attach to tangle before or after I make deposit?

**Comment by wonkytonky** [comment]
no you don't have to attach it.  but it's good practice to do so; this way the network knows someone owns that address
