### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by chrislovessushi** [iotaledger/wallet#263]
Using version 2.4.0 for OSX. Bitfinex host. Every time I open the wallet and type my seed, I click Login, and after different amounts of time I always get Connection Refused. If I go to Tools>Node Configuration, and click Save, then try again it typically works.

**Comment by chrislovessushi** [comment]
Nevermind about the solution I mentioned, that doesn't work. I still keep getting 'Connection Refused'.

**Comment by b-f-** [comment]
Light wallet v2.5.4, IRI 1.4.1.2. "Connection refused at login".
Is it possible to add some kind of verbose info or advice for user how to solve the problem? There seems to be no error log in /Pograms folder (win 10).
I changed the node and wallet connected ok, but a newcomer to IOTA might not think of that.
