### ISSUE TITLE
"Invalid Response" When Sending to Address

### ISSUE THREAD

**Issue by chrislovessushi** [iotaledger/wallet#264]
Attempting to send IOTA to another address. It stays on 'SENDING...' for about 15 minutes then eventually says 'Invalid Response'. This is in OSX, wallet version 2.4.0.

**Comment by chrislovessushi** [comment]
Looks like I also get 'Invalid Response' when trying to 'ATTACH TO TANGLE'

**Comment by wonkytonky** [comment]
change host

**Comment by sagalian** [comment]
i changed node and worked for me in seconds - maybe that helps !
