### ISSUE TITLE
wallet keeps crashing.

### ISSUE THREAD

**Issue by bRI121** [iotaledger/wallet#267]
My wallet keeps sticking and crashing. Can any one tell me why?

**Comment by arancauchi** [comment]
Can you try providing more details about your operating system, what version of the wallet you are using, and what the exact nature of the crashes are?

**Comment by Rutrus** [comment]
In my case, GUI crashes when I open IOTA-wallet a second time. The main window vanishes and then other window shows a message warning me there is a wallet already open.

Even if I close all processes `killall iota`, next time it continues warning me [I can continue successfully].

**Comment by arancauchi** [comment]
I am assuming this is some Linux variant?

**Comment by Rutrus** [comment]
Sorry, I forgot mention it. Yes, in my case is Xubuntu, `java-8-openjdk-amd64`

**Comment by Rutrus** [comment]
I installed [deb release](https://github.com/iotaledger/wallet/releases/download/v2.4.0/iota_2.4.0_amd64.deb) and my `java` command points to `/usr/lib/jvm/java-8-openjdk-amd64/bin/java`
