### ISSUE TITLE
Non-complete transfer

### ISSUE THREAD

**Issue by maxzuel** [iotaledger/wallet#268]
**Non-complete transfer**

I do not receive the iotas. the transactions are repeated multiple times with pending status ...

there are already 28 transfers, all with pending status. This ah more than 48 hours.

follows information from the first packages:

**DETAILS OF THE FIRST TRANSFER:**

Hash: OQRNHEQMO9SKANKOMNPSSFPYIERWBIVYZPYAJCSVPHR9MKCFLJDXPLGYOSERPBQTBYEFKDMNYOBV99999

MAXSUELVYZQGVZXOLXVTKEYZWFNIVGFZPUFPPTNYLHGFIAVKVOVRJMBTVPLMONBCXHEIMNXCSBPHMETZGOLWEPQWAOYXCOFMY
2.7 Mi
MAXSUELITPOPAHKNDZNOJKWSCLYLTMVZGDBRQKWTXGKWDOQZYMAUQGBVDALGJZZ9ACE9TD9OVGXJCFXQPXZYPVMC9XVQJVUI9
-872'444
MAXSUELITPOPAHKNDZNOJKWSCLYLTMVZGDBRQKWTXGKWDOQZYMAUQGBVDALGJZZ9ACE9TD9OVGXJCFXQPXZYPVMC9XVQJVUI9
0
MAXSUELASTWTLXNPHIGKSIRPWRDQWTOPKSEHXWVJAUZBWJDUIBTZVMDMZSVUGOUHWTLNHLLQMOFHJIAPMLJJBRVXRPRKVPZXC
-200M
MAXSUELASTWTLXNPHIGKSIRPWRDQWTOPKSEHXWVJAUZBWJDUIBTZVMDMZSVUGOUHWTLNHLLQMOFHJIAPMLJJBRVXRPRKVPZXC
0
MAXSUELJEFWQF9IPCKRMKMYRALYCLIAKKUCZGM9LID9SGQMPUTCSSLKBWAMKUARURVNHFRTBBBHGWLFAPLIIKHCCCDYPZYMIC
198.1+ Mi

______________

**DETAILS OF THE SECOND TRANSFER:**
Hash: XJOBD9WLJRK9EULLSNKETCBJYOXHGCIWTZYKRCJAIVIQNNMZOHSDCJJVAFVPLICZPCYEWMOUFCYR99999

MAXSUELLPBGZSSTZAO9RLOZXVBSMPXEAHMXRYTQCGGLHSPNEMG9DAHUPKMQPQSFQNKWOCNLXLTRS9PTACFDIPBDGDEVYSAFBND
2.7+ Mi
MAXSUELLITPOPAHKNDZNOJKWSCLYLTMVZGDBRQKWTXGKWDOQZYMAUQGBVDALGJZZ9ACE9TD9OVGXJCFXQPXZYPVMC9XVQJVUI9
-872'444
MAXSUELLITPOPAHKNDZNOJKWSCLYLTMVZGDBRQKWTXGKWDOQZYMAUQGBVDALGJZZ9ACE9TD9OVGXJCFXQPXZYPVMC9XVQJVUI9
0
MAXSUELLASTWTLXNPHIGKSIRPWRDQWTOPKSEHXWVJAUZBWJDUIBTZVMDMZSVUGOUHWTLNHLLQMOFHJIAPMLJJBRVXRPRKVPZXC
-200M
MAXSUELLASTWTLXNPHIGKSIRPWRDQWTOPKSEHXWVJAUZBWJDUIBTZVMDMZSVUGOUHWTLNHLLQMOFHJIAPMLJJBRVXRPRKVPZXC
0
MAXSUELLXJOJHVDQZSOCTZ9CRZ9TDZYIFTXDMZIYOPLPAFHUQBYTHVEG9IEQOX9MNDOEBFSMIVWDFBZVDYSMIMVACTEQZECKRX
198.1+ Mi

__________
**RE:**
maxzuel@gmail.com

**Comment by dutchakdev** [comment]
+

**Comment by wonkytonky** [comment]
change host, (not use bitfinex host) 
does it take long to send?  ty on better pc

**Comment by maxzuel** [comment]
Thanks for the info.

I do not use exchange ...

My wallet is PC and Android. Both counts the same information.

I figured my seller would be from bitfinex ... But also ná is the case, it's IOS ...

**Comment by dutchakdev** [comment]
Works for me, thank you!

**Comment by wonkytonky** [comment]
maxzuel , i'm talking about the host:   
![image](https://user-images.githubusercontent.com/19390834/30216386-28d8eca4-94b3-11e7-9fbb-857f732cf0c7.png)
if it's on bitfinex.; change it to some other one .. doesnt matter which one
