### ISSUE TITLE
Wallet not meeting expectations

### ISSUE THREAD

**Issue by vacsetron** [iotaledger/wallet#269]
Using light wallet 2.4.0 and the mobiel app. Please improve the wallets as a am a fan of IOTA, but it just isn't good enough. My suggestions to improve is making the menu more user friendly for the mainstream, not the techno freaks. Please let a woman in your team jugde the design. This grey, mint green sucks. 
The connection after entering my seed takes too long which makes me want to close and open again and so on... I have a background in telecommunication so i can still figure out how to do the transactions, but my wife thinks thinks you have to posses magic knowledge to make the transactions. 
Had to cancel and re-enter the transactions from bitfinex. Just make it easier and more user friendly.

**Comment by vacsetron** [comment]
Summarized... i have the most problems with the transparancy of the transactions... so i don't just want to leave frustration so i thought about it.... like for slack for example.. when you start using the software you get guided through the main hot items, like a mini wizard.... or an info icon empowering the user to have the basic knowlegde of the proces and the outcome of a choice....

**Comment by vacsetron** [comment]
When you are in a trafic jam (no connection when logging in), are you more or less frustrated when you know the reason (like for example they are building the road of accident)...?? I am less when i know the reason.... so when there is know connection with the right node or whatever... let the app inform the user what's going on and even make suggestions...

**Comment by wonkytonky** [comment]
make a better wallet.  problem sovled

**Comment by kgrsajid** [comment]
I am currently working on it. My goal is to build the most user friendly IOTA wallet (at least, it would be better than the crappy Light Wallet - lol).
Stay tuned!
