### ISSUE TITLE
Invalid transfers object error

### ISSUE THREAD

**Issue by proehlen** [iotaledger/wallet#273]
Possibly related to issue #56  (closed):

Attempting to send 1067.367791 Mi results in error  "invalid transfers object".  Sending the value as 1.067367791 Gi works however.

Edit: no, the second one fails eventually with the same message.  Don't know what I'm doing wrong.  Closing this.

**Comment by cyclux** [comment]
You are not alone, several people including myself have encountered the `invalid transfers object` problem. Here are my findings about it: There seems to be a rounding problem with specific numbers. In my case it was `2.019` MI which threw the error, it's reproducible. If you look into the console you can see `Server.transfer: OW9OJKLJFFUFLFWXL9GUXVVHLWTNTDCPOKWAIKPPJXUGVXEVZNEAZFTGUDDBTXB9GONOBPXFRITISBITXSVYTJJDRX -> 2019000.0000000002` So, there is probably kind of a "loophole" in the rounding function, where some values are not rounded correctly.
