### ISSUE TITLE
account balance is 0 

### ISSUE THREAD

**Issue by xapobilo** [iotaledger/wallet#274]
IOTA Wallet 2.4.0 - IRI 1.3.2

Please check the address FDJHMHHQYFFLIBJMO9NDVFQDMFXRBPBLDSJTZ9VQQFFJTJZ9LIYHTYRMSSRUFXOTBWURJQRSXKPWJKXKXYPSRIZLS9
to which i've sent 1.388Gi . 
now this account has a balance of 0 + 10  which i've sent today.
after transitioning nothing helped. 
the current account is 
IYZWQS9WNTDZNJDDWPWVMKKBBJDYLPPGVUINHLSPZFNNHYWXMD9QPMFQFPCGGGOOCXYAFIWBKMFHENPFAEGAVMCJRD
the balance should be now 1.398Gi but is only 10 Mi

**Comment by wonkytonky** [comment]
do you remember the  new seed you created?   can you just login with that one.(without transitioning) generate a few addresses  and does somthing show up then?

**Comment by xapobilo** [comment]
i logged in always with this seed and the balace was correct. Today i loged in normally as always without transitioning and the balance was 0. later i tryied transition but nothing changed, always it shows up balance 0 although meanwhile today i sent 10 to the wallet and after transitioning it shows up also 0.

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/30177189-5581b6ea-9405-11e7-9019-c95922843bd2.png)
someone moved money out of that address

![image](https://user-images.githubusercontent.com/19390834/30177236-79cb72b6-9405-11e7-8776-896b00c6f704.png)


now most of it is here : 
![image](https://user-images.githubusercontent.com/19390834/30177279-9f60faf0-9405-11e7-8bf2-44a0174a7e12.png)

do you  own the address  where the money is now?  check in your history

**Comment by xapobilo** [comment]
no i don't. i haven't moved any money neither created a new one with this address. but look how much transactions there are about the same amount. its weird

**Comment by xapobilo** [comment]
i see the transactions also in my history but as i said, after opening the wallet the first time after more than one week i thought it's a bug so i am posting here.

**Comment by wonkytonky** [comment]
if it was in windows..    there's a chance it was stolen. ..     windows powershell  is not safe. There has been  going around warnings by iota team on slach, twitter, telegram ....to change seed if  windows powershell was used.

**Comment by xapobilo** [comment]
thats a nice news. but nothing of them were on github from where i downloaded the wallet.

**Comment by toabi** [comment]
Choosing an insecure seed is not really the problem of the technology. You can make that mistake with any crypto currency.

I agree that it would be useful if the wallet could tell new users how to create safe seeds or even generate it itself.

**Comment by wonkytonky** [comment]
there is beeing worked on a wallet wallet where you put in a bunch of words like: cow, water, computer ...   etc..    to then generate a seed/hash..   but that's  still in pipeline and not the official wallet as far as i know. so ppl don't have to be too tech savy.   it will come.  Iota is still very early days. bitcoin knew same problems in the early days.   i remember having private keys without encryption just sitting there on my pc in the "wallet" .

**Comment by xapobilo** [comment]
wallet is not safe. 
the user needs to produce the seed by himself.
the system is vulnerable to brute force attacs. 
nothing helps anymore. who gives me and to other robbed users the assets back? 
how wants iota solve those problems?

**Comment by WireGhost** [comment]
Same issue, but possibly different. Tried the paper wallet generator. Did a small transfer, nothing. The OS X 2.4.0 is bugging at invalid response now most of the time. Generator generated a receive address, and the it shows sent to that address, but loading the seed, & 0 balance.
