### ISSUE TITLE
5Gi Vanished out of wallet

### ISSUE THREAD

**Issue by CRYPTICCURRENT** [iotaledger/wallet#275]
Hello,
I know that this problem has been posted before and I have scoured the internet to find a solution, but without any success. 
I have never used the old wallet. I started using the latest version - 2.4.0 and made a 5Gi transaction, about 15 days back,from Bitfinex to the light wallet.

Hash: https://iotasear.ch/hash/MTUSQMPECPBBIZIR9VJIOBTMJCNFOKGDPYIRLLTSNBOMCETVWZJAOEGJPILNTMOXYONJCSHRKRMHJNJMCIAEOIJMFZ
![capture](https://user-images.githubusercontent.com/31743176/30179342-eb27483a-93c0-11e7-9c02-bfd15b1c05f2.JPG)

The wallet showed 5Gi a few days back but yesterday, when I finally bought some more IOTA, I logged into my wallet and found out that the balance and the history of the 5Gi transaction is gone although the history of some minor 5Mi transaction has been retained.I made the 5 Mi transactions for test purposes. I have tried the following:
1)Logging in and out several times - The Seed checks out so I am not putting in the wrong seed
2)Attaching address to Tangle - Repeated about 50 times with no success
3)Tried transferring some balance from wallet to Bitfinex- It says that I have insuffiecient balance even though it showed 5Gi balance about 3-4 days back.I also have proof of a confirmed transfer of 5Gi from Bitfinex to Lightwallet.
4) Transferred 6Mi from Bitfinex to Light Wallet in hopes of seeing an eventual 5006 Mi balance onmy Light Wallet-It only shows 6Mi balance ( fromthe latest transaction) and not my previous balance.
Hash: AHOXBIZY9KVBWOQSWYGRDVGYYVJJMTLJMXLR99JCZATGBWFKYPFJMHJDMVHVYVXK9VJXDJRZNBBCEBMIWHRJBP9FFX
I truly believein the tech behind IOTA and am in this for the long term but this simple inability of wallet to secure the investor's balance is severly affecting my confidence in this project.

**Comment by wonkytonky** [comment]
does your history show the adresss that holds the 5G ?

https://iotasear.ch/hash/MTUSQMPECPBBIZIR9VJIOBTMJCNFOKGDPYIRLLTSNBOMCETVWZJAOEGJPILNTMOXYONJCSHRKRMHJNJMCIAEOIJMFZ

**Comment by wonkytonky** [comment]
i just sent 1iota to the 5G address. do you see an incomming transfer in your wallet?

![image](https://user-images.githubusercontent.com/19390834/30204257-08567cc2-9485-11e7-8693-025fb10bf951.png)

**Comment by CRYPTICCURRENT** [comment]
My history doesn't show the address the 5Gi address. Neither am I seeing the 1i transfer you made. The address did used to show up 4-5 days back though.

**Comment by wonkytonky** [comment]
then you are not using the same seed , look for typo or maybe 1 or 2 chars smaller seed then 81chars

**Comment by CRYPTICCURRENT** [comment]
I tried a lot of different options. The problem is that my seed is 74 characters so if I  had even typed another alphabet by mistake, it would have connected me to a different wallet. 
Is there no way to get my iota back now? I bought it at $0.80/ Miota so that's a $4K loss!!

**Comment by Pomyk** [comment]
Try generating new addresses.

**Comment by wonkytonky** [comment]
if you don't have the correct seed. there is no way to get that money.

Do you have a friend you trust? let him try on his pc  ..  but my guess is you don't have the correct see.
