### ISSUE TITLE
Please kindly add "generate seed" button

### ISSUE THREAD

**Issue by menkaur** [iotaledger/wallet#278]
All the other wallets have automatic seed generation. Except of IOTA wallet.

Found powershell script to generate the seed, as many other people, lost 4.3 Gi because of this
( https://www.reddit.com/r/Iota/comments/6vh8mv/urgent_all_of_my_iota_was_stolen_today_and_here/?st=j7d226zp&sh=b0fc9726 ).  I'm probably not the only one

Please, kindly fix the issue by adding "generate seed" button in the UI asap

**Comment by Rutrus** [comment]
The only problem with that, is beginner users won't save the seed. If they don't save the seed the first time, they can't login again, and they will lose their _money_.

I propose to instantly download a wallet file with the private info once the seed it is generated. Also, they would want to encrypt with a passphrase.

**Comment by menkaur** [comment]
This can be fixed by a dialog showing something like this: "you are logging in with a generated seed. If you lose the seed, you lose your money. Store the seed in a safe place. To verify that you have stored the seed, please enter your seed again". That'll fix most of the cases

**Comment by menkaur** [comment]
Or you could create a file with hashes of known seeds and each time the user logs in with a new seed, that dialog could be shown. This way, even users who generate seeds in other ways will see the warning
