### ISSUE TITLE
quality control and coding standards?

### ISSUE THREAD

**Issue by laurencefass** [iotaledger/wallet#279]
is this software being written to quality control and coding standards? i'm concerned that i have an install error and i can't see any log files to help me diagnose. thanks.

**Comment by Rutrus** [comment]
What is your Operative System? Mine is XUbuntu, install failed due to a missing lib:

    sudo apt install libappindicator1

I installed it with `dpkg -i iota....deb`

**Comment by laurencefass** [comment]
windows 10. i've raised the issue separately.
