### ISSUE TITLE
Transaction not balanced

### ISSUE THREAD

**Issue by seele7** [iotaledger/wallet#280]
Hello IOTA-Team/Supporter,

The whole IOTA wallet is new to me and I have a problem, hoping you can advise.

2 days ago I started a transaction from my exchange to my IOAT light wallet. On the exchange the transaction is confirmed, but the IOTA light wallet still shows a balance of 0. The address that I generated for the transaction is also not shown anymore in my history (IOTA light wallet), is that normal?
What can I do to secure my balance?

**Comment by wonkytonky** [comment]
probably wrong seed if you adress is suddenly gone.. 

can you show us trasaction hash   you got from bitfinex?

**Comment by seele7** [comment]
Hi,

the address would be:
HBQFETJIRCQOHZKWIXSWBCQLHPDZZFOIXWBITYIWSFFPZNAYBGWLIUTFCWZLQTDGUT9IILZQAFCSNFJRD
<https://iotasear.ch/hash/HBQFETJIRCQOHZKWIXSWBCQLHPDZZFOIXWBITYIWSFFPZNAYBGWLIUTFCWZLQTDGUT9IILZQAFCSNFJRD>
the transaction would be:
D9ABVRPKI9VHEHDTBHENEAHOITUGSNOGEYGHBWTARDYEI9IYNZ9GIXSLHVHGOGGFUCYZQEAYTTBI99999


2017-09-09 17:16 GMT+02:00 barbar <notifications@github.com>:

**Comment by wonkytonky** [comment]
so the bitfinex part is correct .. they did send money  to the address HBQFETJIRCQOHZKWIXSWBCQLHPDZZFOIXWBITYIWSFFPZNAYBGWLIUTFCWZLQTDGUT9IILZQAFCSNFJRD

first: change your host. 
second: generate a few addreses   if none  of them  are equal to : HBQFETJIRCQOHZKWIXSWBCQLHPDZZFOIXWBITYIWSFFPZNAYBGWLIUTFCWZLQTDGUT9IILZQAFCSNFJRD

then your seed is not the same as the one you used before.   look for typo, maybe deleted last character of seed. etc

**Comment by seele7** [comment]
Changed my host, re-logged in and it worked. THANKS :D

**Comment by wonkytonky** [comment]
cool man! good news
