### ISSUE TITLE
JUST WENT ON OUR WALLET AND ITS ZERO!!!

### ISSUE THREAD

**Issue by tjewsmith** [iotaledger/wallet#281]
I WENT ON OUR WALLET TODAY AND IT SHOWS ZERO!!! IT LOOKS LIKE SOMEBODY TOOK THE COINS OUT THE DAY AFTER THEY WERE PUT IN, IT STILL SHOWS ITS PENDING , WHAT CAN I DO? CAN WE CANCEL THIS TRANSACTION???

**Comment by wonkytonky** [comment]
show transaction

**Comment by tjewsmith** [comment]
199996 • 199996 • CPU: 0.00%
-5'582 Mi, I'm not sure if this is what you were asking for , I wasn't sure on how to show you the transaction.

**Comment by tjewsmith** [comment]
if this isn't what your asking for please let me know how I can show this transaction to you.

**Comment by tjewsmith** [comment]
I understand that my seed was to easy , please tell me what I can do to make this different so this doesn't happen again. obviously I need to make my seed much more complicated , but is there a way I can do it so its not stolen again?

**Comment by tjewsmith** [comment]
does  the list of hosts have anything to do with the seeds getting hacked?

**Comment by wonkytonky** [comment]
hi ,no changing host has nothing to do with hacked seed..  
by transaction  i mean: 
![image](https://user-images.githubusercontent.com/19390834/30253892-a846a350-968e-11e7-840a-fca8c13aac20.png)

in your history ..  

but since you know the seed has been compromised.. 
the money probably is gone.

**Comment by wonkytonky** [comment]
how to create seed : https://iotasupport.com/gui-newseed.shtml

i'd not use websites.

you can also use the program http://keepass.info/
it has a password generator , and you can add entropy by using mouse or typing in some random letters 

remember it should be 81 characters : capital letters or the number 9
after it generates a seed you can always change a chars  manually

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/30253942-97e3ca64-968f-11e7-888b-c341a10e81e9.png)

**Comment by tjewsmith** [comment]
Y

12 Transfers 9 Addresses
10/09/2017 15:30
9ZAQYIBMAEUUDXQUBEEHKADVUDN9SKLFWILEATMOARMQAEMCDNAURPXCLFCG9XIYPHIXWRPTZXSQILIW9CRYNSFCWW
Show bundle Pending
0
06/09/2017 10:36
NMOQJPYHUSMOZDFHDVRXJPIAGK9YFYWXOWVMSIQXGDYRUSUKNI9SHQMEVPMFAEVIWBBCQDFRSI9BGYCNDLCVSRCRLW
Show bundle Confirmed
0
06/09/2017 03:37
ZP9JCSTUFSMEX9ONXWHFYEFNCKNDXCWCOYFBNKUOYRTPGUSLQTROIJYV9COCEOCIDVKIZNOATI9CEQJR9JHHMLQEKD
Show bundle Confirmed
0
05/09/2017 07:56
YKO9YRYHVYGTUGHGIFYERSLQLCRUZQAHPHIBQEBBCGMJOZJNSQBCN9BQGWUWGTXJRUAHNDBBFIXHIGPZXOYDHCLOKX
Show bundle Pending
0
01/09/2017 14:39
MBYLQDZBYLNKILY9NPWTBRBA9POJREVKASSBCMLHEQZMHEYMYLRXZCWIBPPCFRUSSRMIXTPFFMPKSQPQZKO9AVYEUD
Show bundle Confirmed
-42 Mi
01/09/2017 12:52
MBYLQDZBYLNKILY9NPWTBRBA9POJREVKASSBCMLHEQZMHEYMYLRXZCWIBPPCFRUSSRMIXTPFFMPKSQPQZKO9AVYEUD
Show bundle Confirmed
-5.5+ Gi
01/09/2017 12:35
RTRSXNWZQVDGNRONEYCHHXAJCIVSCEWIU9LCHBSLZBGRPJGYKCKDSSBXOBFPFON9JJRSLXADDMCROYJRYLDPUDGDWW
Show bundle Pending
-5.5 Gi
31/08/2017 17:26
XKQTQSRVYTZJDJPBDNCMLGTAB9RKVB9WV9JDOWBU9SCRKCPSZWDLXJLYQVWIPJNJBCZENOOOKEKJKEXUDTFANTZOFW
Show bundle Pending
0
31/08/2017 14:42
XKQTQSRVYTZJDJPBDNCMLGTAB9RKVB9WV9JDOWBU9SCRKCPSZWDLXJLYQVWIPJNJBCZENOOOKEKJKEXUDTFANTZOFW
Show bundle Confirmed
5.5+ Gi
31/08/2017 13:57
VNTYPTNVFCYDF9MBE9XNEBIWDGNUHOEJSK9ISIYRLRPYFTOBBNFRGASNJVXAYRRMGQCLWD9XODSEMILCZYCEUYLSQD
Show bundle Confirmed
10 Mi
31/08/2017 13:04
VNTYPTNVFCYDF9MBE9XNEBIWDGNUHOEJSK9ISIYRLRPYFTOBBNFRGASNJVXAYRRMGQCLWD9XODSEMILCZYCEUYLSQD
Show bundle Confirmed
0
31/08/2017 12:49
AWDINXBIWEWJLXXQLBLWDMNZXAIZIJPJSYXJCENZQFAXQZTFZQRIVXDYZLQNB9AZRAJBMZNNXF9M9SXVDGENUOKGFD
Show bundle Pending
0

**Comment by tjewsmith** [comment]
how do I make a new wallet with a new seed, when I go to my wallet it doesn't give me an option to make a new one

**Comment by wonkytonky** [comment]
you cannot cancel a transaction.;  

you seem to own address: 
![image](https://user-images.githubusercontent.com/19390834/30254027-fa07f4fc-9691-11e7-83bf-073d37edc332.png)
![image](https://user-images.githubusercontent.com/19390834/30254028-014d6bd4-9692-11e7-86b1-1a383a81a0e6.png)

this is where the money also is. 

sure all money is gone?  try to change host  and generate  a few(10 addresses)

**Comment by wonkytonky** [comment]
i already explained how to make new seed

**Comment by wonkytonky** [comment]
oh my mistake you don't seem to own address MBYLQDZBYLNKILY9NPWTBRBA9POJREVKASSBCMLHEQZMHEYMYLRXZCWIBPPCFRUSSRMIXTPFFMPKSQPQZKO9AVYEUD

so you don't have the coins anymore

**Comment by tjewsmith** [comment]
I didn't take out the money

**Comment by tjewsmith** [comment]
what do you mean change the  host and generate a few?

**Comment by tjewsmith** [comment]
that is not my address

**Comment by tjewsmith** [comment]
also the history shows 12 transfers and there should only be 2 one for 10 and one for 5.5+which was me putting my iota in my wallet, I never took anything out.

**Comment by tjewsmith** [comment]
no

**Comment by tjewsmith** [comment]
no I don't have the coins

**Comment by tjewsmith** [comment]
if you can see where they went why cant we get them back?

**Comment by wonkytonky** [comment]
no you cannot get them back  
someone else with address : MBYLQDZBYLNKILY9NPWTBRBA9POJREVKASSBCMLHEQZMHEYMYLRXZCWIBPPCFRUSSRMIXTPFFMPKSQPQZKO9AVYEUD 

owns the coins now

**Comment by tjewsmith** [comment]
wow I cant believe that if you can see where they went you cant get them back !!!!

**Comment by wonkytonky** [comment]
this is the same for bitcoin litecoin etc...     basicaly all crypto currencies

**Comment by arancauchi** [comment]
I would recommend that you really do look up crypto fundamentals, along with iota fundamentals before you invest more money. You are fully in charge of your own security, and it is no one else's fault if you make a mistake with respect to security.

**Comment by tjewsmith** [comment]
--------------------------------------------
On Sun, 12/31/17, Rajiv Shah <notifications@github.com> wrote:

 Subject: Re: [iotaledger/wallet] JUST WENT ON OUR WALLET AND ITS ZERO!!! (#281)
 To: "iotaledger/wallet" <wallet@noreply.github.com>
 Cc: "tjewsmith" <tjewsmith@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Sunday, December 31, 2017, 8:10 PM
 
 Closed #281.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
 
 
   
   
 
  Please please help me.  I read online last night about what happened.  Got your email here this morning that my case is closed.  Was so excited I call my husband and we were both in tears it was figured out.  I go to open wallet and its still empty. This situation almost cost me a divorce when it happened.  Were a middle class family with not much savings. My husband thought your company was the greats idea ever.  He sold so jewelry of his and with the money we had he bought 5,800 coins of yours.  When it disappeared he blamed me for weeks.  It was hell here.  And here I fought it was fixed and still at 0 balance.  This is a roller coaster ride.  I'm ready for a hart attack.   Please help me get back on track here.  
 
 Thanks Traci Smith
