### ISSUE TITLE
http://iota.bitfinex.com:80	

### ISSUE THREAD

**Issue by FPVBolly** [iotaledger/wallet#286]
http://iota.bitfinex.com:80	
Could not remote connect to node; what does this mean?

**Comment by wonkytonky** [comment]
some nodes are beeing ddossed.. also explorers. + attack on the network is giong on / beeing delt with .. some nodes have the correct milestones and work though.. shuffle around

**Comment by FPVBolly** [comment]
Thanks bar bar, all good 😊

**Comment by Zete88** [comment]
are my iotas lost? i have the same problem with it. what could i do?

**Comment by wonkytonky** [comment]
no and it's not adviced to send money for now. until  the attack is resoveld.. and it looks like its beeing resolved.  "soon" 

try one of theses hosts and login too see if your balance is still there those hots have a good milestone count 
http://5.9.137.199:14265 
http://5.9.118.112:14265
http://5.9.149.169:14265
http://88.198.230.98:14265
http://176.9.3.149:14265

**Comment by Zete88** [comment]
ok thank you so much

**Comment by FPVBolly** [comment]
I thought that too, initially Zete, but when u join the tangle on another
node its fine.
Wait until the  take profits sell-off finishes on Bitfinex, then it will be
back to business as usual!
Barbar will help.. stay in touch with him and he'll help you.
