### ISSUE TITLE
Status Confusing

### ISSUE THREAD

**Issue by snoroozi** [iotaledger/wallet#287]
Sent some iota to my bitfinex wallet, and the bundle shows confirmed in my wallet, but pending on the tangel explorer for hash ELGVTJOKW9GFO9VGPFHBXG9ZXAYGXZKVWWIVTGUJHRLITWSNVFJ99LYECMSMBZGVUWXVWZBCIUFW99999

My balance already reduced in wallet, but nothing showing at bitfinex.

**Comment by jogearg** [comment]
Now Bitfinex says that they dont receive or withdraw the iota.

**Comment by wonkytonky** [comment]
wait until bitfinex  starts processing deposits again.   the money seems to be stransferd into their wallet..  
write support  if it doesnt show up in your balance after a day or so(after they process deposits again)

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/30340987-a8f5a4a6-97f4-11e7-8407-e06dbab9dd51.png)

yeah now it' seems it never left your wallet .. so they money should be there.  there  is an attack going on the network.; try to find a synced  host 

http://5.9.118.112:14265 | 202467/202467 | @rage1337 |  
http://5.9.149.169:14265 | N/A | @rage1337 |  
http://88.198.230.98:14265 | 202467/202467 | @rage1337 |  
http://176.9.3.149:14265 | 202467/202467 | @rage1337 |  
https://n1.iota.nu:443 | N/A | @gemoz |  
http://node.lukaseder.de:14265 | 202433/202467 | @ghosttyper |  

and login again.. and see if balance is still there

**Comment by rage1337** [comment]
Hey, @wonkytonky , why did you mention me?

**Comment by wonkytonky** [comment]
hi, sorry copy paste from , http://iotasupport.com/lightwallet.shtml

will remove them

**Comment by rage1337** [comment]
No problem, was just a little confused :D

**Comment by snoroozi** [comment]
Still shows gone in the wallet.  One bundle shows confirmed in wallet history.  All show pending in the tangle.

**Comment by wonkytonky** [comment]
can you screenshot the history?

**Comment by snoroozi** [comment]
Here you can see 
![desktop screenshot](https://user-images.githubusercontent.com/2366245/30343344-3da9825e-97cb-11e7-89f6-7d7a34097ed1.png)

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/30344014-d92911c0-97ff-11e7-811c-6cf4cc016547.png)
yeah..  it looks like it arrived now..and they send it to their hot wallet 
(there is some attack going on the network, things are confusing )

show this screenshot to support

**Comment by snoroozi** [comment]
OK. It showed up at Bitfinex.

Only remaining question I have is in the Mobile App for android I tried this transaction once yesterday, and it shows pending on mobile app still.  I wonder if it at some point it will end up going through too?  It never affected my balance in the app though.

**Comment by wonkytonky** [comment]
dont use android app it's still in beta

**Comment by snoroozi** [comment]
Well I did.
