### ISSUE TITLE
I cant connect to my node 

### ISSUE THREAD

**Issue by jogearg** [iotaledger/wallet#288]
i cant´t connect to the http://iota.bitfinex.com:80 can you help me???
Thanks!!!

**Comment by jogearg** [comment]
And i cant connect to any other Node can you tell us whats happening please???
regards!!!

**Comment by wonkytonky** [comment]
some nodes are beeing ddossed..  also explorers. + attack on the network is giong on / beeing delt with .. some nodes have the correct milestones and work though.. shuffle around

**Comment by jogearg** [comment]
but my iotas are safe??? in my wallet???
do you Know which is  a safe node???

**Comment by wonkytonky** [comment]
dont move money now . as suggested in slack announcements  then money is safe .. wait for a new anouncement of devs to confirmit's safe to move money again

**Comment by jogearg** [comment]
Thanks for your great support!!!
I ve already found a node to connect , thanks God my iotas right now are safe the address  i could connect was http://
