### ISSUE TITLE
i cant connect too by my  iota android wallet and Laptop

### ISSUE THREAD

**Issue by jogearg** [iotaledger/wallet#289]
i cant connect too by my  iota android wallet and Laptop can you tell us what we have to do???
 if we have to wait for some support or instructions to prevent the Hacking attack???
Or when we can continue to sending or receiving the iotas.
 I appreciate your Help and keep informing us to help others owners of Iota.
 We trust in this Token help us to continue growing with this project.
Regards!!!!

**Comment by wonkytonky** [comment]
some nodes are beeing ddossed.. also explorers. + attack on the network is giong on / beeing delt with .. 
don't move money until the devs anounce it's safe

**Comment by jogearg** [comment]
thanks for the informatio

**Comment by larrysmith1000** [comment]
Where do we listen for dev announcements?

**Comment by wonkytonky** [comment]
https://iotatangle.slack.com/
https://t.me/iotatrader  not official news but ppl talk about iota and news there

**Comment by jogearg** [comment]
Thanks a lot,
 Can you share me please the iota Node address for android, please?
