### ISSUE TITLE
no tools-> generate seed option to create a new seed.

### ISSUE THREAD

**Issue by laurencefass** [iotaledger/wallet#290]
How to create new seeds/accounts using the wallet? There is no way of generating a new seed in the Tools menu item? I've seen this in videos using earlier versions.

thanks

**Comment by wonkytonky** [comment]
you should create your own seed  

be sure it's realy random 

https://iotasupport.com/gui-newseed.shtml

**Comment by laurencefass** [comment]
may i ask why the design decision to remove seed generation from the wallet? not everyones going to know how to create an 81 character seed. Doesn't this method also create a very small chance of generating a seed already in use?

**Comment by wonkytonky** [comment]
i dont know why the devs removed the seed generator, .

iota is still very early days as you  can see using the wallet ...   better wallets are beeing worked on.  but the current one is good enough if you know what you are doing.   which includes managing seeds.

a good seed generator is so random it will be impossible  (or maybe in a few  thousand years  or more with current technology) to reproduce the same seed.
