### ISSUE TITLE
Balance Zero & Login Problems

### ISSUE THREAD

**Issue by larrysmith1000** [iotaledger/wallet#291]
Serious help needed and appreciated.

The first version of the IOTA wallet that I ever downloaded was 2.4.0 (i.e. after the "change over"), so this is not the typical case of simply regenerating addresses.

I had a substantially large balance in my IOTA 2.4.0 wallet as of 5 days ago (September 8th).

Today, when I attempt to login with my seed, the wallet gets stuck on the message "Logging In...".  I have tried several different nodes.  Next, I downloaded and installed the wallet on another computer.  Since it was a new wallet, it went through the process of adding 50 addresses.  However, the balance read zero.  I clicked "Balance Incorrect" several times, adding more address, but the balance still reads zero.  I was scared to click "Balance Correct" so I just closed the wallet.

I went to bitfinex and I have a history of all withdrawal addresses to where funds were sent (about 8 withdrawals).  When I check these addresses on the explorer at https://iotasear.ch, it shows that these addresses have received the funds, and there are no "out" transactions associated with the addresses, which is comforting.  However, I am still concerned about getting access to these addresses with my seed.

Another thing to note is that I initiated 2 additional transfers FROM Bitfinex to my wallet on September 5th.  As of September 8th, the transfers still said "processing".  Then, today when I couldn't login to my wallet, I logged in to Bitfinex, and it says the transfers are complete.

Please help.  It is a lot of money, and I am very concerned.

Thanks!

**Comment by larrysmith1000** [comment]
I see some of the nodes were being DDoSed.  I tried 176.9.3.149, and I got in, and my balances is there.  However, now I have another question.  While troubleshooting this, I downloaded and installed the wallet on another computer.  That wallet went through the update process (checking 50 addresses at a time), and says that my balance is zero.  The two options are "Balance Incorrect" and "Balance Correct."  Balance Incorrect just checks another 50 addresses.  What should I do if I want to have my wallet on this other computer?  Should I click, "Balance Correct"?  Will my balance show up?

I assume that an array of addresses are generated by putting your seed through a hash with the address's array index.  Is that true?  Is there a place I can read about how addresses are created and managed relative to a seed?

Thanks!

**Comment by wonkytonky** [comment]
try one of theses hosts and login too see if your balance is still there those hosts have a good milestone count
http://5.9.137.199:14265
http://5.9.118.112:14265
http://5.9.149.169:14265
http://88.198.230.98:14265
http://176.9.3.149:14265

**Comment by larrysmith1000** [comment]
Thanks wonky!  I tried 176... and it worked.  How about my question about installing the wallet on a second computer (above).

Cheers,

Ryan

**Comment by wonkytonky** [comment]
you indeed generate an addess based on a seed. in combination with an index number;  google a bit around how this works. 


now the 50 address generation is only needed for  a transition (pre 2.4.0 wallet area they used other crypto to generate adresses)  so you can skip that transition stuff   and just login balance should be there if you use a host that has synced milestone.
