### ISSUE TITLE
Cant Login to Light Wallett

### ISSUE THREAD

**Issue by ThisIsIota** [iotaledger/wallet#292]
Hi there,

Installed Light Wallett 2.4.0. and transferred some Iota to test the functionalty. Everything worked fine. However, after two days now, I cant even login to the Wallett. When starting the application CPU shows 0.0% and the login doesnt even occurr. 

Any thoughts?

**Comment by wonkytonky** [comment]
change node

**Comment by ThisIsIota** [comment]
already tried this but doesnt work out

**Comment by wonkytonky** [comment]
http://88.198.230.98:14265  try this one

**Comment by ThisIsIota** [comment]
yeah, it works now. many thanks! could you tell something about why changing the node is required?

**Comment by wonkytonky** [comment]
there's is an attack going on , ddoss nodes,  spamming network etc.. which seems to get better every hour .. i just made deposit on bitfinex ..   i guess in a day or two everything will be back to normal

**Comment by ThisIsIota** [comment]
ok. thanks again for helping.

cheers

**Comment by eduardoroque10** [comment]
I made the change no No, ay I can access the system more appears in my balance is 0 zero, What can I do?
