### ISSUE TITLE
 Transfer issues

### ISSUE THREAD

**Issue by agathakang** [iotaledger/wallet#294]
He says he can not send iota from his wallet and he keeps sending it.

The same is true for changing nodes
What should I do?

**Comment by wonkytonky** [comment]
try again.. there was an attack on iota last 2 days

**Comment by agathakang** [comment]
Is the attack over?
I can not send it five days ago.

**Comment by wonkytonky** [comment]
i just send some iota around... 3min confirm.

**Comment by wonkytonky** [comment]
do you have a intel graphics card?.. if so update drivers.. 

ppl had problems with this before

**Comment by agathakang** [comment]
I have also updated the drive and I have also tried to treplaced the node, but it still does not work. Is there any way to cancel the transfer?
