### ISSUE TITLE
Balance zero!! please help ->IOTA Light Wallet 2.4.0

### ISSUE THREAD

**Issue by Urklman** [iotaledger/wallet#299]
Hello :-)
My wallet is empty and i dont know why. In the history I can see movements but I never done this. I only send 112 Miotas from bitfinex to this wallet...thats all. Then I logged in a few days later and my wallet is empty and I have 6 Transfers!!??? I did only one...! Where are my Miotas??? Can anybody help?

**Comment by wonkytonky** [comment]
can you show  the transfers

**Comment by Urklman** [comment]
Pic1 is my transfer from bitfinex…Pic2 and Pic3 is unknown…not transfers I did…I’m very sad that my Iotas are lost… but what happened?


Von: wonkytonky [mailto:notifications@github.com]
Gesendet: Freitag, 15. September 2017 14:39
An: iotaledger/wallet <wallet@noreply.github.com>
Cc: Nunheim Joachim <nunheim@svg-pfalz.de>; Author <author@noreply.github.com>
Betreff: Re: [iotaledger/wallet] Balance zero!! please help ->IOTA Light Wallet 2.4.0 (#299)


can you show the transfers

**Comment by wonkytonky** [comment]
i dont see any pictures

**Comment by Urklman** [comment]
[cid:image001.jpg@01D32E33.2FAF6530][cid:image002.jpg@01D32E33.2FAF6530][cid:image003.jpg@01D32E33.2FAF6530]


Von: wonkytonky [mailto:notifications@github.com]
Gesendet: Freitag, 15. September 2017 14:53
An: iotaledger/wallet <wallet@noreply.github.com>
Cc: Nunheim Joachim <nunheim@svg-pfalz.de>; Author <author@noreply.github.com>
Betreff: Re: [iotaledger/wallet] Balance zero!! please help ->IOTA Light Wallet 2.4.0 (#299)


i dont see any pictures

**Comment by wonkytonky** [comment]
i still don't see a picture ..  i see : 

[cid:image001.jpg@01D32E33.2FAF6530][cid:image002.jpg@01D32E33.2FAF6530][cid:image003.jpg@01D32E33.2FAF6530]

**Comment by Urklman** [comment]
How can i send you the pics?


Von: wonkytonky [mailto:notifications@github.com]
Gesendet: Freitag, 15. September 2017 15:01
An: iotaledger/wallet <wallet@noreply.github.com>
Cc: Nunheim Joachim <nunheim@svg-pfalz.de>; Author <author@noreply.github.com>
Betreff: Re: [iotaledger/wallet] Balance zero!! please help ->IOTA Light Wallet 2.4.0 (#299)


i still don't see a picture .. i see :

[cid:image001.jpg@01D32E33.2FAF6530][cid:image002.jpg@01D32E33.2FAF6530][cid:image003.jpg@01D32E33.2FAF6530]

**Comment by wonkytonky** [comment]
copy past them here on github in the text field

**Comment by Urklman** [comment]
![pic1](https://user-images.githubusercontent.com/31983328/30483340-eaa1b78a-9a26-11e7-9b85-47d7cf088884.jpg)
![pic2](https://user-images.githubusercontent.com/31983328/30483345-ec930152-9a26-11e7-86df-6323f9a95291.jpg)
![pic3](https://user-images.githubusercontent.com/31983328/30483348-ef86fd14-9a26-11e7-93b2-1a8858f4bca7.jpg)

**Comment by wonkytonky** [comment]
jep someone moved money out of wallet.  

how did you create your seed?   with windows powershell?

**Comment by Urklman** [comment]
no, I used this link: https://ipfs.io/ipfs/QmdqTgEdyKVQAVnfT5iV4ULzTbkV4hhkDkMqGBuot8egfA

**Comment by wonkytonky** [comment]
never use website  in my oppinion , there's too much attack vectors like sniffing network, malware that screenshots etc . 

http://keepass.info/ is good   . use the password generator   add entropy (mous movements)   and never show your seed (you can hide it) and just use the copy paste  (it will be removed after 1min or less out of clipboard).

make a few copies of the keepass database on some usb sticks and print it on paper (offline preferably)

**Comment by Urklman** [comment]
so its my fault?

**Comment by wonkytonky** [comment]
i'm not an security expert. I asked around.. this link "should" be safe to use..  not sure how your seed is compromised .   where did you safe your seed?

**Comment by Urklman** [comment]
I used the printer...the seed is on the paper ;-)

**Comment by wonkytonky** [comment]
keylogger maybe?. since you have to "type" your seed manuall

**Comment by Urklman** [comment]
no I dont think so...is there any chance to get them back?

**Comment by wonkytonky** [comment]
no if the money is out of wallet and confirmed. it is moved to another address..  
unless you have the seed that generates that adress  where the money is now. you cannot get it back

**Comment by Urklman** [comment]
I didnt confirmed it...why is there no 2-way-security...? mean seed and another one like google authenticator...?

**Comment by wonkytonky** [comment]
i'm not an iota dev .. i know this question has ben asked many times though.;  
but 2fa also asks you to store a secret key on your computer..  that secret key sits then on you pc which is less safe then to store your iota  seed offline on usb stick or paper

**Comment by Urklman** [comment]
ok...give me a short message if https://ipfs.io/ipfs/QmdqTgEdyKVQAVnfT5iV4ULzTbkV4hhkDkMqGBuot8egfA is safe...thx

**Comment by wonkytonky** [comment]
this is my oppinion i stated before: 
never use website in my oppinion , there's too much attack vectors like sniffing network, malware that screenshots etc .

http://keepass.info/ is good . use the password generator add entropy (mous movements) and never show your seed (you can hide it) and just use the copy paste (it will be removed after 1min or less out of clipboard).

make a few copies of the keepass database on some usb sticks and print it on paper (offline preferably)

**Comment by Urklman** [comment]
yes...u said that before...but u said also this link should be safe.

**Comment by wonkytonky** [comment]
yes  other ppl say its safe to use. thats their oppinion . not mine

**Comment by Urklman** [comment]
ok...thx have a good time
