### ISSUE TITLE
Errors / Grammar Mistakes in the Help/FAQ Section

### ISSUE THREAD

**Issue by scottjp** [iotaledger/wallet#30]
Little things, but we are on a bug hunt... 

In the Help/FAQ section of the Wallet:

 **Tangle Not Solid**
>  In the status bar, you'll see: xx / yyyy (zz)

This is not longer the case - we now have xxxxx / yyyyy / CPU %

**How long and complex should my seed be?**

>In order to ensure that only you got access...

Replace with: "In order to ensure that only you have access..."

**Comment by atypicalprogrammer** [comment]
@domschiener why did u close this?
