### ISSUE TITLE
Minimize / close to tray instead of taskbar

### ISSUE THREAD

**Issue by cyjambo** [iotaledger/wallet#31]
Hi, it would be great to have an option to minimize / close to tray area instead of the taskbar. This would make it easier to run the app in the background.

**Comment by MicahZoltu** [comment]
Why was this closed?  Was it implemented?  When I minimize the GUI client on Windows it goes to taskbar, not system tray.

**Comment by uok** [comment]
This would be a helpful feature (optional with logout on minimize to tray). Thanks!
