### ISSUE TITLE
Balance 0, History is empty

### ISSUE THREAD

**Issue by Flashneo** [iotaledger/wallet#314]
Hi. I had installed IOTA wallet few months ago and succesfully used it before (last time 1 week ago). But today when i loggin with same seed i see Balance 0 and all history are gone, when i try to attach my receiving adress to tangle i have error: invalid transaction hash. 

And my last withdrawal from bitfinex has invalid hash also
https://iotasear.ch/hash/HRQHIDDKSUIIOAU9DHAABNHFLHINR9MTOB9QBRTFKGHRQA9VTRJYVFWHPJWAWVOGRHAKADHVERUBVVRPBTNARWCAQW
But in bitfinex it shows like  Completed, and i received this iota to wallet before. 
It was showed 2 same transaction in wallet history one completed and 1 pending. 

Iota light wallet 2.4.0 - IRI 1.4.0

**Comment by th0br0** [comment]
Please wait for new wallet release.
