### ISSUE TITLE
Error message on Light Wallet 2.5

### ISSUE THREAD

**Issue by ac556k** [iotaledger/wallet#316]
I'm getting the message 'Typeerror: Cannot read property "MAX_TEXTURE_SIZE" of Null' when I start the new wallet 2.5.0 (Windows 7 Pro 64 bit)

![image](https://user-images.githubusercontent.com/32224610/30774929-c7783584-a04f-11e7-8774-eb02e4880409.png)

**Comment by MarlonX19** [comment]
I am also getting that error. I have tried both the windows and Linux versions and got the error on both.

**Comment by WPMAGNUS** [comment]
Eu também estou recebendo esse erro. 
windows 7 ultimate. 64

**Comment by vasiauvi** [comment]
The same issue also in Linux Lite (*.deb) package.

**Comment by ericvrp** [comment]
Probably related to https://github.com/iotaledger/curl.lib.js/issues/12

**Comment by OmniBazaar** [comment]
I am getting the same error. I have cURL installed on this machine (if that makes any difference).

**Comment by Weibeler** [comment]
Same error with Windows 10

**Comment by ac556k** [comment]
It worked on my laptop with windows 10 home version 1703.

**Comment by ac556k** [comment]
Version 2.5.1 solved my issue.
