### ISSUE TITLE
Invalid Transaction Hash

### ISSUE THREAD

**Issue by ThisIsIota** [iotaledger/wallet#318]
Hi there, have downloaded the new 2.5.0 wallet. I did the login with my old seed (2.4.0). I was told to attach as many addresses to the tangle (in the receive option) until I see my balance. However, I cant even attach one single address since I always get an error message saying "Invalid Transaction Hash". I have tried multiple hosts and set the weight to 14. What can I do?

**Comment by ThisIsIota** [comment]
I restarted my PC and I got one address attached and a part of my balance occured in the new wallet. However, now I again get invalid transaction hashs. restarting the PC doesnt help anymore.

**Comment by 2MaxSpeed** [comment]
Hello, I've been dealing with that for about an hour... until on TOOLS>CONFIGURATION I changed:
1) WebGLv2 for ccurl
2) 15 for 14
3) and picked another host (I've  been trying many)... and it worked!! I got all my IOTAs back!!

I hope it helps!

**Comment by wonkytonky** [comment]
try new wallet 2.5.1 if you have troubles with  invalid tx hash.

**Comment by ThisIsIota** [comment]
downloaded the 2.5.1 got an invalid hash two times in a row. then it
worked. all good now. thanks!

wonkytonky <notifications@github.com> schrieb am So. 24. Sep. 2017 um 11:49:

**Comment by wonkytonky** [comment]
nice to see it worked..   please close issue :)
