### ISSUE TITLE
Adding of Neighbors doesn't require restart

### ISSUE THREAD

**Issue by domschiener** [iotaledger/wallet#32]
When a user adds a new neighbor, instead of restarting the GUI, it should use the `addNeighbors` (https://iota.readme.io/docs/addneighors) API call and store the new neighbors information in settings.json (as it did previously).

This way we don't need to restart the GUI, the connection to the neighbor still gets established and on the next restart the neighbor will be automatically loaded as a startup parameter to IRI.

**Comment by atypicalprogrammer** [comment]
@domschiener fix your iota api library to include URI's in add/removeNeighbors and i will!

**Comment by atypicalprogrammer** [comment]
@domschiener, u did fix this in iota.lib.js right? Did you test this if this works yet?
