### ISSUE TITLE
while sending a tx/attaching a new address, should disable functions for spammer until other action is complete.

### ISSUE THREAD

**Issue by lueyforje** [iotaledger/wallet#33]
wallet 2.0.2

while spamming on gui wallet, and i went and clicked>tools>claim process
this cancels out my spamming and may have corrupted my db. as i try to spam again, spams shoot out like 10 spams every second

another thing while sending a tx or attaching a receive address and then before it finishes go to the spammer, they both seem to run in conjunction with each other but as i hit cancel spam after running it a few seconds, it then immediately shows as "attach address complete/sending tx complete" but in reality it did not.

**Comment by domschiener** [comment]
@atypicalprogrammer

**Comment by atypicalprogrammer** [comment]
@domschiener well i call interruptAttachToTangle when spam is cancelled. Of course this interrupts the other action too. 

Do you have a better idea? How can I know (with API) that the user is currently attaching something (so as not to allow to open the spam dialog).

However, interruptAttachingToTangle should not corrupt the db.. (first part of question) @domschiener
