### ISSUE TITLE
Displaying the balance after the post-snapshot or coin claim

### ISSUE THREAD

**Issue by Tobo01** [iotaledger/wallet#34]
I wonder if the GUI client can automatically display the balance after users first open the post-snapshot wallet or claim their coins. For instance, the wallet can automatically re-generate the necessary addresses to display the total balance for the users when the users are doing those two actions.

For now, after users claim, they don't see the balance in their wallet before manually generating some addresses. Same for using the post-snapshot wallet. For instance, if a user has 100 addresses in his account, after the snapshot, he has to manually re-create these 100 addresses to let his balance show up. 

Another potential confusion is that if a user has many addresses in his account and he did not write down all the addresses, when he is creating the addresses in his post-snapshot wallet, he won't know which ones are the old and used addresses and which ones are the brand new addresses.

**Comment by atypicalprogrammer** [comment]
@domschiener ? Not possible right?

**Comment by domschiener** [comment]
Technically possible, but adding this feature would largely lead to confusion. We will provide a better mechanism for this in the near future.
