### ISSUE TITLE
IOTA Light Wallet 2.4.0

### ISSUE THREAD

**Issue by weltreisendertj** [iotaledger/wallet#349]
I´ve installed the new version and want receive some iotas. When I click "connect with tangle" I get always the message "Invalid Transaction Hash". I´ve tried same precidure with different nodes.

**Comment by weltreisendertj** [comment]
Sorry it was my fault I´ve used the wrong version. Now I upgraded to v.2.5.1 and it works as expected.

**Comment by sjkelleyjr** [comment]
Can you close this issue then? Thanks

**Comment by weltreisendertj** [comment]
Done…

 

Von: S. Jackson Kelley Jr. [mailto:notifications@github.com] 
Gesendet: Montag, 2. Oktober 2017 05:39
An: iotaledger/wallet <wallet@noreply.github.com>
Cc: weltreisendertj <masterofweb@gmx.at>; Author <author@noreply.github.com>
Betreff: Re: [iotaledger/wallet] IOTA Light Wallet 2.4.0 (#349)

 

Can you close this issue then? Thanks
