### ISSUE TITLE
Wallet empty, where are my iotas?

### ISSUE THREAD

**Issue by 99ermart** [iotaledger/wallet#350]
Hey Guys,

3 Months ago i buy 1200 IOTAs and store them in two Wallets. I checked the Wallets every Week, now i was for 3 Weeks at vacation. Today i log in to my wallets and they are empty.
My Wallet is Version 2.4.0, so i updated to the newest version, but the Wallet is still empty.... (My OS is Linux Mint)
What now? Are my IOTAs away for ever ?
I hope somebody can help me.

**Comment by HrisSC** [comment]
No you just need to log in your seed and attach a number of adresses to the tangle. Do that until the wallet shows your full balance. 

And if you updated to the new wallet you may change the settings of your node. 

Tools --> Edit Node configuration --> Min Weight Magnitude = 14

That should fix your problem.

**Comment by 99ermart** [comment]
Thank you very much.... this works for me, my iotas are back. Thank you Thank you Thank you
