### ISSUE TITLE
Balance at 0 - I've tried everything with no luck

### ISSUE THREAD

**Issue by rllybadcryptotrdr** [iotaledger/wallet#355]
OK.  I know everyone is having the same problem, but mine isn't resolving.  I only had one transaction, and I've updated and generated 240+ new addresses with the proper settings.  The first address created was the only address ever used. It has been "reattached" but still shows 0 balance.  

I know there's a list of address that will have to be recovered at a later date, but the address I used was not listed on that site.  

Searching thetangle.org shows a 0 balance at that address.

I have a couple of possibilities of where things went wrong along the way.
    
  I was running an old version. I accidentally updated to 2.5.0, I think. Maybe 2.4.0, and tried creating new addresses to revive my balance.  I believe the address with the balance was recreated on the first attempt, but not with the latest version.  Not sure if that could affect anything.

   Is there a possibility that the transaction wasn't confirmed, but still showed up in my wallet temporarily? Is this possible? I bought from an individual. They believe their IOTA to be in the possession of the IOTA foundation there is no transaction history for them to look at either.

With nothing showing on thetangle.org, my address missing from the list in possession of the IOTA foundation, and no transaction history to work with, what should I do?

**Comment by rllybadcryptotrdr** [comment]
Out of the 240+ new addresses that have been generated, some of the transactions are pending. The deposit address that was used is one of them.  After looking at the transaction, it shows a status of "failed - invalid".  I'm attempting a rebroadcast, but so far no luck.

**Comment by BFTremans72** [comment]
Hi, Did you get any response to your issue? I am having same problem. I opened my originally installed wallet 2.4.1 and there was 0 balance and no transaction history. I updated my wallet to newer version 2.5.1. Add new address and still same result: 0 balance and no transactions. Not sure what to do next. If you have resolved your issue, and if not too bothersome for you, please share? Thanks in advance!

**Comment by rllybadcryptotrdr** [comment]
Everyone says to add more addresses. 

I believe my issue was that I only did one transaction, and I don't think it ever confirmed. My balance showed immediately. That was Sept 5. I never opened my wallet again until a few days ago. The deposit address doesn't show the transaction on thetangle.org.  

Since I purchased from a friend (who had the same 0 balance issue, and fixed it by upgrading and attaching addresses), I had them check their transaction history. The transaction has completely disappeared for them too, so I am having them resend it. 

It seems like an unlucky coincidence that we had a failed transaction at the same time that everyone else had a 0 balance issue.

If you're sure you're balance was from confirmed transaction/s, I would probably check the deposit addresses you've generated at thetangle.org or another tangle explorer.  It should show you if there's a record of any transactions at those addresses. Since the wallet creates addresses in the same order as it did the first time, you should be able to find a history by searching those addresses.   I'm honestly speculating.  That's what I did, but since I only used one address, it was easy to check, and since it showed nothing, I can't guarantee it will prove anything.  

Also, the IOTA foundation took possession of funds at many addresses that didn't transition. I didn't know anything about that, but there is a list you can check for your addresses (if you know them) to see if they have them. There should be a recovery tool soon, assuming you have a different problem then I did. 

Good luck.

I hope most of that is accurate.

**Comment by seangeleno** [comment]
I'm having exact same issue :'( 

This is very scary, I really need to get this resolved. have there been any official announcements?

**Comment by HilalHakla** [comment]
I am also having the same issue. Had my balance in the 2.4.1 for a while. I logged in today and the balance was zero.
I downloaded the latest one and tried to reattach and generate new addresses with no luck, the balance is still zero.

**Comment by BFTremans72** [comment]
I did add and synced up two addresses in my new updated wallet and my
balance showed up.
So I am all set
Hope the issue will resolve for you soon! It will resolve because your
transactions are on the tangle and it is link to your seed, not the actual
address like other wallets out there.
Best regards!

**Comment by HilalHakla** [comment]
@BFTremans72 
Thanks for that. 
I am not very familiar with the wallet, can you please tell me how you add and sync address?
right now all i do ( or know what to do) is to click on generate new address in the receive section and reattach to tangle.
Is there something else I should do?
thanks

**Comment by BFTremans72** [comment]
Hi
You doing the right thing 
Adding address and attaching to tangle is wallet sync process
The delay may be due to the larger volume of tangle transactions 
So what a I suggest is to:
1) Make sure your internet connection is sound though 
2) leave your wallet open and don’t quit it for awhile, Id say an hour or two or longer, Until your coins appear 
It should work 
All Best!

**Comment by HilalHakla** [comment]
ok thanks, i will try that

**Comment by HilalHakla** [comment]
I followed this advice (https://i.redd.it/hv6n5f0bgynz.jpg) and I got my IOTA's back. 
Thanks for the help

**Comment by BFTremans72** [comment]
Awesome! Glad it worked :)

**Comment by rllybadcryptotrdr** [comment]
I thought I would update... I had my friend send me some more IOTA. Two transactions for 10Mi each. The first one got stuck in pending. The 2nd one confirmed and showed in my balance.  Two days later, my balance shows 0, and both are in Pending status.  

How does a "Confirmed" transaction go back to "Pending"?

**Comment by rllybadcryptotrdr** [comment]
I changed nodes, because it wasn't logging in. When it logged in, it showed a 0 balance.  After 5 minutes, the balance showed up.  The previously pending, then confirmed, then pending transaction has been confirmed again. Woohoo.

**Comment by EQuimper** [comment]
Get same problem, I confirm I need to attach 2 address by transaction. So example for me because of my 6 past transactions took me 12 times.

**Comment by paulhandy** [comment]
It appears that @rllybadcryptotrdr's issue is resolved by attaching addresses - Anyone else who still has an issue, please find a similar issue page or file an independent one.
