### ISSUE TITLE
IOTA wallet transfer pending after 5 hours so far

### ISSUE THREAD

**Issue by fldude** [iotaledger/wallet#378]
Hi experts,
I wanted to change to a new seed, so I created a new one and am now trying to send my IOTA from the old seed to the new seed with the Lite wallet.  I started with a xfer of 2 iota to the new account before I send the majority, but has just been sitting there for 5 hours as pending.
Does anyone know any this is taking so long to complete?
I am starting to have doubts on IOTA because of this.
:-(
Thanks!

**Comment by wonkytonky** [comment]
-check you have latest version wallet    

if latest wallet : reattach every 30min  if it takes long. 

check your weight  = 14  
check your node is synced

**Comment by fldude** [comment]
Wonkytonky,
The version of wallet = IOTA Light Wallet 2.5.1 - IRI 1.4.0
The other settings are:
These look OK to you?
TIA!

**Comment by wonkytonky** [comment]
looks ok 

choose other node then bitfinex  ,

what you can also try is to change curl  implementation
![image](https://user-images.githubusercontent.com/19390834/31683973-b490e10e-b37e-11e7-9d5e-50308c0be093.png)

**Comment by fldude** [comment]
Thanks again for the help!
I have made the changes per your screenshot with Host and Webgl% and reattached accorfingly.
It's odd that I can see the -2 transaction as pending in the 'from' account and the 2 transaction as pending in the 'to' account, but no transfer of iota yet.  I also see the various times I have reattached.
Very strange and unnerving.

**Comment by fldude** [comment]
As I wait for the transfer to complete ... I hope at least:
How do I make sure the node is synced?
Also, when I change to some nodes my balance goes to 0.  Why is that ... I found one node with 15 friends and wanted to give that a try but it had my balance =0.
Thanks!

**Comment by wonkytonky** [comment]
"How do I make sure the node is synced?"
![image](https://user-images.githubusercontent.com/19390834/31686785-8d844372-b387-11e7-8134-0d4d85bc8c71.png)


there's a channel in slack : botbox which shows lates milestones..    
![image](https://user-images.githubusercontent.com/19390834/31686817-ad762b82-b387-11e7-915c-0faff5f951ff.png)

some nodes might not be synced and show 0 balance, i'd stick to the nodes that do give balance .

**Comment by fldude** [comment]
My transaction continue to not get past Pending.  Is there a minimum or something which may be the problem as I am only trying to send 2i to begin with?

Anyone know how I can get onto iotatangle slack?  The site indicates:
Don't have an account on this workspace yet? Contact the workspace administrator for an invitation

**Comment by wonkytonky** [comment]
there is no minimum amount..  sending 1 iota works

**Comment by fldude** [comment]
wonkytonky, thanks for the help!  my 2 iota did indeed finish transfer after around 8 hours of waiting, FYI.

iota needs to improve the lag time if they are going to compete in today's world as people cant wait that long for money moves ... food for thought for any others facing similar issues in the future.

**Comment by fldude** [comment]
Thanks again wonkytonky, its good to have you here to provide guidance.

**Comment by wonkytonky** [comment]
normal confirmations take about 2 - 5 min .. i'm not sure why it took so long for you. 

try another pc if you have one. preferably a good pc with soms cpu or gpu power .

my tx take 5min max ..   sometimes i have to reattach after 30min and then they get confirmed in 5min or less
