### ISSUE TITLE
Missing opportunity to create new seed

### ISSUE THREAD

**Issue by userK177** [iotaledger/wallet#38]
**Issue:** When the seed got lost, you can not use the wallet to create a new one.
**System:** Windows 7, 64bit

Uninstalling the wallet and reinstalling it leads to the wallet's seed box does not appear when you start it again.
Note 1: After uninstalling also the folders C:\Users\username\AppData\Roaming\IOTA Wallet and C:\Users\username\AppData\Local\Programs\iota have been cleaned (removed the whole folders).
Note 2: After reinstalling the wallet then always starts in 'Full Mode' without the opportunity to first select Light or Full Mode (maybe minor issue).
Note 3: No errors are logged in the console.

**The whole issue was discussed with several tries to solve** (using different host addresses, cleanup old MS C++ Redist packages) **in the forum:** [https://forum.iotatoken.com/t/lost-seed-how-to-re-login-to-wallet/1186/20](url)

**Comment by atypicalprogrammer** [comment]
Please open the web inspector (view > show inspector) and go to the console tab and see if there are any errors. Paste them here.

**Comment by userK177** [comment]
No Errors. Only UI status:

```
UI.start: Initialization
ui.login.js:51 UI.showLoginScreen
ui.update.js:43 UI.createStateInterval: 500
ui.update.js:69 UI.createStateInterval: Execute immediately
ui.app.js:3 UI.inAppInitialize
ui.update.js:89 We have an initial connection.
ui.update.js:43 UI.createStateInterval: 2000
ui.login.js:230 UI.updateLoginForm: Fade in
```

Only thing presented is the Login dialog, where the Seed got lost for:
![grafik](https://cloud.githubusercontent.com/assets/26089333/24156606/448bdb06-0e57-11e7-89b0-8843a1fd192f.png)

**Comment by atypicalprogrammer** [comment]
I don't really understand the issue. A seed is simply your password. You don't have to have a function to "create" it. Nevertheless we do provide a generate seed function, see the menu bar. If you lost a seed, of course it cannot be recovered.
