### ISSUE TITLE
Iota wallet broken, Devs don't want to acknowledge. 

### ISSUE THREAD

**Issue by visionguild** [iotaledger/wallet#385]
So myself and a bunch of others on Reddit have lost a bunch of money recently in our Iota wallets.  I posted a thread on it and many others have commented that they've had the same problem.  Iota slack is full and Reddit is the only place to go now.  But, Th0br0 just got on, called my issue suspect and closed it.  Guess they didn't want to hear that from us.  Shame on you Iota.  Your crappy wallet is defective and you should take some accountability.  I'm new to reddit so excuse me if I can't link everything correctly.

**Comment by th0br0** [comment]
Please reply to https://github.com/iotaledger/wallet/issues/382
and provide proof of your claims.
