### ISSUE TITLE
 I need to save my Iotas before octuber 29, Wallet Iota can not connect to remote mode, all the time says that there is no connection

### ISSUE THREAD

**Issue by JennyLopez** [iotaledger/wallet#391]
Wallet Iota can not connect to remote mode, In all times says there is no connection, and I need to save my Iotas, there is no other place. Bitfinex.com.com does not allow people from USA after  October 29.
I also went on Binance.com and they have the deposit and withdrawal suspended, Here neither can not save Iota.
I need to Withdrawal My Iotas from Bitfinex.com.com before of Octuber 29. 
Who gives a solusion to this. 
WHO MAKES RESPONSIBLE FOR SOMETHING LIKE THIS? 
OH DO I HAVE TO LOSE MY IOTAS, AND SELL THEM TO A VALUE IN THE FLOOR? 
 I DO NOT KNOW WHAT TO DO...THIS IS NOT FAIR??????
-----------------------------------------------------------------------------------------------------------------------
El Monedero de Iota no se puede conectar al modo remoto, En todo tiempo dice que no hay conecsión  y necesito guardar mis Iotas, no hay otro lugar.
Bitfinex.com.com no permite a las personas de los EE. UU. Después del 29 de octubre.
También fui a Binance.com y suspendieron el depósito y el retiro. Aquí tampoco pueden salvar a Iota.
Necesito retirar My Iotas de Bitfinex.com.com antes del 29 de octubre.
¿Quién da una solución a esto?
¿QUIÉN SE HACE RESPONSABLE DE ALGO COMO ESTO?
¿TENGO QUE PERDER MI IOTAS Y VENDERLO A UN VALOR EN EL PISO? 
NO SÉ QUÉ HACER....ESTO NO ES JUSTO??????

**Comment by wonkytonky** [comment]
mail support bitfinex .  i'm sure there are many other persons like you..   but what you can do meanwhile is sell your iota on bitfinex  for (ltc.. or some other coin)  move ltc to binance..  and buy your iota back.

**Comment by JennyLopez** [comment]
Thank very much!

**Comment by GoldenStarGate** [comment]
Could not connect to remote node.
any Idea how can I fix this error?

**Comment by zdjaniak** [comment]
we are terminating trading, deposits, and withdrawal functionality for U.S. individual customers by no later than November 9, 2017 
I see November 9 not  October 29 
I'm stil waiting I'm from us

**Comment by hYgen99** [comment]
i can not connect to node either. any ideas?

**Comment by zdjaniak** [comment]
Ok, the wallet 2.5.2 works, you have to updated,  but still Bitfinex works with Iota team so transfer from Bitfinex is not available

**Comment by GoldenStarGate** [comment]
After update to new version 2.5.2 
I checked it and my Iota wallet is empty!!!!
Are there any ideas how to get my iota back?
please help me

**Comment by richardjoo** [comment]
same here. all my coins are gone.  Does this something to do with IOTA recovery tool I need to use?

**Comment by richardjoo** [comment]
hey @GoldenStarGate I went to the IOTA Telegram and got the tip. Login to your IOTA by using your *OLD SEED* and go to *RECEIVE* and keep hitting *ATTACH* over and over until you get your old balance back to your *OLD SEED*  And Yes, the new *RECEIVE* addresses to attach until you get your balance back.

Now I don't know what would happen since I ran the RECLAIM TOOL!  👎

**Comment by GoldenStarGate** [comment]
Dear @richardjoo 
Near 3 hours I try to create a new address and attached to tangle until now nothing happen.

**Comment by richardjoo** [comment]
@GoldenStarGate unless IOTA team get back to you, you might want to go to IOTA telegram to get some help.  That was the only thing I know and tried and worked for my wallet.  Sorry that it did not work out for you...
