### ISSUE TITLE
No Connection v 2.4.0

### ISSUE THREAD

**Issue by Jay513** [iotaledger/wallet#408]
Having the same issue as people with later relaeases... Cannot connect to Node...  Will updating to the latest version solve this issue?

**Comment by wonkytonky** [comment]
yes

**Comment by Jay513** [comment]
Thanks for your response.  I tried downloading v 2.5.2 but it crashes during the install. I get a windows message that says Iota Wallet has stopped working.
Any ideas?

**Comment by th0br0** [comment]
Please use 2.5.3.

**Comment by Jay513** [comment]
same message when I try to install v 2.5.3... Iota Wallest has stopped working

**Comment by th0br0** [comment]
Then please provide more info on your OS, architecture etc

**Comment by Jay513** [comment]
Ok.. I did another re-install and it seems to have installed correctly this time. However the balance is Zero. 
I read another post that says to click on recieve and attach that address to the tangle. I did this and it is showing as pending... hopefully my balance will show up.
