### ISSUE TITLE
Zero balance, tried reclaim, addresses taken by IOTA foundation

### ISSUE THREAD

**Issue by xac33ncsu** [iotaledger/wallet#409]
My wallet balance still shows zero after attaching 20+ addresses. I have a very limited transaction history (all deposits, no sends from wallet). The two addresses that have ever received IOTAs are included on the list of those balances taken by the IOTA foundation for protection.

I can't seem to find these addresses in any sort of Tangle explorer though.

I have done the token reclaim routine. Some "next phase" is mentioned but no details given. 

What is going on? And how do I get these IOTA back?

**Comment by th0br0** [comment]
Please use the reclaim tool to establish ownership of your addresses; the next phase (that will return these tokens to you) will start next week.
