### ISSUE TITLE
Feature: Show checksum as user types their seed

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/wallet#41]
To prevent issues caused by a user mistyping their seed, what do you think about computing a checksum as the user types their seed (same idea as address checksum: run the value through curl and take the first 9 trytes)?

When generating a new seed, present the user with both the seed and the corresponding checksum value.

This would give users an easy way to verify that they typed in their seed correctly, and the checksum cannot be reverse-engineered to gain information about the seed.

**Comment by domschiener** [comment]
Not really sure what the utility is here. The user will know if it's the correct seed if they see the corresponding txs or addresses. So in theory a user could just store the first address that was generated with the seed, instead of the 9-tryte checksum of the seed itself.

**Comment by todofixthis** [comment]
Currently, logging into a light wallet node and generating an address takes 15-20 seconds on my system, whereas a checksum can be generated in a fraction of a second.

If it's a local node, this process is probably near-instantaneous, so this feature might only be a convenience for light wallet users.

**Comment by atypicalprogrammer** [comment]
May be interesting as it allows a user to verify they typed or pasted the correct seed before logging in. Show some mock UI on how u would implement this if you're serious about it.

**Comment by domschiener** [comment]
I will leave this to be discussed via another medium (perhaps Slack), as this is not really an issue and more of a feature suggestion / improvement.

**Comment by todofixthis** [comment]
I'm starting to see a bunch of issues where users are mistyping their seeds.  I strongly urge you to reconsider this feature (or some other type of seed confirmation feature).

- https://github.com/iotaledger/wallet/issues/132
- https://forum.iota.org/t/can-i-see-the-seed-i-typed-in/2082
- https://forum.iota.org/t/unable-to-access-seed-with-large-balance-please-help-preferably-iota-team/2192

**Comment by posti85** [comment]
I've seen it only works when the seed has exactly 81 characters. Could it be possible for another seed length? It makes sense, because it could have another lenght...
