### ISSUE TITLE
My received address changed automatically

### ISSUE THREAD

**Issue by pascalandy** [iotaledger/wallet#429]
A week ago I had another address. I transferred few MIOTA and they are still showing normally in my wallet. 

Today I transferred few more MIOTA to the same address. 

But, I realized that my wallet is showing a **new** address. 

<img width="810" alt="screen shot 2017-11-05 at 3 54 04 pm" src="https://user-images.githubusercontent.com/6694151/32419033-982fee52-c241-11e7-9321-94b3c25f3f54.png">

Is this a normal behavior? Feels weird to me.

Cheers!

P.S. I'm waiting for the transaction to process.

**Comment by rotilho** [comment]
Every time you make a new transfer a new address you be generated.

You can reuse a address until you expend it (partially or fully), if you do, you should never transfer anything to the old address.

**Comment by pascalandy** [comment]
I wasn't aware of it. Thanks for letting me know. 
I also confirm that my last transfer was received normally.
