### ISSUE TITLE
Seed longer than 81 trytes generates incorrect addresses

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/wallet#43]
If the user's seed is longer than 81 trytes, it appears that the wallet will truncate the seed before using it to generate addresses.

Example seed (82 trytes):
```
TESTVALUE9DONTUSEINPRODUCTION99999VBQBZCEAGHJENC99YGBEDDLHYGLFYESGHCOGQAVEFEECVCNA
```

Output from JS lib:

```javascript
> var IOTA = require('./lib/iota.js');
> var iota = new IOTA();

// 82-tryte seed
> iota.api.getNewAddress('TESTVALUE9DONTUSEINPRODUCTION99999VBQBZCEAGHJENC99YGBEDDLHYGLFYESGHCOGQAVEFEECVCNA', {index: 0, total: 1}, function (error, addy) { if(error) { console.log(error); } else { console.log(addy); }});
[ 'DOODVYDEAKYRCOOLHYGWGEABRZEGYRYSFKNNUJJKJEGUFXW9CLOAOITTIFCLEKIRFNHGRJCHRWTEKMLYW' ]

// 81-tryte seed
> iota.api.getNewAddress('TESTVALUE9DONTUSEINPRODUCTION99999VBQBZCEAGHJENC99YGBEDDLHYGLFYESGHCOGQAVEFEECVCN', {index: 0, total: 1}, function (error, addy) { if(error) { console.log(error); } else { console.log(addy); }});
[ 'VOMHWBGRLFSDPVLWUHUQSGU9VC9RUCZYNZQUZWGDXZMADBSMCQOQRMYLXQVFTBDDREULDX9XHQIYHZNLE' ]
```

When logging into the wallet with the 82-tryte seed, the Receive tab shows the same address as the 81-tryte seed (see screenshot).

<img width="1267" alt="Screenshot showing IOTA wallet with Receive tab displaying incorrect address" src="https://cloud.githubusercontent.com/assets/202040/25686971/1c789642-3038-11e7-886c-6fe6712ad7f6.png">

**Comment by todofixthis** [comment]
Note:  The warning message does indicate that extra trytes past 81 are ignored, but this makes it impossible for users who (accidentally or otherwise) used seeds longer than 81 trytes to recover their funds using the wallet.

Also, I'm aware that [seeds longer than 81 trytes do not increase security](https://forum.iota.org/t/why-arent-seeds-longer-than-81-trytes-more-secure/1278/), but as noted above, users may need this functionality to recover funds sent to addresses from too-long seeds.

**Comment by mezzovide** [comment]
hello, i got my iota stuck because of this, i was created my wallet since early 1.0.0-minus1 which does not have any restriction with seeds password. please help?

**Comment by Legoriffic** [comment]
I just had the same issue, is there any known fix yet?

**Comment by WirelessWarehouse** [comment]
I entered an 81-character seed, but clicking the Address button is not generating an address. Please help!

**Comment by BadCoder666** [comment]
hey wireless warehouse, was our problem resolved?
