### ISSUE TITLE
have downloaded 2.5.3

### ISSUE THREAD

**Issue by baz59** [iotaledger/wallet#439]
Getting invalid response when try to publish proof?I have a new seed - but not moving forwards from here any help?please

**Comment by wonkytonky** [comment]
install 2.5.4 and try again .. let us know if it works

**Comment by baz59** [comment]
hi loaded 2.5.4 - used old seed - new seed , message "invalid response" ?where to from here

**Comment by wonkytonky** [comment]
try to change node

**Comment by baz59** [comment]
cannot connect to remote node message

**Comment by wonkytonky** [comment]
are you behind firewall or somthing?

**Comment by baz59** [comment]
hi no - using chrome will check avast settings

**Comment by baz59** [comment]
tried another new seed same invalid response - other wallets work ok

**Comment by baz59** [comment]
fixed - problem was - needed to find a new host >tools>edit node configuration>choose newbie
