### ISSUE TITLE
Zero balance

### ISSUE THREAD

**Issue by tempogroup** [iotaledger/wallet#442]
Hello,

yesterday I transfered Miota to Wallet but today my balance still shows 0. I have light wallet, 2.5.4. what can I do to resolve this. Thank you,

**Comment by wonkytonky** [comment]
you send from where?

**Comment by tempogroup** [comment]
From Bitfinex, Status there is completed. On Iota wallet is still Pending

**Comment by wonkytonky** [comment]
can you see the transaction confirmed on an explorer ?

**Comment by tempogroup** [comment]
yes

**Comment by wonkytonky** [comment]
can you see the address in your wallet?

**Comment by tempogroup** [comment]
yes

**Comment by wonkytonky** [comment]
then the money should be there, are there any outgoing transactions?

**Comment by tempogroup** [comment]
no

**Comment by wonkytonky** [comment]
change node ..      maybe the node isn't working well

**Comment by tempogroup** [comment]
to which number. Now I have 14

**Comment by wonkytonky** [comment]
14 is good .. but the server take a random server

![image](https://user-images.githubusercontent.com/19390834/32699139-0384f426-c7b1-11e7-88e5-9330494a5c08.png)

**Comment by tempogroup** [comment]
thanks, problem solved

**Comment by wonkytonky** [comment]
nice. please close issue
