### ISSUE TITLE
2.5.4 wallet still has 0 balance and 0 history

### ISSUE THREAD

**Issue by mind-zipper** [iotaledger/wallet#445]
The only transaction I have ever had was putting my initial IOTA into my first IOTA wallet about 5 months ago.  I locked my seed away on separate cold device and NEVER left my seed on my computer.  I checked my balanace about 2 months ago and there was still 3.2 Gi in my IOTA wallet.  Last week, I check my IOTA wallet and there was 0 balance AND 0 history.  So I updated my wallet to 2.5.3, executed 50 re-attachments (addresses)....still 0 balance and 50 transactions with 0 balance.  Yesterday, updated my wallet to 2.5.4 and still 0 balance.  Used Reclaim Tool to create a new seed.  Still 0 balance.  Reattached 50 times to new addresses using new seed.  Still 0 balance and now 50 transactions on new seed with 0 balance!!!  What else is there to do to reclaim my tokens!

**Comment by jasegates** [comment]
DItto

**Comment by akash2504** [comment]
+1

**Comment by azazar** [comment]
+1

**Comment by larrysmith1000** [comment]
It's tough to understand this:
https://blog.iota.org/gui-wallet-phase-two-of-the-reclaim-process-f5913109cf46

But, it looks like they are going to process reclaims tomorrow. Since you hadn't used your wallet for so long, your funds may have been taken into custody by the IOTA foundation to protect your funds from a vulnerability.

I don't know if that means your balance will read zero until they process your claim, but I imagine that is what it means, because they actually have custody of your funds.  The reclaim process you went through, I believe, was a proof that you indeed owned the old seed.

That is what I take out of Dom's post (which is hard to interpret).  If anyone else (Dom) could shed light on this, that would be great.  There are a lot of nervous people out there.

**Comment by brunoforever** [comment]
Same here - I am really disappointed in the way this is done. As far as I understand, Byteball appears to be similar technology, and there are never any issues like this with their wallet - never. 

Ok the IOTA-technology is new and by definition not finished but I cannot understand why there is no proper communication.

Hej - it looks like the money of some people is just gone - which is really scary. And even if you try all that stuff with generating tons of new addresses and claiming to move your funds (which funds - they look like they are gone for the old and the new seed) to another seed, you stiill have absolutely no clue at all where your tokens are, who is in possession of them and if you will get them back.

Why isn't there a proper communication e.g. a message after you've (re-)claimed your tokens that says - thank you for reclaiming your tokens, it will take us approx. 5 days to process this. We will keep you updated....

I still don't know, who has my tokens (is it the IOTA foundation or are they simply gone), am I going to get them back and when I am going to get them back - in what time.

Lesson learned (if I get them back) - I will never use the wallet again - I will put half of my tokens on Bitfinex and the other half on Binance. Hopefully there are other exchanges to come in the future.

**Comment by light233** [comment]
Same issue here.

**Comment by mind-zipper** [comment]
Update - My iota wallet 2.5.4 still shows 0 balance.  BUT I went to my Bitfinex withdrawal history and was able to get the tangle address and transaction id from when I moved ALL my iota from Bitfinex to my wallet.  Then I went to the tangle explorer blockchain ( https://iotasear.ch/) and I put in my transaction id.  I was FINALLY able to see all transactions in that wallet address and all of my iota WAS STILL THERE....scheeeww!!!  There was only one big transaction "in" and no transactions "out".  So I am a little less anxious now, seeing that my iota is still there on the blockchain.  But iota support REALLY needs to get their wallet to work correctly so that people can transact and see their iota again!!

**Comment by dominicdixon94** [comment]
@mind-zipper any luck getting your Iota back in your wallet ?? I seem to be having the same problems that you were having a couple weeks ago SMH

**Comment by mind-zipper** [comment]
Update - I have now generated 116 addresses in my wallet with the old seed and approximately the same number of addresses with the new seed and I STILL HAVE ZERO BALANCE.  At this point, I am just hoping a new wallet is released that actually works!

**Comment by crumrinece** [comment]
@mind-zipper Yes, unfortunately you will need to wait for manual action from IOTA team. I'm in the same boat. When you did step 2 of the reclaim process it should have given you an address. This is the same address that's generated from index 0 of the "new seed" you entered in step 1 of the reclaim process - so don't lose that new seed and don't send from it. When the foundation gets around to processing reclaims, that address you got in step 2 is where they'll send it (so it will belong to the new seed.) 

Unfortunately, they are way past the initial date given to start processing the reclaims, and have not given any indication of when they *will* start apart from "soon."

**Comment by ohrian** [comment]
IOTA is in the process of refunding those accounts with a target date of January 16, 2018. Check IOTA's official blog.

**Comment by wdsadsalgasd** [comment]
I looked today in my wallet and balance is zero. I had 500 coins in it....

**Comment by mind-zipper** [comment]
Update - I keep hearing that reclaims are complete.  So I checked my 2.5.4 wallet using my "reclaim tool" (new seed).  History is now 0 transactions and balance is 0.  I attached to tangle.  Balance still 0. Promoted address. Balance is STILL 0!  I then opened wallet using old seed.  Transactions history and balance is 0.  I repeated the above procedure.  Balance 0.
So thinking that the first reclaim did not confirm,  I used reclaim tool again on the first seed.   Waited a couple of days for the confirmation. Checked this "second reclaim" seed.   Balance 0!  Been waiting for months now.   This is truly ridiculous.  I can still see my iota in the original address using block explorer.  Why can't the wallet find it!

**Comment by wonkytonky** [comment]
block explorer?

**Comment by wonkytonky** [comment]
if the money is still in the original address till today: 
download latest wallet 2.5.7. keep generating addresses .. 

if it doesnt show up  chances are high that your seed is not correct. it's mathematical impossible to not generate the correct  address with a correct seed.

**Comment by mind-zipper** [comment]
You can search the iota tangle addresses using https://iotasear.ch/

**Comment by mind-zipper** [comment]
PLEASSEEE….the “it is mathematically impossible to not generate the correct address if one uses the correct seed” line is a lame, flippant, BS excuse that iota developers want all of us naive users to believe.  Why?...because it is the foundation that iota’s tangle security was built on.

What this argument does not address is that if the address-generation code in the wallet has been changed BY THE DEVELOPERS during one of the wallet releases, there is a chance that the original iota seeds no longer produce the same addresses – hence, funds created in the older wallets will never be found!

So, after reading the facts below, please explain how THIS can happen to me as well as many other tech-savvy, prudent iota holders...(other than the wallets have been thoroughly hosed-up by the developers)

FACTS:

My original seed was firstly written down on a sheet of paper with the first 5 and last 5 characters committed to memory – which is the first step a prudent crypto investor should do.  Then, this seed was put on 2 thumbdrives using a computer that has no wireless capability.  This seed was verified to be the same as the seed on the paper and in my memory.  Then, paper and thumbdrives were properly secured.

This seed was then used to create the first iota wallet (release 1.0.2).  The seed was again verified to be the same as the one on thumbdrive and paper.

Funds were placed into the wallet at address index 1 and index 2. (only 2 receives were done, 3 addresses created total, NO SENDS from this wallet ever).

Pictures were taken of paper seed, thumbdrive seed and first indexes created using this seed (index 0, 1 and 2).
The wallet balances were checked and validated several times over 2 months using original seed from thumbdrive.  No problems, ALL FUNDS WERE THERE.  Seed always verified against paper seed.  Everything in iotaville was hunky dory.

THEN, THE TROUBLE BEGAN WHEN I UPDATED MY WALLET TO 2.5.2.

Suddenly, my original seed shows 0 balance and 0 history.

The 0 history was probably because a snapshot had just occurred….no problem there.

BUT HERE IS MY ARGUMENT – When I began attaching to tangle, THE ADDRESSES FOR INDEX 0, 1 AND 2 WERE NO LONGER THE SAME...not even close.  And I have pics to prove seed correctness, original index addresses, etc!!

I proceeded to attach to tangle 150 times and still 0 balance.  And NONE of the addresses were the same as my original first 3 address indexes created in wallet 1.0.2!!  THIS GOES AGAINST ALL IOTA MATHEMATICAL THEORY AND PROMISES OF SECURITY!!

I tried to Reclaim, still no balance.

Promote, still no balance.

As I have pics of the original 2 addresses that hold my funds, I can still go to the tangle explorer and see my funds just sitting there in their original addresses.
BUT I CANNOT DO ANYTHING WITH THEM THANKS TO THIS CRAPPY WALLET!!

So, going back to your claim that these FACTS cannot happen because it is “mathematically impossible” - How does one explain what DID happen to me and MANY OTHERS….

The security of iota has been founded on the theory that – an iota seed used in an iota wallet will ALWAYS produce the same exact iota addresses (index 0 to index infinity) . 

I have proof to the contrary..

As long as developers don’t change the way iota addresses are produced from the original seed, I would agree that the iotas should remain secure.

Unfortunately, my experience leads me to believe that something has changed in the wallets that compromised many iota holders’ funds!

Update – Loaded wallet 2.5.7. Attached many times….still no balance.  Surprise, surprise!

**Comment by yippykaiyay012** [comment]
@mind-zipper sounds like your memory has failed you, not iota. If the seed you entered is not generating the address you sent to last time, then it's not the same seed. As simple as that.

**Comment by rajivshah3** [comment]
>What this argument does not address is that if the address-generation code in the wallet has been changed BY THE DEVELOPERS during one of the wallet releases, there is a chance that the original iota seeds no longer produce the same addresses – hence, funds created in the older wallets will never be found!

This did not happen. It's an open source wallet, you can check the changes if you want. The address generation scheme has not been changed since wallet version 2.4.0

>I tried to Reclaim, still no balance.

You need to wait for your reclaim to be processed

**Comment by mind-zipper** [comment]
You just made both of my points.
Point 1 - My original wallet was 1.0.2.  And you just admitted that the address generation WAS changed at 2.4.0.  Which now explains why everyone is losing their funds. 
Point 2 - Iota's site said ALL reclaims would be complete by Jan 16, 2018.
Um, hello, it is Feb 12 and still no funds....
