### ISSUE TITLE
Black screen following an attempted replay

### ISSUE THREAD

**Issue by benjamesmurray** [iotaledger/wallet#45]
**Steps:** 
1. Create transaction.
2. Spam network
3. Wait one hour from original transaction and choose to replay
4. Wait 20 mins

**Expected Result:** 
See message confirming Replay completed

**Actual Result:** 
Application Window goes black and no functionality apart from closing is available

**Other notes:**

I'm seeing the wallet go black around 20 minutes after a starting replay. No menu items work at all and I need to exit and reopen. I think the replay is done successfully, as I can see it in the history, but no confirmation is given.
 
I think that the wallet fails when attempting to display the confirmation message.
 
This happened three times in a row last night. Over a period of 5 hours.

Using v2.1.1 on Windows Dell i5

I've replayed successfully in the past about a month ago, so unusual to see this happening consistently yesterday.

Today I've done another replay and this has completed successfully.

One possible related consideration, but needs further investigation: When a TX is replayed, and you want to do a second replay, the user has the choice to replay the original bundle, or the new bundle created as a result of a recent replay. The recent successful replay was done against a new bundle, whereas the previous black screens were done against the original bundle. Please note black screen appears intermittently, and may be entirely unrelated to this.

**Comment by benjamesmurray** [comment]
I noticed this issue happened again during spamming, and so I think the theme of this is intermittent issue is that it appears to be rearing it's head during various activities which are a strain on the machine. Might be a graphics card failure under load which causes the wallet not to display correctly maybe?

**Comment by domschiener** [comment]
I think this is most likely related with an issue of your graphics card. @paulhandy @atypicalprogrammer we should probably be able to detect this in ccurl to prevent this from happening.

**Comment by atypicalprogrammer** [comment]
@paulhandy your feedback is appreciated :)

**Comment by domschiener** [comment]
We are working on a revised version of ccurl. Lets retry this then.
