### ISSUE TITLE
GUI Request:Add alias next to neighbors ip for easier contacts 

### ISSUE THREAD

**Issue by lueyforje** [iotaledger/wallet#46]
pretty self-explanatory
Add alias box next to neighbors ip for easier remember who owns it so can be contacted when there's problems, so we don't need to open our precious notepads = ]

might as well create textboxes per ip, and limit wallet to 9-12textboxes so people won't just add loads of ips.
next to each ip textbox has corresponding alias textbox

**Comment by domschiener** [comment]
@atypicalprogrammer something to look at.
