### ISSUE TITLE
Could not connect to remote node?

### ISSUE THREAD

**Issue by Faarborg** [iotaledger/wallet#486]
Hi 
My wallet says: Could not connect to remote node?
What to do then?

Sonny

**Comment by wonkytonky** [comment]
try anohter node 

the one with low ping should be ok
http://iota.dance/nodes

**Comment by Faarborg** [comment]
Thank you very much for you reply, but i am losing my mind......... :-( 
Been trying to connect my iota light wallet, and the node you have giving me, i can not copy it in and use it? It still says Could not connect to remote node??
This Iota thing is very difficult! 
I have 200 Iota at Bitfinex, but i would like to have them transferred to i wallet instead.........

**Comment by Faarborg** [comment]
Thank you very much for you reply, but i am losing my mind......... :-( 
Been trying to connect my iota light wallet, and the node you have giving me, i can not copy it in and use it? It still says Could not connect to remote node??
This Iota thing is very difficult! 
I have 200 Iota at Bitfinex, but i would like to have them transferred to i wallet instead.........
