### ISSUE TITLE
Upgraded to 2.5.4, Cannot Login/Loading Issue

### ISSUE THREAD

**Issue by sspyue** [iotaledger/wallet#499]
Upgraded to 2.5.4, entered seed, cannot login.  Changed to a node that appeared to be working, but just kept spinning and login was stuck.  Closed wallet.  Tried again to login later and wallet having loading issue. 
 Do not even get the field to enter my seed.  Please help.

![iota](https://user-images.githubusercontent.com/33942268/33189456-a38f92c4-d057-11e7-8273-d0382e7b8c62.JPG)

**Comment by sspyue** [comment]
Problem solved.  Please closed ticket.  Used this node and was able to login and my balance is there:

node03.iotatoken.nl:14265

**Comment by 7Finman** [comment]
TROUBLE LOGGING IN AND OBTAINING COINS.

**Comment by wonkytonky** [comment]
i think you can close ticket yourself .. ?
