### ISSUE TITLE
Can't Transfer Iota - Transaction Pending 

### ISSUE THREAD

**Issue by Goldstatue** [iotaledger/wallet#500]
I tried to send funds to Binance and the transaction has been pending for 2 days already.  I ended up sending a new transaction and that one is stuck.

What is the solution?

BNADFIGHCKPN9BXXHOILDUJBGUQIIDLGSGYMNNVYRIJUGLWIXGABYGXYMOZFTTXUDUKJBLAVXJNCGINPDHQ9YWZONX

**Comment by wonkytonky** [comment]
change weight to 14 and keep reattaching until confirm

**Comment by Goldstatue** [comment]
Hi, Thanks. I tried that several times. Still pending...

**Comment by wonkytonky** [comment]
you can try to use android wallet.. and reattach (replay it's called there i  think)..    just to see if it's your pc or the tx is actual not confirming even trough android app.. which should work fine

**Comment by bartolosimpson** [comment]
Yes, select a different node

**Comment by pascalandy** [comment]
It worked for me by doing this https://github.com/iotaledger/wallet/issues/505#issuecomment-346947770

**Comment by Goldstatue** [comment]
Thanks,
I reattached several times. Changed nodes and changed the weight magnitude from 15 to 14 back to 15. Finally confirmed but the amount is not correct.  I sent 10 Iota and received 0.00001100 Miota.  Not sure what I'm suppose to do.
