### ISSUE TITLE
Network congestion and transactions that are not flowing

### ISSUE THREAD

**Issue by pascalandy** [iotaledger/wallet#505]
I saw this message on binance.com. Is there an official place to monitor this behavior from the IOTA Foundation?

<img width="1532" alt="iota-congestion-b" src="https://user-images.githubusercontent.com/6694151/33215364-73f09ddc-d0fd-11e7-823b-23b5ff187503.png">

Many issues are about the fact that we can't transfer our MIOTA in/out.
This is stressful as we don't want to keep our MIOTA in market exchanges.

ADVISORS &  IOTA TEAM, please jump in Github issues. It makes us very uncomfortable to feel alone in here.

Cheers!

**Comment by bartolosimpson** [comment]
Yes, today Tangle is slowly be patient!

**Comment by wonkytonky** [comment]
congestion is a wrong word..  we actually need more traffic  to fasten up confirmations..

**Comment by pascalandy** [comment]
Thanks for jumping in Gents. Patient, I am. My question remains. 

 Is there an official place to monitor this behavior from the IOTA Foundation?

**Comment by pascalandy** [comment]
Using ccurl version it's now attaching!

**Comment by RonRizzo** [comment]
Guys, I'm having the same problem. It's been 24 hours!  Transaction pending ...

**Comment by RonRizzo** [comment]
Pacalandy, any progress? If so please help.

**Comment by pascalandy** [comment]
I'm in the same boat. My address is attached but the transaction is not flowing :-/

**Comment by lowtempo711** [comment]
I have the same problem.... IOTA deposits to Binance just stays on Confirming 0/1.   Does anyone have any recommendations on what to do?

Confirming（0/1）
2017-11-26 22:27:42
IOTA 136
Address: JAHLR9SOT9OUH9XLIMWNGTUVXXBD9ONNAO9VNIGSLYHFAZL9LAAEYLMB9JNWZQ9DHJEPXRRCHPRIJUJDD
Txid: YCTLPECZITCABXDXYCBAPGFYXHBK9BDNFTZQMONLOIBUDUYOVWAVQPSQTXFXJTZGPACHZYOXKVKNZ9999

**Comment by pascalandy** [comment]
It's been 6 days I'm trying to move my funds from the exchange into my wallet.

Thanks, IOTA advisors for not caring about your early adopters.

**Comment by RabeaWahab** [comment]
Same issue here, trying to move from Binance to my wallet.

**Comment by wonkytonky** [comment]
@RabeaWahab thats on binance.. finex works just fine to withdraw.. so it's not an iota issue but binance issue. i wanted to move my iota out of finex too.. to binnance .;but because binance doesnt allaw withdraws for some reason... i moved it to okex..        the withdraw on finex was done in 5min.

**Comment by wonkytonky** [comment]
@lowtempo711  the tx seems to be confirmed now;. after a bunch of reattachements.. so that seems fine

**Comment by RabeaWahab** [comment]
You are right @wonkytonky , thanks.

**Comment by moogus** [comment]
This is still an issue is the network actually viable?

**Comment by ttoleung** [comment]
Binance says this is IOTA issue to fix and vice versa, are we going to get a fix at all?

**Comment by RonRizzo** [comment]
It's iota 100%.  I'm surprised they're still hosting that shit coin.  Frankly they should delist it. Keep trying...

**Comment by ttoleung** [comment]
Check it out guys, this issue has been fixed!

**Comment by pascalandy** [comment]
I don't see this issue as well, but I simply cannot withdraw.
