### ISSUE TITLE
IOTA balance 0....???

### ISSUE THREAD

**Issue by johnvamo** [iotaledger/wallet#506]
Hi, 
I have followed all the ways to get back my IOTAS...I just bought then...send to my wallet and after months came to know there was a huge problem with many wallets...
I am so confused that I need help to follow if I still have any hope to recover my IOTAS:

![actions 001](https://user-images.githubusercontent.com/27964280/33216346-7a5149fc-d101-11e7-918a-59a2a800b7b9.jpeg)

I dont understand why there is a transaction after I send the IOTAS from Bitfinex to the IOTA wallet...I just sent the IOTAs from Bitfinnex... what means the second transaction that appears 2 hours?

Bitfinnex:

Address:
TDGQGJLYOWTJTBAV9DDMWNLWVUEYVMECEYKZUPQNBWVSJXTYNVALIIMHOGDEH9MSATTWOIBBTURNLTGDJFEPEXYFTM

TXID:

NJUR9VOBTO9TPPDMOPDMLXULUHXFDKKZUVQSOOOLYSIN9ZJLLKEBFBBYTF9MESZ9ZVKBRSKJKOYR99999

**Also I am at the list of balances taken to the IOTA Foundation...**
ADDRESS IOTA

TDGQGJLYOWTJTBAV9DDMWNLWVUEYVMECEYKZUPQNBWVSJXTYNVALIIMHOGDEH9MSATTWOIBBTURNLTGDJ

; 18993909114; CURL_NOT_TRANSITIONED . ( it means the IOTAS are still safe and recoverable?)

I made the claiming process...and I got a _**Proof Transaction Confirmed**_ mesagge. 

Then I read the second article about phase two of the claim process, which is not clear to follow:

https://blog.iota.org/gui-wallet-phase-two-of-the-reclaim-process-f5913109cf46

Please any clue what to expect after showing you all my case....

Are still available to recover my IOTAs?

Thanks in advance for the support.

JOHN

**Comment by paulhandy** [comment]
> ( it means the IOTAS are still safe and recoverable?)
Yes

**Comment by paulhandy** [comment]
https://blog.iota.org/gui-wallet-phase-two-of-the-reclaim-process-f5913109cf46
