### ISSUE TITLE
addNeighbor and removeNeighbor doesn't work in GUI

### ISSUE THREAD

**Issue by tiresias54** [iotaledger/wallet#51]
When removing a neighbor in the GUI (Tools > Edit Node Configuration), the message "removed 0 neighbor" appears. If you look at neighbor (Tools > View Neighbors) you see that indeed the neighbor isn't removed. 
It seems this broke addNeighbor too: When you have tried to delete a neighbor and then you try to add another one, you have the message "added 0 neighbor" and indeed no new neighbor appears in the neighbor list.
Note that addNeighbor works when you do it first.

**Comment by atypicalprogrammer** [comment]
Duplicate of https://github.com/iotaledger/wallet/issues/67
