### ISSUE TITLE
mineiota.com = many transactions = login not possible (connection refused)

### ISSUE THREAD

**Issue by RoqueNE** [iotaledger/wallet#512]
Not experienced that myself, but at least 4 people in slack mentioned that exact problem in connection with the mineiota.com page. it seems like as every payout from this page generates one transaction and they really fast stack up. the problem beginns at rougly 300 transactions. from that point it takes to long for the wallet to login and the connection get droped from the node sooner or later (connection refused error).

don't know if it's because to many API-Calls are made or a timeout hits.

see https://iotatangle.slack.com/archives/C1TH3NXJP/p1511620518000028 for example

**Comment by HoneybadgerX** [comment]
I am having the same issue.  FWIW.

**Comment by alessionanes8** [comment]
me too.

**Comment by ScotchWiskey** [comment]
I have had the connection refused message too, but after a few tries I get logged in.

**Comment by wonkytonky** [comment]
as a dirty fix i move my coins out to new seed after 100 200 tx..   it is indeed something that needs to be looked at.

**Comment by ispeaknousa** [comment]
I have the same problem after only 124 transactions. Can't log in at all.

**Comment by O4siang** [comment]
Same issue here, I only got 107 transactions and can't log in.

**Comment by f49888** [comment]
I have the same issue !! 
PLEASE HELP US TO FIGURE OUT!!

**Comment by onemoreitguy** [comment]
Same issue: connection refused after 124 transactions

**Comment by pkkirilov** [comment]
Are there any updates on the issue?
