### ISSUE TITLE
Windows system dependency: Could not load light wallet functionality

### ISSUE THREAD

**Issue by xiongzm** [iotaledger/wallet#52]
On some windows system, the GUI wallet can't work well due to system dependency. The wallet shows " Could not load light wallet functionality". So the user need to download Visual C++ Redistributable Packages(https://www.microsoft.com/en-nz/download/details.aspx?id=48145). After that and restart the GUI wallet, it works fine.

So please prepackage the above package in the GUI package and do auto downloading and installation, or add some hints for users to download and install that package manually.

**Comment by paulhandy** [comment]
The dependency comes pre-packaged with the windows installer of ccurl:
https://github.com/iotaledger/ccurl/releases/
If this was used in the wallet installation process instead of packaging the libraries statically, there would be no need to further package a single-os dependency.

**Comment by paulhandy** [comment]
The dependency comes pre-packaged with the windows installer of ccurl:
https://github.com/iotaledger/ccurl/releases/
If this was used in the wallet installation process instead of packaging the libraries statically, there would be no need to further package a single-os dependency.
@atypicalprogrammer would it be possible to modify the installer to download the latest release from iotaledger/ccurl/releases and install it?

**Comment by atypicalprogrammer** [comment]
@paulhandy : can't test, is that a setup file (with gui?) -- is there a --silent option if so? For linux / mac, we need to continue to package the libs statically?

**Comment by atypicalprogrammer** [comment]
@paulhandy any update?

**Comment by atypicalprogrammer** [comment]
Actually we are already installing visual c++ redistributable package as a dependency:

```
	${If} ${RunningX64}
		NSISdl::download "https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe" "visual_cpp_redistributable.exe"
	${Else}
		NSISdl::download "https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe" "visual_cpp_redistributable.exe"
	${EndIf}      
```

@xiongzm so did you run an old version of IOTA Wallet or something? Don't these files work for you? Uninstall and try again, please. Also tell me your windows version. Closed until reply.

**Comment by xiongzm** [comment]
The past several days many guys still asked me for the help on that problem as they were installing the wallet at least for the version 2.2.3~2.2.5. So I wrote an installation guide at http://www.iotachina.com/iotaqianbaoanzhuangjiaocheng.html for them to download the visual c++ redistributable package. I can confirm some of them are windows 7, and I think they may also have windows 8 or 10.
