### ISSUE TITLE
I do not want to lose my Iotas! Please!

### ISSUE THREAD

**Issue by Sebastian137** [iotaledger/wallet#525]
Hi
I can not open my wallet on the mobile, I get a message: "Network error could no conect to remote node". And I can not open my wallet on the PC either, I get a message: "Connection Refused". Please Helpme! Thanks.
Sebastian from Argentina.

**Comment by Sebastian137** [comment]
Hi
I can not open my wallet on the mobile, I get a message: "Network error could no conect to remote node". And I can not open my wallet on the PC either, I get a message: "Connection Refused". Please Helpme! Thanks.
Sebastian from Argentina.

**Comment by th0br0** [comment]
You are not at risk of losing your funds, please contact me on Slack via @th0br0 - these issues are supposed to be for proper bug reports ...
A new wallet to address this issue will be released this week.

**Comment by Sebastian137** [comment]
Ok thank you. I will wait for a new wallet.
