### ISSUE TITLE
$$$ Thousands of Dollars Stuck on The Tangle $$$

### ISSUE THREAD

**Issue by RonRizzo** [iotaledger/wallet#526]
No confirmations 
No help 
No input from the Iota team 
Faulty Wallet 
Faulty Blockchain
 What the hell is going on Iota? 
I day 6 hours now

**Comment by yippykaiyay012** [comment]
You sound like you have invested thousands of dollars before doing your own full research.
IOTA is beta and improvements are happening all the time.
Reliability will improve with future updates.

If a transaction is showing as pending in your wallet:

Rebroadcast the transaction.
Reattach every so often.
Switch to a different node.
Rebroadcast and reattach again.

Your money is not lost so do not panic.

Spamming the Github with the same issue over multiple posts is not what Github is for.

**Comment by RonRizzo** [comment]
Yeah! obviously i did not dig deep enough with  this company. Lesson lesson
learned. No more AMATEUR projects for me.  Sarcastic as it was, thanks for
your input.

**Comment by RonRizzo** [comment]
yippykaiyay012,

I'm not spamming anything!.  This is a legitimate concern that is affecting
a lot people and i will continue to do daily updates until the problem is
resolved.

**Comment by yippykaiyay012** [comment]
I'm sorry you feel IOTA is an amateur project. I think you need to realize it is beta.
IOTA has a registered non profit foundation and has one of the greatest developers in all of crypto involved. These are early days. Bitcoin was not user friendly to start with, nor Ethereum. Now look at them. If you want to get in on the beta stage then you have to deal with some of the inconveniences. I didn't mean to come across too sarcastic, I understand things can be frustrating. My main gripe was with the multiple issue posts. You only need one. This causes grief for the developers and can slow everything down.

**Comment by arancauchi** [comment]
Also fyi, iota is not a company. So therefore there is no one who is 'in charge'. It is an open source project currently being shepherded by the iota foundation, but no one is 'in control' of anything, besides through consensus.

**Comment by RonRizzo** [comment]
Bullshit - call what you want- just follow the money... A non-profit
organization is still a business.  People still get paid, funds get
disbursed, budgets are balanced, and the  coin\holder's/stock holders are
the life blood of this organization. No investors - no "foundation".

**Comment by spacemanspiff2007** [comment]
Can you post your seed so I can check? ;-)
