### ISSUE TITLE
ALL IOTA ACCOUNTS  SUSPENDED ON BINANCE!!! 11/28/2017

### ISSUE THREAD

**Issue by RonRizzo** [iotaledger/wallet#535]
WON'T BE LONG BEFORE THIS GARBAGE COIN IS DE-LISTED FROM THE EXCHANGES ... YOU BETTER SELL BEFORE THIS COIN TANKS.  
![shut down](https://user-images.githubusercontent.com/33988824/33332376-fd8bc940-d418-11e7-997b-5757a6dcb390.PNG)

**Comment by th0br0** [comment]
This does not belong on the wallet issues. Thanks.

**Comment by RonRizzo** [comment]
It is a  "Wallet Issue" because people can't move their iota's if they
decide to buy or sell by sending their coins to or from the exchange.
Where the hell where you when i was having all sorts problems with the
wallet and and the confirmations? Why don't you make yourself useful and go
help  some of those people who can't access their coins!  You've got a lot
of dam nerve Andreas C. Osowski.
