### ISSUE TITLE
UX/UI - balance text overflowing textbox

### ISSUE THREAD

**Issue by alon-e** [iotaledger/wallet#55]
when expanding the balance value in the wallet (clicking the value)
the text overflows (see image)

![image](https://cloud.githubusercontent.com/assets/25587995/26426441/3a045480-40e1-11e7-9ac3-8dad4be92271.png)

offered solution: dynamically change font size to match textbox.

btw, while value is expanded, switching to "send" & then back to "balance" resizes the textbox to fill the whole text:
![image](https://cloud.githubusercontent.com/assets/25587995/26426550/c921a5d2-40e1-11e7-8ce0-3bf217545805.png)

**Comment by atypicalprogrammer** [comment]
Thanks, fixed.
