### ISSUE TITLE
How to find transaction hash for https://iotasear.ch/

### ISSUE THREAD

**Issue by 0xjacobb** [iotaledger/wallet#555]
After the update to 2.5.4 I have the same problem as many other users, that my balance is 0. I've tried different nodes, different setups, two times the reclaim tool nothing helped (still a lot of pending verifications). 

Then I have found the info to this https://iotasear.ch/ tool here on GitHub. 

How could I now find a valid transaction hash or an address, which proves me, that I am still in possession of my IOTA?

**Comment by wonkytonky** [comment]
first try to generate a lot of addresses (as much as you had before the 2.5.4-) update..

**Comment by 0xjacobb** [comment]
I did that does not helped. Because of that my idea was to find out if my IOTAs are still under my control or still referred to my address (using the iotasear.ch tool...)

**Comment by wonkytonky** [comment]
chances are high your seed is not correct then.  if you cannot generate the correct address .. 

double check if your address is in : https://ipfs.io/ipfs/Qmeb4B5AEi5MWTreKPRtufBFRFWRVTpZkBpX6FeaXCAe3B
just to be sure

**Comment by 0xjacobb** [comment]
To be honest, I don't know which of all these addresses I have generated is the correct one. Should I login to the older Wallet  Version with my old seed or with the new Wallet and the new seed (balance is 0). 

Actually I am doing a reclaim (second time) with the reclaim tool.
