### ISSUE TITLE
failed to send txs with long decimal point (Ti)

### ISSUE THREAD

**Issue by alon-e** [iotaledger/wallet#56]
attempting to send 1.1111111111 Ti fails:

![image](https://cloud.githubusercontent.com/assets/25587995/26426944/66eb6c8e-40e3-11e7-8947-c68e37fd9e81.png)

however, sending the same value in Gi (1111.1111111) succeeds: 
![image](https://cloud.githubusercontent.com/assets/25587995/26426987/890d4242-40e3-11e7-8d93-19cac66ad83e.png)

**Comment by l3wi** [comment]
@alon-e have you experienced this with all long decimal transactions or only this particular instance?

**Comment by nicoschtein** [comment]
I've had this issue too.
To send `12.3456Gi`, I had to send `12Gi` and then `345.6Mi`

**Comment by atypicalprogrammer** [comment]
Error in iota.lib.js, will be fixed soon.

**Comment by rajivshah3** [comment]
This issue seems to have popped up again for around 5-10 users. This picture was posted by a slack user:
![image](https://user-images.githubusercontent.com/19519564/30837116-9dfef1f6-a230-11e7-9bac-9089b370b754.png)

**Comment by rajivshah3** [comment]
Another user reports that this was encountered even while sending whole number amounts (1Gi)
