### ISSUE TITLE
sending a decimal point value shows a cryptic msg

### ISSUE THREAD

**Issue by alon-e** [iotaledger/wallet#57]
attempting to send 1.1i:
I get a cryptic message "Invalid Transfers Object":
![image](https://cloud.githubusercontent.com/assets/25587995/26427513/b2415d7c-40e5-11e7-881a-fc26e6249f5e.png)

**Comment by atypicalprogrammer** [comment]
This seems to return invalid value input (correct) on the most recent version, however it is related to issue https://github.com/iotaledger/wallet/issues/56 so will be fully fixed together.
