### ISSUE TITLE
Could not put in seed in 2.5.4 - no input mask

### ISSUE THREAD

**Issue by 0xjacobb** [iotaledger/wallet#570]
![bildschirmfoto 2017-11-30 um 22 11 43](https://user-images.githubusercontent.com/32514554/33455183-905fe20c-d61b-11e7-9548-4f42d498d777.png)

No input mask in 2.5.4....

**Comment by wonkytonky** [comment]
change node

**Comment by 0xjacobb** [comment]
Thx for your help again does not helped. I am really curios about this node thing. I‘ve changed to several nodes several times with several addresses

**Comment by wonkytonky** [comment]
have you tried with another seed an see if it works?.. there's a bug i think when one seed/address is used too much..   a  ddos protection thing

**Comment by jstillings1** [comment]
The wallet has to connect to the tangle node before displaying the seed log on.
Hit tools. edit node configuration.
Change Node to custom and use this one.
https://iota.thathost.net:443
