### ISSUE TITLE
sending a transaction with long tag - cryptic msg

### ISSUE THREAD

**Issue by alon-e** [iotaledger/wallet#58]
attempting to send a transaction with a long tag ('q'x28),
I get a cryptic message "Invalid Transfers Object":
![image](https://cloud.githubusercontent.com/assets/25587995/26427710/9fa5678e-40e6-11e7-8b73-e47f7f30ceb6.png)

would expect a "tag is too long"  / "tag is invalid"

**Comment by domschiener** [comment]
Will throw more explicit errors in latest iota.lib.js
