### ISSUE TITLE
UX/UI enhancement: send/receive arrows aren't clear

### ISSUE THREAD

**Issue by alon-e** [iotaledger/wallet#60]
I can assume an arrow pointing to the left is a receive tx &
an arrow pointing to the right is a send tx.

but this seems to be a cultural thing (for example right-to-left languages may interpret this differently) 

![image](https://cloud.githubusercontent.com/assets/25587995/26427936/acc0cd7c-40e7-11e7-8faf-b7585f8743b3.png)
I think there should be a color cue as well;
for example red for send & green for receive:
![image](https://cloud.githubusercontent.com/assets/25587995/26428086/6da8db10-40e8-11e7-98c7-08002cdde74f.png)

or maybe even a "-" (minus) sign on sent transactions.

**Comment by alon-e** [comment]
edit: as proof of these arrow directions being a cultural thing.
I interrupted them in-correctly above.
(I write in a right-to-left language :) )

after reviewing bundles I see this is the opposite:
an arrow pointing to the right is a receive tx &
an arrow pointing to the left is a send tx.

**Comment by atypicalprogrammer** [comment]
Thanks, fixed!

**Comment by nicoschtein** [comment]
I know this one is closed, but what about adding `(10)` for sending and `10` for receiving. I think it is an accounting thing that means negative amount.
