### ISSUE TITLE
Connection Refused On Every Node

### ISSUE THREAD

**Issue by stodium** [iotaledger/wallet#608]
I'm trying to log in with my seed but I keep getting the error 'Connection Refused'. I literally tried every node that was available within the drop down menu and none of them worked. When I tried generating a brand new seed and logging in, it worked without an issue.

Is my current seed that has all my funds in it corrupted? Did I just lose all my money? This is very frustrating.

**Comment by luckr0** [comment]
im having the same issue

**Comment by Gearbrylls** [comment]
Have you updated to the latest version? 2.5.4

**Comment by stodium** [comment]
yes i am on 2.5.4, this is the oy version I’ve used as I’m a relatively new IOTA holder.

**Comment by kons233** [comment]
I also have 2.5.4 and cant connect on any host, sometimes it says cant sync, sometimes connection refused'

**Comment by mxsndp** [comment]
I am also running GUI wallet version 2.5.4 it's throwing error "connection refused" on every node.
Nor is the android wallet working.

**Comment by jstillings1** [comment]
Your tokens are not kept in the wallet. The wallet accesses tangle and sums all non zero addresses that are a derivative of your entered seed + the selected curl implementation.

I am assuming you are running the wallet in Light mode, other wise is your running in a full node mode your required to have a static ip

**Comment by mxsndp** [comment]
In any case wallet should be accessible via seed yet I am not able get into wallet.

**Comment by stodium** [comment]
Well that's a little reassuring. Al though I probably won't get over this feeling until I see the funds with my own eyes lol.

I haven't upgraded a wallet before. So when the new version comes out with an update, is there any complicated process to upgrading the wallet? Or simply delete the previous wallet and redownload the new version? 

Thanks!

**Comment by kons233** [comment]
Update: guys I connected to host "http://node02.iotatoken.nl:13265" (its one of the listed hosts), min weight magnitude 14, Webgl 2 Curl implementation ( to get there click tools, edit node configuration, 

it shows my full balance without problem

**Comment by jstillings1** [comment]
The rumor is there is a spam attack going on atm causing the lack of connections.
You can view it here https://tangle.blox.pm/

**Comment by kons233** [comment]
whats atm?

**Comment by stodium** [comment]
at the moment ^^

**Comment by stodium** [comment]
also the host "http://node02.iotatoken.nl:14265" still ended up giving me the same issue. I'm just gonna assume it's the spam attack for now.

**Comment by kons233** [comment]
weird I am reconnecting without issue,,,,https://tangle.blox.pm/ looks so crazy right now

**Comment by mxsndp** [comment]
"http://node02.iotatoken.nl:14265" not working for me

**Comment by kons233** [comment]
Update: although I am able to connect and view my balance, I get a request error whenever I try to send, or attach to tangle.

**Comment by RamaDL** [comment]
https://github.com/iotaledger/wallet/issues/558

**Comment by andrewrgallimore** [comment]
Same issue here. Only since this morning though. Is this normal? The blue line is the empty (i.e. non-value, no MIOTA) transactions...
<img width="800" alt="screen shot 2017-12-05 at 10 53 07" src="https://user-images.githubusercontent.com/31229765/33586579-565fb8da-d9ad-11e7-8b29-4c0a58fbb455.png">

**Comment by seajarman** [comment]
Similar issue. I have been trying to check my IOTA balance in my wallet and haven't had any luck. It either takes a long time to load and then says the connection is refused. Sometimes it automatically says connection refused. But either way I haven't been able to access. Is the security better on the IOTA light wallet versus the exchange? Not being able to access it and being new to this has me worried.

**Comment by andrewrgallimore** [comment]
The IOTA tangle is currently under a massive spam attack - thousands and thousands of zero-value transactions that are deliberately clogging up the network. See them here: https://thetangle.org/live

Remember, your IOTA is always on the tangle, never actually on an exchange or in a wallet as such. The difference is only who has access to the key (seed). So you shouldn't worry about this, as long as your seed is secure, your IOTA is safe, even if you can't see them at the moment...

**Comment by seajarman** [comment]
I tried switching hosts and then switching back to my usual one and it did end up loading for me. Thank you for the heads up about the spam attack.

**Comment by stodium** [comment]
Glad to hear some of you guys are able to log back in!

I just tried every node again and still get the same error. Now that I think about it, not sure how the massive spam attack would effect me directly seeing as how if I create a brand new seed I'm able to log in just fine. Why would the spam attack only congest those seeds with funds associated to it? Maybe I'm not understanding it completely.

**Comment by jstillings1** [comment]
The acceptance of the seed is done local. By using a new seed you are bypassing the Check my balance call which is where your log in with a funded seed is having the issue with the spam attack.

**Comment by stodium** [comment]
Finally able to log back in. However I got stuck with the 0 balance issue now.

I've been generating new addresses and attaching it to the tangle for the past hour now with no luck. Should I be worried that it's taking this long? Should I just keep going until I see something or will exiting my wallet and relogging in tomorrow cause anything to happen. I also tried switching around a couple nodes as well. Not sure what to expect, anybody whose gone through this just out of curiosity how long did you spend doing this process until a balance showed up?

**Comment by andrewrgallimore** [comment]
I'm also not seeing my full balance (not all my addresses are showing). As I understand it, it's fairly common if you switch nodes that the node you login to won't have all of your addresses and you'll have to go through this process of reattaching until they appear (I only have 6 addresses so it's not so bad for me, but some people have hundreds...). However, I'm just gonna wait until this spam attack is dealt with and then login. Your IOTA is safe as long as your seed is secure....

**Comment by stodium** [comment]
is there anyway to check whether your seed has been compromised or not? At the moment I have no history showing so I'm not sure where else I would check.

**Comment by andrewrgallimore** [comment]
Search for your latest address here: https://iotasear.ch/
Just paste your address (NOT your seed!!) into the search box and you'll see the balance on the address...

**Comment by mxsndp** [comment]
I don't think there is a way to validate seed, no need to tell you but DON'T post your iota seed anywhere, just give it some time, it may resolve soon, I wonder if there is any word from Iota team regarding this matter.

**Comment by andrewrgallimore** [comment]
IOTA team are fully aware of the attack, which has now been stopped:
![screen shot 2017-12-05 at 16 21 59](https://user-images.githubusercontent.com/31229765/33595534-c75acb3c-d9db-11e7-9a13-c836dc0ad5ea.png)

**Comment by onemoreitguy** [comment]
I can see the balance and all the 143 transactions. Just cannot access throw the wallets :(

**Comment by stodium** [comment]
update: 

logged out because my balance remained 0 after almost 2 hours of reattaching to the tangle. Tried to log back in later. Back to square one with the 'connection refused'. Seeing as how the spam attacks have stopped now, I don't think that was the cause of the log-in issues (I could be wrong however). If anyone has any update please share when you get the chance.

**Comment by mxsndp** [comment]
I was able to check login and check balance(1 iota) in android wallet via another iota seed created before but when I try to login to wallet via seed which contains my actual balance it is giving error.
What is going on ?

**Comment by onemoreitguy** [comment]
a lot of people on the same boat @mxsndp  :(

**Comment by Acatorn** [comment]
I have that probleem too. Is there any chance Iota team respond what can we do? We shall wait or am I missing something?

**Comment by Acatorn** [comment]
Ok, managed to log in after two days... It really seems that there is lack of public full nodes and a whole system is under huge load... I hope it will get better with further IOTA development (pssst, developers, it's an urgent matter:)

**Comment by bberish** [comment]
Guys, use this node: https://potato.iotasalad.org:14265 

I had the exact same issues... but I used this node, it took about 30mins to login, but I got in and saw my funds accurately. I did not transact on here but apparently it is possible.

**Comment by andrewrgallimore** [comment]
I did the same (used Bitfinex node though)... I found that patience is the key here... took 30-60 mins to log in but just left it going and didn't shut down and try another node... eventually it logged in and all is well, balance is correct.... :)

**Comment by anomaly15** [comment]
Can confirm that https://potato.iotasalad.org:14265 does work, takes a while to connect but does work.. can bypass the connection refused issue

**Comment by onemoreitguy** [comment]
Just to summarize and let everyone to understand:
ISSUE: users are getting connection error when trying to sign-in
CAUSE: wallets with a significant amount of transactions are disconnected after awhile by the nodes. There is a limit defined that prevents large amount of data transfers (max:1000).
WORKAROUND: (a) install a full node (or find one). (b) Define on the ini file the following parameter MAX_REQUESTS_LIST=10000. (c) connect the wallet. It takes more than 10-60 minutes for the node and the wallet to process all the records
SOLUTION: wait for a node and wallet releases

Again: I'm not related to the dev team (I'm just a IOTA supporter and enthusiast) and I found this by searching and code reading

**Comment by tarponjohn** [comment]
I already lost a lot of Iota moving it from the exchange to wallet...then have managed to move some more to the wallet and have not touched the wallet for some time...just hodling along ...but trying to checkin and verify all cool and updated recently  ...**find I cannot connect to the node**...tried zillions of things and still not connected....is IOTA going to present an easier to use wallet....there doesn't seem to be a place for basic users (clueless) like me to work with iota comfortably...how the diddly can we expect mass adoption unless it becomes easier to use...no matter how brilliant a concept it is..
Appreciate any basic advise to see my funds and will get them onto an exchange and trade them...

**Comment by battarov** [comment]
I have faced the same issue ( connection refused ) using all available nodes in the lite mode.
I think its not an overload related issue because my other seeds connecting , but it seamed like the wallet blocked after X number of transaction reattach .
because I this issue present after 124 pending reatach of binance transaction to my wallet.
I have 100 Miota in my wallet worth approx 500 usd in the market but if I succeeded to connect to my wallet again then the I think 100 miota costs was : 500 payed in binance and 500 wasted time in searching and trying to connect to nodes ,

**Comment by duffypaul** [comment]
Jan 28 and I still can't get into iota wallet due to failed node connections. Come on Iota, you're supposed to be a tech company can you not get a basic wallet going so we don't have all our investments sitting on exchanges??! It's gotten silly at this point :(

**Comment by Acatorn** [comment]
Guys, use newest version of the wallet (2.5.6) and try this node:
https://potato.iotasalad.org:14265
Also set Curl Implementation to CCurl (at least I did it and it works).
I connect to my wallet using above configuration and it works fine but it takes about 10-20 minutes to connect (patience is a virtue here, go get some tea in a meantime;)

When you scroll up you will see that I had the same problems as you. Don't panic. As long as you didn't generate your seed on some random website, your funds are safe and you have full control over it:)

I wait for Trinity wallet, which will be official, easy to use and fast. Hope we will see it soon:)

**Comment by duffypaul** [comment]
Thanks. I am already using the latest version of Iota, and when I try the node you sent I get an "invalid node" error. At this point I'll just wait for the Trinity wallet, and pray that the exchange isn't hacked in the meantime. I'm not sure if keeping them on this current wallet is any safer anyway. Do you know of any release date for Trinity?

**Comment by Acatorn** [comment]
Unfortunately, I don't know the exact release date. All I know is that it will be released at the beginning of this year (for me beginning means 28th February, max). 

As long as you generated seed on your own it's completely safe to store funds even on current wallet. Don't let the FUD get you down, current wallet is safe, it's just not convenient enough to use. Still, I prefer to store my funds on that wallet rather than any exchange.
 
Hmm... for me https://potato.iotasalad.org:14265 works perfectly. Are you sure you didn't make a typo or something?

**Comment by Acatorn** [comment]
Pardon me, the newest version of current wallet is 2.5.7 (https://github.com/iotaledger/wallet/releases). It was released yesterday after snapshot.
