### ISSUE TITLE
Reclaim tool not working - ERROR: Invalid tail transaction supplied

### ISSUE THREAD

**Issue by habsworld** [iotaledger/wallet#624]
Using wallet version 2.5.4 on Mac.

After entering my old and new seeds in the reclaim tool, the GUI is displaying this:

Proof transaction is pending
Transaction hash: UAEZMGITIMMOXENABIHLGNNUAUCIZOFZSM9ROSIMNDLDZZUBUVPDJDSUCMTBCREHPHZVKISYSYDU99999
Please wait for the confirmation of the proof transaction and make use of the reattach button if it is pending for too long. A proof is only accepted once it's confirmed.

Left it running overnight, now when I try and press re-attach, I get this error: Invalid tail transaction supplied

Any ideas?

**Comment by kons233** [comment]
Basically nothing is working for anyone right now, so you're not alone, hopefully its up and running soon.

**Comment by habsworld** [comment]
Great - thanks for the info - will try again in a day or so then :-)

**Comment by arasr** [comment]
I have been having this issue from a couple of weeks with one of my reclaims as well. Lots of people on slack with this issue as well.

**Comment by KhanhDam** [comment]
Is there any solution for this? I could have bought a house yesterday if my wallet showing my iota.

**Comment by habsworld** [comment]
I still can't do anything, anyone have any luck transferring tokens from one seed to another?

**Comment by dnorth** [comment]
This is before the Reveal transaction is confirmed, and after discussing this with people on the IOTA slack channel I discovered that it happens in certain cases where the reveal transaction is reattached multiple times.

This is a bug with the current wallet that will be fixed in a newer version of the wallet.

@habsworld @KhanhDam  @arasr for now, I have been able to resolve my issue by building the wallet directly from this PR that was submitted by one of the IOTA devs, and reattaching from this new build:

#516

If you're not familiar with how to do this, then you can just wait until the newest wallet is released for this to be resolved or reach out to @chrisdukakis who helped me. Good Luck!

**Comment by KhanhDam** [comment]
@dnorth You bring me hope my man!

**Comment by KhanhDam** [comment]
Just one more question I have for you since you're the one who knows things. Am I forced to upgrade my wallet? I mean can I uninstall 254 and install 253 or 252 where I can (maybe) reclaim my iota? Thanks.

**Comment by kons233** [comment]
I don't think it would connect

**Comment by kons233** [comment]
but try if you like

**Comment by dnorth** [comment]
@KhanhDam as long as you have your wallet seed, it shouldn't matter if you need to uninstall/re-install wallets. But I know the wallet app (in my experience) doesn't let you add a new wallet from a seed so you'll want to do it from a computer.

Does that answer your question? Maybe I misunderstood.

**Comment by KhanhDam** [comment]
@kons233, @dnorth Thanks guys, I meant is the wallet update is forced or I can stay using my old version. But you guys have answered me more than enough. Appreciated it.

**Comment by habsworld** [comment]
Can someone send me an invite to the slack channel please so I can chat to a dev and get my seeds transferred over please so I can reclaim my coins?

Many thanks,
H

**Comment by KhanhDam** [comment]
@dnorth Man, it works! Now i'm waiting for the reveal phase. Big thanks to you with #516 pointing out for me. But with the not-working-wallet I've made several reclaim with different new-seeds, so what would my iota transfer to, the first one I made or the first one confirmed(should be this)? Another question is: the 0 index of the new-seed (reclaim confirmed) already has an address (which is generated by me to test), if the iota transfer from my old seed, can it go to the 0 index and erase the current address or it'll be blocked?

**Comment by dnorth** [comment]
@KhanhDam hopefully with the reveal phase already rolling out, you should be seeing your iota back  (I got mine!). 

If not, based on the scenario you described  (several reclaim with different new-seeds) your address might be in this list: https://blog.iota.org/claims-and-reclaims-finalization-e692844c505a

If so, you'll need to make sure to reach out to the iota foundation: contact@iota.org with the addresses you're trying to reclaim from. 

About the generation of a new address... I believe you are OK unless you have transacted to that 0 index address. Don't quote me on that, but that's how I understand it. Good luck :)

**Comment by habsworld** [comment]
Got my tokens back, can see them in the wallet now :-)

Thanks to all that helped, and good luck to those still waiting to reclaim them, have faith you will get them back :-)

Thanks,
Habs.

**Comment by habsworld** [comment]
Closing this issue.
