### ISSUE TITLE
1 iota test send to Bitfinex results in strange tangle ... getting stolen? --- please help with response

### ISSUE THREAD

**Issue by mnartnik** [iotaledger/wallet#627]
Hi,

I bought 1.2+G on Oct 11th and transfered it to Wallet 2.5.1.

Yesterday I upgraded to 2.5.4, generated few new addresses and my balance showed up. Everything OK so far.

I tried to send 1 iota as test transfer back to Bitfinex and transaction stayed in pending. Based on other suggestions I did several reattachments with same result. I can see -1 transaction in wallet. What worries me is strange transaction log on the tangle, showing as if complete balance was requested to be sent out:
![capture](https://user-images.githubusercontent.com/26599497/33629441-571a540e-da04-11e7-9cb3-957fee977322.JPG)

https://thetangle.org/address/UQHVSQFBOQAL9FMQMTVOBUZWGBDQINKKQEVVAI9OKTWGYRXVDWSOPAJXTEZGYFLEBKJNLS9UXENMCXVXW

https://iotasear.ch/address/UQHVSQFBOQAL9FMQMTVOBUZWGBDQINKKQEVVAI9OKTWGYRXVDWSOPAJXTEZGYFLEBKJNLS9UXENMCXVXWDSPTWQXEY

Please, explain me if I should be worried and real help or is something that it will get sorted ones transactions get confirmed?
Or maybe sorted with new wallet release?

Thanks
Matjaz

**Comment by gitdisrupt** [comment]
Any luck? I believe my account was hacked in attempt to send to Bitfinex.

**Comment by mnartnik** [comment]
After discussion with iotatangle slack team, I see that this is normal operation. Full amount is always transferred out from address. In my case 1i to Bitfinex and remaining to my new address. Old address is 'closed', that's why it is striked through. Transaction still in pending though.

It is nicely described motion jpeg here: http://iotasupport.com/how-addresses-are-used-in-IOTA.shtml
