### ISSUE TITLE
Unable to switch to light wallet mode if I try to start a full node w/o neighbors

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/wallet#63]
1. Start IOTA wallet for the first time.
2. At the "Choose Wallet Type" dialog, click Full Node.
3. Click "Start" without entering any neighbor URIs.

The "Switch to Light Node" button is disabled, so the only way to get back to the "Choose Wallet Type" dialog is to quit and relaunch the wallet.

![Full Node configuration dialog, showing "Switch to Light Node" button disabled](https://cloud.githubusercontent.com/assets/202040/26524290/ba01c3d4-42f3-11e7-8bb6-7a5a19bde615.png)

**Comment by atypicalprogrammer** [comment]
Fixed (in next build).
