### ISSUE TITLE
[OSX] Testnet GUI shows placeholders instead of translated copy.

### ISSUE THREAD

**Issue by nicoschtein** [iotaledger/wallet#65]
After opening the GUI on OSX for first time and setting Spanish, then closing, and reopening it, I get this:

![gui_iota_placeholders](https://cloud.githubusercontent.com/assets/1649257/26532952/f424247e-43e5-11e7-8e8d-05ebf7b87bc3.png)

![gui_iota_placeholders_2](https://cloud.githubusercontent.com/assets/1649257/26532981/a5788a3a-43e6-11e7-9f86-5274946aa233.png)

Release https://github.com/iotaledger/wallet/releases/tag/v2.2.2-testnet

**Comment by atypicalprogrammer** [comment]
Cannot reproduce. I've added an option in the view menu bar item, to toggle the web developer tools. If you can rebuild (from source), please do so and see if there are any javascript errors in the web console. Otherwise, wait for next build.

**Comment by chrisdukakis** [comment]
#66 fixes this

**Comment by atypicalprogrammer** [comment]
Thank you!
