### ISSUE TITLE
Pending transfer now displays zero balance.

### ISSUE THREAD

**Issue by Azteknician** [iotaledger/wallet#655]
Hi there,

I transferred 1 MIOTA from my exchange to a wallet address as a test (Light Wallet 2.5.4 on Mac) 2 days ago, and it is still pending and now has a zero balance in the history.

- The transfer shows as 'complete' on the exchange and my balance there is reduced accordingly

- Initially the transfer shows up in History in the wallet as 'pending' with the right address details and a balance of 1 Miota, my wallet balance was still 0.

- After a few hours of waiting, logging in and out, changing nodes, reattaching to new 'receive' addresses and general tomfoolery - the balance of the transaction was suddenly 0 

- I now have 4 pending addresses (from reattachments) that all have zero balances including the original transaction address.

It's a tiny transaction but I'm buggered if I know what is going on. 

Can you help me?

**Comment by Azteknician** [comment]
Sorry - you can probably disregard, and close this ticket. The transaction just turned up on the exchange transaction list as 'cancelled'

**Comment by mathiasrw** [comment]
@Azteknician Please close this issue your self as the developers on the repo are busy these days.

**Comment by Azteknician** [comment]
Oh - I didn't realise I could do that.
