### ISSUE TITLE
IOTA Slack Link not working

### ISSUE THREAD

**Issue by SwabianAlien** [iotaledger/wallet#663]
The IOTA Slack Link is not working anymore.

When I click on https://slack.iota.org/ to "Join Slack" I receive:
"Dieser Einladungs-Link ist nicht mehr aktiv.
Bitte wende dich an die Person, die dich eingeladen hat, damit sie dich eventuell mit einem neuen Link einladen kann."

Can you please help me and correct the issue.

Thank you,
Marc

**Comment by wonkytonky** [comment]
https://join.slack.com/t/iotatangle/shared_invite/enQtMjgzNDMwNTc2ODg3LTYwNmFjODNhOThjZDA3OGIzZWIxYjFjYWY4YjAzYjg1NDVlMGVkMWE3N2EyODRiY2UyYmI5OWI4ZDU5MjY0NjQ  try this one

**Comment by ihr-it-projekt** [comment]
This link is also not active.

**Comment by mnns** [comment]
Still not working. Can anyone create a new invite link? thanks

**Comment by alexandr-g** [comment]
Just signed up using: 

https://join.slack.com/t/iotatangle/shared_invite/enQtMjgyODM0Njg0ODY0LTJmNmFhMjBkNzcxZWE2ZmIzODYyZGI3M2ZiYTRlY2M3MDc1NTJlM2I4YTFjZDQ3MjFjZjMzNGQwODEyYTZmNDE

**Comment by thesm2** [comment]
@alexandr-g that link doesn't work for me. Is it possible it's a one time link? If so would you mind inviting me? Thanks in advance!

**Comment by gabrieldi95** [comment]
@alexandr-g that link doesn't work for me neither

**Comment by ThomasZwi** [comment]
Found one :) https://join.slack.com/t/iotatangle/shared_invite/enQtMjg2NDA2NDkwMzc0LTEzZGM0ODRlNzQ3YTI4NjIzZWI1YmJkMTBlODk5MjJjOWZmMjI5YTU2YWU5Mjc4Mjk5ZmRlOGE2NDMwYTVkODU

**Comment by Ryczypisk** [comment]
Hey, could any one invite me to this slack channel? any new link?

**Comment by jgonfer** [comment]
I'm also interested to join the Slack channel 😄 Any link available?

**Comment by alexandr-g** [comment]
@Ryczypisk @jgonfer @gabrieldi95 @thesm2 

https://join.slack.com/t/iotatangle/shared_invite/enQtMjg3MDM0NDY1NjE2LTEyYmNmMWU5YTMxN2FmOGIxZWRkMDU2YWUzMWFhYTc0MmJmMDViMWVjZmE2NDljZjY2MWI4Zjg5NDEzMTAwNGQ

Please keep in mind that it is limited to 1000 sign-ups and quickly expires

**Comment by Ryczypisk** [comment]
thanks :-)

**Comment by jgonfer** [comment]
Thanks! Already registered 😄

**Comment by Onspli** [comment]
@alexandr-g Could you post another link?

**Comment by xmabi2** [comment]
There is a new link please?

**Comment by davidjguinane** [comment]
I'd also be keen on a link, thank you :)

**Comment by amaharana** [comment]
Posted links have expired. Request a new link please :) Trying to run a full node.

**Comment by hero5512** [comment]
I can't register on slack. Could anyone help me? thx

**Comment by hero5512** [comment]
@davidjguinane

**Comment by gesaleh** [comment]
Is it possible to Jon slack still?

**Comment by mudakara** [comment]
Can someone please post an active link?

**Comment by rajivshah3** [comment]
https://join.slack.com/t/iotatangle/shared_invite/enQtMjkzNjAxODI4NjI3LTA4ODlkODM4MTQwYWE5ZDJmMDM5N2E3MzA5MDIwNmEzZmEwNmJjM2IwMjlkNTE4YTY5NTQxZWJkYjJjMjNlYmQ

**Comment by mudakara** [comment]
Thanks @rajivshah3 for the link!

**Comment by hero5512** [comment]
Thank you @rajivshah3

**Comment by rip2503** [comment]
how to get an invite for IOTA Slack?

**Comment by BenStolman** [comment]
Invite anyone?

**Comment by robertohuertasm** [comment]
They're moving to `Discord`. Invite here [https://discordapp.com/invite/fNGZXvh](https://discordapp.com/invite/fNGZXvh)

**Comment by andrei5315** [comment]
добрый день,помогите с приглашением iota slack плиз

**Comment by sagniknitr** [comment]
Discord is great!!!

**Comment by andrei5315** [comment]
купить iota приглашение в slack пришлите

**Comment by mafoti** [comment]
Can someone please post an active link?

**Comment by KapitainJames** [comment]
I'm interested is starting a reliable node. Can someone invite me to the slack channel? Jandrews32@hawkmail.hccfl.edu

**Comment by KapitainJames** [comment]
I'm interested is starting a reliable node. Can someone invite me to the slack channel? Jandrews32@hawkmail.hccfl.edu

**Comment by rajivshah3** [comment]
IOTA has moved to Discord. Please use this link: https://discord.gg/6JUTEdw
