### ISSUE TITLE
Debian package "blind"

### ISSUE THREAD

**Issue by wiwwo** [iotaledger/wallet#665]
Using latest `.deb` package, client is "empty".
If i move the mouse around, the pointer changes so that might mean that `css` is broken?
I mean, it must be something related to colors i think...
Going full screen does not makes it better

`Debian GNU/Linux 9.2 (stretch)` with `MATE Desktop Environment 1.16.2` 

![Screenshot here](https://user-images.githubusercontent.com/3930671/33723503-2b5c9dc6-db6d-11e7-88b7-fe98186b666d.png)

**Comment by manojkumar1001** [comment]
Even I got the same issue.

**Comment by javilonas** [comment]
Problem is solved by adding the option --ignore-gpu-blacklist at the start of the application.

**Comment by sandrokensan** [comment]
Yes, confirmed, the problem is solved by the add.
