### ISSUE TITLE
feature request: reflect the --send-limit X flag to gui

### ISSUE THREAD

**Issue by alon-e** [iotaledger/wallet#70]
in latest IRI (1.1.4*) a new feature was added to allow uplink network cap.
this is mostly used by home users & most of them run the GUI wallet.

my request is to allow users to set this flag
--send-limit 2.5 == limit sending to 2.5Mbit/s
(default is a negative number == unlimited bandwidth)

**Comment by atypicalprogrammer** [comment]
Added.
