### ISSUE TITLE
Transaction taking too long

### ISSUE THREAD

**Issue by c35punk** [iotaledger/wallet#722]
Is it normal for a transaction to be pending for 12+ hours? From IOTA desktop wallet -> Bitfinex.
Thanks in advance.

**Comment by Nexima14** [comment]
I think there is a problem in tangle system. Both withdrawal or deposit actions takes ages (my withdrawal time is over 64 hours by now still in process from bitfinex to wallet). Hope it will be fixed soon

**Comment by MrSergK** [comment]
Same problem. Already 45 hours there is a transaction from Bitfinex to the wallet of IOTA.

**Comment by hyper019** [comment]
warte schon 6Tage

**Comment by c35punk** [comment]
I was able to get my TXs through, changed the not on my Light wallet and et voila :)
