### ISSUE TITLE
Dominik, Whats Happening here. My MI Stolen......PLEASE HELP

### ISSUE THREAD

**Issue by FreedomRocks** [iotaledger/wallet#735]
Dominik,

I had 200 MI balance in my Wallet. To my SHOCK i see that my 200 MI has been transfered to seed address Below 

RFDLVAOMDBKZTZILYEWORTXLOAECCBLYQSVFDTTFJOGACYYFSPISNYJXDV9JMC9HKSLDRQLGONGVAKBPXTXTJLLRLD

Is this how you are going to protect your investors. You really need to help us. I have all security running on my computer.....Kaspersky and Malware Bytes Pro. Inspite of all this, it has happened. I have NEVER shared my SEED with anybody and infact i have taken my seed offline. I BADLY NEED YOUR HELP Dominik. PLEASE RESPOND IF YOU REALLY CARE ABOUT YOUR INVESTORS.

**Comment by chus3r** [comment]
@FreedomRocks Why are you putting this comment on Github instead of iota.org? This space is just for wallet software dev. I mean, he might see it, but since this isn't a bug related to the software it will probably get closed.

**Comment by FreedomRocks** [comment]
Chus3r,
I am new to Github. I am sorry, was not aware of this. Apologies.

**Comment by WarrenBuffett7** [comment]
I think it is okay to write all the problems here, due the Forum is closed to new users !! very strange , something goes very wrong here, I missing my wire of IOTAS for 3 days !!

**Comment by maxhq** [comment]
@FreedomRocks Could you please close this issue?

**Comment by WarrenBuffett7** [comment]
Hi folks, I receive today my Miotas ! Looks good now !
