### ISSUE TITLE
Adding a syncing status on top of the page

### ISSUE THREAD

**Issue by Tobo01** [iotaledger/wallet#75]
Many new users don't know how to use mile stone index to measure the syncing status before they start to make transactriions, especially when using the light wallet because they assume that the light wallet is always synced. I suggest to create a syncing status with three status values, not syncing(in red), still syncing(in yellow), and synced(in green) on top of the page for the users to understand the syncing situation.

**Comment by atypicalprogrammer** [comment]
@domschiener don't think this is possible at the moment, right? Closing until further notice.
