### ISSUE TITLE
Iota stuck in pending

### ISSUE THREAD

**Issue by Cryptofomo** [iotaledger/wallet#750]
Hi Iota Support,

I bought some iota 3months ago and put it into the light iota wallet. I tried to send it to my binance account but the transaction is still stuck on pending. In binance it shows, 0/1 confirmed. This has been over 1 week and a half, can anyone assist? Please let me know what information you need from me, and I will provide it ASAP.

**Comment by markoneo** [comment]
Hi Iota Suport team,

My Iota also stuck in pending! I send Iota to Binance and transaction is still on pending obout 1 week. 0/1 confirmed!!! I try two times and max balance i have and strange bouth times with max balance now shows 2 transaction and 0/1 confirmed!

Please help!
[Iota Hash.txt](https://github.com/iotaledger/wallet/files/1553746/Iota.Hash.txt)

**Comment by chus3r** [comment]
Not a bug, recommend closing.

I suggest you go to the support forums to see if they can provide support. Try https://forum.iota.org or https://forum.helloiota.com/Technology/Help

**Comment by Cryptofomo** [comment]
Now the transaction is not showing on my binance account, but in my wallet I am getting this error:
"You are attempting to sign a transaction with input that have an already been used. IOTA uses Winternitz one-time signature (W-OTS) scheme, due to it's `one-time` nature, the security of funds in an address decreases rapidly if you re-sign new transactions using the same key. Please wait for previous transaction to confirm, e.g. by reattaching, before sending another transaction."

**Comment by Cryptofomo** [comment]
This isn't a bug? I sent my iota out of my wallet it has been in pending, but now the transaction is no longer showing on binance. I see it as "pending" still in the history of my wallet. I tried to send it again but now I am getting this error. I also tried reattaching and re- broadcasting. Still no luck .....

**Comment by Alino** [comment]
It's not a bug. It's a feature.
