### ISSUE TITLE
multiple pending transactions

### ISSUE THREAD

**Issue by mr-holmes221** [iotaledger/wallet#757]
I guess my current seed is an old one so I try to move my IOTA's to another. 

So right now I have around 28 pending transactions because of reattaching, rebroadcasting and sending to several addresses.

If I resend IOTA I get the double spending message one the **light wallet 2.5.4 (Mac)** and the **android wallet**

- changed the min weight magnitude from 15 -> 14
- changed the Webgl 2 Curl implementation -> CCurl implementation and back
- changed the nodes several times 
- I tried the trick of Issue #444 / #440 with the android wallet
- used the Balance Finder Tool of this guy (https://github.com/rajivshah3/IOTA-Balance-Finder)
- used the reclaim tool

I appreciate it if you could help me move my IOTA.
_____
Address: 
FICJJQVXLILRTSSSVGBX9SVTFUSAVABDYUDKSFKUOUQMYTJSTTQE99HHJNNVDHTEBESFIEJWWGZPYCJECYVPSJIWQY

**Comment by josecaos** [comment]
Same issue here, transaction has been pending for 15 days now.
https://iotasear.ch/transaction/FSTXPMTZFJGHSSVGWZXQENROCHSPYLDAACNUAHHTOCLO9WHRICPEXXBWMCEXDNGAXWMXWCEYM9LL99999

Now with multiple pending transactions ':/

**Comment by Birkmoe** [comment]
I have the exact same issue, please let me know if one of you find a solution.

bmj@lyse.net

**Comment by thekansasphil** [comment]
Please let me know what you find out- 60+ Reattachments and reattachements of reattachments, new nodes etc. Wallet 2.5.4. to Binance- Binance entirely unresponsive.

Confirming（0/1）
2017-12-09 17:38:28
IOTA 695.304
Address: CPICHSJCGKVSHDSPIKRWRCKDRUSOFTIC9GDPVARARKKHEQMDQENBFCFCSPXBAFVJCLYMZLONNPZITOQLZ
Txid: IEEFAOHZFOWLYXJRKWASNH9TYLEEWJMQ9ZHTRUTXUVSLNEJAYNFYLYWQSCKSHOTNZCADUTVOVM9GA9999

**Comment by markoneo** [comment]
Same problem!!! For 8 days now

**Comment by thekansasphil** [comment]
Talked to Binance- sounds like we are waiting for the new Wallet release…

smh.

I would REALLY like to be trading it right now.  Got in at just around $1

**Comment by maxhq** [comment]
This is a technical issue (i.e. bug/feature) tracker.
You are more likely to get appropriate answers to your questions at https://forum.helloiota.com or https://iotatangle.slack.com.
Could you please close this issue?

**Comment by mr-holmes221** [comment]
[IOTA.pdf](https://github.com/iotaledger/wallet/files/1564730/IOTA.pdf)

**Comment by mr-holmes221** [comment]
That's my status! I think the wallet or I mixed some addresses and now I'm stuck till the next snapshot. Hopefully, I solve this problem, and if so I'll let you know what to do!

**Comment by solidminds** [comment]
Same problem here. Private key reuse, but i didnt even spend a single iota from this seed, only receiving. Now i want to transfer all my iota to an exchange, and i get this weird private key error.
Very bad this. It makes me very nervous. And not really willing to go on with iota. To many bugs, and by the looks of it, no real and fast solutions. Come one devs, fix it!
