### ISSUE TITLE
New/Parallel Transactions not possible?

### ISSUE THREAD

**Issue by pecX24** [iotaledger/wallet#776]
The following is my problem:

I have 60 MI on my Iota Light windows wallet.

I started a transaction of 10 MI to Adress A. This is still "pending" since 2 days.

Now i wanted to start new transactions to Adress B, C and D.
But every time i get the "private key reuse"-error message. 
What´s wrong? How can i send Miotas to several adresses? Is it even possible?
- or is this a bug?

**Comment by wonkytonky** [comment]
reattach the pending one ..    ask help in forums telegram etc.  this is not bug

**Comment by pecX24** [comment]
What do you mean with "telegram" - who can help with that issue?

**Comment by rajivshah3** [comment]
You need to wait until a transaction is confirmed before sending another. Concurrent sending is not possible at this time
