### ISSUE TITLE
Can't download wallet

### ISSUE THREAD

**Issue by digitaldorobo** [iotaledger/wallet#780]
Hi,

Windows 10, Chrome browser. Add blocker off.

I go to https://github.com/iotaledger/wallet/releases/tag/v2.5.4

I click on the v2.5.4 link. I see the bottom left of the browser e.g. 'waiting for github...' and a couple others -- but nothing happens.

Any idea how I can download the wallet?

cheers and thanks

**Comment by wonkytonky** [comment]
works fine here..    try again ..

**Comment by digitaldorobo** [comment]
Hi,

This is very strange. I've tried Wifi and hotspotting, but I still get the same outcome--can't download it. Do you know if it is hosted anywhere else?

cheers

**Comment by wonkytonky** [comment]
ask a friend to download it..  and send you ... you can double check if it is the right file by checking  .. the checksum

**Comment by digitaldorobo** [comment]
Hi,

Thanks again. Just to be certain, am I supposed to click on 'v2.5.4' or download each Asset individually?

See attached photo
![github](https://user-images.githubusercontent.com/34631306/34138871-67d8d2de-e4a4-11e7-9274-bdd0104e421d.png)


Clicking '2.5.4' on my PC and on my android cell phone doesn't go anywhere.

thanks,
Gene

**Comment by digitaldorobo** [comment]
Hi,

My wife tried on her mobile and has the same problem.

Do I have to download each Asset individually?

thanks

**Comment by rajivshah3** [comment]
You need to click on where it says IOTA.Wallet.Setup.2.5.4.exe
