### ISSUE TITLE
When i recieve MIOTA from bitfinex i lost all of them

### ISSUE THREAD

**Issue by s3cr37** [iotaledger/wallet#782]
Hi

Before five days Bitfinex send to me 73.5 MIOTA .he transaction was confirmed from them. 
But when i opened my wallet to check  I have received the MIOTAs i saw that i have 0 MIOTA. Before this i already have 33 MIOTA.

Now im waiting 4 days to recieve my MIOTA , reataching almost every day , but nothing happend. 
This my hash IYQVJFEHMUDWUVJSSLLUGA9QVLY9UFYAKOGWCFTVUVCNJMKXBXWVDAPTJWBAFLD9LEHDAXTWLALGYSVYCVSLXGLFHW

Why i have 0 MIOTA and where is the problem?

**Comment by tukpedro** [comment]
Hello, I searched for your hash at https://thetangle.org/ and it has a confirmed withdrawal of the amount that you said. 

https://thetangle.org/transaction/XPJDSSXGLZKIJANTZAELSCHQFDQXZCHVIY9MT9NIOBJBYBFHLLJHMMORCHECPKTOPGRD9RTJMFFMZ9999

Was it made without your request?

**Comment by s3cr37** [comment]
Yes! It was made without my request.
