### ISSUE TITLE
Transactions pending for over a week...

### ISSUE THREAD

**Issue by c35punk** [iotaledger/wallet#783]
Please do explain what to do since I can't get funds out of my wallet for over a week now... I wanted to trade a bit but sadly this came up... Here's just a fair example:

https://thetangle.org/transaction/BFKQREUPTRDCDPGQVMAQIMCBUUG9DEXUJGAGSOHJVJDGRGBFPXLLKZQCF9OK9CSCTMSEVAQE9HTOZ9999

Thanks in advance.

**Comment by th0br0** [comment]
That bundle confirmed just fine after I just reattached this.
Also, please don't abuse the issues here for customer support. GitHub issues are meant for bug reports.
