### ISSUE TITLE
IOTA DOESN´T APPEAR

### ISSUE THREAD

**Issue by theoppositeface** [iotaledger/wallet#785]
I withdrawn 587.3 Miota form bitfinex to my adress and in the tangle appears that the transaction is confirmed. But when I enter to my wallet the transaction appears unconfirmed so they don´t appear in my total balance :(
https://iotasear.ch/hash/ARVEQGYECYTAZIPGVZLMWWRUKFCANZDTLLHGEFUSMDY9FXUXHATPZRRHPPHZMCYLQHJDZVOKZ99LMOTC9LQHHZWENA

**Comment by yippykaiyay012** [comment]
Try switching nodes. The node you are connected to is possibly not synced. Don't worry though, as long as you have access to that address the iota is safe and confirmed.

**Comment by theoppositeface** [comment]
YEP FIXED. I tried 8 nodes and finally in one they where there... i thought that when it says that the  node is not sync wasnt a BIG problem but it is. thanks
