### ISSUE TITLE
Directions please on how to activate Android IOTA wallet.

### ISSUE THREAD

**Issue by TanzaOne** [iotaledger/wallet#787]
I downloaded the Iota wallet frm Google play, goes by the name of IOTA Wallet (BETA), signed up and signed in but once i' try to connect to tangle explorer network error could not connect to iota.cool network notification appears.

I'm in Guangzhou China how do i do the right Node settings please?

Do you still recomend that i keep on using this version of wallet in my Android device or there is a better one?

How can i acquire some IOTA's?

That's it for now Thanks.

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
