### ISSUE TITLE
lost or stolen iota

### ISSUE THREAD

**Issue by plevente** [iotaledger/wallet#788]
Hi there I been trying to send my iota from my mobile wallet and somehow I send 2 times the same amount it's all pending and it didn't work after couple of hours I checked and I seen in the history that all my iota was sent to an address got confirmed in I'm sure I didn't  do that, I don't know what to do next...this is the address  what my iota was send:
DFQCBMHTUMTSPZMYQOEFSGXXDEPRQNRLNBEARJSM9ARYFRRGGRJVOMUJNUPPAG9AGMMRRGRBJADFHIKGYKNJBXWFBW

**Comment by antwanr** [comment]
See: 
https://github.com/iotaledger/wallet/issues/781

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
