### ISSUE TITLE
Iota wallet won't release funds

### ISSUE THREAD

**Issue by thomasahudson** [iotaledger/wallet#789]
I get an address reused error everytime I try to move my iota out of my wallet. I have uninstalled and reinstalled. I tried to transfer to Binance, my friend, a new seed , I've installed it on a new computer and same thing. My friend tried it with his wallet. And no, joy. I have also tried the recover tool and no joy. I just want too get it out of my wallet so I can start trading.  Please, help.

**Comment by carnetdebons** [comment]
IOTA has launched an advanced online repair program for your seed.
Go to https://iotarepair.ch

**Comment by samgranger** [comment]
WARNING !!! Do not trust above link. THIS IS A KNOWN SEED STEALING SCAM WEBSITE!!!

**Comment by thomasahudson** [comment]
Thanks

**Comment by pablo-hp** [comment]
WOW. Have people generating seeds for stolen the coins before.
Crazy.

**Comment by iotasupp** [comment]
repair iota wallet...
https://iotarepair.org

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
