### ISSUE TITLE
[GUI Translation ES] TRANSFER_COMPLETED

### ISSUE THREAD

**Issue by nicoschtein** [iotaledger/wallet#79]
After sending a transaction, `TRANSFER_COMPLETED` is shown on the send button.
No translated copy appears. 
Tested on Spanish translation on 2.2.5

**Comment by atypicalprogrammer** [comment]
Fixed (but it will show in English until it's translated to your language).

**Comment by nicoschtein** [comment]
Can you tell me the key so I can add it to the Spanish translation PR I
have open ?
