### ISSUE TITLE
can't  attaching to tangle 

### ISSUE THREAD

**Issue by mb100** [iotaledger/wallet#790]
hi
i am trying to attach the address to tangle
but it isn't doing it
i want to buy IOTA from ebay and want to give address to the seller but it isn;t attaching?
thanks

**Comment by pablo-hp** [comment]
Change the nod.
Use: http://node.lukaseder.de:14265
Magnitude: 14
Curl: CCurl Implementation.
See: https://www.youtube.com/watch?v=vVFM0iiVMvU

**Comment by mb100** [comment]
thanks it works
