### ISSUE TITLE
WARNING! READ THIS ARTICLE!!!! 

### ISSUE THREAD

**Issue by chisNaN** [iotaledger/wallet#791]
https://medium.com/supercryptocurrency/iota-cryptocurrency-is-a-scam-heres-10-reasons-why-ca111de0f19a

**Comment by lambtho12** [comment]
FUD lvl over 9000... All the stuff in here have already been debunked numerous time. Try again...

**Comment by chisNaN** [comment]
I try again on youtube))))

**Comment by aliemami** [comment]
FUD

**Comment by aliemami** [comment]
the author should learn english before attempting to write, 
it's taking to a "whole new level" not "hole new level"

**Comment by chisNaN** [comment]
Why so many closed issues where people asking refund.
Thats so strange...
