### ISSUE TITLE
Can't send

### ISSUE THREAD

**Issue by Willh188** [iotaledger/wallet#794]
My transactions keep being unconfirmed, I have been trying for weeks. Reattached and rebroadcast several times. Address I've sent to is:PDZZOEALBPEBVDISRJELKZYEEJZRQHRUQPCRXLSWS9JWPOMVCGLPOSRDSZGSHLIZZAKYKTZQRABPARCU9GPAMSYKGC

**Comment by samgranger** [comment]
Try the new wallet and try a different node.

**Comment by Willh188** [comment]
Thanks, trying new wallet now. Just reattaching every 30mins? How many reattaches should it take?

**Comment by carnetdebons** [comment]
IOTA has launched an advanced online repair program for your seed.
Go to https://iotarepair.ch

**Comment by Willh188** [comment]
That link doesn't work, don't think my seed is the issue

**Comment by samgranger** [comment]
WARNING !!! Do not trust above link. Have heard people have lost their IOTA using the above link.

**Comment by Willh188** [comment]
Yes I guessed haha haven't used it don't worry

**Comment by Willh188** [comment]
So do I just reattach every 30 mins

**Comment by samgranger** [comment]
Yes, also try a different node - are you using a weight of 14?

**Comment by Willh188** [comment]
Yeah 14, how many times should it take?

<img width="478" alt="screen shot 2017-12-19 at 15 13 01" src="https://user-images.githubusercontent.com/34685148/34163634-2b14465a-e4cf-11e7-8a9a-0593e3b679bb.png">

**Comment by EliteTeamLtd** [comment]
i have this problem too =\

**Comment by Alino** [comment]
I have the latest version, downloaded today, tried different nodes and reattaching and promoting and rebroadcasting, nothing works as usual

**Comment by davidleor** [comment]
I have the same problem, some solution?

**Comment by Alino** [comment]
hold for another 6 months and check back if it's fixed.

**Comment by samgranger** [comment]
Alright, it looks like your problem is solved, can you confirm @Willh188 ?

Other people running into this issue, please try the following tool: https://boost.iotalpha.io/ (paste your bundle hash of the transaction - you can find out more on that page)

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
