### ISSUE TITLE
Cant download

### ISSUE THREAD

**Issue by aduringa** [iotaledger/wallet#796]
I cant download the File... maybe im doing it wrong

**Comment by robinbastien** [comment]
@aduringa More info? Did you try installing from one of the releases at https://github.com/iotaledger/wallet/releases/tag/v2.5.5 or compiling yourself?

**Comment by aduringa** [comment]
@robinbastien I mean where do I have to press... I need more info... I tried to compile my self but it didnt work.

**Comment by robinbastien** [comment]
Try visiting the link I sent you, and click the file that corresponds to
your operating system (.exe Windows, .dmg Mac, .deb Debian, etc...).
They're pre-compiled.

[image: Machine]
Robin Bastien
Web Developer
613-801-1350 / 1-888-670-9640
robin@machine-agency.com
machine-agency.com <https://goo.gl/ei8o2u>
[image: Instagram] <https://goo.gl/rOiDSg>   [image: Facebook]
<https://goo.gl/4cjsz7>   [image: Twitter] <https://goo.gl/WfVZyN>   [image:
Get Directions] <https://goo.gl/dG1HoI>
Holiday Hours: We'll be out of the office from December 22nd to January
1st, inclusive. If you need anything urgent during that time, please call
the office and select the emergency option.
We use Slack with most of our clients for the speediest replies. Ask me
about it today! <scott@machine-agency.com?subject=Interested%20in%20Slack>

**Comment by aduringa** [comment]
I did but I cant find that... pls help

**Comment by robinbastien** [comment]
Mac OSX: https://github.com/iotaledger/wallet/releases/download/v2.5.6/IOTA.Wallet-2.5.6.dmg
Windows: https://github.com/iotaledger/wallet/releases/download/v2.5.6/IOTA.Wallet.Setup.2.5.6.exe

---
Once you downloaded and installed, you'll need a private key. You can do:
Max/Linux: `cat /dev/urandom |LC_ALL=C tr -dc 'A-Z9' | fold -w 81 | head -n 1 ` in Terminal
Windows: Use a seed generator like https://ipfs.io/ipfs/QmdqTgEdyKVQAVnfT5iV4ULzTbkV4hhkDkMqGBuot8egfA
