### ISSUE TITLE
Errors in PT-Portuguese translation.

### ISSUE THREAD

**Issue by rafaelstyvie** [iotaledger/wallet#798]
corrected pt-PT translation
[pt-PT translation.zip](https://github.com/iotaledger/wallet/files/1572388/pt-PT.translation.zip)

**Comment by jmrodriguesgoncalves** [comment]
I  can help out with this. I took a quick look and saw some typos/awkward phrasing. If you'd like, I can brush it all up for you, I'm fluent in Portuguese.

**Comment by rajivshah3** [comment]
You can update the strings at http://crowdin.com/project/iota-wallet
