### ISSUE TITLE
pt-BR Translation

### ISSUE THREAD

**Issue by rafaelstyvie** [iotaledger/wallet#799]
rev 0.1
[pt-BR.zip](https://github.com/iotaledger/wallet/files/1573926/pt-BR.zip)

**Comment by pablo-hp** [comment]
Thanks, obrigado ;)

**Comment by pablo-hp** [comment]
Esta tradução em PT-BR ainda contém erros de acentuação e cedilha. Se puderem arrumar será bom também.

**Comment by rajivshah3** [comment]
You can update the strings at http://crowdin.com/project/iota-wallet

**Comment by rafaelstyvie** [comment]
PT-BR Updated.
