### ISSUE TITLE
Wallet 2.2.5 won't open / WIN 7

### ISSUE THREAD

**Issue by alphakanal** [iotaledger/wallet#80]
Hi,
just installed the latest iotaledger version, but it won't work . Once installed double-clicking the shortcut it won't open or it doesn't even start ( strg + alt + del = no iota process is running/started ).
Using WIN 7 / 64bit - any ideas what's going wrong?

**Comment by rennne** [comment]
Hi
Have a similar Problem on Win7. The Icon is there but "IOTA Wallet.exe" is missing

**Comment by atypicalprogrammer** [comment]
32 bit or 64 bit ?

**Comment by atypicalprogrammer** [comment]
Try to run the exe via command line if you know how to, and output the log that you see here.

**Comment by rennne** [comment]
64 bit.
Triedthe installer on the commandline. Just normal behavior there.
The Installer seem to work.

Investigated a bit:
Error 0x80070666: Cannot install a product when a newer version is installed.

It seems that that installer tries to install the visual_cpp_redistributable, fails and stops there, without further installing the wallet

I have 14.0.24215 already installed, the wallet-installer tries to install 14.0.23026

**Comment by rennne** [comment]
PS: there was no output or log on the commandline

**Comment by atypicalprogrammer** [comment]
I meant after installation. What do you mean by "the icon is there"? Did you mean the setup file? 

About that error, is that an error dialog that pops up?

**Comment by rennne** [comment]
The installer tells me that it downloads the visual_cpp_redistributable, after that there pops up a window for a splitt second, and than the setup closes immediately.

I suspected that it tries to launch the visual_cpp_redistributable.exe so ...
I found that error in the log file of the  visual_cpp_redistributable-installer in the install-folder of the wallet.

After I start the installer I get the IOTA-Wallet icon in the start menu, but when I click on it, it tells me that the "C:\Users\ratchet\AppData\Local\Programs\iota\IOTA Wallet.exe" is missing

**Comment by Tachyon2032** [comment]
Having same issue under Windows 10 64-bit.  visual_cpp_redistributable will not install since I already have a newer version installed, however with the installation failing, something is preventing wallet from opening.  I have IOTA Wallet.exe present, but opening it shows activity icon for a few seconds, then nothing.  Nothing in task manager, either.

**Comment by MIOLFE** [comment]
Tachyon2032

I have this issue too under Windows 10.
any suggestions to resolve it?

**Comment by Tachyon2032** [comment]
None yet.  I've tried uninstalling, rebooting, reinstalling, shutting down, etc. in every combination I can think.  I believe it's related to the Java installation, but since I have a newer Java version installed I an not inclined to uninstall it to let Iota install an older version.  Will get on it again this weekend and see what i can do.  

Any suggestions from any devs would be greatly appreciated.

**Comment by rennne** [comment]
As far as i remember, I executed just visual_cpp_redistributable.exe on its own in the admin console manually, afterwards the wallet installer worked fine.

**Comment by Tachyon2032** [comment]
This may be a stupid question, but does the IRI have to be installed before I install the wallet, even if I run the Light wallet?

**Comment by wonkytonky** [comment]
IRI = public node..  run by someone else.. you don't need to install it.      your light wallet connects to such public host. 

running IRI  is only for ppl who know how to run fullnodes

**Comment by Tachyon2032** [comment]
That's what I was thinking, but still trying to figure out why this will not work on my Win10 system.  I really want to buy into and support Iota, but will not until I get a working wallet.  Thanks for the info!

**Comment by mountassir** [comment]
Same issue with windows 10 64bit, the wallet (2.5.4) installs as well as the included MVR 2015 but I can't start it. When I double click on the wallet icon nothing happens, when I run the wallet from the command I get a one line mesage "Quite this instance.". Is there a way to get this to print more logs?

I have another windows 10 machine and the wallet works fine there! I can't figure out what's different between them!

**Comment by mihcis** [comment]
Same issue here! Win 10 64bit and wallet v25.4.

Wallet doesn't start. Console just prints "Quit this instance".

**Comment by mihcis** [comment]
Found solution:
Under "C:\Users\%yourusername%\AppData\Roaming" there was a link "IOTA Wallet.lnk" -- Clicking this link didnt take anywhere, perpahs it was corrupted? Deleting this link solved the issue for me.

**Comment by ManfOo** [comment]
Hi guys,
Same problem here with theses versions : 
- IOTA.Wallet.Setup.2.5.3.exe
- IOTA.Wallet.Setup.2.5.4.exe
- (up to date) IOTA.Wallet.Setup.2.5.5.exe

Everthing seems to install correctly, but when trying to launch the app, it does nothing.

@  mihcis : I don't have any IOTA Wallet.lnk it the AppData\Roaming folder.

Any other ideas ?
