### ISSUE TITLE
IOTA; how to reclaim now?

### ISSUE THREAD

**Issue by Michael8819** [iotaledger/wallet#800]
Dear iota-friends,

I still haven't my IOTA's back. I have followed the previous steps from the reclaim process, which said that I have to wait. 

My suggestion was that this all was solved by introducing the new wallet (2.5.5), but it isn't. Does someone know what to do or when this is solved, so people can have their iota's back?

Thanks in advance friends, kind regards, Michael

**Comment by Tw0Face** [comment]
Hello, I can only tell you that I have the same status. I have successfully used the reclaim tool with the previous version and wait like you for the iotas. The specially created seed is still empty. :-(

**Comment by pablo-hp** [comment]
Are a great chance that you're stolen. Where did you creat your Seed? In any site? Maybe you goes stolen.

**Comment by Michael8819** [comment]
No it is not. There are many many people with this problem. We are all waiting on the team to solve this.

**Comment by TheNec** [comment]
If I understand [this](https://forum.helloiota.com/Topic1242.aspx) correctly then they have just started to process the reclaims yesterday or today. It could still take some time because they need to do it manually.
