### ISSUE TITLE
The Iota Corp can generate more Iota Coins?

### ISSUE THREAD

**Issue by pablo-hp** [iotaledger/wallet#802]
The Iota Corp can generate more Iota Coins? 
Before the genesis, how mutch chance of Iota generate new coins?

**Comment by musaa32** [comment]
its limited, but it must be generated someway.  like btc

**Comment by pablo-hp** [comment]
Btc can generate someway BTC?

**Comment by yippykaiyay012** [comment]
Uch. This isn't an issue for posting on the github repo. Come on man. Iotas full supply was created in the genesis. This was then distributed through an ico. Now the full supply is simply bought and sold through exchanges. There will be no new coins created. Bitcoins are mined every 10 minutes with every block up to a total of 21000000. Close the 'issue' please.
