### ISSUE TITLE
Iota Interface

### ISSUE THREAD

**Issue by loopster40** [iotaledger/wallet#803]
I see no difference in the new wallet. Still does not fix transactions just hanging out there in the tangle. Also, I thought the interface was suppose to be totally different in appearance.

**Comment by smitch88** [comment]
As far as the codebase I can only see a change to fix some interval cache and an update to iota.lib.js. I don't really understand the decision to use es6 features like Set and Map then code exactly as if this were es5. 😩

**Comment by loopster40** [comment]
It's so frustrating when you can not even move coins.
