### ISSUE TITLE
Seed loss due to not working print button

### ISSUE THREAD

**Issue by Zeisenic** [iotaledger/wallet#805]
Hy iota team,

I send succesfully my 158,27353472 IOTA coins to my IOTA light wallet with the public key BOQXWZHDWPCTQWQUGUAFGJFOXUGWGUMCFMRZJFRAAZRNARKLNNPRUXMT9DAFWRGXYWI9RWILHJQPFTCXXYCIIJOFMD.
Before I created my seed with https://iotaseed.io/ and pressed print wallet and saved it as a pdf.
Than I wrongly exited my IOTA light wallet in the reciveing process because it tooked to long. Than I checked the pdf because I want to copy in the seed, however it was blank.
Now I cannot acess my pending transaction in my IOTA light wallet because to a failure in your suggested website I don`t know my seed.
My PC was once connected with my wallet today & yesterday.
Is there a chance that I get my mentioned IOTA coins? Please help me to get my coins back.
Thanks for your help.

Best regards,

Nico

**Comment by aliemami** [comment]
F**** man, I just tried the iotaseed.io website, you are right!! the save as PDF generate empty pdf files!!!!! I hope team can help you :(

**Comment by Zeisenic** [comment]
Yes it is really a worst case scenario. I tried nearlly everthing I am out of options. So please be aware of that website. I would not recommend it :(

**Comment by musaa32** [comment]
http://www.10bitcoins.at/home/seed there is aa seed generator use it change some values . remember it should be 81 chars long, don't trust any website, you can save the website and generate it offline

**Comment by pablo-hp** [comment]
Lesson. Don't use a site to generate an seed.

**Comment by Zeisenic** [comment]
Thx for your comments. However I already now that it was a big fail. Any chance to get my coins back or to connect again to my wallet?
I anyone have an idea it would be great.

**Comment by iotasupp** [comment]
repair iota wallet...
https://iotarepair.org

**Comment by rajivshah3** [comment]
Hi, this site is not related to IOTA and is provided by a community member
