### ISSUE TITLE
Downloading troubles

### ISSUE THREAD

**Issue by elstasiu** [iotaledger/wallet#811]
Download speed is about 30kB/s and after some time connection is lost. Anyone else got same problem?

**Comment by Alino** [comment]
I have no idea what you are talking about, downloading what?

**Comment by elstasiu** [comment]
Sorry m8, im newbie here. Im talking about wallet from github

**Comment by Alino** [comment]
I had no issues with that, I did download it today quite quickly. Maybe it's issue with your network.

**Comment by elstasiu** [comment]
Ok, problem solved. You were right, troubles with my network
