### ISSUE TITLE
Error Private key reuse detected all the time 

### ISSUE THREAD

**Issue by InakMC** [iotaledger/wallet#813]
Hi all,

I'm trying to do a transfer to binance from my account but all the time appears the error private key use detected.

I have tried generating new addresses in Binance and new directions in IOTA Light Wallet 2.5.4 but the message continues.

The previous transfers are all cofirmed only appears as pending some resends.

Is posible to recovery my IOTA to other wallet using the Recovery tool or somebody know what is happening?

Thanks!

**Comment by urkovs** [comment]
I am having the exact same issue. Was having this issue in 2.5.4 and after upgrading to 2.5.5 I still have the issue. Screenshots attached:  

![screen shot 2017-12-19 at 8 38 09 pm](https://user-images.githubusercontent.com/31389454/34191534-95bb4cb0-e4fc-11e7-945f-4cf8b55b453a.png)
This occurs when I try to send IOTA to ANY address, even if I generate a new seed to send it to.

A lot of the re-attaches say "pending" under the History section, but when I look at their details they say "Persistence: a reattachment confirmed". 

So as of right now I have IOTA but the tokens appear to be trapped in the IOTA light wallet. 

Can anyone tell me how to transfer some out to an exchange like Binance so I can actively trade with them?

**Comment by samgranger** [comment]
It sounds like you have a transaction that is still pending, please check under your history tab.

**Comment by urkovs** [comment]
This is beyond frustrating. I know they say they are pending under the History tab. When I click for more information it says they have been confirmed. How do I get rid of these previous transactions so that I can place a new one? These older ones are clearly not going through.

**Comment by samgranger** [comment]
You have to reattach a pending transaction.

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
