### ISSUE TITLE
Transfers remain in pending state

### ISSUE THREAD

**Issue by andrewrooke** [iotaledger/wallet#814]
Transfer initiated (13 December) from my wallet to an exchange under 2.5.4 IOTA light wallet. Both wallet and exchange see transaction as pending. Transfer still pending after pointing wallet to different nodes and rebroadcasting. Moved to 2.5.5, same problem. 

Promoting the transfers fails with no information given.

I have tried to use the highest milestone nodes from http://iotasupport.com/lightwallet.shtml#list

**Comment by davidleor** [comment]
Hi, I have the same problem, some solution?

**Comment by rajivshah3** [comment]
You should reattach. Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
