### ISSUE TITLE
Iota disappeared

### ISSUE THREAD

**Issue by kk8105** [iotaledger/wallet#816]
Purse address ：VQWNWIMVQMUTPUIOYGGARJHL9QYESNRSGYKXH9JJ9ZKUDWRUGFUGVPRPVDBYYLVJB9QHXA9VMWVFUHDGDJRLBLJKHA

Transaction details ：YTCTRKKLCFLVLKAVTIBFFBSVCCEBGZSDDXUJFVTAY9BUFSLXVPWZUYYXMDWCOVTPNQGVDEKJECEFA9999

https://thetangle.org/search    <<<<  I can't find it here    https://iotasear.ch/transaction/YTCTRKKLCFLVLKAVTIBFFBSVCCEBGZSDDXUJFVTAY9BUFSLXVPWZUYYXMDWCOVTPNQGVDEKJECEFA9999     <<<<<    I can't get it here but I can see it here.

**Comment by kk8105** [comment]
But I can't get it at https://www.bitfinex.com

**Comment by samgranger** [comment]
Hi kk8105,

Is VQWNWIMVQMUTPUIOYGGARJHL9QYESNRSGYKXH9JJ9ZKUDWRUGFUGVPRPVDBYYLVJB9QHXA9VMWVFUHDGDJRLBLJKHA one of your own wallets receiving addresses? Or is it a deposit address at Coinone?

If it is your address (withdrawn from Coinone to your address), we can see in iotasear.ch that the funds have been sent to another address which would mean that your seed was probably compromised. If this is the case, how did you generate your seed? And how are you storing it?

If you sent this to an exchange like Coinone from elsewhere, it could be moved to a cold wallet - if this is the case, please contact Coinone's support if the balance hasn't shown up in your account.

**Comment by kk8105** [comment]
VQWNWIMVQMUTPUIOYGGARJHL9QYESNRSGYKXH9JJ9ZKUDWRUGFUGVPRPVDBYYLVJB9QHXA9VMWVFUHDGDJRLBLJKHA    It's my receiving address    I sent it from coinone to https://www.bitfinex.com  

The balance is not shown in my account.

**Comment by samgranger** [comment]
Ok this is clear, this is not an issue with IOTA but rather with Bitfinex. Please reach out to Bitfinex support. The funds have been sent to a cold wallet.

**Comment by kk8105** [comment]
samgranger   Thank you

**Comment by fredercik32** [comment]
just to know....can u explain " cold wallet " ?

**Comment by samgranger** [comment]
You're more than welcome!
