### ISSUE TITLE
Balance changes from 0 to 1, and vice versa

### ISSUE THREAD

**Issue by Vantskruv** [iotaledger/wallet#819]
Having the wallet active for some while, waiting for a transaction to come active, I noticed I suddenly had a balance of 1 IOTA instead of 0 IOTA. After a while, I had 0 IOTA again. And then yet again 1 IOTA, and so on. Time between iterations is undefined, but but maybe 10-30 minutes???

Also transfers in history changed from 14 to 13, and then to 14....

Yesterday I had a test transaction with a guy on discord, where he sent me 1 IOTA, and I did send him 1 IOTA back, both successfully.

IOTA Light Wallet 2.5.5 Linux 64 bit.

**Comment by rajivshah3** [comment]
Try a different node, you can use the list at http://iota.dance/nodes
