### ISSUE TITLE
slack chat room not available

### ISSUE THREAD

**Issue by iota-user** [iotaledger/wallet#820]
Would you check why we cannot log in to this chat?
Thanks a lot

**Comment by samgranger** [comment]
You can't login or you can't register? If you can't register, please try signing up with the following link: https://join.slack.com/t/iotatangle/shared_invite/enQtMjg5MjE5NTMxNDQzLTVkZDU1NDk2NTZjYjUxYzAxZjk0MTY2NWViZWU0ZmIzMmM2ZjNhMzdiZmU4MDhjY2RkMjAwOGUwZmFiNDQzNWE

**Comment by zenmetsu** [comment]
@samgranger what is the purpose of that slack?  I saw reference to an iota slack channel previously which had a nodesharing channel, but the invite link was expired.  I'm trying to set up a full node, but haven't been able to find a list of neighboring nodes to add to my configuration.  Is there such a node-sharing resource on the slack that you referenced?

**Comment by samgranger** [comment]
You should check out Nelson, see:
https://medium.com/deviota/iota-nelson-ready-for-public-preview-a958c6d0a531
https://github.com/SemkoDev/nelson.cli

**Comment by zenmetsu** [comment]
Thanks, I will give that a shot.
