### ISSUE TITLE
How Can I get IOTA coins?

### ISSUE THREAD

**Issue by iota-user** [iotaledger/wallet#821]
Would like to have IOTA coins , my light wallet is created on my computer.

**Comment by samgranger** [comment]
This is not the place to ask such questions (this is a bug tracker for the wallet). I will however answer your question.

You can buy IOTA on Bitfinex unless you are a US citizen. If this is the case, you can buy them from Binance using Bitcoin or Ethereum.

For a full list of exchanges, please refer to the following page: https://coinmarketcap.com/currencies/iota/#markets

Feel free to join the IOTA Slack channel (https://join.slack.com/t/iotatangle/shared_invite/enQtMjg5MjE5NTMxNDQzLTVkZDU1NDk2NTZjYjUxYzAxZjk0MTY2NWViZWU0ZmIzMmM2ZjNhMzdiZmU4MDhjY2RkMjAwOGUwZmFiNDQzNWE) or use the IOTA subreddit (https://www.reddit.com/r/Iota/) for all your questions.

**Comment by zenmetsu** [comment]
As an aside, I would like to recommend that you not use Binance as they have suspended IOTA withdrawals due to abysmal IOTA network performance.

**Comment by yntrader** [comment]
Do not put your Iota on Light Wallet. You'll never get them back. Gone. Can't get them out. At least this has been my experience and you have no recourse. Reattach, Reattach, Reattach. Rebroadcast, Rebroadcast. Nada.

**Comment by zenmetsu** [comment]
This is nonsense.  You can always use the same seed on a full wallet and get access to anything that was sent to that account.  

That said, light wallet or full wallet, the network is not working correctly at the moment.  The pages that I have seen show that the average network speed is sitting at about 1.5TPS.  There are also tens of thousands of transactions that are sitting in a pending state.  At 1.5TPS, I don't see any chance of the network ever catching up.  

I'd love for someone with the IOTA project to chime in and tell me why I'm wrong to think this way, but I don't see a happy ending if things keep up they way they are right now.
