### ISSUE TITLE
DEAR DEVELOPERS - POWERFUL PUBLIC NODE FOR LIGHT WALLETS http://cryptoiota.win:14265, please insert in the wallet's list.

### ISSUE THREAD

**Issue by ALEX778899** [iotaledger/wallet#823]
Hi, I'd like to help as much as I can because I really believe IOTA will bring freedom and a better future.
I'm keeping alive a reliable public node (24/7 powerful dedicated server in data center), it would be nice if you could insert in wallet's list so MORE WALLETS CAN USE IT.

- http address: http://www.cryptoiota.win
- API address for the wallet http://cryptoiota.win:14265

Please kindly let me know, thanks in advance, best regards

**Comment by andreafalzetti** [comment]
good job

**Comment by rajivshah3** [comment]
Closing as duplicate
