### ISSUE TITLE
Tangle 

### ISSUE THREAD

**Issue by Stang46** [iotaledger/wallet#824]
I cannot attach my wallet to the tangle, it keeps saying Invalid Response. Can someone help please?

**Comment by andreafalzetti** [comment]
@Stang46 try using another node

**Comment by samgranger** [comment]
Also make sure you are using the latest version of the wallet.

**Comment by Stang46** [comment]
Thanks but the newest version doesn't install after download.

________________________________

**Comment by Stang46** [comment]
What node should I change it to? I am using 2.5.4, the only one that lets me log in

________________________________

**Comment by rajivshah3** [comment]
Try the nodes at http://iota.dance/nodes
