### ISSUE TITLE
the error when I make new seed in Wallet2.55

### ISSUE THREAD

**Issue by koasis89** [iotaledger/wallet#825]
When i tried to make new seed in wallet on Windows, Wallet app occured error and warning message "~~ 81 characters". 
I entered  new seed many things : qwerty12345, qwertyuiop1234567890 and etc. 

Can you check it?

**Comment by samgranger** [comment]
Hi koasis89,

Making a seed like qwerty12345, qwertyuiop1234567890 is just asking to be hacked. And it simply won't work.

Some important notes.
 - Never share your key
 - Save your key in a secure way, if you misplace it, you have lost your funds
 - Make sure your key is totally random, you might think you can make a random key, but people are bad at this - MAKING9AKEY9LIKE9THISFOREXAMPLE9MIGHT999SEEMRANDOM9BUTISABADIDEA
 - Seeds should consist of uppercase letters and only the number 9 and should be 81 characters. ie:
    OZGMPXBPHSEOLSJF9CEMBTKZHOYFIAENJLYKVEABPOHOPHADERTCMOIXOIRHQGWVYROCQDTBKFIPLMXVA (Obviously, do not use this seed)

If you are running on a **Mac**, you can generate a seed in terminal with the following command: cat /dev/urandom | LC_ALL=C tr -dc 'A-Z9' | fold -w 81 | head -n 1 

If you are running on **Linux**, you can generate a seed in terminal with the following command:  
cat /dev/urandom |tr -dc A-Z9|head -c${1:-81} 

If you are on **Windows**, you can generate a secure seed using KeePass (this is the current recommended solution) - read the following documentation that explains the process from A to Z: https://ukcryptocurrency.com/iota/how-to-make-an-iota-seed/

I also suggest you look at the following link, https://iotasupport.com/gui-sendingandreceiving.shtml

Especially the Receiving IOTA part. **Make sure to only use receive addresses once.**

**Make sure, multiple times, that you have backed up your seed before generating a receive address / send funds to an address. You lost your seed? You've lost your money :(**

**Comment by koasis89** [comment]
Thanks a lot. Don't worry secret. I want only test for developing in localhost.

**Comment by koasis89** [comment]
I am so difficult to test what i make complete Iota running environment. Can Iota DEV team make one complete test sample with Iri and java script and HTML step by step?

**Comment by rajivshah3** [comment]
Check the documentation at [iota.lib.js](http://github.com/iotaledger/iota.lib.js)
