### ISSUE TITLE
Big Problems with the Wallet v2.5.5

### ISSUE THREAD

**Issue by chillside123** [iotaledger/wallet#826]
Hi people,

i tried to send iota from bitfinex to the updated wallet. now the transaction remains only on "pending" since 24 hours and nothing else happens. i tried to use different offical nodes like 30 times. But it didnt work.
Right now i cant even login into my wallet. after some time i get the notification that a login is not possible/allowed. 

Please help. Dont know what to do ..

**Comment by samgranger** [comment]
It is a possibility that Bitfinex needs to reattach the transaction. If https://iotasear.ch/ shows the transaction as pending, this is the case. If it shows it as confirmed, but your wallet doesn't, please try a different node / wait.

**Comment by ANDI117117** [comment]
Is there anybody who succeeded in withdrawal from IOTA Wallet to bitfinex or binance last two days? Please, share your experience. The last update 2.5.5 doesn't solve the most critical issue of withdrawal from IOTA Wallet.

**Comment by fredercik32** [comment]
Hello,
   Make transfet from bitifinex to my iota wallet....but don't work. It's Unconfirmed
LBGCNVRUWOFMZMCBHLYRMYTWNI9JDDYQKPIMMUETE9VHGHYBVXLWEHROZIDVGAOTVAOQPDLHHTTDFQAXZUZNWVCLTW
to see it

**Comment by mgrassotti** [comment]
@fredercik32 What I can say from my experience is that Bitfinex periodically tries to reattach the transactions, if they are pending. I did a few withdrawals in the last weeks that always went good in the end. I noticed a slowing down in the latest days, maybe they are having a lot of requests? Anyway if if the transaction lays there for days, as you requested a withdrawal from them, you can directly ask for their support.

**Comment by wonkytonky** [comment]
did withdraw .today.. it did work from bitfinex.
did deposit today.. it did work to  bitfinex

**Comment by fredercik32** [comment]
Ok but i didn't attached the adress to the tangle...( read not necessary on a iota forum) does it matter ,??? 

TK YOU

 

    Le Jeudi 21 décembre 2017 0h29, wonkytonky <notifications@github.com> a écrit :
 

 did withdraw .today.. it did work from bitfinex.
did deposit today.. it did work to bitfinex—

**Comment by fredercik32** [comment]
Hello
Ok but i didn't attached the adress to the tangle...( read not necessary on a iota forum) does it matter ,??? 

Tk you 

    Le Jeudi 21 décembre 2017 0h05, Matteo Grassotti <notifications@github.com> a écrit :
 

 @fredercik32 What I can say from my experience is that Bitfinex periodically tries to reattach the transactions, if they are pending. I did a few withdrawals in the last weeks that always went good in the end. I noticed a slowing down in the latest days, maybe they are having a lot of requests? Anyway if if the transaction lays there for days, as you requested a withdrawal from them, you can directly ask for their support.—

**Comment by TRADE-ALL-THINGS** [comment]
@wonkytonky I am so happy to hear some progress. Did you use a special host or did you use iota.bitfinex.com:80? I have tried different hosts, curl implementation, weight. Every time I generate new address on bitfinex or binance I receive "key reused" output of IOTA Wallet 2.5.5 for mac. Please, help us!

**Comment by chillside123** [comment]
Wow, so many comments. I solved my problem with the following steps:

1)search your transaction by using your hash number or directly with the transaction adress on this site https://iotasear.ch/ and check the status of your transaction and/or find out what your hash bundle is.

2)then put in your bundle hash here and boost your transaction: http://www.reattach.online/

3)i did that like 20 times and it finally worked after ~24 hours.

**Comment by TRADE-ALL-THINGS** [comment]
Thank you for the instructions.

**Comment by fredercik32** [comment]
Ok thank you chillside....but when i try this whith the hash numberit s telling me " No transactions found, try again."
                       -Can i reattach my reception adress ?
                       - must i necessary use http://iota.bitifinex.com:80 in my iota wallet ? or it doesn t matter ?
tk again

**Comment by chillside123** [comment]
Hi Fredercik32,
go on http://iota.dance/nodes and take one of the nodes with the highest "health rate" and try reattaching your transaction again and again. after some time - for me it took like 24 hours - it will work. the most important thing is, that you can see your transaction in the wallet as in a "pending" status. If so, you can try the written things above by me. otherwise maybe your exchange didnt approve your transaction yet. Then you will have to wait for bitfinex/binance etc. to process your transaction.

**Comment by fredercik32** [comment]
OK i understand ( more difficult for me cause my englis is not perfect !!!)
I see every pending transaction with bitifinex hash code.....i'm not the only who is waiting soooooooo
looooooong. BITIFINEX is maybe bigger than it could be to do efficient job !!
  But i'm a little bit surprise IOTA is "the  new" crypto suppose to be safe and faster to be really use
in the futur....but if simple transaction is such a mess....what is the real potential of this technology ??

**Comment by smartboy2017** [comment]
when we use https://iotasear.ch/address/ to lookup some address,
Why always stay "Unconfirmed", even if the transaction has already succeeded?

**Comment by TRADE-ALL-THINGS** [comment]
http://www.reattach.online/ is down. Today is a special day, a crypto bloodbath! Is there any viable alternative to reattach efficiently IOTA transaction?

**Comment by TRADE-ALL-THINGS** [comment]
The future technology of bloody shit. Many IOTA owners are unhappy!
