### ISSUE TITLE
Is Seed Vulnerable During Invalid Response 

### ISSUE THREAD

**Issue by mb-deihl** [iotaledger/wallet#827]
When I try to send IOTA mi. from wallet 2.5.4 I get an error: "Invalid Response" .  It takes about 1 minute for the transaction to fail and put out the message.  During that time is my private seed exposed out on the network?  

It's too bad the error message is not a more descriptive error "response".  I think what it means to say is: Invalid Input, or Unable to Connect to Tangle, or "You're too stupid to own IOTA".  The true meaning is lost in translation.

**Comment by zenmetsu** [comment]
Your private key is never sent over the network.

**Comment by mb-deihl** [comment]
Thanks for that.  I guess I'll have to wait to see of the error messages get more meaningful when the full production wallet is released.
