### ISSUE TITLE
big problem to login light wallet 2.5.5

### ISSUE THREAD

**Issue by ali59sh** [iotaledger/wallet#828]
i cant login in my wallet 
about 1 day light wallet just logginig in process

**Comment by SanderLesage** [comment]
try changing the host configuration.

**Comment by dentemm** [comment]
I have the same issue on my Mac with OS 10.12

**Comment by NathanielatCode** [comment]
Same for me: I open the wallet and it doesn't show my balance, my history or anything. It doesn't give me an option to enter a seed for login. It's just a green rectangle with menus that drop down. 

Last night it worked fine. Between now and then I updated my windows OS with whatever patch they just ran through.

**Comment by aliemami** [comment]
the node that you are connected is out of sync, change your node and you should be fine (happened to me yesterday), I'm connected to bitfinex node and works fine

**Comment by iotasupp** [comment]
repair iota wallet...
https://iotarepair.org

**Comment by aliemami** [comment]
can someone ban iotasupp user?? 

and never put your seed to anywhere online! don't use above link, you will never see your IOTA

**Comment by samgranger** [comment]
He's been removed.
