### ISSUE TITLE
Problem with my wallet....still be 0 an unconfirmed transaction.

### ISSUE THREAD

**Issue by fredercik32** [iotaledger/wallet#829]
Please could you tell me why it is so long to receive my iota on my iota wallet...

I'm biginer and i didn't attached the adress to the tangle ( read that it's not necessary on tuto...)
I can attach other adress to the tangle...so i think my wallet work correctly.

But now my wallet it empty....and transaction not confirmed...why ?

iota adress is 

LBGCNVRUWOFMZMCBHLYRMYTWNI9JDDYQKPIMMUETE9VHGHYBVXLWEHROZIDVGAOTVAOQPDLHHTTDFQAXZUZNWVCLTW

Tks for help ( sorry for my english....i m a french guy)

**Comment by ali59sh** [comment]
i have the same problem about 2 days

**Comment by fredercik32** [comment]
CONFIRM NOW...BUT NOT SEE IT IN MY WALLET

**Comment by mario589736** [comment]
@fredercik32 - same problem here, you found a solution?

**Comment by fredercik32** [comment]
My transaction is confirmed since yesteday ....but wallet still empty. I M REALLY TIRED ABOUT THIS
SITUATION. 
 Look, i use a wallet for safety...and i'm unable to have my iota on it !!!!
 No solution for the moment...

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
