### ISSUE TITLE
Tangle DB should _not_ be stored in %APPDATA% on Windows.

### ISSUE THREAD

**Issue by MicahZoltu** [iotaledger/wallet#83]
On Windows, %APPDATA% roams across the network on login/logout. Files written here should be measured in KB, not in GB. For user-specific cache files like the Tangle DB, they should be written to %LOCALAPPDATA% instead.

Having the tangle DB written to %APPDATA% can destroy a network since it will sync on login/logout and it can render a user's account inoperable until an admin manually addresses the issue. Users in a corporate/school network also often have a quota and filling it with the tangle DB will make it so none of their actual roaming data will sync until the tangle is deleted.

**Comment by atypicalprogrammer** [comment]
Will do. On another note, what about the installation location of the wallet itself? Is program files preferred, or appdata?

**Comment by atypicalprogrammer** [comment]
Note I've already added the ability for the user to choose the database location in the current version. Now I'm wondering if everything should be in localappdata, and the app itself in program files? What are your thoughts on that. (I'm not a windows guy).

**Comment by MicahZoltu** [comment]
`%PROGRAMFILES%/<vendor>/<app_name>` should be used for any application executables that you want to install for _all_ users.
`%LOCALAPPDATA%/Programs/<vendor>/<app_name>` should be used for any application executables that you want to install for only the current user.

`%APPDATA%` should not be used for executables as they are generally too large to go here.  `%APPDATA%` is intended for juts configuration files like `.ini` or `.cfg`, meaning measured in small number of kb or bytes.

**Comment by MicahZoltu** [comment]
The _simple_ solution is to just put everything in `%LOCALAPPDATA%/...` with the exception of user-configuration that you want to roam across the network.  If you have no such configuration or don't want to deal with that, putting everything in `%LOCALAPPDATA%` is "safe" and won't hurt anything (just means configuration won't roam between devices).

**Comment by MicahZoltu** [comment]
Something to consider about `%PROGRAMDATA%` is that _only_ administrators of the system have write-access to that folder.  This means that any writes need to go through an elevated application execution (the Windows pop-up asking for admin writes).  In Linux terms, this is similar to having to `sudo` to write to a directory.  This is generally why you don't want to put anything there other than executables at install time.  From a security perspective, there is value in putting executables here because it is much harder for a trojan/virus to mess with them.

Glancing at the installed files now, it looks like just `settings.json` and `Preferences` would go into `%APPDATA%/Iota/wallet`.  Though, that file does have a `javaLocation` path in it which (ideally) would be separated into a different config file that was system-local and lived in `%LOCALAPPDATA%/Iota/wallet`.

I'm not sure where the seed is stored, but having that roam would probably be correct behavior, along with the current seed index.

**Comment by atypicalprogrammer** [comment]
Thanks for the info, will do!

**Comment by atypicalprogrammer** [comment]
I will just store everything under localappdata since it's not necessarily true that you will want the same configuration on all your computers. One you may want to set up as a full node, the other as a light node, etc.

**Comment by atypicalprogrammer** [comment]
Fixed on dev branch, not yet tested by many though. Use on your own risk ;-)
