### ISSUE TITLE
transaction pending

### ISSUE THREAD

**Issue by cerosyunos01** [iotaledger/wallet#830]
I made a shipment of iota on 12/16/2017 12:34 and has remained pending. I have tested the retransmission option several times and restarted and it does not solve the problem. What I can do? When I'm pending, he does not let me send or receive my blocked account. I just tried the latest version, 2.5.5 and it remains the same.

**Comment by eusuntacum** [comment]
same here.What I can do?

**Comment by samgranger** [comment]
Try reattaching your transaction using this tool: https://boost.iotalpha.io

**Comment by Stroys** [comment]
Hello! In the history of IOTA.Wallet. 2.5.5 there are three waiting transactions for the same transfer. Something broke. Where can I go for help? 
https://thetangle.org/address/JFIXHPNT9ONB9ZIJKWPNGEKDPNXEX9SANHQYA9MGOQOPJLPXUZRBCHQDDCAVYVMIMJCRFFDVSVHLDHWJD

**Comment by samgranger** [comment]
It's a reattachment, nothing wrong with that. This is normal, and it looks like the transfer succeeded.

**Comment by Stroys** [comment]
The fact is that two transactions in the program are still pending, while one of them is constantly changing its status. The balance appears for a short time, then again reset to zero. It does not seem to be normal.

**Comment by Stroys** [comment]
When you try to transfer 1 Mi , just hung in anticipation. Unable to find an official support service, tell me please! https://thetangle.org/address/LRVWMEKGAXXLYT9OBZFRSCJ9LFPRKPZBIFSJ9VSVJNPBKDNJOSIGADANYDFOKKCDVSNH9ETAJCC9RNV9D

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
