### ISSUE TITLE
why my withdraw don t work since 15 hours from bitifinex ???

### ISSUE THREAD

**Issue by fredercik32** [iotaledger/wallet#832]
Please i'm waiting since 2 days my withdraw from bitifinex to my iota wallet....i didn't attached the
adress to the tangle ( read no matter on a tuto....) maybe make a mystake ...
 Please what can i do ??

LBGCNVRUWOFMZMCBHLYRMYTWNI9JDDYQKPIMMUETE9VHGHYBVXLWEHROZIDVGAOTVAOQPDLHHTTDFQAXZUZNWVCLTW   to see the transaction.

thank for helping me

**Comment by samgranger** [comment]
This isn't a wallet issue, nor have you done anything wrong. Attaching your address is not mandatory - Bitfinex will have to reattach the transaction (this happens quite often - we can see they have already attempted to reattach the transaction but will need to do so again). Please wait a bit longer, I know Bitfinex is under quite a lot of load lately. You can also send a ticket to Bitfinex support requesting them to maybe reattach the transaction manually.
