### ISSUE TITLE
IOTA light wallet 2.4.0 no connection

### ISSUE THREAD

**Issue by Crystyna** [iotaledger/wallet#833]
Hi, I bought some IOTA back in August and left them in my IOTA wallet on my desktop. When open this now it has 'no connection'. I have tried 'edit node configuration' and selected various other hosts (from reading other posts) but can't get a connection.
Please would you let me know if I need to download a newer version? or is there a newer host that I should be using?

**Comment by mgrassotti** [comment]
There is a new version (2.5.5, see https://github.com/iotaledger/wallet/releases). But I don't think it matters a lot. This morning I signed in using https://nodes.iota.cafe:443 without problems. Hope it helps. Cheers.

**Comment by fredercik32** [comment]
Hello,

  Maybe stupid question...but i have problem to receive iota from bitifinex to my wallet...should i use
https://bitifinex.iota***   or it doesn t matter ?

**Comment by Crystyna** [comment]
Hi, thank you for answering.

 

I have just tried the new node, but it is still saying ‘could not connect to remote node’. Is there anything else I can try?

**Comment by mgrassotti** [comment]
@Crystyna it can happen sometimes, but it usually works after a few trials.

**Comment by mgrassotti** [comment]
@fredercik32 I don't think the node you are connected to really matters. I would suggest to wait, it took me approximately 24 hours last time to have IOTA from Bitfinex, but they arrived in the end.

**Comment by fredercik32** [comment]
Tk you mgrassotti...i'm a little stressed about this opération cause it's my first...
BITIFINEX seems to have big problems to be efficiant with iota transaction ( i m not alone to
feel it like this in many forum...)
  my order was given the 19/12....so more than24 hours !!!

**Comment by mgrassotti** [comment]
@fredercik32 yes I understand, it creates a lot of stress 😂 . But I also think that if it would be already perfect we all would be already millionaires 😆

**Comment by Crystyna** [comment]
Thank you Matteo, it appears to be trying to connected every minute, so do I just leave this window open for a few hours to see if it connects? (its been open about half an hour now).

**Comment by mgrassotti** [comment]
@Crystyna does https://nodes.iota.cafe:443 gives the same problem to you? It didn't to me just a few minutes ago

**Comment by th0br0** [comment]
Old wallets (pre 2.5.3 IIRC) won't work anymore. Please upgrade.

**Comment by Crystyna** [comment]
yes, its been on that one since you told me about it earlier

**Comment by mgrassotti** [comment]
Ok so you can try to install the latest version https://github.com/iotaledger/wallet/releases

**Comment by Crystyna** [comment]
Sorry for being thick/nervous is it the .exe that I need to download?

**Comment by mgrassotti** [comment]
No worries, it depends from your machine. If you are on Windows then yes `.exe` is the right one. If you are for example on a Mac, `.dmg` is the right one.

**Comment by Crystyna** [comment]
Thank you Matteo, I now have a new light wallet (2.5.5) but this has a zero balance. Do I need to do something else to import my coins over from my old wallet?

**Comment by wonkytonky** [comment]
generate addresses.; until your balance pops up.. if it doesnt you might need to claim your coins ..

**Comment by fredercik32** [comment]
tk you mgrassotti...
  Just one more question to you...is it normal that i can't reattach the hash transaction  in http://www.reattach.online/ ?

**Comment by mgrassotti** [comment]
@Crystyna as probably @wonkytonky said, you can click on "receive" and then "attach to tangle". I had the same issue also connecting to another node. So you can also try to connect to the same node as before. Anyway if you don't lose your seed, you don't lose your money. They are in the network, you just need your wallet to be updated.

**Comment by mgrassotti** [comment]
@fredercik32 I am not sure as I didn't use that before. I would just make sure you are pasting the _bundle_ id and not the transaction id or the address.

**Comment by Crystyna** [comment]
Thank you so much Matteo, my coins are in my new wallet.

You have a very clear and concise way of explaining things, and it is much appreciated. x
