### ISSUE TITLE
Faile to build with MACOS 10.13.2

### ISSUE THREAD

**Issue by dexterchan** [iotaledger/wallet#834]
Followed the instruction. failed to build the wallet
[2017-12-21T08_55_18_879Z-debug.log](https://github.com/iotaledger/wallet/files/1578540/2017-12-21T08_55_18_879Z-debug.log)

**Comment by samgranger** [comment]
This isn't an issue with the wallet, node-gyp doesn't seem to want to build on your machine - there can be various reasons for this. Please refer to https://github.com/nodejs/node-gyp/issues/489
