### ISSUE TITLE
Pending transactions to an old adress

### ISSUE THREAD

**Issue by Birkmoe** [iotaledger/wallet#836]
Hello, i just resolved my pending transaction issue within my wallet, but all my pending transactions is to old adresses. I have several transactions which is to my old bitfinex funding adress. It says on bitfinex that transactions to old adresses will not be funded, so what do i do?

thanks for answers.

**Comment by ali59sh** [comment]
i have the same problem

**Comment by Birkmoe** [comment]
Have u tried sending to one of ur old adresses?

**Comment by rajivshah3** [comment]
You should contact Bitfinex about this
