### ISSUE TITLE
"Connection refused" on seed log in

### ISSUE THREAD

**Issue by MerryPanda** [iotaledger/wallet#838]
Well... i can't connect with any of my seeds :(
HELP

**Comment by juan-martinez12** [comment]
im having the same problem, have you solved it?

**Comment by wonkytonky** [comment]
change node

**Comment by MerryPanda** [comment]
yep, thanks, node change solved the issue

**Comment by lamaca** [comment]
I changed node beacause I could not connect with the light wallet and now the connection is refused with my existing seed. Is it because of that it is refused ?
How can i go back to restaure my previous node ?
thankfor any help

**Comment by lamaca** [comment]
I managed to return to my original node but now when I tried to connect  the message say "not synced"

What is mean ? what can I do to connect to my wallet ?
thanks

**Comment by lamaca** [comment]
solved :-)
