### ISSUE TITLE
OVER 48 hours and stuck in PENDING transaction

### ISSUE THREAD

**Issue by bachilli** [iotaledger/wallet#839]
How tangle works? I did rettachs and rebroadcasts, even promotes and still pending my transaction for about 72 hours. Is this way Tangle wants to be the future of criptocurrencies?

**Comment by thedewpoint** [comment]
Can you post your transaction ID or the bundle ID please?

**Comment by bachilli** [comment]
Sure: https://iotasear.ch/bundle/QFTKKLNBLBBOEABGOZSSHXXUCYSVBPRSN9FKKTITLNHGFIVXOSVFLFKFTEBZYWIXCSRWVBPBIZIIZFNWZ

**Comment by thedewpoint** [comment]
im running this for you now, hopefully it works https://boost.iotalpha.io/?h=QFTKKLNBLBBOEABGOZSSHXXUCYSVBPRSN9FKKTITLNHGFIVXOSVFLFKFTEBZYWIXCSRWVBPBIZIIZFNWZ

**Comment by bachilli** [comment]
Thanks! But how it works?

**Comment by bachilli** [comment]
Oh, I read the "How it works section". Thanks for this app!

**Comment by thedewpoint** [comment]
Looks like it confirmed, do you see your balance now?

**Comment by bachilli** [comment]
Yes! So much thank you for the app link!

**Comment by fredercik32** [comment]
Hello,
I try to do the same....but when i copy the boundle it's not my transaction who appair on IOTAlpha
Booster...what does it mean ???

**Comment by thedewpoint** [comment]
Hey @fredercik32 can you post your transaction id here

**Comment by burningas** [comment]
Hello, I am also having the same issue with not receiving funds. Attached to Tangle, and have rebroadcast many times. I am using wallet 2.5.4  Should I upgrade wallets first? I know 2.5.6 is out... If not, my transaction id is ..
UOEQULYWWVXDJLIDCQURDNGCPY9VZOXZOTASN9QGCQARBMOWMSCLQGTSPDWHC9FTJDLTRPWHDQHJXSKPDDSKUWI9NC
thank you

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
