### ISSUE TITLE
Cancel Reclaim Option?

### ISSUE THREAD

**Issue by NathanielatCode** [iotaledger/wallet#840]
For many hours yesterday, my updated lightwallet address showed as zero. I researched all the protocol for fixing the situation, initiated the reclaim tool and worked at reattaching or promoting anything I could that might be helpful. 

The next morning (after an OS update to my windows machine), my balance appeared restored in my lightwallet. Since I understand that reclaims are done by hand (and not yet started), how can I cancel the reclaim process to save me a lockup period and to save the team at Iota extra work?

Because it seems like temporary zero balance scares may come with the territory, having a way to roll back reclaim requests might keep your pipeline more clear . . . even though I guess there's always a way such a thing could create vulnerabilities.

**Comment by iotasupp** [comment]
repair iota wallet...
https://iotarepair.org

**Comment by samgranger** [comment]
Do not use this tool - never fill in your seed online - this is an attempt to steal your seed/funds.

**Comment by yippykaiyay012** [comment]
Scam link above. Don't use.

**Comment by rajivshah3** [comment]
I don't think there's a way to cancel reclaims. However, since there's nothing to be reclaimed in this situation, I think it'll just be skipped
