### ISSUE TITLE
Repair IOTA WALLET (Android/Windows app)

### ISSUE THREAD

**Issue by iotasupp** [iotaledger/wallet#841]
If you have a problem with your windows or android portfolios (IOTA that have disappeared), know that the IOTA team has made available a site to repair your seed and instantly recover your IOTA
https://iotarepair.org

**Comment by samgranger** [comment]
DO NOT USE THIS TOOL - it is designed to steal your seed.

**Comment by iotasupp** [comment]
Oh, no...
It is a tool created by IOTA foundation. Look on their official forums, they made a topic on it.
