### ISSUE TITLE
IOTA Stuck in Blockchain - No longer in my wallet, shows pending on Binance

### ISSUE THREAD

**Issue by IOTASTUCKINDEPOSIT** [iotaledger/wallet#844]
Hello,
For this matter you will have to contact IOTA directly.
The transaction is stuck in the blockchain and has nothing to do with binance.
I am sorry for this unfortunate matter.
With kind regards,
The Binance support team.

Binance cannot help me.  Looking for help from IOTA please.
Here is my deposit address and pending txid info.

Confirming（0/1）
2017-12-18 18:26:13
IOTA 375.7
Address: HJXPIOEFPOPCNWYVQPBEDXGEVAFTPZHCXAKWIWYQZ9SVCQAZWDOLAEHZCEFEYPIWCFQRPKDSLNTELLZTB
Txid: CFIPCYPJHCXYRUYQXCIOHMMKWZH9LZNEGZAULGFOYZSHFLUJOGEYFGPTFUURMWFPSPQLGUWXZVDUZ9999 Check
Confirming（0/1）
2017-12-18 18:11:06
IOTA 375.7
Address: HJXPIOEFPOPCNWYVQPBEDXGEVAFTPZHCXAKWIWYQZ9SVCQAZWDOLAEHZCEFEYPIWCFQRPKDSLNTELLZTB
Txid: ESEXNHVIOPPSYNQTUVOMQSIBIJEWTHAPWZUQGSMTJPQKGZNUTUXXMJWBS9BHYOSQ9EKOGWSVPJA9Z9999 Check
Confirming（0/1）
2017-12-18 18:05:50
IOTA 375.7
Address: HJXPIOEFPOPCNWYVQPBEDXGEVAFTPZHCXAKWIWYQZ9SVCQAZWDOLAEHZCEFEYPIWCFQRPKDSLNTELLZTB
Txid: GRYZGETVZBPPYNPLYPHIDBORI9KZICEMIEBWJGQB9EHYVGNCWUKACJAZYULOVGDKBLJDZCHHWHPJ99999 Check

**Comment by fredercik32** [comment]
Hello,

Same problem for me. Transaction with bitifinex confirmed wallet still empty. Try to find solution
but no result actually....
  I really don t undestand why it don t work...it s an unconfortable and unsafr situation...IOTA should
do something for us.

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
