### ISSUE TITLE
Wrong SHA256 checksum for v2.5.6 (.exe)

### ISSUE THREAD

**Issue by zarko-tg** [iotaledger/wallet#848]
https://github.com/iotaledger/wallet/releases/tag/v2.5.6
shows 734a6206194150cadb1570852464aabf204988e074118739bd50d967b0ac13eb for IOTA Wallet Setup 2.5.6.exe

while I get a38f7e85764c1c6bb507822afce1a67a0731e81bee38d039c6c6ecc15bb118d0.

Command used:
```
>certutil -hashfile Downloads\IOTA.Wallet.Setup.2.5.6.exe SHA256
SHA256 hash of Downloads\IOTA.Wallet.Setup.2.5.6.exe:
a38f7e85764c1c6bb507822afce1a67a0731e81bee38d039c6c6ecc15bb118d0
CertUtil: -hashfile command completed successfully.
```

**Comment by wonkytonky** [comment]
agree : 
![image](https://user-images.githubusercontent.com/19390834/34304461-2a6951e2-e73a-11e7-81cd-379715789561.png)

**Comment by pablo332** [comment]
Same

**Comment by wonkytonky** [comment]
@chrisdukakis important

**Comment by domschiener** [comment]
Updated, was a mistake on my end. 

``` 
PS C:\Users\dominik\Desktop\IOTA\wallet\out> CertUtil -hashfile '.\IOTA Wallet Setup 2.5.6.exe' SHA256
SHA256 hash of .\IOTA Wallet Setup 2.5.6.exe:
a38f7e85764c1c6bb507822afce1a67a0731e81bee38d039c6c6ecc15bb118d0
CertUtil: -hashfile command completed successfully.
```
