### ISSUE TITLE
Binance > IOTA Light Wallet 2.5.5

### ISSUE THREAD

**Issue by mts1620** [iotaledger/wallet#849]
Noob here.

Binance confirmed outgoing sum approx. 12 hours ago. Still waiting for confirmation (?) and receipt in wallet.

Questions:

1. How long should I expect to wait?
2. Is there anything more I need to do?

Thanks!

**Comment by mts1620** [comment]
p.s. I attached the receive address to the tangle before initiating the send from Binance. Binance holding now empty, so the issue appears to be with the wallet/iota.

I realize others have had issues, but would welcome pointers. Thank you, all.

**Comment by brunoamancio** [comment]
This is not the place to discuss that.

**Comment by mts1620** [comment]
That answer would have been helpful if you had pointed to the place where it can be discussed. As you didn't, it isn't.

**Comment by brunoamancio** [comment]
I would, but poeple have to start using their brains and search for the content they want.

**Comment by mts1620** [comment]
I’m afraid your presumptiousness and lack of courtesy make you about as useful as your replies. A community is only as good as the behavior of its members to one another. Kindly cease if you have nothing constructive to contribute. Many thanks.
