### ISSUE TITLE
Allow login without waiting for solid.

### ISSUE THREAD

**Issue by MicahZoltu** [iotaledger/wallet#85]
The GUI will _only_ let me login when I am solid.  I should be able to login without being solid, perhaps just with some kind of indicator that I'm not solid.

At the moment, my node is constantly just a tad behind solid and I am never able to catch up (separate issue).  This situation should not prevent me from being able to login, create new tips, see my balance (as of whatever milestone I'm at), etc.

**Comment by domschiener** [comment]
We generally do that to ensure that the user has the most recent "state". For this GUI Wallet, I actually prefer to keep it that way to make it as user friendly as possible. Else people suddenly ask questions of "where is my transactions?".
