### ISSUE TITLE
Automatic send iota

### ISSUE THREAD

**Issue by vboasso** [iotaledger/wallet#851]
First sorry for my english...
I've a few iotas going out of my wallet and I don't do that...
Is it normal, like a refund, or someone is stealing me?

![cap](https://user-images.githubusercontent.com/29603146/34314791-498c5d82-e756-11e7-8109-97ab97de0b4d.png)

**Comment by worcesterman** [comment]
Did you create your seed using one of the online generators?  Or using the Windows shell command (which isn't random enough to be secure)?  If so it is possible that someone has your seed and is trying to steal.  This is where the beta nature of the wallet could work in your favour: you can send the IOTA which are in the pending transaction to somewhere else, and if that transaction completes first then you have saved your IOTA.  I also understand that using the IOTA light wallet on a PC this isn't possible (the same IOTA cannot be sent twice), but that there is a bug in the Android wallet which allows the same IOTA to be sent to another address while the "stealing" transaction is still pending.  Then it is a race to see which completes first (you need to keep reattaching your transaction to help it complete faster).
Can anyone confirm this?

**Comment by vboasso** [comment]
I was using a short seed... Now I open a new wallet with 81 caracters typed by me, whitout generator to store the iota. But when I try to send, get this message: 
![captura de pantalla de 2017-12-24 10-34-37](https://user-images.githubusercontent.com/29603146/34326891-908cbf56-e896-11e7-9e99-b514cbc1bf19.png)

Is this for the pending transactions?

**Comment by worcesterman** [comment]
Yes, the Windows version of the Light Wallet won't let you send if the same IOTA has already started to be sent already,  BUT the Android version does let you send the same IOTA twice, and so you can try to send your IOTA to your new wallet and it is a race to see which transaction completes quickest.  You can reattach your own transaction and rebroadcast it to try and give it a better place in the race.
I'm not an expert though: hopefully someone can verify what I'm saying

**Comment by rajivshah3** [comment]
You should avoid double spending if possible, it exposes you to theft. Double spending is now prohibited in the latest update of the android wallet
