### ISSUE TITLE
Cancel pending withdrawels

### ISSUE THREAD

**Issue by allardg78** [iotaledger/wallet#853]
Hi - is it possible to cancel pending withdrawels?

I have 3 that have been pending now for a week and im worried the address they are being sent to on Bitfinex is no longer valid.

Thanks

**Comment by xq0404** [comment]
I don't think it can be cancelled,  because my desktop wallet is "confirmed" while the Android app wallet still shows "pending". I suggest a delete option is introduced for the next upgrade.
