### ISSUE TITLE
IOTA balance stuck in PENDING then disappeared

### ISSUE THREAD

**Issue by r34per000** [iotaledger/wallet#854]
Hi, I am a complete NooB when it comes to crypto currency so please bear that in mind. I bought some IOTA from Binance.com and transferred it to my IOTA wallet. initially it showed up in my balance and everything was ok. I checked back the next day and my balance was showing as 0, I then found the coins to be sitting under the History tab with a status of pending. I found this to be odd as the previous day the funds were showing in my balance as cleared. I read up on some forums who advised to select the 'bundle' icon and select 'rebroadcast'. I did this and the status changed to confirm however the funds stayed under the history tab. I gave it another day and no change. I then read I should try the 'reattach' option which I did. Now all my funds have disappeared, I cant see any transactions in the  History tab or the Balance tab. 

I am using wallet 2.5.6

Can anyone help? have I just lost off my funds? What am I doing wrong?

**Comment by solidminds** [comment]
Did you already changed to another node first, and then do the above handling? Might be a problem with the node you are using.
CHeck iota.dance and pick one of the nodes at the top.

**Comment by r34per000** [comment]
+solidminds I didn't switch nodes before trying the above but have now and the funds are back in the wallet in the available balance section - thank you sir, you are a life saver!!!!
