### ISSUE TITLE
iota withdrawl from binance to lightwallet pending over a week

### ISSUE THREAD

**Issue by vvvvvvvvvita** [iotaledger/wallet#858]
hello

tried to reatach. after reataching  binance showed 3 unconfirmed transactions. one was left after i asked the binance support for help. after 3 days tried to reatach again. 
now i have 2 unconfimed transactions. my wallet still show the full iota amount. 
please help me

（0/1）
2017-12-24 02:22:28
IOTA 1132.14

Txid: MNNIT9SEHRCESUDYWSVWEFMOTKSZBRCXGMQWCFNFKZ9MI9UR9CAIQVOKWAQIQQV9FQQH9VXINVCSA9999

（0/1）
2017-12-18 22:21:28
IOTA 1132.14

Txid: XAIJK9VOLPHGUGSCMU9LETRJRXT9HNDMJVIWHHQQDLTQOYXJJGRZKEZLRHKNWIISHD9AMVXQBSNYZ9999

**Comment by xq0404** [comment]
I suggest you click "Promote" instead of "reattach" for "unconfirmed" status in the latest GUI wallet version.

**Comment by vvvvvvvvvita** [comment]
last time i clicked "promote" in the latest gui wallet. right.

but the week before i reattached 3 times...

**Comment by xq0404** [comment]
You are a little unfortunate, I'm afraid. That's exactly the same mistake I made when I first started using the wallet. The wallet kept confirming reattached transactions that could not be cancelled. I eventually discarded the wallet, and generated a new seed for a new wallet as I did not have balance under the old seed.

**Comment by vvvvvvvvvita** [comment]
i tried diferent nodes from :https://iotasalad.org/nodes  and reatached. 

finaly my wallet shows  transaction confirmed. and after a while everything on binance.

**Comment by xq0404** [comment]
You are lucky again. Be warned that "iotasalad" website may reportedly contain scam nodes. Better not add nodes manually.  https://medium.com/supercryptocurrency/iota-cryptocurrency-is-a-scam-heres-10-reasons-why-ca111de0f19a
