### ISSUE TITLE
Transfer question/ concern from Binance to Iota Light Wallet 2.5.6

### ISSUE THREAD

**Issue by JeffersonAirplane** [iotaledger/wallet#859]
Hi there,

I recently transferred over my IOTA currency from the Binance exchange sight to the Iota Light Wallet 2.5.6.
I am seeing it in the history section but my balance is zero & the RECEIVE section is empty.
What can I do to fix this issue?
Thanks in advance
Jefferson

please see attachment

![capture](https://user-images.githubusercontent.com/34805769/34324719-714babd0-e831-11e7-8e57-0c0300577b95.JPG)

**Comment by cascio** [comment]
In my experience, the node you're connected to could negatively impact transaction time. When I started with IOTA, I was connected to a node that would take forever to confirm a transaction on. I used the following list and picked a different node and now I don't have an issue: http://iotasupport.com/lightwallet.shtml.

**Comment by JeffersonAirplane** [comment]
Nice! Picked the 1st one in the drop down menu and BAM!
Thank You Cascio!

**Comment by omarthecrypto** [comment]
My transfer to CoinSpace crypto wallet wath OK [https://www.coin.space/blank.html?utm_source=cardano.org&utm_medium=Binance Coin&utm_campaign=English&utm_content=Wallet discussion](url)
