### ISSUE TITLE
minor GUI bug for 2.2.5 linux desktop

### ISSUE THREAD

**Issue by kav108** [iotaledger/wallet#86]
Hi,
Enter an incorrect seed to a freshly installed iota linux desktop (mint 17.2) wallet, 
Log off.
Then enter the correct seed.
You cannot access your account with the correct seed - stuck with "logging in" at seed/pw.

The application has to be purged and reinstalled. Then the application will allow you to access your account with the correct seed.

Thank you.

**Comment by atypicalprogrammer** [comment]
What do you mean by an incorrect seed, there are no incorrect seeds in IOTA.

**Comment by kav108** [comment]
I created an account with the android app and got a seed/pw. Then I installed the desktop client, but entered the seed incorrectly: 'S' instead of 'Z'. I noticed the balance was not there and that I had input the incorrect seed, so I logged off and tried with the correct seed.
The desktop client would not let me log in with the correct seed.

**Comment by atypicalprogrammer** [comment]
A seed is just a passphrase so that should work since the app doesn't know the difference. Check view > web inspector and look at console output for any errors next time.

**Comment by domschiener** [comment]
What does "stuck at" mean. For how long was this?

**Comment by atypicalprogrammer** [comment]
Closed until user provides more information.
