### ISSUE TITLE
My IOTA Coins in limbo for over 24 hours now! Please help!

### ISSUE THREAD

**Issue by ssdsap** [iotaledger/wallet#860]
Yesterday I transferred my IOTA Coins from my Binance account to my IOTA light wallet (Version 2.5.5).

It has been well over 24 hours the funds still does not show up in my wallet.  It still shows up in History "pending" but the balance is still "0".  Actually it shows 3 transfer entries in history where as I only did transfer once.

Iotasear.ch says the status "Confirmed" in Green. But I have not received the money in my wallet? Where did the money go?

I am really worried about my money, is there any support team or someone we can contact? If I can not get the transfer into my wallet quickly, is there any way to cancel the transaction thru Binance exchange? I am really confused. This is my first transaction with IOTA. Thanks for your help.

**Comment by yippykaiyay012** [comment]
Wallet 2.5.6 is out. Use this and use a synced node. If the explorer says it's confirmed it is safe in the address. You just need the wallet and a good node to see it.

**Comment by xq0404** [comment]
The same problem occurred for me, but with Android app only. It was eventually synchronized with my desktop GUI wallet. The coins should be in the wallet. Also I have decided to keep most of my IOTAs in the Binance exchange instead of the GUI wallet.  The chances of Binance being hacked are small actually.

**Comment by ssdsap** [comment]
Hi yippykaiyay012

Thanks for the advice.

How do I upgrade my current Wallet version 2.5.5 to Wallet 2.5.6? Just
download and install the new version on top of the old version OR delete
the old one first and then start new installation of 2.5.6?

As long as I use the same Seed after upgrade/new installation of 2.5.6,
will I be able to see my coins in my desktop wallet though the receive
address is new this time?

Thanks for your time.

**Comment by xq0404** [comment]
I installed the new 2.5.6 first, then deleted the 2.5.5. It does not matter. They seem to be stand-alones. Yes, balance is there if you log in with the same seed.

**Comment by ssdsap** [comment]
Hi

Thank you all for your advice. I deleted the version 2.5.5 and installed
wallet 2.5.6 but still did not show up, however when I installed version
2.5.6 on a different laptop the whole amount showed up eventually.

Regards
