### ISSUE TITLE
Can't connect to remote node- India

### ISSUE THREAD

**Issue by rishabhkapoor8711** [iotaledger/wallet#861]
Hello, I hold IOTA for a long time now and came back to see the status. While installing light wallet 2.5.1  I picked bitfiniex local server to connect with and had no trouble transferring. While logging in now, I tried with all the possible light nodes and could not connect. Not sure, if my coins are safe or in my custody if I can't even login to the wallet provided by IOTA. Please help with this asap.

**Comment by yippykaiyay012** [comment]
Wallet 2.5.6 is out. Download and try again using a good synced node.

**Comment by rishabhkapoor8711** [comment]
Can you send me the link? Also, Where are my coins now? Will it automatically retrieve my coins in the new version of the wallet? There was no password on the wallet.

**Comment by yippykaiyay012** [comment]
https://github.com/iotaledger/wallet/releases

You log in with your seed, just as before. Your seed is your password to your wallet. 

Pick a good healthy node from here:
https://iota.dance/nodes

The iotasalad , iotatoken or iota.cafe ones a good for me.

**Comment by rishabhkapoor8711** [comment]
Thanks I was able to login automatically with the seed. But it shows 0 balance. I have near 10,000 USD IOTA. I also replaced the old wallet with this new wallet. Could you please give me details of balance?

**Comment by yippykaiyay012** [comment]
Is the iota address you sent the money to within that wallet? Is there a transaction showing? If no addresses are showing maybe it's been a while since you accessed and you need to generate the address to see the balance. Attach addresses to the tangle to find that address if it's not currently within the wallet addresses.

**Comment by yippykaiyay012** [comment]
Becuase you have said how much iota you have please be aware there are scammers trying to get your seed. They will post links where the lie about fixing seeds etc. Please do not use these sites. Always keep your seed to yourself only. Just a warning incase they post here.

**Comment by rishabhkapoor8711** [comment]
Thanks, yes none of the transactions are showing on its history or receive bar. Thanks for the caution as well. 

How do I attach the addresses to the tangle and finally view it in my wallet and use it as an easy interphase? 

Will not share my seed with anyone. 

I am a novice at this, Kindly guide me to the steps.

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/34327696-6b627cb8-e8cb-11e7-9496-f07f39384fb8.png)

click generate address   until balance shows up

**Comment by rishabhkapoor8711** [comment]
Thanks for your kindness. It is showing 9.999995 Mi. How much is this? Do I need to generate more addresses to get the entire balance?

**Comment by yippykaiyay012** [comment]
That's currently about $30. You must have sent the rest to a different address. Did you do more than 1 send? Attach more and the balance will appear if it is in that wallet.

**Comment by rishabhkapoor8711** [comment]
Yes I sent to multiple addresses and my entire balance has appeared. Thanks for the help. Will it disappear if I log in again after a long time? Why does tangle send coins to a different address each time? If I keep adding more addresses will it make any difference? 

General feedback, this isn’t quite user friendly and generally quite scary :) If I

**Comment by yippykaiyay012** [comment]
Balance will disappear when there is a snapshot. The money isn't gone, you just have to attach the addresses again. 

There is a new wallet called trinity coming out in January which will be much more user friendly. This will get rid of most of the slightly awkward parts of IOTA.

**Comment by rishabhkapoor8711** [comment]
Thanks for all your help! Please send that out in a newsletter or something if possible :)

**Comment by yippykaiyay012** [comment]
Remember to close the issue now that you are sorted. 

All the best.
