### ISSUE TITLE
Hack light wallet Lost all my iota

### ISSUE THREAD

**Issue by martingou59** [iotaledger/wallet#862]
Hello,
I send 61 Miota in my light wallet from binance but after 2 days a 

 transaction appeared in my light wallet, and I lost all my iotas....
now impossible to connect in my light wallet with my private seed but it's ok with another seed...

i think it's a hack

Is there any solution ? Thanks a lot for your help ! Merry christmas.

![1](https://user-images.githubusercontent.com/34812563/34327002-c3ecdc5a-e8b9-11e7-947c-3698c9e801df.png)

![2](https://user-images.githubusercontent.com/34812563/34327014-1cb42ff0-e8ba-11e7-8e73-eddb391d0e53.png)

**Comment by xama5** [comment]
Your seed probably got compromised. How did you generate it?
Also, I don't think your issue belongs here. It's not an issue with the wallet.

**Comment by martingou59** [comment]
I never copy my private seed somewhere else my light Wallet.. i generate at the website « official » for generate and offline 

Ah Sorry.. where i can post that ? 

Thanks

**Comment by xama5** [comment]
**Never** generate a seed online, it is **NOT** secure. And there's also no "official" seed generator, you have to generate a seed yourself on your computer.
You can get help in the #help Slack Channel, _however_, your iotas are stolen, there is absolutely no way to get them back. The channel can't help you in this situation.

To make sure this does not happen again:

- Educate yourself on how to securely generate and store a seed. Do NOT trust the first link you see, especially when it's an online generator. Use multiple sources.
- Learn how to use your wallet properly.
- Ask people in the appropriate slack channels if you're still unsure about something. Do not rely on a single person, they might be wrong.

**Comment by hoseinam1** [comment]
IOTA is a scam Because it does not have strong support and It has a fake wallet

=>https://medium.com/supercryptocurrency/iota-cryptocurrency-is-a-scam-heres-10-reasons-why-ca111de0f19a

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
