### ISSUE TITLE
not generating seeds - Light Wallet 2.5.6 - IRI 1.4.1.4

### ISSUE THREAD

**Issue by Samen12** [iotaledger/wallet#864]
Please remove above mentioned software

**Comment by janvlug** [comment]
@Samen12 Could you please elaborate and be more specific in describing the issue?

**Comment by Samen12** [comment]
I have downloaded the wallet and followed instructions provided. Once
server is linked and opened the tool, I have clicked on tools to get seeds.
I was not able to get seed

I am able to explain it in Dutch also, please let me know

**Comment by janvlug** [comment]
@Samen12 you have to [generate the seed yourself](https://helloiota.com/generate-seed.html).
Please note that this is an issue tracker. Not a support forum. For support questions I recommend the [Hello IOTA forum](https://forum.helloiota.com/).
Please close this issue if the above answers your questions.
