### ISSUE TITLE
Account shows 0-No History WTF

### ISSUE THREAD

**Issue by IOTASOCAL** [iotaledger/wallet#866]
Transferred a lot of Iota to my iota wallet on my phone. Everything shows zero. no history. Addresses on my history now gone. Same seed.  I'm beginning to wonder if this is a scam.  How the heck do you send a deposit but nobody knows where it is or you can't contact anyone.  11 mil just vanished. Cmon.

**Comment by wonkytonky** [comment]
whats the transaction id?

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
