### ISSUE TITLE
Transaction after 4x reattach still pending - How to fix?

### ISSUE THREAD

**Issue by TheCherry** [iotaledger/wallet#867]
Hi,

I have 2 IOTA wallets, the first got 9.5 Mi, then I tried to send 1.0 Mi to the next wallet.
First I attached the address to the Tangle, after that I did send the IOTA to that address.
The Transaction is still **Pending**, I tied to reattach now 4 times.

The first wallet address: https://thetangle.org/address/D9TNZUUJJDNUJBTCKXRGPLVMCKFQZZCZCPMCUXVGNBUFGOMYMYPHSZ9DOEFCHPVRVYDFYVFEGTSTRVRUD

The second wallet address: https://thetangle.org/address/EVMPRBOJPVWDXOGQKILUGDZKDISZGTXVFNIWLLZ9BPEU9ZQCRGTHWDZRMVRGLHG9XTLQEOSNBKYNSHJDY

Is it normal that the first wallet shows now -9.5 Mi ? Is it that like Electrum by Bitcoins, that the left Bitcoins gets send to a new address from the own wallet?

Thanks for your support.

**Comment by TecumsehSamp** [comment]
Looks like its confirmed.
