### ISSUE TITLE
TRANSACTION BITIFINEX TO IOTA WALLET...........110 IOTA LOST.

### ISSUE THREAD

**Issue by fredercik32** [iotaledger/wallet#870]
I try for the umpteenth time to get a solution to my problem. I did not attach the address to the tangle and I can not get my IOTA on my wallet ....

here is the transaction....always an empty wallet.... since 19/12/2017 date of my transaction request to bitifinex. Think deffinitly lost... 

ADRESS LBGCNVRUWOFMZMCBHLYRMYTWNI9JDDYQKPIMMUETE9VHGHYBVXLWEHROZIDVGAOTVAOQPDLHHTTDFQAXZUZNWVCLTW

HASH 

WUFXER9DDYMRNDYDO9MUVFJJWEGH9TTCVMKVFKKVVYEDC9RQNIWBQ9OXLNZXTPTXWGTPFRC9MWCTZ9999

**Comment by fredercik32** [comment]
And yes i have reattach the transaction many times....

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/34342929-f7b109a6-e9bf-11e7-976a-b91eb19a7e44.png)
tx is confirmed. i dont see what the problem is?   it doesnt show up on bitfinex?

**Comment by fredercik32** [comment]
The problem is that my wallet stay 0...

**Comment by wonkytonky** [comment]
you realy have to give more info ..   ,what wallet from where to where?  version. 
 how much money is still suppose to be in the wallet. 
what are the addresses that hold that money. 
etc

**Comment by fredercik32** [comment]
Transaction from bitifinex to my iota wallet version 2.5.5

Status | Completed
-- | --
Note | OK WALLET
Amount | 110.76814255 IOTA (Mi)
Wallet | Funding Wallet
Info | AddressExploreTXIDExplore | Address |   | Explore | TXID |   | Explore
Address |   | Explore
TXID |   | Explore
Created | 17-12-19 22:42:16
Permalink | https://www.bitfinex.com/withdraw/7162638

It was the first time that i use ans install the wallet on my computer...for this first time i
 did not manage to attach to the tangle but as the tutorial said it was not a problem I passed...
 Today it's easy for me to attach adress to the TANGLE ...but this first transaction never appear on it.

**Comment by fredercik32** [comment]
It was my first transaction so my iota wallet should logically indicate 110.76...

**Comment by fredercik32** [comment]
I do not understand what happened ... I do not think I typed the wrong seed. But how can i proove it know with this non attach adress...

**Comment by wonkytonky** [comment]
the address should indeed not be attached.. to recieve mone onto it. 
so you copied the recieving addres from your wallet on pc..   
and then withdrew the money  from finex to your address .. 

looking at the tangle the address the transaction did confirm  so 
the only reason why  you can't see your iota is that 
A) your seed is wrong
B) your node that you connected to is bad .. so try to change to whatever other nodes to check
C) for  some reason  your address isnt known in your wallet yet : try to generate a bunch of addresses 

in your history you can see a tab : addresse..  does LBGCNVRUWOFMZMCBHLYRMYTWNI9JDDYQKPIMMUETE9VHGHYBVXLWEHROZIDVGAOTVAOQPDLHHTTDFQAXZUZNWVCLTW 

shot up there?
![image](https://user-images.githubusercontent.com/19390834/34343081-3ea88056-e9c4-11e7-80ed-c1786e7ace7a.png)

**Comment by fredercik32** [comment]
Ok tk trying to help me.

       A---don't think but  if so, is there a solution?

       B----already try a lot of nodes and no problem to attach new adress to the dangle..

      C----i can pass a life trying having the adress LBGCNVRUWOFMZMCBHLYRMYTWNI9JDDYQKPIMMUETE9VHGHYBVXLWEHROZIDVGAOTVAOQPDLHHTTDFQAXZUZNWVCLTW  with the automatic gererate, no ?

Is it possible to manually tip an adress in wallet ? don t think....but

**Comment by wonkytonky** [comment]
A) no , you need to have the correct seed  there is no other way
C)  since there has not been a snapshot lately. your address should be already in your wallet so my guess is .; your seed is wrong. 

no you cannot manually  put address in wallet.  

the addresses are generated out of the seed based on index nummer
seed->   addres0  index 0,      seed -> addres1 index 1    and so on.

**Comment by fredercik32** [comment]
Tell me please....if i didn't have attach the adress in my wallet i'm suppose to find it in the history ??

**Comment by fredercik32** [comment]
Maybe y're right...maybe i tip a bad seed...in this case i'm stupid and my iota are lost !!!!

**Comment by fredercik32** [comment]
tk you for helping....i will by a brain...with my bitcoin.

**Comment by wonkytonky** [comment]
"Tell me please....if i didn't have attach the adress in my wallet i'm suppose to find it in the history ??"

the wallet will attach your address at some point if you generated more then 1 address so it should be there in history

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
