### ISSUE TITLE
Cannot access wallet. 

### ISSUE THREAD

**Issue by skitso** [iotaledger/wallet#871]
For about a month now I have been having major issues with the IOTA wallet. Sometimes I can't login to my account in which case I get a "Connection Refused" or other time of connection error. Then if I am able to connect to the wallet and login I can't connect to the tangle so that I can retrieve my missing funds. Anyone have any ideas? Thanks in advance.

**Comment by wonkytonky** [comment]
change node, look for better node.. ask around in forums, slack , telegram

**Comment by skitso** [comment]
I have asked multiple times on slack and never get a response. I have tried multiple different nodes nothing has worked. That's why I'm here

**Comment by wonkytonky** [comment]
have you tried in some other location ( your friends house or somthing?) i use all public nodes all the time.. i dont have much problems with connection refused.; it sometimes happens.. but then i just change node and then it works

**Comment by xq0404** [comment]
I sugest you upgrade to the latest wallet version and keep trying.

**Comment by hoseinam1** [comment]
IOTA is a scam Because it does not have strong support and It has a fake wallet

=>https://medium.com/supercryptocurrency/iota-cryptocurrency-is-a-scam-heres-10-reasons-why-ca111de0f19a

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
