### ISSUE TITLE
MY MONEY DID NOT GET TO MY WALLET - 0 BALANCE!

### ISSUE THREAD

**Issue by TN100** [iotaledger/wallet#873]
I sended IOTA from Binance to my iota wallet version 2.5.6 on my PC. Binance shows that the withdrawal was completed, but my IOTA balance in the wallet is 0.
What can I do?????

**Comment by TN100** [comment]
The transaction from Binance to my iota wallet version 2.5.6 as appears in thetangle.org is confirmed.
I have tryed number of nodes but none of them show my new balance (if that was the solution - should I see it immediately or after some time?).
I dont think the seed is the problem, as I can sign in to the wallet with no problem, so it works.
No addresses or transfers are shown in the history of my wallet.
What else can be the problem?

**Comment by wonkytonky** [comment]
if there's no history  your seed is different then the one you created your address with.. 

try changing some nodes  maybe the node you are conecting too is not synced

**Comment by TN100** [comment]
I have tried a few nodes.. it might take a long time from the moment I change it till I see my balance?

Regarding the seed I would be happy if you clarify it for me - I created a seed when creating the wallet. from that moment I didn't enter any other seed. In what situation (other than logging in) do I use the seed? 

Thank you!

**Comment by wonkytonky** [comment]
yeah it takes time for your wallet to update info from node  after you change node , you can fasten that up by loggin in again.

the only time you need seed = for login. thats it

**Comment by TN100** [comment]
It works! Just tried more nodes and for with one of them my money appeared! Thank you so much:)))
