### ISSUE TITLE
windows_32_bit_unsupported

### ISSUE THREAD

**Issue by abdulsettarova** [iotaledger/wallet#874]
windows_32_bit_unsupported why???? why not work in 32 bit ???

**Comment by hoseinam1** [comment]
IOTA is a scam Because it does not have strong support and It has a fake wallet

=>https://medium.com/supercryptocurrency/iota-cryptocurrency-is-a-scam-heres-10-reasons-why-ca111de0f19a

**Comment by abdulsettarova** [comment]
![bc14d6dacf2c975208dfdcb50ad78159](https://user-images.githubusercontent.com/20702299/34387185-c7328668-eb3d-11e7-8536-8d91e8bea19f.png)

**Comment by abdulsettarova** [comment]
make a version for 32 bits

**Comment by wonkytonky** [comment]
get a 64bit version
