### ISSUE TITLE
my iota after Charging in wallet 2.5.6 now is lost my balanc is zero without any transaction history

### ISSUE THREAD

**Issue by ali59sh** [iotaledger/wallet#875]

**Comment by loopster40** [comment]
Use another node.

**Comment by hoseinam1** [comment]
iota is a scam....not invest in it

**Comment by loopster40** [comment]
And where do you get that information?


________________________________

**Comment by praveenballa** [comment]
He is just spamming everywhere with the same FUD. Please ignore.

**Comment by loopster40** [comment]
I think you should do more research.


________________________________

**Comment by ali59sh** [comment]
after 3 days now is charg agine

**Comment by loopster40** [comment]
What is charg agine?


________________________________

**Comment by ali59sh** [comment]
my iota

**Comment by loopster40** [comment]
I do not understand your statement.

after 3 days now is charg agine

________________________________

**Comment by ali59sh** [comment]
my wallet was empty 3 days ago without any transaction
now my coins came back

**Comment by loopster40** [comment]
Dude relax...It's the node not working. Just connect to a different node. If that one does not work use another node. People who are running these nodes sometimes their server is down for whatever reason. It happens, it's normal. Iota works as in a chain of computers. Try this node http://5.9.118.112:14265 I have not had any issues with it. You got to remember this coin is in beta. In the beginning, you will have issues, but they all will be fixed. I have had the same issues and I have all my iota.


________________________________

**Comment by ali59sh** [comment]
thanks alot but i tried all nodes many time 3 days and i cant see my coin 
but now is right

**Comment by loopster40** [comment]
http://www.iotasupport.com/lightwallet.shtml#list

[http://www.iotasupport.com/images/headerlogo.png]<http://www.iotasupport.com/lightwallet.shtml#list>

Light Wallet Servers / Load Balancing Service - IOTA Support<http://www.iotasupport.com/lightwallet.shtml#list>
www.iotasupport.com
Click here or scroll down for the list of lightwallet servers. In IOTA, a Lightwallet is a wallet that connects remotely to a Server on which the IOTA IRI is running.





________________________________

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
