### ISSUE TITLE
0 Balance After Transfer

### ISSUE THREAD

**Issue by uzielroy** [iotaledger/wallet#877]
I cant see the transfer in history.. 
what should i do?

I tried different nodes.
I tried to generate new addresses .
v 2.5.6

https://thetangle.org/transaction/MEMGGAHQWGPSWULKMEALIYCSQN9GLFXLBBZMDDJNXMEWJBKYKAOTPOTJCYVPBHUT9SLWQTQDH9PRZ9999

**Comment by wonkytonky** [comment]
![image](https://user-images.githubusercontent.com/19390834/34359528-16173c6e-ea59-11e7-99a8-ce2b792aefd2.png)
can you find the address you created . and where the money arrived on tangle.. in your history?

**Comment by uzielroy** [comment]
Can't see the address in the history.
It was my first one i ever created.
I now have plenty of new addresses I created, but no one is the same as the one i was looking for

**Comment by wonkytonky** [comment]
if you cannot see your first addres.  your seed is probably wrong.

**Comment by uzielroy** [comment]
i can see addresses, but not the one the was used for the transfer. 
i probably didnt attached it to tangle.

what should i do?

**Comment by rajivshah3** [comment]
Please don't post help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
