### ISSUE TITLE
moving coins to Binance

### ISSUE THREAD

**Issue by MKD68** [iotaledger/wallet#878]
I have been trying to move my coins to trade to Binance but I keep getting this error message for 3 weeks
I have tried the following:
Updating dangel
changing node info

ERROR: PRIVATE KEY REUSE DETECTED!

You are attempting to sign a transaction with input that have an already been used. IOTA uses Winternitz one-time signature (W-OTS) scheme, due to it's `one-time` nature, the security of funds in an address decreases rapidly if you re-sign new transactions using the same key. Please wait for previous transaction to confirm, e.g. by reattaching, before sending another transaction.

Please help

**Comment by wonkytonky** [comment]
you probably have on old outgoing tx that not confirmed yet try to reattach /promote it.; be sure that one is "ok" to send out.. otherwise wait till next snapshot

**Comment by MKD68** [comment]
Sorry dont understand..what is old tx and how do i promote it?

Thank you

**Comment by praveenballa** [comment]
HI @MKD68, 

Please read, understand and follow the instructions from here about reattach from the "HOW TO BUY" section from here: 

[https://iotaprices.com/](https://iotaprices.com/)

Please close the ticket, if this is resolved.

**Comment by hoseinam1** [comment]
IOTA is a scam Because it does not have strong support and It has a fake wallet

=>https://medium.com/supercryptocurrency/iota-cryptocurrency-is-a-scam-heres-10-reasons-why-ca111de0f19a

**Comment by rajivshah3** [comment]
Please don't post issues/help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
