### ISSUE TITLE
missing address checksum

### ISSUE THREAD

**Issue by propertygeek** [iotaledger/wallet#879]
after looking at the iota support instructions on inserting the address by going to (view) clicking toggle web inspector... this option is not showing. cant send to this address
WXLRRACTJOYHUTUZUARSJIIKQDHCUZSCKITSVFUM9SKTHHVHDOFFBKMBICGNHJMPTNSJGCLHWFBTE9RUY

**Comment by rajivshah3** [comment]
Try this address: WXLRRACTJOYHUTUZUARSJIIKQDHCUZSCKITSVFUM9SKTHHVHDOFFBKMBICGNHJMPTNSJGCLHWFBTE9RUYBBCSASXUD
