### ISSUE TITLE
Invalid transaction hash

### ISSUE THREAD

**Issue by lukisi** [iotaledger/wallet#88]
In date 6/6/2017 I did a transaction. The latest releases were then: GUI 2.2.5 - IRI 1.1.4.2.
I had the GUI in light-wallet mode connected to http://service.iotasupport.com:14265.
For some reason the transaction did not confirm.

Today I installed the GUI 2.2.6 and the server at http://service.iotasupport.com:14265 is 1.1.4.3 and the milestones are ok.
In the pending transaction of yesterday, I clicked RE-ATTACH. After the PoW the GUI said: Invalid transaction hash.
I retried a couple of time at eventually it said RE-ATTACH COMPLETED.

I am attaching screenshots:
02.png. when the button was "RE-ATTACH"
03.png. when the report said "RE-ATTACH COMPLETED"
04.png. what is now reported as "Confirmed"

Unfortunately I don't have a screenshot when it said "Invalid transaction hash".

See that the bundle hash is different in 04.png.

**Comment by lukisi** [comment]
![04](https://user-images.githubusercontent.com/17383110/26870056-fae15f08-4b6e-11e7-852f-de676adf03b0.png)
![03](https://user-images.githubusercontent.com/17383110/26870057-fae369ba-4b6e-11e7-991c-2e71bf4cf07e.png)
![02](https://user-images.githubusercontent.com/17383110/26870059-fb6d33a2-4b6e-11e7-96db-da48f39209b8.png)

**Comment by lukisi** [comment]
02.png

![02](https://user-images.githubusercontent.com/17383110/26870105-257a0724-4b6f-11e7-9b55-c4c9ca4e2931.png)

**Comment by lukisi** [comment]
03.png

![03](https://user-images.githubusercontent.com/17383110/26870132-39af3a0c-4b6f-11e7-89df-6b2a452b9d3f.png)

**Comment by lukisi** [comment]
04.png

![04](https://user-images.githubusercontent.com/17383110/26870140-42ae4b48-4b6f-11e7-823b-20698801754e.png)

**Comment by lukisi** [comment]
In the transaction I specified an (optional) tag. Just saying.

**Comment by lukisi** [comment]
I have encountered it again while attaching an address to the Tangle.
With GUI 2.3.0 on IRI 1.2.0 on a synced service.iotasupport.com node.
Then I retry and it works.

**Comment by domschiener** [comment]
We're aware of this issue, probably related to ccurl. Will be fixed in latest release.
