### ISSUE TITLE
error message says private key whatever reciving address i input

### ISSUE THREAD

**Issue by propertygeek** [iotaledger/wallet#882]
VJNCIIACKHVECGKTHUR9WG9TCOMQPZIOYUGESOP9JPHTKOYSRDQLQEBMQOPBKWFICLXTCMBLQZBVPUZDYXWZDIXETW

**Comment by propertygeek** [comment]
ERROR: PRIVATE KEY REUSE DETECTED!

You are attempting to sign a transaction with input that have an already been used. IOTA uses Winternitz one-time signature (W-OTS) scheme, due to it's `one-time` nature, the security of funds in an address decreases rapidly if you re-sign new transactions using the same key. Please wait for previous transaction to confirm, e.g. by promoting/reattaching, b
ERROR: PRIVATE KEY REUSE DETECTED!

You are attempting to sign a transaction with input that have an already been used. IOTA uses Winternitz one-time signature (W-OTS) scheme, due to it's `one-time` nature, the security of funds in an address decreases rapidly if you re-sign new transactions using the same key. Please wait for previous transaction to confirm, e.g. by promoting/reattaching, before sending another transaction.efore sending another transaction.

trying to send to binance on the addresses  they generate but wallet wont accept them

**Comment by wonkytonky** [comment]
you have an old transaction still pending that needs to confirm first. go to history and make it confirm..

**Comment by dwest2** [comment]
I have the same problem with the ERROR: PRIVATE KEY REUSE DETECTED! No transactions are pending. What next?

**Comment by dwest2** [comment]
I know one of the developers said 100% of the time it is an error from us, the user. I also found on one of my accounts, the public key (and I am guessing the private key) was being used already. I mistakenly sent coins to that account and can not transfer the coins out because of the ERROR: PRIVATE KEY REUSE DETECTED! Also, why are transactions pending for days? (I reattached and rebroadcast). Why are the paper wallet random key generator duplicating keys? Can a developer please explain?

**Comment by hoseinam1** [comment]
iota is a scam....not invest in it

**Comment by hoseinam1** [comment]
IOTA is a scam Because it does not have strong support and It has a fake wallet

=>https://medium.com/supercryptocurrency/iota-cryptocurrency-is-a-scam-heres-10-reasons-why-ca111de0f19a

**Comment by propertygeek** [comment]
thank you for the replies . I have one transaction pending for just 3 iota that was sent as a test. after 3 days trying all sorts of reconnecting logging in and whatever I can find on making a transaction confirm it still shows as pending . is it correct that I will get the error privet key reuse detected on everything else I want to send until this tansaction has confirmed . also any other sugestions on how I can force it to confirm any help much apreciated

**Comment by propertygeek** [comment]
SRYZLRHUHDUWVCGLWVUDKQHSOCHRELDPURLUIRFQEA9LCXRTCOHWZMPQVAL9BLFCSKHVB9ZBPQVQRJRZBRZDDKDBKC  always shows pending

**Comment by rajivshah3** [comment]
Please don't post issues/help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
