### ISSUE TITLE
http://iota.bitfinex.com:80-bitfinex node not working for 1 week now

### ISSUE THREAD

**Issue by CryptoResponse** [iotaledger/wallet#883]
Hi,

http://iota.bitfinex.com:80 

This particular node is not working since a week now. I have funds in my bitfinex account and need to transfer, however, it has connections issues and when I try to attach the tangle it gives "No Response" error.

Can you please help at your earliest.

Regards,
Syed

**Comment by hoseinam1** [comment]
iota is a scam....not invest in it

**Comment by hoseinam1** [comment]
IOTA is a scam Because it does not have strong support and It has a fake wallet

**Comment by hoseinam1** [comment]
https://medium.com/supercryptocurrency/iota-cryptocurrency-is-a-scam-heres-10-reasons-why-ca111de0f19a

**Comment by samgranger** [comment]
Are you running the latest version of the wallet? You are not required to use the bitfinex node so trying a different node might fix your issue if you're already running the latest version.

**Comment by rajivshah3** [comment]
It seems like the bitfinex node has been out of sync for a while now. Try a different node, you can check http://iota.dance/nodes for a list
