### ISSUE TITLE
Private Key Re-Use Detected

### ISSUE THREAD

**Issue by chronic8000** [iotaledger/wallet#887]
Having a problem where it says:

ERROR: PRIVATE KEY REUSE DETECTED!

You are attempting to sign a transaction with input that have an already been used. IOTA uses Winternitz one-time signature (W-OTS) scheme, due to it's `one-time` nature, the security of funds in an address decreases rapidly if you re-sign new transactions using the same key. Please wait for previous transaction to confirm, e.g. by promoting/reattaching, before sending another transaction.

CLOSE

I have re-attached and rebroadcast all previous transactions, changed nodes and nothing helps. Can't seem to get any support elsewhere either. @bitcoinmayhem on Twitter.

**Comment by hoseinam1** [comment]
iota is a scam

**Comment by hoseinam1** [comment]
https://medium.com/supercryptocurrency/iota-cryptocurrency-is-a-scam-heres-10-reasons-why-ca111de0f19a

**Comment by hoseinam1** [comment]
IOTA is a scam Because it does not have strong support and It has a fake wallet

**Comment by praveenballa** [comment]
@hoseinam1 All the issues that were pointed were already refuted. Please read on the updates :)

**Comment by hoseinam1** [comment]
**praveenballa**  No, I can not transfer money from my wallet yet

=>https://iotasear.ch/bundle/MIKGX9TQFQZJI9IWURRKGANKFL9HBBTKDPQJTBCWYISG9KCDQAEGFY9YYTHHSAXDDFOTYYETZVAJIIBPY

**Comment by hoseinam1** [comment]
Developers  IOTA do not care about users' problems

**Comment by hoseinam1** [comment]
IOTA coin not has support

**Comment by praveenballa** [comment]
STOP SPAMMING, will ya? 👎 I wanted to help but you are really obnoxious.

So, you spread all this fud for this? Did you try changing your node, try to relogin and check?

**Comment by hoseinam1** [comment]
**praveenballa** no I changed the nodes...
This is my question?
Why is technology iota too weak? Why iota did people deceive?

**Comment by praveenballa** [comment]
@hoseinam1 First of all, IOTA is not weak. It is a "beta" software. I don't understand why you keep saying deceive, when you can't even follow simple instructions. bye!

**Comment by chronic8000** [comment]
I have tried changed node to one with 10 health. Running latest wallet. Still no joy. @hoseinam1 stop hijacking threads.

**Comment by wonkytonky** [comment]
can you show us the address you want to spend from?

**Comment by rajivshah3** [comment]
Please don't post issues/help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!

**Comment by chronic8000** [comment]
@rajivshah3 no I can't post on forum as I couldn't sign up.

**Comment by rajivshah3** [comment]
Try the new forum, http://forum.helloiota.com

**Comment by chronic8000** [comment]
Never mind it's different than the forum I found before. I will sign up now.

**Comment by chronic8000** [comment]
Yeah didn't realize their was a new one.
