### ISSUE TITLE
After 2 months, updates, diffrent nodes, still zero balance

### ISSUE THREAD

**Issue by vinotinto** [iotaledger/wallet#889]
I'm the only one who don't get his reclaim back after all that time? After al the updates, reclaim, diffrent adress and nodes...still zero balans.

Have the dev team start to refund?

Greets,

Vino

**Comment by johnvamo** [comment]
Same situation...Zero balance...
When the foundation would give back the balances???

**Comment by rajivshah3** [comment]
The foundation has begun sending back reclaims. Please don't post issues/help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
