### ISSUE TITLE
I lost some iota.

### ISSUE THREAD

**Issue by Tedley54** [iotaledger/wallet#891]
I can't seem to figure out how all this stuff works I guess I'm just a little too old for it.
I tried to use an Iota wallet it didn't hook up it didn't give my Iota from Finance to my wallet and I think it's gone maybe forever?
Anyway I guess I just screwed up and I don't know if I just should forget about it or try and find it or what to do so I thought I'd just let you knowso I thought I'd just let you know

**Comment by Mcelroy-sg** [comment]
si te sale que esta pendiente el envio en la wallet?no deberias preocuparte no desaparece asi como asi. verifica que la direccion a la que lo enviaste es la misma en el wallet abajo pone las direcciones usadas y los montos de dinero recibido y enviado si tu saldo sale como pendiente entra en el paquete y dale a reattach para que se vuelva a vincular al tangle

**Comment by rajivshah3** [comment]
Please don't post issues/help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
