### ISSUE TITLE
Large number of transactions showing in wallet and not processing

### ISSUE THREAD

**Issue by AriaX3** [iotaledger/wallet#892]
**The Situation:**
- I run the latest version of IOTA light wallet 2.5.6.
- I have only used this wallet address to receive 1 transaction.
- I logged on today in order to send the funds from that wallet elsewhere.

**The Problem:**
- When I logged into the wallet, there was 30 transfers showing in the history which I know nothing about.  All of these show the green inbound icon.  All 30 look to be identical and only one of them is confirmed.  The rest are pending.

- I have tried to send my funds to another address.  However these now also seem to be stuck with pending message.  I've tried to reattach to tangle and rebroadcast, but this has done nothing expect to create a 2nd copy of the transactions in my histroy.  So now I have a total of 32 transactions showing in history and the status of those has not changed in 6 hours.  Occasionally I'll get high CPU usage by the wallet but still nothing progressing.  I have tried connecting to another node, but that didn't seem to make a difference.

I would greatly appreciate any advise.

**Comment by rajivshah3** [comment]
Please don't post issues/help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
