### ISSUE TITLE
I CAN NOT CONNECT WITH TANGLE LIGHT WALLET 2.5.6

### ISSUE THREAD

**Issue by hugor49** [iotaledger/wallet#895]
I HAVE INSTALLED A FEW DAYS THE VERSION 2.5.6 OF IOTA WALLET, I CONFIGURE IT AND I CONNECTED IT WITH ANY HOST, I KEEP THE KEY AND THE SESSION BEGINS, BUT WHEN ATTEMPTING TO CONNECT WITH TANGLE, IT TRY TO CONNECT FOR A FEW SECONDS AND THEN THE SCREEN IS IN BLACK AND ALTHOUGH I HAVE LEFT YOU A WHOLE DAY DOES NOT CONNECT. CAN YOU HELP ME?

**Comment by Moongazer** [comment]
Where do you enter the seed? I have just a blank wallet screen (with the IOTA logo in the background), no input field or anything to enter the seed... Very strange! (Windows 8.1)

**Comment by hugor49** [comment]
i THINK YOU MUST EDIT THE NODE CONFIGURATION AND SELECT ONO OF THEM


________________________________
De: Moongazer <notifications@github.com>
Enviado: viernes, 29 de diciembre de 2017 7:10
Para: iotaledger/wallet
Cc: hugor49; Author
Asunto: Re: [iotaledger/wallet] I CAN NOT CONNECT WITH TANGLE LIGHT WALLET 2.5.6 (#895)


Where do you enter the seed? I have just a blank wallet screen (with the IOTA logo in the background), no input field or anything to enter the seed... Very strange! (Windows 8.1)

**Comment by rajivshah3** [comment]
Please don't post issues/help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
