### ISSUE TITLE
pending 3 days

### ISSUE THREAD

**Issue by farshadkhoshbakht** [iotaledger/wallet#897]
Hi 
I bought IOTA  from binance and there is complete but in my Iota wallet windows is pending yet after 3 days . this is my wallet address 
JDFTDBRFHTALYWWIONBGTLNROJQYOKNFKASUWWKZIPFMJILYKUNYLOPMSNVXNDLORFOIKJZNS9TVXWYGCPHXZCFBOX

**Comment by wonkytonky** [comment]
it's also confirmed on the iota network. 
change node and look if the milestones are up to date (below on wallet)

**Comment by rajivshah3** [comment]
Please don't post issues/help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
