### ISSUE TITLE
IOTA light wallet broken

### ISSUE THREAD

**Issue by davidmoldenchen** [iotaledger/wallet#899]
After managing to create the wallet and deposit my IOTA coins it will now not allow me to log in and gives me an error message 'CONNECTION REFUSED'. Anyone know what's going on here? Is it some bad coding, or are hackers involved? Is anyone looking at this problem with a fix?

**Comment by davidmoldenchen** [comment]
I am using IOTA light wallet, 2.5.4 which I'm pretty sure is a scam wallet. It looks good, but doesn't work. It allowed me to deposit my coins and now will not give me access - I just get the error message 'CONNECTION REFUSED' when I try to log in. I believe my coins have been stolen ... so watch out, this wallet is not good to use guys!

**Comment by yippykaiyay012** [comment]
2.5.6 is out. 

Use it and a good synced node. 

Good job immediately jumping to scam because of user error though.

**Comment by davidmoldenchen** [comment]
OK, thank you - there is so much info about scam wallets, so it’s not such a big leap to make if you are unable to access your coins and the wallet has no ‘contact us’ email or phone number.

So I will look for this new version and try it - but I don’t know how to use a ‘good synced node’ - could you elaborate on this please? What does it mean I have to do?

Thank you for responding. I will try and find a link to 2.5.6

David.

David Molden
+44(0)7710476710
davidmoldenchen@gmail.com

**Comment by yippykaiyay012** [comment]
Iota.dance/nodes shows a list of nodes. You can see if they are in sync and connect the wallet to one.

**Comment by davidmoldenchen** [comment]
Someone, yipikaiyay mailed me to say there's a new version, 2.5.6 which I loaded, and yes, it has fixed the problem. I can now log in and see my coins. So a big thank you to yipikaiyay.
