### ISSUE TITLE
GUI Spammer 1948 Bug

### ISSUE THREAD

**Issue by project-Shift** [iotaledger/wallet#9]
Not really a wallet issue, but related to atypical's GUI, but I think we can consider it under this scope :-)

The Network Spammer function always stops working when it hits 1948 tx
This as happen every time I run the spammer, with either version 1.0.4 or 1.0.5 (can't remember if it happened in the previous version)
It simply stays stuck in getting tips, no matter how much time goes by.

Tested and verified in Windows Server 2012 R2, Java 64 bit 1.8 build 101, running in a VM with an Hyper-V environment

**Comment by domschiener** [comment]
As discussed in Slack, quite a weird bug. Would greatly help if you can answer the following questions @project-Shift 

- Did you have this problem with 1.0.3?
- What happens after the 1948 limit is reached? 
- Does IRI continue to run after the limit is reached?
- If yes, can you still make normal transactions (not spammer ones)? 
- What is the console output (check Server Log), any specific error, if so, can you past the stack trace?

**Comment by project-Shift** [comment]
Can't remember if the issue happened with 1.0.3, but the node was running only in 4 cores back then, so it was slower than now and took close to a week to get there, which means I probably stopped it before said limit - you can't login or do anything when the GUI is spamming (except check logs and related stuff)

What happens is that the node stops spamming (CPU activity disappears) and the getting tips operation stays on forever - no progress from then on until you stop it. Restarting the spammer goes ok, back from 0 tx

I think IRI is ok, but I'll check it with nostalgia the next time and post more details; same goes for server log, I'll get a sample when it reaches the limit and post the results

**Comment by project-Shift** [comment]
btw, spammer in on 1123 tx right now, so a few more hours before I have new information

**Comment by project-Shift** [comment]
ok, here are  the details:

IRI is definitely working, nostalgia is able to get a response (Y)

The error in the logs are the same:  Invalid hash and GC limit (sample below)

Transactions to request = 53 / 632065 (43 ms)
Transactions to request = 53 / 632065 (44 ms)
java.lang.RuntimeException: Invalid transaction hash
	at iri.Transaction.<init>(Transaction.java:132)
	at iri.Node.lambda$launch$0(Node.java:49)
	at java.lang.Thread.run(Unknown Source)
Following coordinator address = C9KDHJKGKPUKQCYWTEFRARFQHQ9GHPBCESACJRLQYMOVUEJ9QURJZMCDQWOKNKL9Z9STOTHFKSCHTYUOF (21051)
Transactions to request = 53 / 632065 (43 ms)
Transactions to request = 53 / 632065 (45 ms)

Transactions to request = 54 / 632076 (44 ms)
Transactions to request = 54 / 632077 (45 ms)
Exception in thread "pool-1-thread-185" java.lang.OutOfMemoryError: GC overhead limit exceeded
Following coordinator address = BIDBWXF9VNURU9W9JFHJVYCCHU9KNYKGPK9HUMHKRWEMISBNGGPEVSGSNBX9CELLVSN9HZVHLJCHYGHTC (21055)
Transactions to request = 54 / 632078 (44 ms)
Transactions to request = 54 / 632078 (45 ms)

So, I guess all it might need is the recent fix :-) I'll upgrade now and restart spamming away.
My felling is that the heap memory limit you removed in 1.0.5.1 is enough to solve this issue, since it's probably what it causes the spammer to fail.
The errors started around tx 1870 ...

I'll let you know tomorrow. Meanwhile, if one somebody else could also teste, it would be great - I can't recall who, but there was at least one more that referred the 1948 bug  and someone else but with a different number.

**Comment by project-Shift** [comment]
:-(  1.5.0.1 spammer.

It didn't solve the issue. It got stuck at 1948 tx anyway.
Can no longer see GC errors, but invalid TX keeps popping up

**Comment by project-Shift** [comment]
Hi!  Behavior is confirmed, no GC errors, just invalid hash, like this sample:

Transactions to request = 608 / 770918 (46 ms)
Following coordinator address = CLYTBBNPQBNYNVIWBVTSIFZUKVRYBDYYQCPMDUMCYDVGWVBZWSLUQFFPKUOOOOVQOGLODOM9UAWMIMPJL (25176)
Transactions to request = 608 / 770920 (47 ms)
Following coordinator address = WGLGJSOKUGOWMCAJWUNZOMWBCPGNQOIWXK9LW9HZGC9MPRFVAOLLMJIZDNDVOBMFRXQMIJRIEQZDRYTMF (25177)
Following coordinator address = WGLGJSOKUGOWMCAJWUNZOMWBCPGNQOIWXK9LW9HZGC9MPRFVAOLLMJIZDNDVOBMFRXQMIJRIEQZDRYTMF (25177)
java.lang.RuntimeException: Invalid transaction hash
	at iri.Transaction.<init>(Transaction.java:132)
	at iri.Node.lambda$launch$0(Node.java:49)
	at java.lang.Thread.run(Unknown Source)
Transactions to request = 608 / 770920 (46 ms)
Following coordinator address = WGLGJSOKUGOWMCAJWUNZOMWBCPGNQOIWXK9LW9HZGC9MPRFVAOLLMJIZDNDVOBMFRXQMIJRIEQZDRYTMF (25177)
Transactions to request = 608 / 770920 (47 ms)
Following coordinator address = WGLGJSOKUGOWMCAJWUNZOMWBCPGNQOIWXK9LW9HZGC9MPRFVAOLLMJIZDNDVOBMFRXQMIJRIEQZDRYTMF (25177)
Transactions to request = 608 / 770920 (45 ms)

It still get's stuck at 1948 TX every time, node still responds to nostalgia, can see all info from GUI's menu.

**Comment by domschiener** [comment]
I will try and take a look next week. If you have time @atypicalprogrammer, please take a look

**Comment by atypicalprogrammer** [comment]
@project-Shift please confirm if this still occurs with latest release.

**Comment by atypicalprogrammer** [comment]
Closed until more info is supplied.
