### ISSUE TITLE
Dear maintainer of the wallet's list of nodes - Chris is trying to contact you, users need more public servers, please add in the list http://cryptoiota.win:14265.

### ISSUE THREAD

**Issue by ALEX778899** [iotaledger/wallet#901]
Dear maintainer of the wallet's list of nodes,
the developer Chris is trying to contact you, light wallet users need more public servers, there are a few public servers and many have an insane load. I've asked already with https://github.com/iotaledger/wallet/issues/823 but nobody replied. I contacted the developer Chris and he told me he isn't the maintainer of the lists of node and he's trying to contact you.
I'm helping as much as I can because I really believe IOTA will bring freedom and a better future.
I'm even keeping alive with my money a reliable public node (24/7 powerful dedicated server in data center), it's a pity, now has 1% load only, PLEASE INSERT IT IN THE WALLET'S LIST so more wallets can use it.

Status address: http://www.cryptoiota.win
API address for the wallet http://cryptoiota.win:14265

I hope to receive good news from you soon, thanks in advance, best regards

**Comment by wonkytonky** [comment]
not a wallet issue: please close

**Comment by ALEX778899** [comment]
Hi @wonkytonky, many expert members in the community told me to open a issue here, it seems the only way. I'm trying to help and I hope this isn't a clan, but if you know another system you're welcome :-)

**Comment by rajivshah3** [comment]
Hi, try asking iota.dance in slack to list you on his site

**Comment by brunoamancio** [comment]
Add it yourself by forking the repo, adding your entry, and creating a PR to master.

**Comment by rajivshah3** [comment]
Just double checked, it looks like it's getting the list from https://iotasupport.com/providers.json. Try contacting Scott J in Slack, I think he owns that site

**Comment by ALEX778899** [comment]
@rajivshah3, I wrote a message to Scott J in Slack, I hope he'll insert soon. Could you please ask him too? Thanks in advance
