### ISSUE TITLE
2.5.6 NO BALANCE

### ISSUE THREAD

**Issue by jskillz860** [iotaledger/wallet#902]
I downloaded version 2.5.6 light wallet to my Mac, transferred my iota from binance and for a brief second it showed my balance after transfer then it was gone, I have read multiple forums and tried switching nodes and generating new addresses multiple times, attaching to tangle multiple times, between 20 and 30 times, and I still have no balance, where are my funds???

**Comment by rajivshah3** [comment]
Please don't post issues/help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
