### ISSUE TITLE
Time for transaction to complete?

### ISSUE THREAD

**Issue by davidmoldenchen** [iotaledger/wallet#903]
I made my first test transfer off 11 IOTA into Binance and it's taken over 6 hours and is still pending. There are two boxes to press when you click Show Bundle - to Rebroadcast and Reattach. There is no description explaining what these do. So I pressed Rebroadcast, and it's still pending. I just clicked Reattach and it has now changed to a button saying PROMOTE. I have no idea what this button is supposed to do, and my transaction is still pending. So, does zero fees and the absence of miners mean that transactions will take a very long time?

**Comment by wonkytonky** [comment]
"So, does zero fees and the absence of miners mean that transactions will take a very long time?"
no  just have to learn how to use these features.. i suggest to look  in slack, forums, telegram  etc. 

but in short : whenever you do a tx .; keep hitting that reattach/promotion buttion  until it confirms.  most of my tx go trough between 4min to 20min   

reattaching and promoting is part of the tangle

**Comment by davidmoldenchen** [comment]
Thank you wonkytonky ..... I'll try that. It just completed about 30 mins ago, so lets see if I can improve on that.
