### ISSUE TITLE
IOTA stolen with unauthorised transaction

### ISSUE THREAD

**Issue by frankang** [iotaledger/wallet#904]
My friend invested in IOTA recently on bitfinex. But after several days when he moved the IOTAs from the exchange account to his wallet, an unauthorised transaction was made and all IOTAs are gone now(the receiving address was used only once). He did not use an online seed generator, but his se/ed is 4 characters repeated 20 times plus 9. Could this be the vulnerability? Any suggestions are appreciated.

The IOTA flow path, FYI.
MCYKNNURJZMCXWFO9RH9OANTQBOGGNCIPBREPTPKPG99FAHGDR9AJ9MCALUG9BYBCJNZKJUVAS9FTJXPAUXVOTKMNW (my friend's address)
->
CUTOEQYIQRHMREXNEEIS9XIZFXLBKGUWMQFKINP9HOTD9WOQUOAQRLCQUZCXSBTWC9DQUCFZGRQCVQUGCOWENRCDTW
[the bundle info](https://iotasear.ch/bundle/SCFCFHEJGIUOVHB9BDNLHOKYOONWODDOOCJGFC9GLQLGILXZEFDKJJWKYQGWGEKFOOVHTAFPJNE9IFVAB?preload)
->
QCGMBJSVHCUFKAEVOIT9CBVVC9WDK9BDIUXNCQXKQUPWIQGMYVHIAFBYUIQMYHOXRGK9HRVZG9ST9IEYBBIGVCPJCZ

**Comment by wonkytonky** [comment]
thats a very week seed indeed.   use  81 random chars next time..  ppl run password dictionaries against the tangle all the time to catch these week passwords

**Comment by frankang** [comment]
@wonkytonky thanks, what is ppl by the way?

**Comment by wonkytonky** [comment]
people :)
