### ISSUE TITLE
Error Private Key Reuse Detected How to Fix this??? Iota Light Wallet 2.5.6

### ISSUE THREAD

**Issue by mardebtx** [iotaledger/wallet#906]
![screen shot 2017-12-28 at 9 23 16 pm](https://user-images.githubusercontent.com/9908012/34443832-5f63eea2-ec8f-11e7-9cf5-e61477bd5a16.png)
How can I fix this? My account is completely unusable to send iota. I have tried reattaching the pending transactions in my history and it will tell me I dont have enough iota and won't complete. I do have enough iota in my account but have no access to it. How am I going to be able to get access to my iota? Can I use the reclaim tool? Can I make a second iota wallet account on the same device? Please help.

**Comment by BTExpress1** [comment]
I have the same error message. All my transaction are confirmed and one shows pending after it was reattached and confirmed. This is the Hash for it: NUWYLLDIYODIVFPPGCYIWZSUQPHMURZEAQFSHWBEOYKVVDJUJUSZLP9TWDSHGYCPP9HRQRQO99FJ99999.

This is the only thing I see pending but like I said it is reattached and confirmed. So how do I get rid of the error message?

**Comment by wonkytonky** [comment]
@BTExpress1  it looks like your tx is confirmed

**Comment by rajivshah3** [comment]
Please don't post issues/help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
