### ISSUE TITLE
Invalid Mnemonic - Unable to Restore Seed

### ISSUE THREAD

**Issue by TheHeshmat** [iotaledger/wallet#909]
Hi, I have previously created a seed using https://iotaseed.io/ and have saved the Mnemonic phrase. Now I have been logged out from IOTA wallet so I'm trying to decode the mnemonic phrase to access my wallet, but I'm getting the error (Wrong words, word-order or parity word)
I have also tried decoding it on https://www.ledgerwallet.com/support/bip39-standalone.html#english
but no luck either.

Is there any way I can restore my seed? 
I have tried generating another seed and backed up the 36 phrase, and they also do not seem to generate the seed, so it does seem to be an issue with the recovery phrase generated on iotaseed, rather than mine being incorrect

Update: Issue resolved - there seems to be a glitch with the page as after a number of trials, the seed was finally generated

**Comment by wonkytonky** [comment]
https://iotaseed.io/ is a scam ssite..  never generate seeds online.. if you can move your money out to new seed

**Comment by rllybadcryptotrdr** [comment]
Dude. Did you get robbed? If you didn't, you will.
