### ISSUE TITLE
Suggest to add a note on the Log in, Send, and Receive pages for checking the syncing status before users doing anything

### ISSUE THREAD

**Issue by Tobo01** [iotaledger/wallet#91]
Because tangle is new and its syncing is different from blockchain, many new users don't know how to check the syncing status and assume the wallet is always synced especially for the light wallet when thay are make transactions or replays (we all know that the light wallet can be not synced from time to time).

I suggest that on the Log in and the Send and Receive pages add a note that says something like "Make sure your wallet is synced before you do anything. Check the Status Bar (making the status bar visible by default) on the bottom left of your wallet. If the first two numbers are same and equal to the latest milestone number in #botbox in IOTA Slack, your wallet is synced. Otherwise it is not."

**Comment by domschiener** [comment]
Actually, a user cannot login unless the node is synced.
