### ISSUE TITLE
Пропали средства с кошелька IOTA

### ISSUE THREAD

**Issue by gorunuchs** [iotaledger/wallet#910]
Вчера хотел перевести 341,6 IOTA с кошелька на биржу binance. Запрос обрабатывался 6 часов, в результате средства были списаны, история транзакций стерлась, а средства на биржу не поступили

**Comment by rajivshah3** [comment]
Hi, would you mind translating your issue into English and then reopening this? Thanks

**Comment by sarmat555sar** [comment]
hello
