### ISSUE TITLE
Error getting out. Says there is a pending transaction

### ISSUE THREAD

**Issue by daniezlt007** [iotaledger/wallet#912]
You are attempting to sign a transaction with input that have an already been used. IOTA uses Winternitz one-time signature (W-OTS) scheme, due to it's `one-time` nature, the security of funds in an address decreases rapidly if you re-sign new transactions using the same key. Please wait for previous transaction to confirm, e.g. by reattaching, before sending another transaction.

OBS: Already pending for more than 15 days

**Comment by rajivshah3** [comment]
You need to reattach/promote until the transaction is confirmed. Please do not post issues/help requests like this on GitHub, they belong on the [forum](forum.helloiota.com). Thanks!
