### ISSUE TITLE
Norton removed .exe while trying to install

### ISSUE THREAD

**Issue by whitegloves18** [iotaledger/wallet#913]
Norton would not allow windows system to install saying it was a medium risk:
WS.Reputation.1

is this normal?

**Comment by wonkytonky** [comment]
if your wallet is from official github  iota release . it's ok

**Comment by whitegloves18** [comment]
Thanks-
I’d heard there are “fake” sites that will set up so they can steal your tokens...and this warning scared me. It’s just cause this is all so new to me. Im A bit skeptical and cautious.

**Comment by rajivshah3** [comment]
Hi, this is because the wallet is currently not signed. Since the IOTA Foundation is now officially registered, I think signed wallets will come soon that will certify that they are from the foundation.

**Comment by whitegloves18** [comment]
Thank you for the reply- and re assurance. I’m new to crypto currency, so my skepticism is high, cautious really.

Thanks
