### ISSUE TITLE
HELP!! IOTA WALLET NOT SHOWING BALANCE AFTER I TRANSFERRED FROM BINANCE

### ISSUE THREAD

**Issue by jkharris123** [iotaledger/wallet#915]

**Comment by cleto123** [comment]
Hi there. I'm having the same issue. Have you received your Iota yet? I know I copied the right address, and the transaction is complete on the half of Binance. If I had read up more on this wallet and the issues they have been having, I might have just left it there. Do you know if we can send Iota to myetherwallet?

**Comment by rajivshah3** [comment]
@cleto123 you cannot send IOTA to MEW, IOTA is not an ERC20 token

**Comment by rajivshah3** [comment]
@jkharris123 Please do not post issues/help requests like this on GitHub, they belong on the [forum](forum.helloiota.com). Thanks!

**Comment by cleto123** [comment]
I had it sent from Binance to my Iota wallet
