### ISSUE TITLE
IOTA wallet 2.5.6 MAC not sending big amount of IOTA

### ISSUE THREAD

**Issue by analogpusher** [iotaledger/wallet#916]
HI! i'm new here! i have issue w my wallet (2.5.6 mac version), i can send 1i (one iota) w no one problem, but when i try to send for example 5Mi appear error messages. Someone know? Help, please.
![screen shot 2017-12-30 at 7 47 31 pm](https://user-images.githubusercontent.com/34975929/34459257-0420510e-eda0-11e7-94b6-9c41f2bea700.png)

**Comment by wonkytonky** [comment]
one of your addresses with bigger amounts probably has been used before..  if you still have pending transactions those need to confirm first..

**Comment by razormaik** [comment]
<img width="432" alt="screen shot 1396-10-10 at 1 35 00 pm" src="https://user-images.githubusercontent.com/34980048/34460834-c79fff1e-ee2f-11e7-89bb-785b1f51d442.png">
<img width="428" alt="screen shot 1396-10-10 at 1 35 17 pm" src="https://user-images.githubusercontent.com/34980048/34460835-c7ca87de-ee2f-11e7-9b92-ebcb29146194.png">
I also have this problem!
also i now see 1 transection in iotasear.ch OUT , but i never send this transetion never
please help me!
<img width="1260" alt="screen shot 1396-10-10 at 1 44 06 pm" src="https://user-images.githubusercontent.com/34980048/34460865-ce7dc310-ee30-11e7-9a90-ded11d926f07.png">
you can see link my transetion also
https://iotasear.ch/hash/ESSNRCGGBHBVWLJNICXHUVUTSVETKRTCWF9QDWBNZGHCYMRRIUHWHCSPYRUTWZPCSBEKVCLKIZUHDK9OBZZTCXUZSW


if my balance out way i can see it in my wallet?

**Comment by wonkytonky** [comment]
in everytime you send money to some address.; in background the remaining money is send to a new address in your wallet so  works as designed .. the money is still in  your wallet :)

**Comment by analogpusher** [comment]
i let you know, thanks, I'll try...

**Comment by analogpusher** [comment]
Everything works well now!!! Thanks a lot

**Comment by wonkytonky** [comment]
cool , please close issue
