### ISSUE TITLE
Error getting out. Says there is a pending transaction 

### ISSUE THREAD

**Issue by daniezlt007** [iotaledger/wallet#917]
You are attempting to sign a transaction with input that have an already been used. IOTA uses Winternitz one-time signature (W-OTS) scheme, due to it's one-time nature, the security of funds in an address decreases rapidly if you re-sign new transactions using the same key. Please wait for previous transaction to confirm, e.g. by reattaching, before sending another transaction.

OBS: Already pending for more than 15 days

**Comment by wonkytonky** [comment]
some old transaction is still pending ..  make sure it get's confirmed..

**Comment by rajivshah3** [comment]
You should reattach and/or promote this transaction until it confirms. Please don't post issues like this here, instead post on the forum: forum.helloiota.com. Thanks!

**Comment by daniezlt007** [comment]
I know there is a pending transaction. And prediction to adjust it? There's money at stake. It's not RPG.
