### ISSUE TITLE
Tangle says transaction compelte - wallet says everything still pending

### ISSUE THREAD

**Issue by Jimboscott** [iotaledger/wallet#918]
Did a small test transfer from Binance to Wallet v. 2.5.6.  Roughly 13 hours later, wallet still has 0 balance and the history shows no completed transactions.  The tangle hash explorer shows a completed transaction outside of my wallet.

What gives?  I thought this was supposed to be quite fast...

**Comment by wonkytonky** [comment]
sure you have the right seed .. does the recieving address show up in your history?.. 
if so, change to another node.

**Comment by Jimboscott** [comment]
Had the right seed.  Everything looked right except for the balance and everything still showing as pending.  Changed nodes and... bingo.  Mi showed up instantly.

Thanks.
