### ISSUE TITLE
Why can not withdrawl IOTA from Binace to IOTA wallet?????

### ISSUE THREAD

**Issue by BaronNguyen** [iotaledger/wallet#919]
Withdrawl IOTA from Binance to IOTA wallet for aday but still pending status. Pls help me. Why and how to get IOTA into my IOTA wallet now? May be I loss these IOTA?

**Comment by rajivshah3** [comment]
Binance withdrawals may take some time. Also, please don't post issues/help requests like this here, instead post on the [forum](http://forum.helloiota.com). Thanks!
