### ISSUE TITLE
I can receive transfers but not attach to the tangle and send transfers in the iota light wallet 2.2.6

### ISSUE THREAD

**Issue by marc005** [iotaledger/wallet#92]
I can receive transfers but not attach to the tangle and send transfers (the transaction does not even get pending) in the iota light wallet 2.2.6 on windows 10 professional. I am using nod http://service.iotasupport.com:14265 with Min Weight Magnitude of 13. Please see attached txt error log. 

[iota error.txt](https://github.com/iotaledger/wallet/files/1060573/iota.error.txt)

iota.js:12623 
[Violation] Handler took 554ms of runtime (50ms allowed)

[Violation] Long running JavaScript task took 554ms
iota.js:12623 
[Violation] Handler took 561ms of runtime (50ms allowed)

[Violation] Long running JavaScript task took 562ms
iota.js:12623 
[Violation] Handler took 252ms of runtime (50ms allowed)

[Violation] Long running JavaScript task took 252ms
iota.js:12623 
[Violation] Handler took 268ms of runtime (50ms allowed)

[Violation] Long running JavaScript task took 268ms
VM125:2 Light Wallet: iota.api.attachToTangle
iota.js:12623 
[Violation] Handler took 522ms of runtime (50ms allowed)

I also wants to take this opportunity to communicate that when you install the iota wallet on windows 10 professional windows defender protests and says that it can be dangerous software. You are forced to force install the iota wallet which is not optimal.

**Comment by atypicalprogrammer** [comment]
Does it give an error in the GUI also or does it look as if it is processing? I think these "violations" are "normal" due to the long time it takes to do the POW.

Regarding windows, yea the team will be adding certificates soon.

**Comment by marc005** [comment]
It does not give an error in the GUI it only says sending for like an hour and nothing ells. The transaction does not even show up as pending. I have tried every day for like two weeks to send a transaction it never works! I am starting to get tiered of trying. The FAQ in the help pages say that it should take 1 - 25 minutes to send a transaction which is not very precise. Some people I have talked to says that it only takes a couple of minutes for them to send. My windows 10 pro Microsoft surface pro 4 tablet has a m3 CPU with 0.9 GHz base frequency and 4 GB of RAM but even though the RAM is low I don't think that that is the problem because I have monitored the load and it never spikes to 100%.

**Comment by atypicalprogrammer** [comment]
Do you see the CPU usage in the status bar and at how much percentage is it during sending?

**Comment by marc005** [comment]
I can try again to see exactly how much it is. Please wait a second or two..

**Comment by marc005** [comment]
Unfortunately it has to wait because the node seems to be down. 

"could not connect to remote node"

**Comment by atypicalprogrammer** [comment]
Yes, it's down, change node here: http://iotasupport.com/lightwallet.shtml

**Comment by marc005** [comment]
I change the node to http://lightserver1.iota.community:14600 and logged in ok. When I try to send a transaction in the iota wallet the CPU spike up to 51% after a couple of seconds and then immediately down to around 14% according to the statues bar in the iota wallet. On window around 70% of the CPU is used and 81% of the RAM is being used during sending. But nothing happens it just say sending in the iota wallet. I check the developer tool (toggle web inspector) again and I get the same violations as previously. I have being trying to send for 28 minute now without any luck so I think I will shut down the wallet now.  The CPU load is about 30% now according to the iota wallet. As I was typing this and trying to send in my iota wallet my tablet shut down because I think it was over heating. I haven't confirmed this yet but I think that was the reason for the shut down. This is however the first time this has happened when I am trying to send.

**Comment by domschiener** [comment]
I don't think that a table makes sense for the GUI. It uses ccurl which access your GPU (if possible), so that might have lead to it being overloaded.
