### ISSUE TITLE
Why IOTA Wallet Receive Address change when I login with the same seed

### ISSUE THREAD

**Issue by BaronNguyen** [iotaledger/wallet#923]
Why IOTA Wallet receive address change when I login with the same seed?

So now how can I get back my IOTA coins and check and trace my account information?

Pls help me

Thanks so much

**Comment by rajivshah3** [comment]
Check the history section in the wallet for info on previous addresses. Please post help requests like this on http://forum.helloiota.com. Thanks!

**Comment by BaronNguyen** [comment]
Many thanks  rajivshah3

**Comment by BaronNguyen** [comment]
I cannot transfer my MiOTA from Light Wallet to my Binance Exchange add.
Pls help me.

Status still pending for 4 days...

These are Txid (include reattach):

Txid: GKQYLHSBULHXXDXHLOMXLLUJYTQMHDOOXS9PUAWMUMB9FUEKNNYDUIJOUQQQ
LYJJTEEVGBZH9F9Q99999

Txid: ANKZPMTUTEFRKHU9UVCICVTLCKACPP9RVXF9HDNTRQEIOVWPNBXJEN9BOKGY
GL9CMQTWJHCYJVRGA9999

Txid: TTYOPMGMCSIRHHRG9HDZBVSHM9VCYFUOKBPXWVYDJJLHENQMVBGZLTKUKMRY
PSTIXTZFUPGFCXXJZ9999

And now I cannot login to Light Wallet too despite the true seed. :(

Pls help me

Tks so much
