### ISSUE TITLE
Address/seed problem

### ISSUE THREAD

**Issue by cryptoamd** [iotaledger/wallet#924]
I just did a transfer to my new IOTA wallet and instead of saving the seed I saved the address. The transaction went through and I have all the transaction data saved. Is there any way to recover my seed with the address and all the other info I have apart from the seed?
I created the seed with Terminal and trying to go on Terminal history but haven't been successful so far.. Please help!
Thanks in advance.

**Comment by wonkytonky** [comment]
not possible to reverse engineer de seed from address. this would make all addresses unsecure. 
you need the seed.  this is not a wallet issue . please close   thanks.
