### ISSUE TITLE
All IOTA automatically withdraw/stolen from light chain wallet

### ISSUE THREAD

**Issue by jenksp** [iotaledger/wallet#929]
Hello,
I am missing my all IOTA from IOTA wallet. I open today to see if everything going fine or not and found out in history that all my IOTA has been withdrawal and now i have less than 1 IOTA which is 25'425. Can anyone help me out what is going on or how to restore the IOTA which was automatically withdraw.

**Comment by rajivshah3** [comment]
This is not true, if you would like help recovering your lost funds please post on http://forum.helloiota.com

**Comment by jenksp** [comment]
how
