### ISSUE TITLE
IOTA light chain hacked please withdraw your IOTA ASAP

### ISSUE THREAD

**Issue by jenksp** [iotaledger/wallet#930]
Hello,
I would like to update you guys that IOTA light wallet has been hacked. its  automatically withdrawing your all IOTA, I lost my all IOTA so before it get worse just withdraw your IOTA ASAP

**Comment by yippykaiyay012** [comment]
You fucked up somewhere. Not the wallet. Stop spreading  fud and learn how to crypto.

**Comment by rajivshah3** [comment]
This is not true, if you would like help recovering your lost funds please post on http://forum.helloiota.com
