### ISSUE TITLE
 unconfirmed transaction

### ISSUE THREAD

**Issue by gorunuchs** [iotaledger/wallet#934]
December 29 commissioned a transaction to transfer funds from the purse IOTA Wallet to the exchange binance in the amount of 340.6 tokens, the transaction to date has not received confirmation

**Comment by wonkytonky** [comment]
reattach/promote pending transactions

**Comment by gorunuchs** [comment]
How i can to do it?

**Comment by wonkytonky** [comment]
go to bundle of the pending transaction.  
this is not an wallet issue please close

**Comment by gorunuchs** [comment]
IOTA-Balance-Finder error. No repository field
