### ISSUE TITLE
Possible LightWallet bug

### ISSUE THREAD

**Issue by patchthecode** [iotaledger/wallet#935]
https://www.reddit.com/r/Iota/comments/7njjyy/here_is_what_i_learnt_after_losing_53_gi_to_a_hack/

key to note here ->

> And I had completely forgotten about it since _**my wallet didn't recognise it too.**_

**Comment by rajivshah3** [comment]
This is not a bug, this is a user error

**Comment by patchthecode** [comment]
The wallet possibly generating a seed that has already been generated becase the recods were wiped after snapshotting happened is not a bug?

**Comment by rajivshah3** [comment]
This cannot be fixed as the wallet does not remember how many addresses were generated before the snapshot. Other wallets however aim to implement that feature.
