### ISSUE TITLE
 Problems with log in to my IOTA wallet

### ISSUE THREAD

**Issue by Orest007** [iotaledger/wallet#936]
Hi
I had a problem with log in to my IOTA wallet. I installed the wallet, applied the key and everything was fine until I dropped more than 100 mIOTA on it. After that I can not log in to my wallet. Constantly produces an error "CONNECTION REFUSED"
Help, please, understand why this error occurs and why I can not access my coins?

**Comment by wonkytonky** [comment]
change node

**Comment by Orest007** [comment]
Thank you
Changed the node and  log in to my IOTA wallet
But my balance sheet is empty, although more than 3 hours ago there was a transaction in the amount of 104.395 Mi
How long does the transaction take?
Link: https://iotasear.ch/hash/NBGYODATSFJSGRAPXE9IZUSDJGIJUNFKBSLJCLVWVBBHFEUQOHZKSGDTUFD9ZOGPQIZZAEXWTKWHDNMDXRORRLIRFZ

**Comment by Mcelroy-sg** [comment]
la transaccion puede ser instantanea o que tarde minutos,horas,depende de las transacciones que se realicen en el momento.pero tus miotas si las enviaste a tu semilla estan seguras.no te preocupes todo esta en fase inicial y todavia no lleva la velocidad que deveria

**Comment by Orest007** [comment]
Thank you

**Comment by wonkytonky** [comment]
the transaction is confirmed so it should be in your wallet .; if you own the wallet address.  
sometimes public nodes are laggy or not syned to the last milestone .. so try a few nodes

**Comment by Orest007** [comment]
All is clear now. Thank you for your help.
