### ISSUE TITLE
node file -recover seed

### ISSUE THREAD

**Issue by uzielroy** [iotaledger/wallet#937]
I probably lost my seed. I tried to recover data, and found 2 files that (I hope) could help me recover my seed.
the files are ***.node. I dont know how to read the files.
Do they contain relevant data?

**Comment by wonkytonky** [comment]
seed is not stored on system as far as i know..

**Comment by uzielroy** [comment]
Cant i recover it somehow? Any information from my seed?

**Comment by wonkytonky** [comment]
no
