### ISSUE TITLE
Private error key reuse

### ISSUE THREAD

**Issue by MKD68** [iotaledger/wallet#939]
I am getting the following error for about 3 weeks now
ERROR: PRIVATE KEY REUSE DETECTED!

You are attempting to sign a transaction with input that have an already been used. IOTA uses Winternitz one-time signature (W-OTS) scheme, due to it's `one-time` nature, the security of funds in an address decreases rapidly if you re-sign new transactions using the same key. Please wait for previous transaction to confirm, e.g. by reattaching, before sending another transaction.

Cannot transfer coins to binance

**Comment by rajivshah3** [comment]
Please fill out the template for issues. Private key reuse warnings are not a wallet bug

**Comment by MKD68** [comment]
Can you help understand the issue- I cant deposit any IOTA coins to Binance

**Comment by wonkytonky** [comment]
Telegram, https://t.me/iotatangle 
https://forum.helloiota.com/

**Comment by MKD68** [comment]
Hi not sure why you are saying its not a wallet issue- people on the forum
are being sent back to the gitwallet to open a issue.
