### ISSUE TITLE
View Node Info -> nothing happens after changing host

### ISSUE THREAD

**Issue by bluedigits** [iotaledger/wallet#94]
Steps to reproduce:
1. Configure wrong host (e.g. wrong port 14600 instead of 14265)
2. Restart GUI
3. Click _Tools_ -> _View Node info_ => Nothing happens
4. Set the right host information (i.e. correct node and correct port).
5. Again, click _Tools_ -> _View Node info_ => Nothing happens
6. Restart GUI wallet
7. Now, View Node info works

**Comment by domschiener** [comment]
@atypicalprogrammer we should use the `iota.changeNode` function to change the provider on the fly.

**Comment by atypicalprogrammer** [comment]
@domschiener not good enough, because old request that may be running blocks new request. So completely destroying iota object and reinitializing may be better..

**Comment by atypicalprogrammer** [comment]
Should be fixed in dev, please try.
