### ISSUE TITLE
 Unconfirmed transaction

### ISSUE THREAD

**Issue by gorunuchs** [iotaledger/wallet#940]
The transaction has not been confirmed since Dec. 29. What should I do?
I can not do the transaction retransmission, because it's not in the history.
Users say that a month is waiting for the transaction
Help me please

**Comment by Tobo01** [comment]
The single most important first step to send transaction is to check if the server you get connected is synced. The servers are not always synced. To check the synced status, you can compare the two milestone numbers (in the nodeinfo under Tools) in your wallet to the most recent milestone number in the #botbox of the Slack. If all the three numbers are same, your wallet or your server is synced. If they are not same you need either wait for them to be same or change a server.

After you have done the above first step correctly, you can make the transaction. I would say 80% of times your transactions will get confirmed in 30 minutes.

If your trasanction does not get confirmed in 30 minutes, you can do the Promoting (previously called Reattaching). You will see it if clicking the bundle next to the transaction in the History in your wallet. You can do the Promoting once every 30 minutes. But make sure you do the first step to make sure your wallet is synced first every time. 

If you do the above steps correctly 99% of your transaction should get confirmed within one Promoting and most will be confirmed without Promoting.
