### ISSUE TITLE
Do not save IOTA in IOTA wallet its easily hacked and stolen

### ISSUE THREAD

**Issue by jenksp** [iotaledger/wallet#942]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by jhmblvd** [comment]
I keep getting a Request Error. Using the latest wallet. I've reattached over and over. Coin not arriving, and when trying to attach to Tangle big Red bar saying "Request Error"

**Comment by jhmblvd** [comment]
What really is scary is every help forum from slack to your own forum is down. I go to help in the wallet and click on any of the links for help and they go to 404 pages??

**Comment by wonkytonky** [comment]
close/ban 
op is troll/fud 
![image](https://user-images.githubusercontent.com/19390834/34504588-b55162ca-f01f-11e7-8f08-6bdf7c27bca5.png)

**Comment by jenksp** [comment]
do not trust IOTA wallet, IOTA will stay in your wallet and than automatically it will be hacked and withdraw from wallet

**Comment by rajivshah3** [comment]
@jenksp I have reported your account to GitHub for spam
