### ISSUE TITLE
I can not transfer my IOTA from my wallet

### ISSUE THREAD

**Issue by MazurovE** [iotaledger/wallet#944]
Hello! I tried to send IOTA from my wallet 2.5.6 to Bitfinex. My balance has not changed, in the history the status - "Pending". Today I press "REBROADCAST" and "REATTACH" in "BUNDLE DETAILS", but there are any changes. This is my first experience of transferring IOTA to exchange. How should this be done correctly? How long does it take? Thank you in advance!

**Comment by wonkytonky** [comment]
show us the pending outgoing transaction

**Comment by SZMEK67** [comment]
I have the same problem

Please help

**Comment by bluscreen** [comment]
had the same problem. it got stuck on "SENDING..."... then i chose a good node. sending again via that one after a while my cpu went up to like 700% (i wonder how that works) and after a while again i got a notification saying "transfer complete"

**Comment by MazurovE** [comment]
Thanks!
