### ISSUE TITLE
History disapeared

### ISSUE THREAD

**Issue by NicolasMassart** [iotaledger/wallet#96]
After the snapshot, I logged in again with the same seed, generated addresses to get my balance back, but I can't figure how to get my transactions history back.
I admit I don't know if it's possible or if it's something managed by the wallet... but it's confusing to loose such information.

Using OSX light wallet v2.3.0

**Comment by domschiener** [comment]
The whole point of snapshots is to get rid of your transaction history :) The only thing you essentially really care about is the correct balance.

In the future we will make it possible to query the full history.
