### ISSUE TITLE
Wallet crashed Windows System

### ISSUE THREAD

**Issue by Fredi100** [iotaledger/wallet#97]
After opening the transactions and looking them through. I accidentally clicked on re-attach on a transaction which was pending at the moment. As soon as I did that my computer completely shut down.

**Comment by domschiener** [comment]
Can you give us some more information about your computer?

**Comment by Fredi100** [comment]
```
------------------
System Information
------------------
      Time of this report: 6/11/2017, 16:03:43
             Machine name: ALIENWARE17
               Machine Id: {2E559651-3FE0-43A9-B1B3-D69FF0E790F3}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 15063) (15063.rs2_release.170317-1834)
                 Language: German (Regional Setting: German)
      System Manufacturer: Alienware
             System Model: Alienware 17
                     BIOS: A14
                Processor: Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz (8 CPUs), ~2.8GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16308MB RAM
                Page File: 8180MB used, 10558MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: Using System DPI
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Not Available
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.15063.0000 64bit Unicode
```

**Comment by Fredi100** [comment]
It crashed my system again. This time I just wanted to transfer some Iotas. As soon as I hit send my computer turned of. As if I pulled the cable.

**Comment by Fredi100** [comment]
And because everyone knows that third time is the charm, it happend again.
Like before, trying to send some IOTA. A few seconds after starting to calculate the computer just goes black.

**Comment by Fredi100** [comment]
It crashed my system twice today. I was trying to attach the recieve address after I created a new seed. Twice in a row it crashed my system. The third time it could finish attaching it so I could recieve my Iota tokens.

**Comment by atypicalprogrammer** [comment]
There's been some updates to ccurl in the next version, perhaps that will help. If not, please re-open the issue.
