### ISSUE TITLE
Error: Private Key reuse although there are no pending transactions

### ISSUE THREAD

**Issue by IsThisNickFree** [iotaledger/wallet#974]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x ] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x ] I confirm that this is an issue with the wallet, not IRI
* [x ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x ] I confirm that this is not an issue related to stolen/lost funds
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ x] I confirm that this issue is present on the latest version of the wallet

### Description

Error: Private Key Reuse

I tried to send 120 Miotas to a friend of mine.
I got the "Error: Private Key reuse"

However i could send him 10 Miotas without any problem. I could do that 3 times. After the first transaction of 10 Miotas was confirmed i tried to send the rest of the 120 Miotas and got the Private Key Reuse error. I tried it again with 10 Miotas and it worked instantly.

He sent me 1 Miota back and i sent him 1 Miota. Everything got confirmed and worked fine.
I tried to send him 20 Miotas: "Error: Private Key Reuse"

For more detailed information: https://forum.helloiota.com/7755/RE-Help-with-unconfirmed-transactions-and-private-key-error#7821

### Steps to Reproduce

1. Get a bitfinex transaction of 131,8 Miota to your Wallet.
2. Send 43,6 Miota to friend A.
3. Generate new Receiving Address and attach to tangle
4. Send 49,6 Miota to friend B.
5. Watch as your wallet freaks out and lists up 8(!) transactions of 49,6 Miotas.
6. Receive 6 Miotas back from friend B.
7. Buy more Iota
8. Receive 210,5 Miota form Bitfinex
9. Wallet lists up the first 210,5 as confirmed.
10. Try to send 120 Miotas to your friend A.
11. Error: Private Key reuse
12. Receive 1 Miota from friend A.
13. Generate new Receiving Address.
14. Send 1 Miota to friend A.
15. Receive 1 Miota from Friend A.
16. Send 10 Miota to friend A.
17. Try to send 110 Mitoa to friend A.
18. Error: Private Key Reuse
19. Generate new Receiving address.
20. Send 10 Miota to friend A.
21. Generate new Receiving address.
22. Send 10 Miota to friend A.
23. Generate new Address.
24. Try to send 80 Miotas to friend A.
25. Private Key Reuse
26. Lay down.
27. Contemplate Life.
28. Go trhough evere transaction ever made with and in your wallet(110 by now)
29. Manually reattach and promote every. single. transaction.
30. Get them all confirmed.
31. Generate new Address.
32. Try to send 80 Miotas to friend A.
33. ERROR: Private Key Reuse
34. Lay down.
35. Cry.

**Expected behavior:** 

"TRANSACTION COMPLETED"

**Actual behavior:** 

ERROR: Private Key Reuse

### Versions

[Win 10 64-bit]
[Light Wallet 2.5.6]

**Comment by wonkytonky** [comment]
can you show us the addresses that hold value you want to send from?

**Comment by IsThisNickFree** [comment]
What exactly do you mean? Do you mean the receiving addresses i used for the bitfenix transactions?
Or do you generally just need one oft the now 50(1) addresses i got?

**Comment by IsThisNickFree** [comment]
This is the address used to receive the iotas:
WFFIWNRPTUGJQMGJPNCECBFR9HOQDILNRHVPFIXHHOIWEE9LFYDJHFXBEG9WGYZKRGFEDWTSRQLGFNVBYCCLFHBVQC

This address is now crossed out in the Address Section of my Wallet-history

I already generated new addresses. And

This is the connected Hash:
PXKJCRG9UKEFYPCOKYZHZMVIYDABIJNCB9EF9IIELJMZGEQFBJOUZUABDYGWZIMQIZTDCWXEYFZ999999


Holy shit i know what i did wrong.

**Comment by IsThisNickFree** [comment]
For everyone with the same problems like me:

https://github.com/MichaelSchwab/iota-commandline-wallet
Follow his readme and tutorial on youtube. You can then acces your funds and transfer them to either your friends wallet or your new wallet.

If you run into issues, he is quick at replying:
https://github.com/MichaelSchwab/iota-commandline-wallet/issues/6

Afterwards generate a new seed and login to your new wallet and never look back!
