### ISSUE TITLE
0 balance transfer pending

### ISSUE THREAD

**Issue by katkat597** [iotaledger/wallet#976]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [x] I confirm that this is not an issue related to stolen/lost funds
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by katkat597** [comment]
Everything is fine with the wallet and I have both my balances in the wallet. I must have tried to do a 0 balance transfer and it is showing up as pending. Will it just fall off or do I need to do something

**Comment by Dotshoot** [comment]
IOTA is the most terrible shit I've ever seen.
Yes that I have, if I'm buying this coin.
In general, such otstoy.Da still talking about the future. With koshelkem it is clear that this project is doomed to failure.

**Comment by rajivshah3** [comment]
@Dotshoot stop fudding. I will have your account reported to GitHub

**Comment by rajivshah3** [comment]
An address attachment will show as a 0 value transaction. It doesn't need to confirm

**Comment by Dotshoot** [comment]
@rajivshah3 OK I'm just very wicked, and I'm sorry that I bought a coin. Now I can not withdraw from my wallet what to exchange for another

**Comment by katkat597** [comment]
Thanks much for the help! It is a little tricky getting it set up but once
you do it is a breeze.

**Comment by Dotshoot** [comment]
And it never occurred to you how to automate your wallet.
That people and investors do not have to worry.
Do you have programmers there who are stupid?
Can I come and write software for automation.

Отправлено из Почты для Windows 10

От: katkat597
Отправлено: 8 января 2018 г. в 4:52
Кому: iotaledger/wallet
Копия: Dotshoot; Mention
Тема: Re: [iotaledger/wallet] 0 balance transfer pending (#976)

Thanks much for the help! It is a little tricky getting it set up but once
you do it is a breeze.
