### ISSUE TITLE
Iota Light Wallet 2.5.6 balance 0

### ISSUE THREAD

**Issue by leinaf** [iotaledger/wallet#977]
hi all,

I am using the light wallet 2.5.6. 
I transferred my Iota to this wallet. After one day my balance shows 0 and no history.
I tried pressing the generate new address button more than 210 times. I changed the host connection often. But my Iota didn't come back yet.  What else should I do?
Please help me with a good advice to get it back

kind regards
leinaf

**Comment by Dotshoot** [comment]
IOTA is Scam.

**Comment by rajivshah3** [comment]
Are you sure you're typing the seed correctly?

**Comment by Dotshoot** [comment]
IOTA is the most terrible shit I've ever seen.
Yes that I have, if I'm buying this coin.
In general, such otstoy.Da still talking about the future. With koshelkem it is clear that this project is doomed to failure.

**Comment by leinaf** [comment]
More than sure!

**Comment by hamid349** [comment]
Hello everyone
I also have such a problem?
Is there someone to help me؟

**Comment by hamid349** [comment]
Is this version of IOTA WALLET fake?

**Comment by hamid349** [comment]
I had 42 mg of stock in my wallet, but now it's zero

**Comment by hamid349** [comment]
Please help me with a good advice to get it back

**Comment by TinaGudi** [comment]
I have the same problem.

**Comment by rishab8** [comment]
have u tried attaching to tangle @hamid349 
keep on tring it might work
thanks

**Comment by hamid349** [comment]
این کیف پول جعلی است و این یک برنامه سرقت اطلاعات است من توصیه میکنم از آن استفاده نکنید.
This wallet is fake, and this is a data stealing program. I advise you not to use it.

**Comment by hamid349** [comment]
The designer of this app is a thief

**Comment by cocoaboost** [comment]
I had same problem with version 2.5.4, funds went to 0 this morning

**Comment by rishab8** [comment]
@cocoaboost yesterday snapshot happen u need to rettach again

**Comment by cocoaboost** [comment]
rishab8 you are right, yeah guys, after searching i found some useful info when these things happen. In my case my MIOTA were in the Tangle but when I close the wallet the balance come back to 0, this means that your MIOTA is in the tangle but not necessarily in the wallet. So you have to click on Receive and it will show your address to receive MIOTA and a button that says Attach to Tangle, when clicking there the wallet will connect to the tangle again and the balance will be shown. Also, you can check your balance in this page https://iotabalance.com/ , in this site you have to put your receive address (not the seed address, the seed address don't share it with anyone)
