### ISSUE TITLE
I can not take coins from my wallet

### ISSUE THREAD

**Issue by Dotshoot** [iotaledger/wallet#979]
For an hour I'm waiting. Writes that it is sent.
I see nothing in history.
All probyval nodes changed, etc.
And the sense to change the nodes when they all lag.
I already have no patience.
Give me back the coins and I'll forget it as a terrible dream.
I'm just very wicked, and I'm sorry that I bought a coin. Now I can not withdraw from my wallet what to exchange for another

Who has a suggestion why this happens?

**Comment by rajivshah3** [comment]
Check your transaction on thetangle.org

**Comment by rajivshah3** [comment]
And stop fudding, I will report you to GitHub

**Comment by rajivshah3** [comment]
I can send transactions just fine, so I'm not sure what you're talking about. I have reported you to GitHub
