### ISSUE TITLE
Sending iota on a Mac does not work

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/wallet#98]
I am unable to send iota from my wallet, and 2 other people in the slack are having the same issue. If I try to send it, it says "sending" for about 5 min, and then says that there was an incorrect hash (or it might have said incorrect hash length). I'm using macOS Sierra 
10.12.5

**Comment by domschiener** [comment]
We're aware of this issue, not related to Mac alone. Closing now as it's a duplicate.
