### ISSUE TITLE
Seed lost

### ISSUE THREAD

**Issue by commanderi72** [iotaledger/wallet#983]
hello, I have lost my seed or my PC crashed when creating the Seed with KeePass and the database was not saved.

What can you do or is it hopeless?

I offer 100 € for those who can help me.

thanks
christian

**Comment by wonkytonky** [comment]
if you lose your seed, you cannot access your iota,  this is the same for any other cryptocurrency i'm afraid.

**Comment by samgranger** [comment]
The only suggestion I can make is to reach out to the developers of KeePass and see if they know any  methods on how you might be able to recover your seed.

**Comment by commanderi72** [comment]
hello sam, that would be very nice of you if you could contact the developers contact. If there is a solution, I would be worth the 100 € or us dollar

**Comment by samgranger** [comment]
I don't have any contact with Keepass developers but you could try reaching out to them, maybe through their forum - https://sourceforge.net/p/keepass/discussion/

This is not something I am interested in doing and it would be best that you do this, since you can provide the most information.
