### ISSUE TITLE
Login on Iota Wallet 2.5.6 does not show up.

### ISSUE THREAD

**Issue by bradmt** [iotaledger/wallet#994]
I just downloaded the new Iota wallet 2.5.6 for windows and ran it.  There is no login area as there was on the older wallets.  I can't copy and paste my seed on this wallet?  I uninstalled and re-installed this and same problem persisted.  How do I get the LOGIN -----------------  to show up on this wallet so I can paste my seed

**Comment by wonkytonky** [comment]
change node
