### ISSUE TITLE
Problem with sending iota. ERROR.

### ISSUE THREAD

**Issue by MrocznyTynkarz** [iotaledger/wallet#995]
Hello!
When I try send iota to another seed (paper wallet) it shows that:

> ERROR: PRIVATE KEY REUSE DETECTED! You are attempting to sign a transaction with input that have an already been used. IOTA uses Winternitz one-time signature (W-OTS) scheme, due to it's one-time nature, the security of funds in an address decreases rapidly if you re-sign new transactions using the same key. Please wait for previous transaction to confirm, e.g. by promoting/reattaching, before sending another transaction.

I have four transaction with status "pending". It't old transaction. When I tried send 1 iota, I send this 3 times. I had 3 status pending on the same receiving adress and the same 1 iota. One transaction was confirmed but others twice are still pending. How to delete this pending transaction? Or fix this? **Curva!**

**Comment by wonkytonky** [comment]
make old transactions confirm first   by reattaching/promoting

**Comment by MrocznyTynkarz** [comment]
I did it, but transactions dubled with status pending. Now I do not have button reattaching/promoting.

**Comment by MKD68** [comment]
ERROR: PRIVATE KEY REUSE DETECTED! You are attempting to sign a transaction with input that have an already been used. IOTA uses Winternitz one-time signature (W-OTS) scheme, due to it's one-time nature, the security of funds in an address decreases rapidly if you re-sign new transactions using the same key. Please wait for previous transaction to confirm, e.g. by promoting/reattaching, before sending another transaction.

Having the same issue and transfer pending is showing for 2 weeks at BINANCE
I am assuming something is wrong.  Can anyone provide support instread of closing ticket

**Comment by MrocznyTynkarz** [comment]
I made old transactions confirm by reattaching. In history shows "pending" but in show bundle shows "Persistence: A reattachment confirmed". All transactions shows in "show bundle", "Confirmed" or "Persistence: A reattachment confirmed". I still have the same error and I still can't send even 1 iota... HELP!

**Comment by wonkytonky** [comment]
show address that you are trying to spend from

**Comment by MrocznyTynkarz** [comment]
PLAESJTWDBSCNHPIUJPGAUV9KK9MTVIEERGZ99WEZYC9IMHTUJESIXTDRYWBZVKSOGPJQLCTJYVXK9JGWXZCBIBZKY

It's actual my receive adress. I did attach to tangle 2 or 3 times.

**Comment by wonkytonky** [comment]
i dont find that address on explorer so it's not attached.   
but i need the address that you send form.. not the one you recieve on

**Comment by MrocznyTynkarz** [comment]
*I copy receive adress from wallet so... idk...
*Sorry but idk witch adress do you want. You want my seed?

**Comment by wonkytonky** [comment]
no dont give seed anywhere  ppl will take your money out if they know your seed

**Comment by MrocznyTynkarz** [comment]
I know seed is most important, but idk witch adress do you want...

**Comment by rajivshah3** [comment]
Closing as this is not a wallet bug
